# 📦 Section 0: Data Loading & Sanity Checks

> Load data, validate relationships, basic checks

---

In [1]:
# =========================
# Instacart data familiarization script (runnable as-is)
# =========================

import os
import pandas as pd

# 1) Edit here: path to your data folder
# e.g. DATA_DIR = "./"  (if csv and notebook are in the same folder)
#      DATA_DIR = "./data" (if csv is in a data subfolder)
DATA_DIR = "./"

# 2) File name list (already provided)
FILES = {
    "aisles": "aisles.csv",
    "departments": "departments.csv",
    "order_products_prior": "order_products__prior.csv",
    "order_products_train": "order_products__train.csv",
    "orders": "orders.csv",
    "products": "products.csv",
}

# 3) Load data
dfs = {}
for name, filename in FILES.items():
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"File not found: {path}\n"
            f"Please confirm DATA_DIR is correct and the file exists in that folder."
        )
    print(f"Loading {filename} ...")
    dfs[name] = pd.read_csv(path)

print("\n✅ All files loaded.\n")

Loading aisles.csv ...
Loading departments.csv ...
Loading order_products__prior.csv ...
Loading order_products__train.csv ...
Loading orders.csv ...
Loading products.csv ...

✅ All files loaded.

_1️⃣ Check each file: shape / columns / dtypes_

In [2]:
for name, df in dfs.items():
    print(f"\n--- {name} ---")
    print("shape:", df.shape)
    print("columns:", list(df.columns))
    print("\ndtypes:")
    print(df.dtypes)

--- aisles ---
shape: (134, 2)
columns: ['aisle_id', 'aisle']

dtypes:
aisle_id     int64
aisle       object
dtype: object

--- departments ---
shape: (21, 2)
columns: ['department_id', 'department']

dtypes:
department_id     int64
department       object
dtype: object

--- order_products_prior ---
shape: (32434489, 4)
columns: ['order_id', 'product_id', 'add_to_cart_order', 'reordered']

dtypes:
order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

--- order_products_train ---
shape: (1384617, 4)
columns: ['order_id', 'product_id', 'add_to_cart_order', 'reordered']

dtypes:
order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

--- orders ---
shape: (3421083, 7)
columns: ['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order']

dtypes:
order_id                    int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

--- products ---
shape: (49688, 4)
columns: ['product_id', 'product_name', 'aisle_id', 'department_id']

dtypes:
product_id        int64
product_name     object
aisle_id          int64
department_id     int64
dtype: object

_2️⃣ Check the first 20 rows + describe() of each core file_

In [3]:
# 2.1 orders.csv
orders = dfs["orders"]
print("\n--- orders: head(20) ---")
display(orders.head(20))

print("\n--- orders: describe(include='all') ---")
display(orders.describe(include="all"))

--- orders: head(20) ---

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0
11,2168274,2,prior,1,2,11,NaN
12,1501582,2,prior,2,5,10,10.0
13,1901567,2,prior,3,1,10,3.0
14,738281,2,prior,4,2,10,8.0
15,1673511,2,prior,5,3,11,8.0
16,1199898,2,prior,6,2,9,13.0
17,3194192,2,prior,7,2,12,14.0
18,788338,2,prior,8,1,15,27.0
19,1718559,2,prior,9,2,9,8.0

--- orders: describe(include='all') ---

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3421083,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
unique,NaN,NaN,3,NaN,NaN,NaN,NaN
top,NaN,NaN,prior,NaN,NaN,NaN,NaN
freq,NaN,NaN,3214874,NaN,NaN,NaN,NaN
mean,1.710542e+06,1.029782e+05,NaN,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,NaN,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,NaN,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,NaN,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,NaN,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,NaN,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,NaN,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [4]:
# 2.2 order_products__prior.csv
prior = dfs["order_products_prior"]
print("\n--- order_products_prior: head(20) ---")
display(prior.head(20))

# Key columns (show if present, skip if not)
prior_focus_cols = [c for c in ["order_id", "product_id", "add_to_cart_order", "reordered"] if c in prior.columns]
print("\n--- order_products_prior: focus columns head(20) ---")
display(prior[prior_focus_cols].head(20))

--- order_products_prior: head(20) ---

    order_id  product_id  add_to_cart_order  reordered
0          2       33120                  1          1
1          2       28985                  2          1
2          2        9327                  3          0
3          2       45918                  4          1
4          2       30035                  5          0
5          2       17794                  6          1
6          2       40141                  7          1
7          2        1819                  8          1
8          2       43668                  9          0
9          3       33754                  1          1
10         3       24838                  2          1
11         3       17704                  3          1
12         3       21903                  4          1
13         3       17668                  5          1
14         3       46667                  6          1
15         3       17461                  7          1
16         3       32665                  8          1
17         4       46842                  1          0
18         4       26434                  2          1
19         4       39758                  3          1

--- order_products_prior: focus columns head(20) ---

    order_id  product_id  add_to_cart_order  reordered
0          2       33120                  1          1
1          2       28985                  2          1
2          2        9327                  3          0
3          2       45918                  4          1
4          2       30035                  5          0
5          2       17794                  6          1
6          2       40141                  7          1
7          2        1819                  8          1
8          2       43668                  9          0
9          3       33754                  1          1
10         3       24838                  2          1
11         3       17704                  3          1
12         3       21903                  4          1
13         3       17668                  5          1
14         3       46667                  6          1
15         3       17461                  7          1
16         3       32665                  8          1
17         4       46842                  1          0
18         4       26434                  2          1
19         4       39758                  3          1

In [5]:
# 2.3 order_products__train.csv (not strictly required, checking anyway)
train = dfs["order_products_train"]
print("\n--- order_products_train: head(20) ---")
display(train.head(20))

train_focus_cols = [c for c in ["order_id", "product_id", "add_to_cart_order", "reordered"] if c in train.columns]
print("\n--- order_products_train: focus columns head(20) ---")
display(train[train_focus_cols].head(20))

# prior vs train column diff comparison
prior_cols = set(prior.columns)
train_cols = set(train.columns)
print("\n--- prior vs train: column diff ---")
print("Columns only in prior:", sorted(list(prior_cols - train_cols)))
print("Columns only in train:", sorted(list(train_cols - prior_cols)))
print("Columns in both:", sorted(list(prior_cols & train_cols)))

--- order_products_train: head(20) ---

    order_id  product_id  add_to_cart_order  reordered
0          1       49302                  1          1
1          1       11109                  2          1
2          1       10246                  3          0
3          1       49683                  4          0
4          1       43633                  5          1
5          1       13176                  6          0
6          1       47209                  7          0
7          1       22035                  8          1
8         36       39612                  1          0
9         36       19660                  2          1
10        36       49235                  3          0
11        36       43086                  4          1
12        36       46620                  5          1
13        36       34497                  6          1
14        36       48679                  7          1
15        36       46979                  8          1
16        38       11913                  1          0
17        38       18159                  2          0
18        38        4461                  3          0
19        38       21616                  4          1

--- order_products_train: focus columns head(20) ---

    order_id  product_id  add_to_cart_order  reordered
0          1       49302                  1          1
1          1       11109                  2          1
2          1       10246                  3          0
3          1       49683                  4          0
4          1       43633                  5          1
5          1       13176                  6          0
6          1       47209                  7          0
7          1       22035                  8          1
8         36       39612                  1          0
9         36       19660                  2          1
10        36       49235                  3          0
11        36       43086                  4          1
12        36       46620                  5          1
13        36       34497                  6          1
14        36       48679                  7          1
15        36       46979                  8          1
16        38       11913                  1          0
17        38       18159                  2          0
18        38        4461                  3          0
19        38       21616                  4          1

--- prior vs train: column diff ---
Columns only in prior: []
Columns only in train: []
Columns in both: ['add_to_cart_order', 'order_id', 'product_id', 'reordered']

In [6]:
# 2.4 products.csv
products = dfs["products"]
print("\n--- products: head(20) ---")
display(products.head(20))

# product_id uniqueness check
if "product_id" in products.columns:
    is_unique = products["product_id"].is_unique
    nunique = products["product_id"].nunique()
    nrows = len(products)
    print(f"\nproducts.product_id is_unique = {is_unique} (nunique={nunique}, rows={nrows})")
else:
    print("\n⚠️ product_id column not found in products (unexpected, check the file)")

# products missing value check
print("\n--- products: missing values ---")
display(products.isnull().sum().sort_values(ascending=False))

--- products: head(20) ---

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13
5,6,Dry Nose Oil,11,11
6,7,Pure Coconut Water With Orange,98,7
7,8,Cut Russet Potatoes Steam N' Mash,116,1
8,9,Light Strawberry Blueberry Yogurt,120,16
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7
10,11,Peach Mango Juice,31,7
11,12,Chocolate Fudge Layer Cake,119,1
12,13,Saline Nasal Mist,11,11
13,14,Fresh Scent Dishwasher Cleaner,74,17
14,15,Overnight Diapers Size 6,56,18
15,16,Mint Chocolate Flavored Syrup,103,19
16,17,Rendered Duck Fat,35,12
17,18,Pizza for One Suprema Frozen Pizza,79,1
18,19,Gluten Free Quinoa Three Cheese & Mushroom Blend,63,9
19,20,Pomegranate Cranberry & Aloe Vera Enrich Drink,98,7

products.product_id is_unique = True (nunique=49688, rows=49688)

--- products: missing values ---

product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

In [7]:
# 2.5 aisles.csv + departments.csv
aisles = dfs["aisles"]
departments = dfs["departments"]

print("\n--- aisles: head(20) ---")
display(aisles.head(20))
print("aisles rows:", len(aisles))

print("\n--- departments: head(20) ---")
display(departments.head(20))
print("departments rows:", len(departments))

--- aisles: head(20) ---

    aisle_id                         aisle
0          1         prepared soups salads
1          2             specialty cheeses
2          3           energy granola bars
3          4                 instant foods
4          5    marinades meat preparation
5          6                         other
6          7                 packaged meat
7          8               bakery desserts
8          9                   pasta sauce
9         10              kitchen supplies
10        11              cold flu allergy
11        12                   fresh pasta
12        13                prepared meals
13        14        tofu meat alternatives
14        15              packaged seafood
15        16                   fresh herbs
16        17            baking ingredients
17        18  bulk dried fruits vegetables
18        19                 oils vinegars
19        20                  oral hygiene

aisles rows: 134

--- departments: head(20) ---

    department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli

departments rows: 21

_3️⃣ Key relationship validation (join cardinality)_

In [8]:
def nunique_report(df, col, label):
    if col not in df.columns:
        print(f"⚠️ {label}: column '{col}' not found")
        return None
    return df[col].nunique()

# orders.order_id -> prior.order_id
orders_order_nunique = nunique_report(orders, "order_id", "orders")
prior_order_nunique = nunique_report(prior, "order_id", "prior")
prior_rows = len(prior)

print("\n--- orders.order_id → prior.order_id ---")
print("orders: order_id nunique =", orders_order_nunique, "rows =", len(orders))
print("prior : order_id nunique =", prior_order_nunique, "rows =", prior_rows)
print("Interpretation hint: if prior rows >> prior order_id nunique, it's 1-to-many (expected).")

--- orders.order_id → prior.order_id ---
orders: order_id nunique = 3421083 rows = 3421083
prior : order_id nunique = 3214874 rows = 32434489
Interpretation hint: if prior rows >> prior order_id nunique, it's 1-to-many (expected).

In [9]:
# products.product_id -> prior.product_id
products_pid_nunique = nunique_report(products, "product_id", "products")
prior_pid_nunique = nunique_report(prior, "product_id", "prior")

print("\n--- products.product_id → prior.product_id ---")
print("products: product_id nunique =", products_pid_nunique, "rows =", len(products))
print("prior   : product_id nunique =", prior_pid_nunique, "rows =", len(prior))
print("Interpretation hint: prior is many rows per product, products is 1 row per product (expected).")

--- products.product_id → prior.product_id ---
products: product_id nunique = 49688 rows = 49688
prior   : product_id nunique = 49677 rows = 32434489
Interpretation hint: prior is many rows per product, products is 1 row per product (expected).

In [10]:
# products.aisle_id -> aisles.aisle_id
print("\n--- products.aisle_id → aisles.aisle_id ---")
if "aisle_id" in products.columns and "aisle_id" in aisles.columns:
    print("products aisle_id nunique =", products["aisle_id"].nunique(), "rows =", len(products))
    print("aisles   aisle_id nunique =", aisles["aisle_id"].nunique(), "rows =", len(aisles))
else:
    print("⚠️ aisle_id not found in products or aisles")

--- products.aisle_id → aisles.aisle_id ---
products aisle_id nunique = 134 rows = 49688
aisles   aisle_id nunique = 134 rows = 134

In [11]:
# products.department_id -> departments.department_id
print("\n--- products.department_id → departments.department_id ---")
if "department_id" in products.columns and "department_id" in departments.columns:
    print("products department_id nunique =", products["department_id"].nunique(), "rows =", len(products))
    print("departments department_id nunique =", departments["department_id"].nunique(), "rows =", len(departments))
else:
    print("⚠️ department_id not found in products or departments")

--- products.department_id → departments.department_id ---
products department_id nunique = 21 rows = 49688
departments department_id nunique = 21 rows = 21

_4️⃣ User behavioral time structure (user-level summary)_

In [12]:
needed_cols = {"user_id", "order_id", "days_since_prior_order", "order_number"}
missing = needed_cols - set(orders.columns)
if missing:
    print(f"⚠️ orders is missing columns: {missing}, please check orders.csv")
else:
    user_summary = orders.groupby("user_id").agg(
        order_count=("order_id", "count"),
        days_since_prior_mean=("days_since_prior_order", "mean"),
        days_since_prior_max=("days_since_prior_order", "max"),
        max_order_number=("order_number", "max")
    ).reset_index()

    print("\n--- user_summary head(10) ---")
    display(user_summary.head(10))

    print("\n--- user_summary describe ---")
    display(user_summary.describe(include="all"))

--- user_summary head(10) ---

,user_id,order_count,days_since_prior_mean,days_since_prior_max,max_order_number
0,1,11,19.000000,30.0,11
1,2,15,16.285714,30.0,15
2,3,13,12.000000,21.0,13
3,4,6,17.000000,30.0,6
4,5,5,11.500000,19.0,5
5,6,4,13.333333,22.0,4
6,7,21,10.450000,30.0,21
7,8,4,23.333333,30.0,4
8,9,4,22.000000,30.0,4
9,10,6,21.800000,30.0,6

--- user_summary describe ---

,user_id,order_count,days_since_prior_mean,days_since_prior_max,max_order_number
count,206209.000000,206209.000000,206209.000000,206209.000000,206209.000000
mean,103105.000000,16.590367,15.448686,27.062068,16.590367
std,59527.555167,16.654774,6.915575,5.961237,16.654774
min,1.000000,4.000000,0.000000,0.000000,4.000000
25%,51553.000000,6.000000,9.814815,29.000000,6.000000
50%,103105.000000,10.000000,15.000000,30.000000,10.000000
75%,154657.000000,20.000000,20.625000,30.000000,20.000000
max,206209.000000,100.000000,30.000000,30.000000,100.000000

_5️⃣ Missing value check (all tables)_

In [13]:
for name, df in dfs.items():
    print(f"\n--- {name}: missing values ---")
    display(df.isnull().sum().sort_values(ascending=False))

--- aisles: missing values ---

aisle_id    0
aisle       0
dtype: int64

--- departments: missing values ---

department_id    0
department       0
dtype: int64

--- order_products_prior: missing values ---

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

--- order_products_train: missing values ---

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

--- orders: missing values ---

days_since_prior_order    206209
order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
dtype: int64

--- products: missing values ---

product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

In [14]:
# Check which tables were loaded

import pandas as pd

[var for var in globals() if isinstance(globals()[var], pd.DataFrame)]

['df',
 'orders',
 'prior',
 'train',
 'products',
 'aisles',
 'departments',
 'user_summary']

In [15]:
# Check loaded table contents

tables = [
    'df',
    'orders',
    'prior',
    'train',
    'products',
    'aisles',
    'departments',
    'user_summary'
]

for name in tables:
    table = globals()[name]
    
    print(f"\n{'='*50}")
    print(f"📊 Table: {name}")
    print(f"Shape: {table.shape}")
    print(f"Columns ({len(table.columns)}):")
    print(list(table.columns))

==================================================
📊 Table: df
Shape: (49688, 4)
Columns (4):
['product_id', 'product_name', 'aisle_id', 'department_id']

==================================================
📊 Table: orders
Shape: (3421083, 7)
Columns (7):
['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order']

==================================================
📊 Table: prior
Shape: (32434489, 4)
Columns (4):
['order_id', 'product_id', 'add_to_cart_order', 'reordered']

==================================================
📊 Table: train
Shape: (1384617, 4)
Columns (4):
['order_id', 'product_id', 'add_to_cart_order', 'reordered']

==================================================
📊 Table: products
Shape: (49688, 4)
Columns (4):
['product_id', 'product_name', 'aisle_id', 'department_id']

==================================================
📊 Table: aisles
Shape: (134, 2)
Columns (2):
['aisle_id', 'aisle']

==================================================
📊 Table: departments
Shape: (21, 2)
Columns (2):
['department_id', 'department']

==================================================
📊 Table: user_summary
Shape: (206209, 5)
Columns (5):
['user_id', 'order_count', 'days_since_prior_mean', 'days_since_prior_max', 'max_order_number']

In [16]:
# Check - 👉 whether prior + train are a subset of orders (split by eval_set)

print("orders order_id unique:", orders.order_id.nunique())
print("prior order_id unique:", prior.order_id.nunique())
print("train order_id unique:", train.order_id.nunique())

orders_prior = set(orders[orders.eval_set == 'prior'].order_id)
orders_train = set(orders[orders.eval_set == 'train'].order_id)

print("prior match:", orders_prior == set(prior.order_id))
print("train match:", orders_train == set(train.order_id))

print("prior ∩ train:", len(set(prior.order_id) & set(train.order_id)))

orders order_id unique: 3421083
prior order_id unique: 3214874
train order_id unique: 131209
prior match: True
train match: True
prior ∩ train: 0

# 📊 Section 1: Weekly Active Score Construction

> Build the orders_enriched2 + active_score_week master table

---

**Weekly Active Item (Active Score) Construction**

**Objective**: Build an order-level user activity metric that unifies "how much" (basket size) and "how often" (purchase interval) into one comparable dimension.

**Formula**:
    active_score_week = (items_per_order / days_since_prior_order) * 7

Converts each order into a "weekly-equivalent consumption level." First orders (no days_since_prior_order) are excluded.

**Usage**: Downstream user segmentation (high/mid/low), lifecycle comparison (early vs. late), and growth decomposition (frequency vs. basket) all build on this metric.

In [17]:
# Step 1: Count items per order
order_products = pd.concat([prior, train])

items_per_order = (
    order_products
    .groupby("order_id")
    .size()
    .reset_index(name="items_per_order")
)
# Step 2: Merge into orders

orders_enriched = (
    orders
    .merge(items_per_order, on="order_id", how="left")
)
# Step 3: Build order-level active score, then check overall distribution

orders_enriched = orders_enriched.dropna(subset=["days_since_prior_order"])

orders_enriched["active_score_week"] = (
    orders_enriched["items_per_order"] /
    orders_enriched["days_since_prior_order"]
) * 7
orders_enriched["active_score_week"].describe()

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    3.139874e+06
mean              inf
std               NaN
min      2.333333e-01
25%      3.266667e+00
50%      7.500000e+00
75%      1.633333e+01
max               inf
Name: active_score_week, dtype: float64

In [18]:
# Treat gap=0 as "same-day reorder", use 1 day as the minimum interval (no data dropped) - build new master table

import numpy as np
import pandas as pd

orders_enriched2 = orders_enriched.copy()

gap = orders_enriched2["days_since_prior_order"]

# Only drop NaN (first order)
orders_enriched2 = orders_enriched2.dropna(subset=["days_since_prior_order"]).copy()

# Treat 0-day gaps as a minimum 1-day interval (interpretable as same-day reorder)
orders_enriched2["gap_days_adj"] = orders_enriched2["days_since_prior_order"].clip(lower=1)

orders_enriched2["active_score_week"] = (
    orders_enriched2["items_per_order"] / orders_enriched2["gap_days_adj"]
) * 7

# sanity check
print("Inf:", np.isinf(orders_enriched2["active_score_week"]).sum())
print(orders_enriched2["active_score_week"].describe())

Inf: 0
count    3.139874e+06
mean     1.310056e+01
std      1.776134e+01
min      2.333333e-01
25%      3.266667e+00
50%      7.368421e+00
75%      1.633333e+01
max      6.860000e+02
Name: active_score_week, dtype: float64

_The above produced a new table, orders_enriched2, as the master analysis table, and computed weekly active score_

_Examine the distribution of user-level weekly active score_

# 🔍 Section 2: Active Score Distribution & 50% Cut Validation

> Distribution analysis + validate that the early/late split isn't confounded by lifecycle

In [19]:
# Build user-level active score

user_active = (
    orders_enriched2
    .groupby("user_id")["active_score_week"]
    .agg(["median", "mean", "std", "min", "max", "count"])
    .reset_index()
)

user_active.head()

   user_id    median      mean        std       min    max  count
0        1  2.050000  6.349725  12.586494  1.206897  42.00     10
1        2  7.924359  8.608659   5.281741  2.100000  22.75     14
2        3  5.000000  5.056279   2.721733  1.750000   9.00     11
3        4  1.633333  6.250877   9.858408  0.736842  21.00      4
4        5  5.074163  6.037081   3.112446  3.500000  10.50      4

In [20]:
print("User median distribution:")
print(user_active["median"].describe())

print("\nUser mean distribution:")
print(user_active["mean"].describe())

print("\nUser std distribution:")
print(user_active["std"].describe())

User median distribution:
count    206209.000000
mean          6.819123
std           6.506190
min           0.233333
25%           2.566667
50%           4.900000
75%           9.000000
max         154.000000
Name: median, dtype: float64

User mean distribution:
count    206209.000000
mean          9.188050
std           8.209834
min           0.233333
25%           3.597047
50%           6.953030
75%          12.282669
max         167.066667
Name: mean, dtype: float64

User std distribution:
count    206209.000000
mean          8.174997
std           9.590084
min           0.000000
25%           2.244135
50%           5.250341
75%          10.658789
max         267.416424
Name: std, dtype: float64

In [21]:
import numpy as np
import pandas as pd

df = orders_enriched2.copy()

# --- 0) Basic cleanup ---
# Keep only orders with a valid intensity value
df = df.dropna(subset=["user_id", "order_number", "active_score_week"])
df["order_number"] = df["order_number"].astype(int)

# Count orders per user
user_n = df.groupby("user_id")["order_id"].nunique().rename("n_orders")
df = df.merge(user_n, on="user_id", how="left")

# Keep only n_orders >= 6 (satisfies the lowest bucket, 6-10)
df6 = df[df["n_orders"] >= 6].copy()

# Bucket: 6-10 / 10-30 / 30+
def n_bucket(n):
    if 6 <= n < 10:
        return "6-10"
    elif 10 <= n < 30:
        return "10-30"
    else:
        return "30+"

df6["n_bucket"] = df6["n_orders"].apply(n_bucket)
# ① Group by order count, look at Δ Weekly (Early/Late 50%)
# Signal to watch for:
# If median / pct_upgrader rises clearly with n_bucket, that suggests a "more orders = more growth" stage effect.
# If roughly flat, the 50% split is relatively safe.

# --- 1) early/late 50%: split by order sequence number ---
# Use position = order_number / n_orders as relative position
df6["pos"] = df6["order_number"] / df6["n_orders"]

df6["half"] = np.where(df6["pos"] <= 0.5, "early", "late")

# User level: each user's typical early / late intensity (median is more robust)
user_half = (
    df6.groupby(["user_id", "n_orders", "n_bucket", "half"])["active_score_week"]
      .median()
      .unstack("half")
      .reset_index()
)

# Keep only users with both early and late
user_half = user_half.dropna(subset=["early", "late"])
user_half["delta_weekly"] = user_half["late"] - user_half["early"]

# Bucket summary (question of interest: does growth become more pronounced with more orders)
bucket_summary = (
    user_half.groupby("n_bucket")["delta_weekly"]
      .agg(
          users="count",
          mean="mean",
          median="median",
          p25=lambda s: s.quantile(0.25),
          p75=lambda s: s.quantile(0.75),
          pct_upgrader=lambda s: (s > 0).mean(),
          pct_sig_up=lambda s: (s > 1).mean(),   # threshold can be adjusted
          pct_down=lambda s: (s < 0).mean()
      )
      .sort_index()
)

display(bucket_summary)

# Also inspect the delta distribution description per bucket
display(user_half.groupby("n_bucket")["delta_weekly"].describe())

,users,mean,median,p25,p75,pct_upgrader,pct_sig_up,pct_down
n_bucket,,,,,,,,
10-30,70139,-0.137640,-0.046667,-2.291667,2.10,0.483454,0.347082,0.505453
30+,28639,0.797060,0.450000,-2.271780,3.50,0.532456,0.442578,0.432417
6-10,42693,-1.441793,-0.257197,-2.800000,1.35,0.441501,0.285621,0.548568

,count,mean,std,min,25%,50%,75%,max
n_bucket,,,,,,,,
10-30,70139.0,-0.137640,5.479643,-118.125000,-2.291667,-0.046667,2.10,96.600000
30+,28639.0,0.797060,6.002418,-77.000000,-2.271780,0.450000,3.50,57.750000
6-10,42693.0,-1.441793,7.964191,-164.383333,-2.800000,-0.257197,1.35,132.024038

In [22]:
# ② Check whether Δ Weekly correlates with order count (Pearson / Spearman)
# Signal to watch for:
# A clearly positive and non-trivial Spearman (e.g. >0.2) usually indicates a "more orders = more growth" stage effect.
# Close to 0 means no overall acceleration trend.

# --- 2) correlation between delta and n_orders ---
# Pearson (linear correlation), Spearman (monotonic correlation, more robust)
pearson = user_half["delta_weekly"].corr(user_half["n_orders"], method="pearson")
spearman = user_half["delta_weekly"].corr(user_half["n_orders"], method="spearman")

print("Correlation(delta_weekly, n_orders)")
print(f"  Pearson : {pearson:.4f}")
print(f"  Spearman: {spearman:.4f}")

# Optional: look at median delta by n_orders quantile, for a visual trend check
qcut_bins = pd.qcut(user_half["n_orders"], q=10, duplicates="drop")
trend = user_half.groupby(qcut_bins)["delta_weekly"].median()
display(trend)

Correlation(delta_weekly, n_orders)
  Pearson : 0.1079
  Spearman: 0.1120

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/259573871.py:17: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  trend = user_half.groupby(qcut_bins)["delta_weekly"].median()

n_orders
(5.999, 7.0]   -0.442105
(7.0, 8.0]     -0.087500
(8.0, 9.0]     -0.033333
(9.0, 11.0]    -0.216993
(11.0, 14.0]   -0.033333
(14.0, 17.0]   -0.095260
(17.0, 22.0]    0.000000
(22.0, 30.0]    0.083333
(30.0, 44.0]    0.343056
(44.0, 99.0]    0.600000
Name: delta_weekly, dtype: float64

In [23]:
# "Symmetric split" validation: first 30% vs. middle 30%, middle 30% vs. last 30%

df10 = df[df["n_orders"] >= 10].copy()  # for thirds, recommend at least 10 orders for stability
df10["pos"] = df10["order_number"] / df10["n_orders"]
df10["n_bucket"] = df10["n_orders"].apply(n_bucket)

def third_segment(pos):
    if pos <= 0.30:
        return "first30"
    elif (pos > 0.35) and (pos <= 0.65):
        return "mid30"
    elif pos > 0.70:
        return "last30"
    else:
        return np.nan  # orders falling in the buffer zone are excluded from comparison

df10["seg30"] = df10["pos"].apply(third_segment)
df10 = df10.dropna(subset=["seg30"])

user_30 = (
    df10.groupby(["user_id", "n_orders", "n_bucket", "seg30"])["active_score_week"]
        .median()
        .unstack("seg30")
        .reset_index()
)

# Keep only users with all three segments present
user_30 = user_30.dropna(subset=["first30", "mid30", "last30"])

user_30["delta_mid_first"] = user_30["mid30"] - user_30["first30"]
user_30["delta_last_mid"] = user_30["last30"] - user_30["mid30"]

# Overall summary: check for "linear increase"
overall_30 = user_30[["delta_mid_first", "delta_last_mid"]].agg(["count","mean","median",
                                                                lambda s: s.quantile(0.25),
                                                                lambda s: s.quantile(0.75)])
overall_30.index = ["count","mean","median","p25","p75"]
display(overall_30)

# Bucketed view: does "stronger in later stages" appear more often at higher order-count levels
bucket_30 = (
    user_30.groupby("n_bucket")[["delta_mid_first","delta_last_mid"]]
        .agg(["count","mean","median",
              lambda s: s.quantile(0.25),
              lambda s: s.quantile(0.75)])
)
# Clean up column names
bucket_30.columns = ["_".join([c for c in col if c and c != "<lambda>"]) for col in bucket_30.columns]
display(bucket_30)

# Also check "linearity": correlation between delta_last_mid and delta_mid_first
lin_pearson = user_30["delta_last_mid"].corr(user_30["delta_mid_first"], method="pearson")
lin_spearman = user_30["delta_last_mid"].corr(user_30["delta_mid_first"], method="spearman")
print("Linearity check corr(delta_mid_first, delta_last_mid)")
print(f"  Pearson : {lin_pearson:.4f}")
print(f"  Spearman: {lin_spearman:.4f}")

seg30   delta_mid_first  delta_last_mid
count      98778.000000    98778.000000
mean          -0.461528        0.205585
median        -0.131104        0.116667
p25           -2.947438       -2.350000
p75            2.362500        2.916667

,delta_mid_first_count,delta_mid_first_mean,delta_mid_first_median,delta_mid_first_<lambda_0>,delta_mid_first_<lambda_1>,delta_last_mid_count,delta_last_mid_mean,delta_last_mid_median,delta_last_mid_<lambda_0>,delta_last_mid_<lambda_1>
n_bucket,,,,,,,,,,
10-30,70139,-0.636950,-0.138889,-2.837461,2.208333,70139,-0.215435,-0.016667,-2.489236,2.290967
30+,28639,-0.031908,-0.097222,-3.222222,2.800000,28639,1.236694,0.923077,-2.083333,4.533333

Linearity check corr(delta_mid_first, delta_last_mid)
  Pearson : -0.3068
  Spearman: -0.2870

**Combined results from three validation tests:**

1. corr(delta_mid_first, delta_last_mid) = **-0.30**, a significant negative correlation — users with larger early-stage declines are more likely to rebound later, and vice versa
2. No significant lifecycle-driven linear acceleration observed
3. **50% order-based split** is a robust method for defining behavioral stages

> This reflects a shift in **behavioral stage**, not mechanical time-based acceleration.

# 🗂️ Section 3: User Segmentation (Low / Mid / High)

> Segment by business thresholds, build user_seg

---

**User Weekly Active Score Segmentation**

Method: based on 25th / 75th percentiles, rounded slightly

- Low: ≤ 3
- Mid: 3 – 9
- High: > 9

In [24]:
# Step 1: Segment by business thresholds

# Copy to avoid polluting the original table
user_seg = user_active.copy()

# Business segmentation
def segment(x):
    if x <= 3:
        return "Low"
    elif x <= 9:
        return "Mid"
    else:
        return "High"

user_seg["segment"] = user_seg["median"].apply(segment)
# Step 2: check segment proportions
seg_dist = (
    user_seg["segment"]
    .value_counts()
    .reindex(["Low", "Mid", "High"])
    .to_frame("users")
)

seg_dist["share"] = seg_dist["users"] / seg_dist["users"].sum()

display(seg_dist)

         users     share
segment
Low      62494  0.303061
Mid      92952  0.450766
High     50763  0.246173

In [25]:
# Step 3: check intensity structure within each segment
seg_stats = (
    user_seg.groupby("segment")["median"]
    .agg(
        users="count",
        mean="mean",
        median="median",
        p25=lambda s: s.quantile(0.25),
        p75=lambda s: s.quantile(0.75),
        min="min",
        max="max"
    )
    .reindex(["Low", "Mid", "High"])
)

display(seg_stats)

         users       mean  median        p25        p75       min    max
segment
Low      62494   1.734784    1.75   1.121795   2.333333  0.233333    3.0
Mid      92952   5.480286    5.25   4.000000   7.000000  3.000784    9.0
High     50763  15.529962   13.50  10.791667  17.750000  9.002778  154.0

_Check the relationship with observable lifecycle_

In [26]:
# 1) Compute user-level lifecycle (observation window)
user_lifecycle = (
    orders_enriched2
    .groupby("user_id")
    .agg(
        lifecycle_days=("gap_days_adj", "sum"),
        order_count=("order_id", "count")
    )
    .reset_index()
)

# 2) Merge in segment
user_lifecycle = user_lifecycle.merge(
    user_seg[["user_id", "segment", "median"]],
    on="user_id",
    how="left"
)

# 3) Check lifecycle distribution by segment
lifecycle_stats = (
    user_lifecycle
    .groupby("segment")
    .agg(
        users=("user_id", "count"),
        lifecycle_mean=("lifecycle_days", "mean"),
        lifecycle_median=("lifecycle_days", "median"),
        lifecycle_p25=("lifecycle_days", lambda s: s.quantile(0.25)),
        lifecycle_p75=("lifecycle_days", lambda s: s.quantile(0.75)),
        orders_mean=("order_count", "mean"),
        orders_median=("order_count", "median")
    )
    .reindex(["Low", "Mid", "High"])
)

display(lifecycle_stats)

,users,lifecycle_mean,lifecycle_median,lifecycle_p25,lifecycle_p75,orders_mean,orders_median
segment,,,,,,,
Low,62494,152.787052,133.0,90.0,201.0,8.529315,6.0
Mid,92952,176.564485,160.0,90.0,256.0,14.072511,10.0
High,50763,193.847034,183.0,73.0,325.0,27.062526,19.0

**Conclusion**: Intensity (active score) correlates with lifecycle but is not dominated by it → safe to proceed with further analysis.

# 🔄 Section 4: 9-Path Transition Analysis

> early/late segmentation → 9 paths → path_contribution

---

**Objective**: Build early / late user segments, to be used for the subsequent transition group analysis.

In [27]:
# Split orders by first vs. last 50%

# Step 1: label each order early / late

import numpy as np

df = orders_enriched2.copy()

# Count orders per user
user_n = df.groupby("user_id")["order_id"].nunique().rename("n_orders")
df = df.merge(user_n, on="user_id", how="left")

# Relative position
df["pos"] = df["order_number"] / df["n_orders"]

df["half"] = np.where(df["pos"] <= 0.5, "early", "late")

# Step 2: compute user-level early / late intensity (using median)
user_half = (
    df.groupby(["user_id", "half"])["active_score_week"]
      .median()
      .unstack("half")
      .reset_index()
)

user_half = user_half.dropna(subset=["early", "late"])

# Step 3: apply the earlier thresholds to segment early / late
def segment(x):
    if x <= 3:
        return "Low"
    elif x <= 9:
        return "Mid"
    else:
        return "High"

user_half["early_segment"] = user_half["early"].apply(segment)
user_half["late_segment"] = user_half["late"].apply(segment)

# Step 4: generate the 9-path label
def make_path(row):
    e = row["early_segment"]
    l = row["late_segment"]
    
    if e == "High":
        if l == "High":
            return "High Stay"
        elif l == "Mid":
            return "High Down to Mid"
        else:
            return "High Down to Low"
    
    elif e == "Mid":
        if l == "High":
            return "Mid Up to High"
        elif l == "Mid":
            return "Mid Stay"
        else:
            return "Mid Down to Low"
    
    else:  # Low
        if l == "High":
            return "Low Up to High"
        elif l == "Mid":
            return "Low Up to Mid"
        else:
            return "Low Stay"

user_half["path_9"] = user_half.apply(make_path, axis=1)

# Step 5: check the 9-path distribution
path_dist = (
    user_half["path_9"]
    .value_counts()
    .to_frame("users")
)

path_dist["share"] = path_dist["users"] / path_dist["users"].sum()

display(path_dist)

                  users     share
path_9
Mid Stay          45020  0.247060
Low Stay          33439  0.183506
High Stay         32345  0.177502
High Down to Mid  18107  0.099367
Low Up to Mid     16262  0.089242
Mid Down to Low   16018  0.087903
Mid Up to High    14752  0.080956
High Down to Low   3649  0.020025
Low Up to High     2631  0.014438

In [28]:
import numpy as np
import pandas as pd

# user_half already exists (contains: early, late, path_9)
# Make sure delta_weekly exists
if "delta_weekly" not in user_half.columns:
    user_half["delta_weekly"] = user_half["late"] - user_half["early"]

# Keep only key columns & drop missing
uh = user_half.dropna(subset=["path_9", "delta_weekly"]).copy()

# 1) Stats + contribution per path
path_contribution = (
    uh.groupby("path_9")["delta_weekly"]
      .agg(
          users="count",
          mean_delta="mean",
          median_delta="median",
          p25_delta=lambda s: s.quantile(0.25),
          p75_delta=lambda s: s.quantile(0.75),
          pct_upgrader=lambda s: (s > 0).mean(),
          pct_sig_up=lambda s: (s > 1).mean(),
          pct_down=lambda s: (s < 0).mean()
      )
      .reset_index()
)

# share
total_users = path_contribution["users"].sum()
path_contribution["share"] = path_contribution["users"] / total_users

# Net structural contribution: users × mean_delta (aggregate contribution)
path_contribution["net_contribution"] = path_contribution["users"] * path_contribution["mean_delta"]

# 2) Contribution share (of total net change)
total_net = path_contribution["net_contribution"].sum()

path_contribution["contribution_share_of_total_net"] = np.where(
    total_net != 0,
    path_contribution["net_contribution"] / total_net,
    np.nan
)

# 3) Sort by net contribution, descending
path_contribution = path_contribution.sort_values("net_contribution", ascending=False)

display(path_contribution)

print("\n========== Sanity checks ==========")
print(f"Total users in user_half: {uh['user_id'].nunique():,}")
print(f"Total users in contribution table: {total_users:,}")
print(f"Total net contribution (sum(users * mean_delta)): {total_net:,.4f}")

# Optional: also output "overall mean Δ × user count" as a consistency check
overall_mean_delta = uh["delta_weekly"].mean()
overall_net = overall_mean_delta * uh["delta_weekly"].count()
print(f"Overall mean delta: {overall_mean_delta:.6f}")
print(f"Overall net (overall_mean_delta * N): {overall_net:,.4f}")

,path_9,users,mean_delta,median_delta,p25_delta,p75_delta,pct_upgrader,pct_sig_up,pct_down,share,net_contribution,contribution_share_of_total_net
8,Mid Up to High,14752,7.385048,5.956731,3.850000,8.983333,1.000000,0.979664,0.000000,0.080956,108944.235449,-1.072304
5,Low Up to Mid,16262,2.894815,2.566667,1.594895,3.966667,1.000000,0.886053,0.000000,0.089242,47075.473634,-0.463349
4,Low Up to High,2631,12.664408,10.300000,8.361111,13.924653,1.000000,1.000000,0.000000,0.014438,33320.056309,-0.327959
3,Low Stay,33439,0.060278,0.029167,-0.458477,0.557355,0.511170,0.122013,0.457191,0.183506,2015.621941,-0.019839
7,Mid Stay,45020,-0.083792,-0.033333,-1.480769,1.283333,0.471790,0.290249,0.503754,0.247060,-3772.326991,0.037130
2,High Stay,32345,-0.580949,0.000000,-3.694444,3.600350,0.491946,0.420931,0.484155,0.177502,-18790.786193,0.184952
6,Mid Down to Low,16018,-2.902010,-2.566667,-4.000000,-1.605143,0.000000,0.000000,1.000000,0.087903,-46484.396510,0.457531
0,High Down to Low,3649,-15.886655,-11.291667,-17.266667,-8.609025,0.000000,0.000000,1.000000,0.020025,-57970.402859,0.570584
1,High Down to Mid,18107,-9.164179,-6.475758,-10.167210,-4.214205,0.000000,0.000000,1.000000,0.099367,-165935.781339,1.633253

========== Sanity checks ==========
Total users in user_half: 182,223
Total users in contribution table: 182,223
Total net contribution (sum(users * mean_delta)): -101,598.3066
Overall mean delta: -0.557549
Overall net (overall_mean_delta * N): -101,598.3066

In [29]:
# Re-sort by intensity

# Copy to avoid modifying the original table
pc = path_contribution.copy()

# ---- Positive-contribution paths (net contribution > 0) ----
positive_paths = (
    pc[pc["net_contribution"] > 0]
    .sort_values("net_contribution", ascending=False)
    .reset_index(drop=True)
)

print("📈 Positive Contribution Paths (High → Low)")
display(positive_paths[[
    "path_9", 
    "users", 
    "share",
    "mean_delta", 
    "net_contribution",
    "contribution_share_of_total_net"
]])

# ---- Negative-contribution paths (net contribution < 0) ----
negative_paths = (
    pc[pc["net_contribution"] < 0]
    .assign(abs_contribution=lambda x: x["net_contribution"].abs())
    .sort_values("abs_contribution", ascending=False)
    .drop(columns=["abs_contribution"])
    .reset_index(drop=True)
)

print("📉 Negative Contribution Paths (High → Low by absolute impact)")
display(negative_paths[[
    "path_9", 
    "users", 
    "share",
    "mean_delta", 
    "net_contribution",
    "contribution_share_of_total_net"
]])

📈 Positive Contribution Paths (High → Low)

,path_9,users,share,mean_delta,net_contribution,contribution_share_of_total_net
0,Mid Up to High,14752,0.080956,7.385048,108944.235449,-1.072304
1,Low Up to Mid,16262,0.089242,2.894815,47075.473634,-0.463349
2,Low Up to High,2631,0.014438,12.664408,33320.056309,-0.327959
3,Low Stay,33439,0.183506,0.060278,2015.621941,-0.019839

📉 Negative Contribution Paths (High → Low by absolute impact)

,path_9,users,share,mean_delta,net_contribution,contribution_share_of_total_net
0,High Down to Mid,18107,0.099367,-9.164179,-165935.781339,1.633253
1,High Down to Low,3649,0.020025,-15.886655,-57970.402859,0.570584
2,Mid Down to Low,16018,0.087903,-2.902010,-46484.396510,0.457531
3,High Stay,32345,0.177502,-0.580949,-18790.786193,0.184952
4,Mid Stay,45020,0.247060,-0.083792,-3772.326991,0.037130

In [30]:
# Do not modify user_half
uh = user_half.copy()

# Compute early distribution
early_dist = (
    uh["early_segment"]
    .value_counts()
    .reindex(["Low", "Mid", "High"])
    .to_frame("early_users")
)

early_dist["early_share"] = early_dist["early_users"] / early_dist["early_users"].sum()

# Compute late distribution
late_dist = (
    uh["late_segment"]
    .value_counts()
    .reindex(["Low", "Mid", "High"])
    .to_frame("late_users")
)

late_dist["late_share"] = late_dist["late_users"] / late_dist["late_users"].sum()

# Merge into a new table
segment_shift_table = early_dist.join(late_dist)

display(segment_shift_table)

               early_users  early_share  late_users  late_share
early_segment
Low                  52332     0.287187       53106    0.291434
Mid                  75790     0.415919       79389    0.435669
High                 54101     0.296894       49728    0.272896

# 🧠 Section 5: User Dynamics Classification

> Stepper / Drifter / Oscillator / Immature dynamics classification

---

In [31]:
orders_enriched2.groupby("user_id")["order_number"].max().describe()

count    206209.000000
mean         16.590367
std          16.654774
min           4.000000
25%           6.000000
50%          10.000000
75%          20.000000
max         100.000000
Name: order_number, dtype: float64

**Terminology note**: In the code below, "week" actually refers to "one order / one order point" (more precisely: one order-index time step), not a calendar week.

In [32]:
# =========================
# Main labels on orders_enriched2 (active_score_week)
# Outputs: user_tags_main  (user-level labels)
# NOTE: does NOT modify orders_enriched2
# =========================

import numpy as np
import pandas as pd

# -------------------------
# Config (from our agreed defaults)
# -------------------------
USER_COL = "user_id"
TIME_COL = "order_number"          # order-index as time
VAL_COL  = "active_score_week"     # your weekly intensity proxy

MIN_WEEKS_MATURE = 12
MIN_POST_WEEKS   = 4
EXCLUDE_LAST     = True

BAND_MULT = 1.5
MIN_BAND = 2.0
EPS       = 1e-6

# Stepper
Z_STEPPER = 3.0
STEPPER_CONFIRM_WEEKS = 3
SHIFT_STEPPER = 0.20
SIDE_CONSISTENCY = 2/3

# Drifter
DRIFT_SAME_SIGN_PCT = 0.60
SHIFT_DRIFT = 0.15

# Oscillator
OSC_Z_IN_BAND = 1.2
OSC_IN_BAND_PCT = 0.75

In [33]:
# -------------------------
# Helpers
# -------------------------
def mad(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    m = np.median(x)
    return float(np.median(np.abs(x - m)))

def label_one_user_from_series(y: np.ndarray) -> dict:
    y = np.asarray(y, dtype=float)
    n = int(len(y))

    if n < MIN_WEEKS_MATURE:
        return {"n_points": n, "baseline_weeks": np.nan, "baseline": np.nan, "band": np.nan,
                "label": "immature", "reason": f"n_points<{MIN_WEEKS_MATURE}"}

    baseline_weeks = int(max(6, int(np.ceil(0.2 * n))))
    base = y[:baseline_weeks]
    baseline = float(np.median(base))
    band = float(max(MIN_BAND, BAND_MULT * mad(base), EPS))

    post = y[baseline_weeks:]
    if EXCLUDE_LAST and len(post) > 0:
        post = post[:-1]

    if len(post) < MIN_POST_WEEKS:
        return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
                "label": "uncertain", "reason": f"post_points<{MIN_POST_WEEKS}"}

    post_z = (post - baseline) / band

    # Stepper
    step_idx = np.where(np.abs(post_z) >= Z_STEPPER)[0]
    if len(step_idx) > 0:
        t0 = int(step_idx[0])
        after = post[t0+1:]
        if len(after) >= STEPPER_CONFIRM_WEEKS:
            after_slice = after[:STEPPER_CONFIRM_WEEKS]
            after_med = float(np.median(after_slice))
            shift = (after_med - baseline) / max(abs(baseline), EPS)

            side = np.sign(after_med - baseline)
            side_cons = float(np.mean(np.sign(after_slice - baseline) == side)) if side != 0 else 0.0

            if (abs(shift) >= SHIFT_STEPPER) and (side_cons >= SIDE_CONSISTENCY):
                return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
                        "label": "stepper",
                        "reason": f"|z|>={Z_STEPPER} at post_idx={t0}; shift={shift:.2f}; side_cons={side_cons:.2f}"}

    # Drifter
    drift_w = int(max(6, int(np.ceil(0.4 * len(post)))))
    drift_w = min(drift_w, len(post))
    tail = post[-drift_w:]
    tail_z = post_z[-drift_w:]

    same_sign_pct = float(max(np.mean(tail_z > 0), np.mean(tail_z < 0)))
    tail_med = float(np.median(tail))
    shift_tail = (tail_med - baseline) / max(abs(baseline), EPS)

    if (same_sign_pct >= DRIFT_SAME_SIGN_PCT) and (abs(shift_tail) >= SHIFT_DRIFT):
        return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
                "label": "drifter",
                "reason": f"tail_w={drift_w}; same_sign={same_sign_pct:.2f}; shift={shift_tail:.2f}"}

    # Oscillator
    osc_w = int(max(8, int(np.ceil(0.5 * len(post)))))
    osc_w = min(osc_w, len(post))
    tail2_z = post_z[-osc_w:]
    in_band_pct = float(np.mean(np.abs(tail2_z) < OSC_Z_IN_BAND))

    if in_band_pct >= OSC_IN_BAND_PCT:
        return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
                "label": "oscillator",
                "reason": f"osc_w={osc_w}; in_band={in_band_pct:.2f}"}

    return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
            "label": "mixed",
            "reason": f"no_match (drift_same_sign={same_sign_pct:.2f}, drift_shift={shift_tail:.2f}, osc_in_band={in_band_pct:.2f})"}
# ===== build input =====
x = (
    orders_enriched2[[USER_COL, TIME_COL, VAL_COL]]
    .dropna(subset=[VAL_COL])
    .sort_values([USER_COL, TIME_COL])
)

# ===== label users (stable column names) =====
rows = []
for uid, s in x.groupby(USER_COL, sort=False)[VAL_COL]:
    d = label_one_user_from_series(s.to_numpy())
    d[USER_COL] = uid
    rows.append(d)

user_tags_main = pd.DataFrame(rows)

print("✅ user_tags_main created:", user_tags_main.shape)
print(user_tags_main["label"].value_counts(dropna=False))
display(user_tags_main.head(10))

✅ user_tags_main created: (206209, 7)
label
immature      121617
stepper        39256
drifter        32466
oscillator      7751
mixed           5119
Name: count, dtype: int64

,n_points,baseline_weeks,baseline,band,label,reason,user_id
0,10,NaN,NaN,NaN,immature,n_points<12,1
1,14,6.0,11.341346,2.00,drifter,tail_w=6; same_sign=0.83; shift=-0.41,2
2,11,NaN,NaN,NaN,immature,n_points<12,3
3,4,NaN,NaN,NaN,immature,n_points<12,4
4,4,NaN,NaN,NaN,immature,n_points<12,5
5,2,NaN,NaN,NaN,immature,n_points<12,6
6,20,6.0,5.250000,5.55,stepper,|z|>=3.0 at post_idx=7; shift=1.06; side_cons=...,7
7,3,NaN,NaN,NaN,immature,n_points<12,8
8,3,NaN,NaN,NaN,immature,n_points<12,9
9,5,NaN,NaN,NaN,immature,n_points<12,10

In [34]:
# Check results

# Absolute counts
print(user_tags_main["label"].value_counts(dropna=False))

# Proportions
print(
    user_tags_main["label"]
    .value_counts(normalize=True, dropna=False)
    .round(4)
)

label
immature      121617
stepper        39256
drifter        32466
oscillator      7751
mixed           5119
Name: count, dtype: int64
label
immature      0.5898
stepper       0.1904
drifter       0.1574
oscillator    0.0376
mixed         0.0248
Name: proportion, dtype: float64

**New table: `user_tags_main`**

Primary user dynamics classification table, based on raw weekly active score, split into three main categories: **stepper / drifter / oscillator** (+ immature).

Next step: compute log weekly for stepper users, to test whether it smooths out the impact of gap day being used as the denominator.

In [35]:
USER_COL = "user_id"
TIME_COL = "order_number"
VAL_COL  = "active_score_week"

# ===== switches =====
USE_LOG = True  # log(weekly)

# ===== params (same logic, rescaled for log) =====
MIN_WEEKS_MATURE = 12
MIN_POST_WEEKS   = 4
EXCLUDE_LAST     = True

BAND_MULT = 1.5
EPS       = 1e-6

# ---- LOG-scale band floor (critical) ----
MIN_BAND_LOG = 0.15   # try 0.10~0.25
MIN_BAND_RAW = 2.0    # your raw setting (unused when USE_LOG=True)

# Stepper
Z_STEPPER = 2.5
STEPPER_CONFIRM_WEEKS = 3
SIDE_CONSISTENCY = 2/3

# shift threshold
SHIFT_STEPPER_LOG = 0.20  # exp(0.20)=1.22 (~+22%)
SHIFT_STEPPER_RAW = 0.20  # your old ratio (unused when USE_LOG=True)

# Drifter
DRIFT_SAME_SIGN_PCT = 0.60
SHIFT_DRIFT_LOG = 0.15     # exp(0.15)=1.16 (~+16%)
SHIFT_DRIFT_RAW = 0.15

# Oscillator
OSC_Z_IN_BAND = 1.2
OSC_IN_BAND_PCT = 0.75

In [36]:
def mad(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    m = np.median(x)
    return float(np.median(np.abs(x - m)))

def label_one_user_from_series(y: np.ndarray) -> dict:
    y = np.asarray(y, dtype=float)
    n = int(len(y))

    if n < MIN_WEEKS_MATURE:
        return {"n_points": n, "baseline_weeks": np.nan, "baseline": np.nan, "band": np.nan,
                "label": "immature", "reason": f"n_points<{MIN_WEEKS_MATURE}"}

    baseline_weeks = int(max(6, int(np.ceil(0.2 * n))))
    base = y[:baseline_weeks]
    baseline = float(np.median(base))

    # band floor by scale
    min_band = MIN_BAND_LOG if USE_LOG else MIN_BAND_RAW
    band = float(max(min_band, BAND_MULT * mad(base), EPS))

    post = y[baseline_weeks:]
    if EXCLUDE_LAST and len(post) > 0:
        post = post[:-1]

    if len(post) < MIN_POST_WEEKS:
        return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
                "label": "uncertain", "reason": f"post_points<{MIN_POST_WEEKS}"}

    post_z = (post - baseline) / band

    # thresholds by scale
    shift_step = SHIFT_STEPPER_LOG if USE_LOG else SHIFT_STEPPER_RAW
    shift_drift = SHIFT_DRIFT_LOG if USE_LOG else SHIFT_DRIFT_RAW

    # Stepper
    step_idx = np.where(np.abs(post_z) >= Z_STEPPER)[0]
    if len(step_idx) > 0:
        t0 = int(step_idx[0])
        after = post[t0+1:]
        if len(after) >= STEPPER_CONFIRM_WEEKS:
            after_slice = after[:STEPPER_CONFIRM_WEEKS]
            after_med = float(np.median(after_slice))
            shift = (after_med - baseline)  # log-space uses difference (still ok for raw too)

            side = np.sign(after_med - baseline)
            side_cons = float(np.mean(np.sign(after_slice - baseline) == side)) if side != 0 else 0.0

            if (abs(shift) >= shift_step) and (side_cons >= SIDE_CONSISTENCY):
                return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
                        "label": "stepper",
                        "reason": f"|z|>={Z_STEPPER} at post_idx={t0}; shift={shift:.3f}; side_cons={side_cons:.2f}"}

    # Drifter
    drift_w = int(max(6, int(np.ceil(0.4 * len(post)))))
    drift_w = min(drift_w, len(post))
    tail = post[-drift_w:]
    tail_z = post_z[-drift_w:]

    same_sign_pct = float(max(np.mean(tail_z > 0), np.mean(tail_z < 0)))
    tail_med = float(np.median(tail))
    shift_tail = (tail_med - baseline)  # log-space diff

    if (same_sign_pct >= DRIFT_SAME_SIGN_PCT) and (abs(shift_tail) >= shift_drift):
        return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
                "label": "drifter",
                "reason": f"tail_w={drift_w}; same_sign={same_sign_pct:.2f}; shift={shift_tail:.3f}"}

    # Oscillator
    osc_w = int(max(8, int(np.ceil(0.5 * len(post)))))
    osc_w = min(osc_w, len(post))
    tail2_z = post_z[-osc_w:]
    in_band_pct = float(np.mean(np.abs(tail2_z) < OSC_Z_IN_BAND))

    if in_band_pct >= OSC_IN_BAND_PCT:
        return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
                "label": "oscillator",
                "reason": f"osc_w={osc_w}; in_band={in_band_pct:.2f}"}

    return {"n_points": n, "baseline_weeks": baseline_weeks, "baseline": baseline, "band": band,
            "label": "mixed",
            "reason": f"no_match (drift_same_sign={same_sign_pct:.2f}, drift_shift={shift_tail:.3f}, osc_in_band={in_band_pct:.2f})"}
# ===== build input =====
x = (
    orders_enriched2[[USER_COL, TIME_COL, VAL_COL]]
    .dropna(subset=[VAL_COL])
    .copy()
)
x = x[x[VAL_COL] > 0].copy()
x = x.sort_values([USER_COL, TIME_COL])

if USE_LOG:
    x["val_used"] = np.log(x[VAL_COL].astype(float))
else:
    x["val_used"] = x[VAL_COL].astype(float)

rows = []
for uid, s in x.groupby(USER_COL, sort=False)["val_used"]:
    d = label_one_user_from_series(s.to_numpy())
    d[USER_COL] = uid
    rows.append(d)

user_tags_main_stepper_log_v2 = pd.DataFrame(rows)

print("✅ user_tags_main_stepper_log_v2 created:", user_tags_main_stepper_log_v2.shape)
print(user_tags_main_stepper_log_v2["label"].value_counts(dropna=False))

share = user_tags_main_stepper_log_v2["label"].value_counts(normalize=True).rename("proportion")
display(share)

✅ user_tags_main_stepper_log_v2 created: (206209, 7)
label
immature      121617
stepper        38034
drifter        33013
oscillator      7559
mixed           5986
Name: count, dtype: int64

label
immature      0.589775
stepper       0.184444
drifter       0.160095
oscillator    0.036657
mixed         0.029029
Name: proportion, dtype: float64

In [37]:
# Rename to master table: user_dynamics_log (used consistently in later dynamics analysis)

user_dynamics_log = user_tags_main_stepper_log_v2.copy()
del user_tags_main_stepper_log_v2

In [38]:
# ===============================
# Path × Dynamics Cross Table
# ===============================

import pandas as pd

# ---- 1) Merge ----
path_dyn = (
    user_half[["user_id", "path_9"]]
    .merge(
        user_dynamics_log[["user_id", "label"]],
        on="user_id",
        how="left"
    )
)

print("Merged table shape:", path_dyn.shape)

# ---- 2) Raw counts ----
cross_counts = (
    path_dyn
    .groupby(["path_9", "label"])
    .size()
    .unstack(fill_value=0)
)

print("\n=== Raw Counts ===")
display(cross_counts)

# ---- 3) Row-wise share (within path) ----
cross_row_share = (
    cross_counts
    .div(cross_counts.sum(axis=1), axis=0)
)

print("\n=== Row Share (Within Path) ===")
display(cross_row_share.round(3))

# ---- 4) Column-wise share (within dynamics) ----
cross_col_share = (
    cross_counts
    .div(cross_counts.sum(axis=0), axis=1)
)

print("\n=== Column Share (Within Dynamics) ===")
display(cross_col_share.round(3))

# ---- 5) Save results (optional)
path_dyn_counts = cross_counts
path_dyn_row_share = cross_row_share
path_dyn_col_share = cross_col_share

print("\nNew tables created:")
print(" - path_dyn (merged user-level table)")
print(" - path_dyn_counts")
print(" - path_dyn_row_share")
print(" - path_dyn_col_share")

Merged table shape: (182223, 3)

=== Raw Counts ===

label             drifter  immature  mixed  oscillator  stepper
path_9
High Down to Low      217      3038      3           3      388
High Down to Mid     3413      9419    358         478     4439
High Stay            7995      8885   2153        2626    10686
Low Stay             3565     25128    723         867     3156
Low Up to High        287      1693      2           4      645
Low Up to Mid        2264     10993    148         248     2609
Mid Down to Low      2227     11085    171         222     2313
Mid Stay             9228     21736   2175        2702     9179
Mid Up to High       3817      5654    253         409     4619

=== Row Share (Within Path) ===

label             drifter  immature  mixed  oscillator  stepper
path_9
High Down to Low    0.059     0.833  0.001       0.001    0.106
High Down to Mid    0.188     0.520  0.020       0.026    0.245
High Stay           0.247     0.275  0.067       0.081    0.330
Low Stay            0.107     0.751  0.022       0.026    0.094
Low Up to High      0.109     0.643  0.001       0.002    0.245
Low Up to Mid       0.139     0.676  0.009       0.015    0.160
Mid Down to Low     0.139     0.692  0.011       0.014    0.144
Mid Stay            0.205     0.483  0.048       0.060    0.204
Mid Up to High      0.259     0.383  0.017       0.028    0.313

=== Column Share (Within Dynamics) ===

label             drifter  immature  mixed  oscillator  stepper
path_9
High Down to Low    0.007     0.031  0.001       0.000    0.010
High Down to Mid    0.103     0.096  0.060       0.063    0.117
High Stay           0.242     0.091  0.360       0.347    0.281
Low Stay            0.108     0.257  0.121       0.115    0.083
Low Up to High      0.009     0.017  0.000       0.001    0.017
Low Up to Mid       0.069     0.113  0.025       0.033    0.069
Mid Down to Low     0.067     0.114  0.029       0.029    0.061
Mid Stay            0.280     0.223  0.363       0.357    0.241
Mid Up to High      0.116     0.058  0.042       0.054    0.121

New tables created:
 - path_dyn (merged user-level table)
 - path_dyn_counts
 - path_dyn_row_share
 - path_dyn_col_share

In [39]:
# Check the new table

path_dyn.head()

   user_id            path_9     label
0        1          Low Stay  immature
1        2  High Down to Mid   drifter
2        3          Mid Stay  immature
3        4          Low Stay  immature
4        5          Mid Stay  immature

**Stepper Subtype Definitions**

- `stable_up` — jumps up and stays at the new level
- `stable_down` — jumps down and stays at the new level
- `reverse_up` — rises then falls back
- `reverse_down` — falls then rebounds

In [40]:
# ============================================================
# Stepper subtype labeling (stable/reverse × up/down) on LOG weekly
# Input:
#   - user_dynamics_log  (user-level main labels; must contain: user_id, label, baseline_weeks, baseline, band)
#   - orders_enriched2   (order-level; must contain: user_id, order_number, active_score_week)
# Output (NEW, does NOT modify sources):
#   - user_dynamics_log_stepper_detail  (all steppers with subtype + diagnostics)
# ============================================================

import numpy as np
import pandas as pd

# -------------------------
# Config (match your v2 log params)
# -------------------------
USER_COL = "user_id"
TIME_COL = "order_number"
VAL_COL  = "active_score_week"

USE_LOG = True

# stepper detection params (must match your main labeling run)
Z_STEPPER = 2.5
STEPPER_CONFIRM_WEEKS = 3
SIDE_CONSISTENCY = 2/3

# log thresholds
SHIFT_STEPPER_LOG = 0.20   # stable threshold (≈ +22%)
SHIFT_DRIFT_LOG   = 0.10   # reverse threshold (looser; ≈ +10%)

# band floor on log scale (must match your main labeling run)
MIN_BAND_LOG = 0.15
BAND_MULT = 1.5
EPS = 1e-6

# tail window rule for subtype stability
MIN_TAIL_W = 6
TAIL_FRAC  = 0.30  # last 30% of post points (>=6)

In [41]:
# -------------------------
# Safety checks
# -------------------------
if "orders_enriched2" not in globals():
    raise ValueError("orders_enriched2 not found in globals()")
if "user_dynamics_log" not in globals():
    raise ValueError("user_dynamics_log not found in globals() (you said you renamed it to user_dynamics_log)")

needed_orders = [USER_COL, TIME_COL, VAL_COL]
missing_orders = [c for c in needed_orders if c not in orders_enriched2.columns]
if missing_orders:
    raise ValueError(f"orders_enriched2 missing columns: {missing_orders}")

needed_user = [USER_COL, "label", "baseline_weeks", "baseline", "band"]
missing_user = [c for c in needed_user if c not in user_dynamics_log.columns]
if missing_user:
    raise ValueError(f"user_dynamics_log missing columns: {missing_user}")

In [42]:
# -------------------------
# 0) Select stepper users (from your FINAL log-based main table)
# -------------------------
steppers = user_dynamics_log.loc[user_dynamics_log["label"] == "stepper", needed_user].copy()
print("Stepper users:", steppers.shape[0])

if steppers.shape[0] == 0:
    raise ValueError("No stepper users found in user_dynamics_log. Check that you're using the correct main table.")

Stepper users: 38034

In [43]:
# -------------------------
# 1) Pull their order-level weekly series and log-transform
# -------------------------
x = (
    orders_enriched2.loc[orders_enriched2[USER_COL].isin(steppers[USER_COL]), [USER_COL, TIME_COL, VAL_COL]]
    .dropna(subset=[VAL_COL])
    .sort_values([USER_COL, TIME_COL])
    .copy()
)

# active_score_week can be 0-ish in rare cases; protect for log
x["weekly_raw"] = pd.to_numeric(x[VAL_COL], errors="coerce")
x = x.dropna(subset=["weekly_raw"])
x = x.loc[x["weekly_raw"] > 0].copy()

x["weekly_log"] = np.log(x["weekly_raw"].astype(float))

# merge baseline/band/baseline_weeks from main table
x = x.merge(
    steppers[[USER_COL, "baseline_weeks", "baseline", "band"]],
    on=USER_COL,
    how="left"
)

# ensure band floor consistent with your log setup
x["band"] = x["band"].astype(float)
x["band"] = x["band"].where(np.isfinite(x["band"]), np.nan)
x["band"] = x["band"].fillna(MIN_BAND_LOG)
x["band"] = np.maximum(x["band"], MIN_BAND_LOG)
# -------------------------
# 2) Per-user subtype classifier
# -------------------------
def classify_stepper_subtype(g: pd.DataFrame) -> dict:
    g = g.sort_values(TIME_COL).copy()

    uid = int(g[USER_COL].iloc[0])
    baseline_weeks = int(g["baseline_weeks"].iloc[0])
    baseline = float(g["baseline"].iloc[0])  # log baseline
    band = float(g["band"].iloc[0])

    y = g["weekly_log"].to_numpy(dtype=float)
    n = int(len(y))

    # baseline / post split (same logic as your main labeling)
    if baseline_weeks >= n:
        return {
            USER_COL: uid,
            "n_points": n,
            "step_order": np.nan,
            "step_post_idx": np.nan,
            "step_direction": "unknown",
            "shift_confirm": np.nan,
            "shift_tail": np.nan,
            "side_cons_tail": np.nan,
            "tail_w": np.nan,
            "stepper_subtype": "stepper_unknown",
            "reason": "baseline_weeks>=n_points"
        }

    post = y[baseline_weeks:]
    if len(post) <= 1:
        return {
            USER_COL: uid,
            "n_points": n,
            "step_order": np.nan,
            "step_post_idx": np.nan,
            "step_direction": "unknown",
            "shift_confirm": np.nan,
            "shift_tail": np.nan,
            "side_cons_tail": np.nan,
            "tail_w": np.nan,
            "stepper_subtype": "stepper_unknown",
            "reason": "post_too_short"
        }

    post_z = (post - baseline) / max(band, EPS)

    # find first z-hit (same as main stepper)
    step_idx = np.where(np.abs(post_z) >= Z_STEPPER)[0]
    if len(step_idx) == 0:
        return {
            USER_COL: uid,
            "n_points": n,
            "step_order": np.nan,
            "step_post_idx": np.nan,
            "step_direction": "unknown",
            "shift_confirm": np.nan,
            "shift_tail": np.nan,
            "side_cons_tail": np.nan,
            "tail_w": np.nan,
            "stepper_subtype": "stepper_unknown",
            "reason": "no_z_hit_found_in_post"
        }

    t0 = int(step_idx[0])  # post index where it first hits z
    # map to original order_number for interpretability
    # post starts at baseline_weeks index, so absolute idx = baseline_weeks + t0
    abs_idx = baseline_weeks + t0
    step_order = int(g.iloc[abs_idx][TIME_COL])

    # confirm window: take K points AFTER step point
    after = post[t0+1:]
    if len(after) < STEPPER_CONFIRM_WEEKS:
        return {
            USER_COL: uid,
            "n_points": n,
            "step_order": step_order,
            "step_post_idx": t0,
            "step_direction": "unknown",
            "shift_confirm": np.nan,
            "shift_tail": np.nan,
            "side_cons_tail": np.nan,
            "tail_w": np.nan,
            "stepper_subtype": "stepper_unknown",
            "reason": "not_enough_after_for_confirm"
        }

    confirm_slice = after[:STEPPER_CONFIRM_WEEKS]
    confirm_med = float(np.median(confirm_slice))
    shift_confirm = float(confirm_med - baseline)

    # direction
    if shift_confirm > 0:
        direction = "up"
    elif shift_confirm < 0:
        direction = "down"
    else:
        direction = "flat"

    # tail window for stability check (use AFTER slice, not including baseline window)
    # Here we use the whole post (after baseline), but stability is best evaluated on "after step"
    after_all = after  # all points after the step hit
    if len(after_all) == 0:
        return {
            USER_COL: uid,
            "n_points": n,
            "step_order": step_order,
            "step_post_idx": t0,
            "step_direction": direction,
            "shift_confirm": shift_confirm,
            "shift_tail": np.nan,
            "side_cons_tail": np.nan,
            "tail_w": np.nan,
            "stepper_subtype": "stepper_reverse_" + ("up" if direction == "up" else "down"),
            "reason": "no_points_after_step"
        }

    tail_w = int(max(MIN_TAIL_W, int(np.ceil(TAIL_FRAC * len(after_all)))))
    tail_w = min(tail_w, len(after_all))
    tail = after_all[-tail_w:]

    tail_med = float(np.median(tail))
    shift_tail = float(tail_med - baseline)

    # side consistency in tail vs direction
    if direction in ("up", "down"):
        side = 1.0 if direction == "up" else -1.0
        side_cons_tail = float(np.mean(np.sign(tail - baseline) == side))
    else:
        side_cons_tail = float(np.mean(np.sign(tail - baseline) == 0))

    # stable criteria (log-space)
    if direction == "up":
        stable = (shift_tail >= SHIFT_STEPPER_LOG) and (side_cons_tail >= SIDE_CONSISTENCY)
        # reverse heuristic: tail loses advantage
        # (you can keep this as "not stable" if you want it simpler)
        subtype = "stepper_stable_up" if stable else "stepper_reverse_up"

    elif direction == "down":
        stable = (shift_tail <= -SHIFT_STEPPER_LOG) and (side_cons_tail >= SIDE_CONSISTENCY)
        subtype = "stepper_stable_down" if stable else "stepper_reverse_down"

    else:
        subtype = "stepper_unknown"

    return {
        USER_COL: uid,
        "n_points": n,
        "baseline_weeks": baseline_weeks,
        "step_order": step_order,
        "step_post_idx": t0,
        "step_direction": direction,
        "shift_confirm": shift_confirm,
        "shift_tail": shift_tail,
        "side_cons_tail": side_cons_tail,
        "tail_w": tail_w,
        "stepper_subtype": subtype,
        "confirm_mult": float(np.exp(shift_confirm)),  # translate to multiplier
        "tail_mult": float(np.exp(shift_tail)),        # translate to multiplier
        "reason": f"z_hit@post={t0}; confirmK={STEPPER_CONFIRM_WEEKS}; tail_w={tail_w}"
    }
# -------------------------
# 3) Run classification (no source table modified)
# -------------------------
detail_rows = (
    x.groupby(USER_COL, sort=False)
     .apply(lambda g: pd.Series(classify_stepper_subtype(g), dtype="object"))
     .reset_index(drop=True)
)

# This is your requested table name:
user_dynamics_log_stepper_detail = detail_rows.copy()

print("✅ user_dynamics_log_stepper_detail created:", user_dynamics_log_stepper_detail.shape)
print(user_dynamics_log_stepper_detail["stepper_subtype"].value_counts(dropna=False))

display(user_dynamics_log_stepper_detail.head(10))

✅ user_dynamics_log_stepper_detail created: (38034, 14)
stepper_subtype
stepper_stable_up       11724
stepper_stable_down     10838
stepper_reverse_down     8737
stepper_reverse_up       6735
Name: count, dtype: int64

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/2059477608.py:197: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series(classify_stepper_subtype(g), dtype="object"))

,user_id,n_points,baseline_weeks,step_order,step_post_idx,step_direction,shift_confirm,shift_tail,side_cons_tail,tail_w,stepper_subtype,confirm_mult,tail_mult,reason
0,15,21,6,17,9,up,0.356475,0.307685,0.600000,5,stepper_reverse_up,1.428286,1.360272,z_hit@post=9; confirmK=3; tail_w=5
1,17,40,8,11,1,down,-0.312077,-1.123007,1.000000,9,stepper_stable_down,0.731925,0.325300,z_hit@post=1; confirmK=3; tail_w=9
2,22,14,6,11,3,up,1.673976,1.530135,0.750000,4,stepper_stable_up,5.333333,4.618802,z_hit@post=3; confirmK=3; tail_w=4
3,24,18,6,8,0,down,-0.587787,0.905981,0.166667,6,stepper_reverse_down,0.555556,2.474358,z_hit@post=0; confirmK=3; tail_w=6
4,27,81,17,25,6,down,-1.791759,0.262218,0.333333,18,stepper_reverse_down,0.166667,1.299810,z_hit@post=6; confirmK=3; tail_w=18
5,37,23,6,8,0,down,-0.537143,-0.723067,0.833333,6,stepper_stable_down,0.584416,0.485262,z_hit@post=0; confirmK=3; tail_w=6
6,50,67,14,33,17,up,0.405465,0.336472,0.818182,11,stepper_stable_up,1.500000,1.400000,z_hit@post=17; confirmK=3; tail_w=11
7,52,27,6,20,12,down,-1.108922,-0.680488,0.666667,6,stepper_stable_down,0.329914,0.506370,z_hit@post=12; confirmK=3; tail_w=6
8,54,76,16,22,4,up,0.211789,0.378843,0.647059,17,stepper_reverse_up,1.235887,1.460593,z_hit@post=4; confirmK=3; tail_w=17
9,56,12,6,8,0,down,-0.481480,-0.481480,1.000000,5,stepper_stable_down,0.617868,0.617868,z_hit@post=0; confirmK=3; tail_w=5

In [44]:
# merged into the path 9 table
# =========================
# Build path_dyn_step
# =========================

# 1) Confirm base tables exist
required_tables = ["path_dyn", "user_dynamics_log_stepper_detail"]

for t in required_tables:
    if t not in globals():
        raise ValueError(f"{t} not found")

# 2) Keep only the columns needed for stepper detail
step_detail = user_dynamics_log_stepper_detail[
    ["user_id", "stepper_subtype"]
].copy()

# 3) merge (left join to keep all users)
path_dyn_step = path_dyn.merge(
    step_detail,
    on="user_id",
    how="left"
)

# 4) Check
print("✅ path_dyn_step created:", path_dyn_step.shape)

print("\nStepper subtype distribution (overall):")
print(path_dyn_step["stepper_subtype"].value_counts(dropna=False))

✅ path_dyn_step created: (182223, 4)

Stepper subtype distribution (overall):
stepper_subtype
NaN                     144189
stepper_stable_up        11724
stepper_stable_down      10838
stepper_reverse_down      8737
stepper_reverse_up        6735
Name: count, dtype: int64

In [45]:
# 5) Optional: inspect path × subtype structure
path_step_table = (
    path_dyn_step
    .pivot_table(
        index="path_9",
        columns="stepper_subtype",
        values="user_id",
        aggfunc="count",
        fill_value=0
    )
)

print("\nPath × Stepper Subtype:")
display(path_step_table)

# New table:
# - path_dyn_step
# - path_step_table

Path × Stepper Subtype:

stepper_subtype,stepper_reverse_down,stepper_reverse_up,stepper_stable_down,stepper_stable_up
path_9,,,,
High Down to Low,4,21,363,0
High Down to Mid,541,789,3046,63
High Stay,3178,2492,2330,2686
Low Stay,644,607,852,1053
Low Up to High,56,7,0,582
Low Up to Mid,382,213,27,1987
Mid Down to Low,253,297,1733,30
Mid Stay,2565,1951,2406,2257
Mid Up to High,1114,358,81,3066

**New tables:**

- `path_dyn_step` — combined Type + Subtype table
- `path_step_table` — standalone Stepper Subtype summary table

In [46]:
# Keep only stepper users
step_only = path_dyn_step.dropna(subset=["stepper_subtype"]).copy()

# 1) Counts
path_step_counts = (
    step_only
    .groupby(["path_9", "stepper_subtype"])
    .size()
    .unstack(fill_value=0)
)

# 2) Row-wise share (proportion within each path)
path_step_row_share = (
    path_step_counts
    .div(path_step_counts.sum(axis=1), axis=0)
    .round(3)
)

print("=== Path × Stepper Subtype (Counts) ===")
display(path_step_counts)

print("\n=== Path × Stepper Subtype (Row Share) ===")
display(path_step_row_share)

=== Path × Stepper Subtype (Counts) ===

stepper_subtype,stepper_reverse_down,stepper_reverse_up,stepper_stable_down,stepper_stable_up
path_9,,,,
High Down to Low,4,21,363,0
High Down to Mid,541,789,3046,63
High Stay,3178,2492,2330,2686
Low Stay,644,607,852,1053
Low Up to High,56,7,0,582
Low Up to Mid,382,213,27,1987
Mid Down to Low,253,297,1733,30
Mid Stay,2565,1951,2406,2257
Mid Up to High,1114,358,81,3066

=== Path × Stepper Subtype (Row Share) ===

stepper_subtype,stepper_reverse_down,stepper_reverse_up,stepper_stable_down,stepper_stable_up
path_9,,,,
High Down to Low,0.010,0.054,0.936,0.000
High Down to Mid,0.122,0.178,0.686,0.014
High Stay,0.297,0.233,0.218,0.251
Low Stay,0.204,0.192,0.270,0.334
Low Up to High,0.087,0.011,0.000,0.902
Low Up to Mid,0.146,0.082,0.010,0.762
Mid Down to Low,0.109,0.128,0.749,0.013
Mid Stay,0.279,0.213,0.262,0.246
Mid Up to High,0.241,0.078,0.018,0.664

In [47]:
# Full-population growth accounting

# ============================================
# Path-Level Strict Log Growth Accounting
# ============================================

import numpy as np
import pandas as pd

# -------------------------
# Config
# -------------------------
USER_COL = "user_id"
PATH_COL = "path_9"
TIME_COL = "order_number"

EPS = 1e-9

# -------------------------
# Sanity Check
# -------------------------
for name in ["orders_enriched2", "path_dyn_step"]:
    if name not in globals():
        raise ValueError(f"Missing required table: {name}")

# -------------------------
# 1️⃣ Merge path label
# -------------------------
path_orders_tmp = (
    orders_enriched2[[USER_COL, TIME_COL, "order_id",
                      "items_per_order", "gap_days_adj"]]
    .merge(
        path_dyn_step[[USER_COL, PATH_COL]],
        on=USER_COL,
        how="inner"
    )
    .dropna(subset=["items_per_order", "gap_days_adj"])
    .copy()
)

path_orders_tmp = path_orders_tmp[path_orders_tmp["gap_days_adj"] > 0]

# -------------------------
# 2️⃣ Split Early / Late (50%)
# -------------------------
n_orders_tmp = (
    path_orders_tmp.groupby(USER_COL)["order_id"]
    .nunique()
    .rename("n_orders")
    .reset_index()
)

path_orders_tmp = path_orders_tmp.merge(n_orders_tmp, on=USER_COL, how="left")

path_orders_tmp["pos"] = path_orders_tmp[TIME_COL] / path_orders_tmp["n_orders"]
path_orders_tmp["half"] = np.where(path_orders_tmp["pos"] <= 0.5, "early", "late")

# weekly intensity per order
path_orders_tmp["weekly_order"] = (
    path_orders_tmp["items_per_order"] /
    path_orders_tmp["gap_days_adj"] * 7.0
)

# -------------------------
# 3️⃣ User-level medians (NO OVERWRITE)
# -------------------------
path_user_half_tmp = (
    path_orders_tmp
    .groupby([USER_COL, PATH_COL, "half"], as_index=False)
    .agg(
        weekly_med=("weekly_order", "median"),
        basket_med=("items_per_order", "median"),
        gap_med=("gap_days_adj", "median")
    )
)

path_growth_user = (
    path_user_half_tmp
    .pivot_table(index=[USER_COL, PATH_COL],
                 columns="half",
                 values=["weekly_med","basket_med","gap_med"],
                 aggfunc="first")
)

path_growth_user.columns = [f"{a}_{b}" for a,b in path_growth_user.columns]
path_growth_user = path_growth_user.reset_index()

# drop incomplete users
path_growth_user = path_growth_user.dropna(
    subset=[
        "weekly_med_early","weekly_med_late",
        "basket_med_early","basket_med_late",
        "gap_med_early","gap_med_late"
    ]
)

# -------------------------
# 4️⃣ Strict Log Decomposition
# -------------------------
def safe_log(x):
    return np.log(np.maximum(x, EPS))

path_growth_user["d_log_weekly"] = (
    safe_log(path_growth_user["weekly_med_late"])
    - safe_log(path_growth_user["weekly_med_early"])
)

path_growth_user["d_log_basket"] = (
    safe_log(path_growth_user["basket_med_late"])
    - safe_log(path_growth_user["basket_med_early"])
)

path_growth_user["d_log_gap"] = (
    safe_log(path_growth_user["gap_med_late"])
    - safe_log(path_growth_user["gap_med_early"])
)

# absolute contributions
path_growth_user["abs_gap"] = path_growth_user["d_log_gap"].abs()
path_growth_user["abs_basket"] = path_growth_user["d_log_basket"].abs()
path_growth_user["total_abs"] = (
    path_growth_user["abs_gap"]
    + path_growth_user["abs_basket"]
)

path_growth_user["gap_share"] = (
    path_growth_user["abs_gap"] /
    np.maximum(path_growth_user["total_abs"], EPS)
)

path_growth_user["basket_share"] = (
    path_growth_user["abs_basket"] /
    np.maximum(path_growth_user["total_abs"], EPS)
)

# -------------------------
# 5️⃣ Path-level Summary
# -------------------------
path_growth_summary = (
    path_growth_user
    .groupby(PATH_COL, as_index=False)
    .agg(
        users=(USER_COL, "nunique"),
        mean_d_log_weekly=("d_log_weekly","mean"),
        median_d_log_weekly=("d_log_weekly","median"),
        mean_d_log_basket=("d_log_basket","mean"),
        mean_d_log_gap=("d_log_gap","mean"),
        mean_gap_share=("gap_share","mean"),
        mean_basket_share=("basket_share","mean"),
    )
)

# identity check
path_growth_summary["check_identity"] = (
    path_growth_summary["mean_d_log_basket"]
    - path_growth_summary["mean_d_log_gap"]
    - path_growth_summary["mean_d_log_weekly"]
)

print("✅ path_growth_user created:", path_growth_user.shape)
print("✅ path_growth_summary created:", path_growth_summary.shape)

display(path_growth_summary.sort_values("mean_d_log_weekly", ascending=False))

✅ path_growth_user created: (175072, 16)
✅ path_growth_summary created: (9, 9)

,path_9,users,mean_d_log_weekly,median_d_log_weekly,mean_d_log_basket,mean_d_log_gap,mean_gap_share,mean_basket_share,check_identity
4,Low Up to High,2314,1.917622,1.819847,0.807597,-1.017010,0.550162,0.449838,-0.093016
5,Low Up to Mid,15269,0.903742,0.826679,0.455984,-0.398371,0.490973,0.504115,-0.049387
8,Mid Up to High,14217,0.731260,0.687177,0.227507,-0.462432,0.571785,0.422376,-0.041322
3,Low Stay,31483,0.052018,0.013699,0.052465,0.034874,0.444069,0.523373,-0.034428
2,High Stay,31722,-0.009396,0.000000,0.024186,0.024101,0.487307,0.488357,0.009481
7,Mid Stay,43780,-0.017391,-0.008476,0.014489,0.036119,0.528469,0.455862,-0.004239
1,High Down to Mid,17502,-0.819694,-0.750306,-0.137199,0.610664,0.629535,0.366751,0.071832
6,Mid Down to Low,15370,-0.874622,-0.818310,-0.295170,0.539061,0.560391,0.435836,0.040391
0,High Down to Low,3415,-2.005430,-1.890605,-0.443977,1.375286,0.690178,0.309822,0.186167

# 📉 Section 6: High → Mid Analysis

> Downgrade mechanism: gap vs. basket, anchor item, early signals, A/C validation

---

**Objective**: Decompose the High → Mid downgrade mechanism — is it driven by declining purchase frequency (longer gap), shrinking order size (smaller basket), or both?

In [48]:
# 1) First localize: did gap vs. basket change?

# Don't just look at magnitude — also check: direction consistency (how many users' gap grew? how many users' basket shrank?), and whether the change concentrates in the tail (does p75/p90 widen?)

import numpy as np
import pandas as pd

# ========== 0) Base: keep only High -> Mid users ==========
# Requires user_half to already have path_9
hm_users = user_half.loc[user_half["path_9"] == "High Down to Mid", "user_id"].unique()

# Order-level table: keep only these users + necessary columns
df = orders_enriched2.loc[
    orders_enriched2["user_id"].isin(hm_users),
    ["user_id", "order_id", "order_number", "gap_days_adj", "items_per_order"]
].copy()

# Compute order count per user, for the 50% split
n_orders = df.groupby("user_id")["order_id"].nunique().rename("n_orders")
df = df.merge(n_orders, on="user_id", how="left")

# Relative position & half
df["pos"] = df["order_number"] / df["n_orders"]
df["half"] = np.where(df["pos"] <= 0.5, "early", "late")

# ========== 1) User-level aggregation: early/late basket & gap ==========
# basket：median(items_per_order)
# gap：median(gap_days_adj)
lever_user_hm = (
    df.groupby(["user_id", "half"])
      .agg(
          basket_med=("items_per_order", "median"),
          gap_med=("gap_days_adj", "median"),
          n_orders_half=("order_id", "count")
      )
      .unstack("half")
)

# Flatten column names
lever_user_hm.columns = [f"{a}_{b}" for a, b in lever_user_hm.columns]
lever_user_hm = lever_user_hm.reset_index()

# Keep only users with both early and late
need_cols = ["basket_med_early","basket_med_late","gap_med_early","gap_med_late"]
lever_user_hm = lever_user_hm.dropna(subset=need_cols).copy()

# Δ
lever_user_hm["delta_gap"] = lever_user_hm["gap_med_late"] - lever_user_hm["gap_med_early"]
lever_user_hm["delta_basket"] = lever_user_hm["basket_med_late"] - lever_user_hm["basket_med_early"]

# ========== 2) Localization stat function ==========
def dist_stats(s: pd.Series) -> pd.Series:
    return pd.Series({
        "count": s.count(),
        "mean": s.mean(),
        "median": s.median(),
        "p25": s.quantile(0.25),
        "p75": s.quantile(0.75),
        "p90": s.quantile(0.90),
        "min": s.min(),
        "max": s.max(),
    })

# ========== 3) Distribution: early/late & delta ==========
summary_parts = []

for var in ["gap_med", "basket_med"]:
    for phase in ["early", "late"]:
        col = f"{var}_{phase}"
        out = dist_stats(lever_user_hm[col])
        out["metric"] = var
        out["phase"] = phase
        summary_parts.append(out)

for var, col in [("gap_med", "delta_gap"), ("basket_med", "delta_basket")]:
    out = dist_stats(lever_user_hm[col])
    out["metric"] = var
    out["phase"] = "delta(late-early)"
    summary_parts.append(out)

lever_summary_hm = pd.DataFrame(summary_parts)[
    ["metric","phase","count","mean","median","p25","p75","p90","min","max"]
].reset_index(drop=True)

print("========== 1) Distribution summary (High Down to Mid) ==========")
display(lever_summary_hm)

# ========== 4) Direction consistency (proportions) ==========
direction_table = pd.DataFrame({
    "users": [lever_user_hm.shape[0]],
    "pct_gap_longer": [(lever_user_hm["delta_gap"] > 0).mean()],
    "pct_gap_shorter": [(lever_user_hm["delta_gap"] < 0).mean()],
    "pct_gap_same": [(lever_user_hm["delta_gap"] == 0).mean()],
    "pct_basket_down": [(lever_user_hm["delta_basket"] < 0).mean()],
    "pct_basket_up": [(lever_user_hm["delta_basket"] > 0).mean()],
    "pct_basket_same": [(lever_user_hm["delta_basket"] == 0).mean()],
    "pct_gap_longer_and_basket_down": [((lever_user_hm["delta_gap"] > 0) & (lever_user_hm["delta_basket"] < 0)).mean()],
    "pct_gap_longer_only": [((lever_user_hm["delta_gap"] > 0) & (lever_user_hm["delta_basket"] >= 0)).mean()],
    "pct_basket_down_only": [((lever_user_hm["delta_basket"] < 0) & (lever_user_hm["delta_gap"] <= 0)).mean()],
})

print("\n========== 2) Direction consistency ==========")
display(direction_table)

# ========== 5) Tail / cap check: share of gap=30 (early vs. late) ==========
# gap_days_adj is capped at 30, so checking the cap rate is important
tail_flags_hm = pd.DataFrame({
    "pct_gap30_early": [(lever_user_hm["gap_med_early"] >= 30).mean()],
    "pct_gap30_late": [(lever_user_hm["gap_med_late"] >= 30).mean()],
    "pct_gap30_increase": [((lever_user_hm["gap_med_early"] < 30) & (lever_user_hm["gap_med_late"] >= 30)).mean()],
})

print("\n========== 3) Tail / cap check (gap=30) ==========")
display(tail_flags_hm)

print("\nNew tables created:")
print(" - lever_user_hm  (user-level early/late gap & basket for High->Mid)")
print(" - lever_summary_hm (distribution summary)")
print(" - tail_flags_hm (gap cap check)")

========== 1) Distribution summary (High Down to Mid) ==========

,metric,phase,count,mean,median,p25,p75,p90,min,max
0,gap_med,early,18107.0,7.757635,7.0,5.0,9.50,14.0,1.0,30.0
1,gap_med,late,18107.0,14.593058,13.0,8.0,20.00,29.0,1.0,30.0
2,basket_med,early,18107.0,13.129867,12.0,8.5,16.00,21.5,1.5,73.0
3,basket_med,late,18107.0,11.405782,10.0,7.0,14.25,19.0,1.0,38.5
4,gap_med,delta(late-early),18107.0,6.835423,5.0,1.5,11.00,18.0,-19.0,29.0
5,basket_med,delta(late-early),18107.0,-1.724085,-1.5,-4.0,1.00,3.5,-60.0,25.0

========== 2) Direction consistency ==========

,users,pct_gap_longer,pct_gap_shorter,pct_gap_same,pct_basket_down,pct_basket_up,pct_basket_same,pct_gap_longer_and_basket_down,pct_gap_longer_only,pct_basket_down_only
0,18107,0.849892,0.096316,0.053791,0.622632,0.307616,0.069752,0.497045,0.352847,0.125587

========== 3) Tail / cap check (gap=30) ==========

   pct_gap30_early  pct_gap30_late  pct_gap30_increase
0         0.003258        0.089579            0.087977

New tables created:
 - lever_user_hm  (user-level early/late gap & basket for High->Mid)
 - lever_summary_hm (distribution summary)
 - tail_flags_hm (gap cap check)

**Objective**: Use log decomposition to quantify how much gap (purchase frequency) and basket (order size) each contribute to the High → Mid weekly decline.

In [49]:
import numpy as np
import pandas as pd

# Based on the previously generated lever_user_hm
df = lever_user_hm.copy()

# Avoid log(0) - gap is at least 1, basket is at least 1
df = df[
    (df["basket_med_early"] > 0) &
    (df["basket_med_late"] > 0) &
    (df["gap_med_early"] > 0) &
    (df["gap_med_late"] > 0)
].copy()

# log change
df["d_log_basket"] = np.log(df["basket_med_late"]) - np.log(df["basket_med_early"])
df["d_log_gap"] = np.log(df["gap_med_late"]) - np.log(df["gap_med_early"])

# log change in weekly (theoretically equal to the difference of the two above)
df["d_log_weekly"] = df["d_log_basket"] - df["d_log_gap"]

# Take average contribution
mean_log_basket = df["d_log_basket"].mean()
mean_log_gap = df["d_log_gap"].mean()
mean_log_weekly = df["d_log_weekly"].mean()

# Contribution share (absolute-value attribution)
gap_contrib_ratio = abs(mean_log_gap) / (abs(mean_log_gap) + abs(mean_log_basket))
basket_contrib_ratio = abs(mean_log_basket) / (abs(mean_log_gap) + abs(mean_log_basket))

log_decomp_summary = pd.DataFrame({
    "metric": ["d_log_weekly", "d_log_basket", "d_log_gap"],
    "mean": [mean_log_weekly, mean_log_basket, mean_log_gap]
})

contribution_ratio = pd.DataFrame({
    "gap_contribution_ratio": [gap_contrib_ratio],
    "basket_contribution_ratio": [basket_contrib_ratio]
})

print("========== Log Decomposition (High → Mid) ==========")
display(log_decomp_summary)

print("\n========== Contribution Ratio ==========")
display(contribution_ratio)

========== Log Decomposition (High → Mid) ==========

         metric      mean
0  d_log_weekly -0.781089
1  d_log_basket -0.141236
2     d_log_gap  0.639853

========== Contribution Ratio ==========

   gap_contribution_ratio  basket_contribution_ratio
0                0.819181                   0.180819

**Presentation Material**

1. Basket vs. Gap — Early vs. Late % change comparison (describes how much each changed)
2. Basket vs. Gap — contribution share to the Weekly decline (log decomposition, attributing how much each contributed)

**Interim conclusion**: Gap (purchase frequency) is the primary driver of the weekly decline → next, decompose the specific causes of gap deterioration.

In [50]:
import numpy as np
import pandas as pd

# =========================
# 0) Get High -> Mid users + order-level data
# =========================
hm_users = user_half.loc[user_half["path_9"] == "High Down to Mid", "user_id"].unique()

cols = ["user_id", "order_id", "order_number", "gap_days_adj", "items_per_order"]
hm_orders = orders_enriched2.loc[orders_enriched2["user_id"].isin(hm_users), cols].copy()

# Order count per user + early/late flag (by order_number / n_orders)
n_orders = hm_orders.groupby("user_id")["order_id"].nunique().rename("n_orders")
hm_orders = hm_orders.merge(n_orders, on="user_id", how="left")

hm_orders["pos"] = hm_orders["order_number"] / hm_orders["n_orders"]
hm_orders["half"] = np.where(hm_orders["pos"] <= 0.5, "early", "late")

# For "consecutive gap streak" analysis, sort by user + order_number first
hm_orders = hm_orders.sort_values(["user_id", "order_number"]).reset_index(drop=True)

print("hm_orders:", hm_orders.shape)

# =========================
# 1) Cap effect (strong evidence from gap=30)
#    - early/late: share of gap=30, share of gap>=25
#    - user level: count and share of gap=30
# =========================
CAP = 30
LONG_GAP = 25

hm_orders["is_cap30"] = (hm_orders["gap_days_adj"] >= CAP).astype(int)
hm_orders["is_long25"] = (hm_orders["gap_days_adj"] >= LONG_GAP).astype(int)

cap_table = (
    hm_orders.groupby("half")
    .agg(
        orders=("order_id", "count"),
        pct_gap30=("is_cap30", "mean"),
        pct_gap25p=("is_long25", "mean"),
        gap_median=("gap_days_adj", "median"),
        gap_p75=("gap_days_adj", lambda s: s.quantile(0.75)),
        gap_p90=("gap_days_adj", lambda s: s.quantile(0.90)),
    )
    .reindex(["early","late"])
)

print("\n========== 1) Cap / long-gap rates (order-level) ==========")
display(cap_table)

# User level: cap count and share for each user's early/late
user_cap = (
    hm_orders.groupby(["user_id","half"])
    .agg(
        orders_half=("order_id","count"),
        cap30_cnt=("is_cap30","sum"),
        long25_cnt=("is_long25","sum"),
        cap30_share=("is_cap30","mean"),
        long25_share=("is_long25","mean"),
        gap_med=("gap_days_adj","median"),
        gap_std=("gap_days_adj","std"),
    )
    .reset_index()
)

print("\nuser_cap:", user_cap.shape)

# =========================
# 2) Long gap streaks (consecutive breaks)
#    - streaks of consecutive gap>=25
#    - streaks of consecutive gap=30
#    Output: longest streak per user for early/late, and whether it occurred >=2 times
# =========================
def streak_max(series_bool: pd.Series) -> int:
    """Return the length of the longest consecutive run of True"""
    s = series_bool.fillna(False).astype(int).to_numpy()
    if len(s) == 0:
        return 0
    # Consecutive-run length calculation
    max_run, run = 0, 0
    for v in s:
        if v == 1:
            run += 1
            max_run = max(max_run, run)
        else:
            run = 0
    return int(max_run)

streaks = (
    hm_orders.groupby(["user_id","half"])
    .apply(lambda g: pd.Series({
        "max_streak_gap25p": streak_max(g["gap_days_adj"] >= LONG_GAP),
        "max_streak_gap30": streak_max(g["gap_days_adj"] >= CAP),
    }))
    .reset_index()
)

# Merge into the user table (mechanism table)
user_mech = (
    user_cap.merge(streaks, on=["user_id","half"], how="left")
)

# Build an early/late pivot for easier comparison
user_mech_wide = (
    user_mech.pivot(index="user_id", columns="half")
)

# Flatten column names
user_mech_wide.columns = [f"{a}_{b}" for a,b in user_mech_wide.columns]
user_mech_wide = user_mech_wide.reset_index()

print("\nuser_mech_wide:", user_mech_wide.shape)

# =========================
# 3) Cadence stability (volatility)
#    - gap_std early vs late
#    - IQR / p90-p50 can also serve as a tail-stretch indicator
# =========================
user_mech_wide["delta_gap_std"] = user_mech_wide["gap_std_late"] - user_mech_wide["gap_std_early"]

stability_summary = pd.DataFrame({
    "metric": ["gap_std_early", "gap_std_late", "delta_gap_std"],
    "mean": [
        user_mech_wide["gap_std_early"].mean(),
        user_mech_wide["gap_std_late"].mean(),
        user_mech_wide["delta_gap_std"].mean()
    ],
    "median": [
        user_mech_wide["gap_std_early"].median(),
        user_mech_wide["gap_std_late"].median(),
        user_mech_wide["delta_gap_std"].median()
    ],
    "p25": [
        user_mech_wide["gap_std_early"].quantile(0.25),
        user_mech_wide["gap_std_late"].quantile(0.25),
        user_mech_wide["delta_gap_std"].quantile(0.25)
    ],
    "p75": [
        user_mech_wide["gap_std_early"].quantile(0.75),
        user_mech_wide["gap_std_late"].quantile(0.75),
        user_mech_wide["delta_gap_std"].quantile(0.75)
    ],
})

print("\n========== 3) Stability (gap std) ==========")
display(stability_summary)

# Direction consistency: is late-stage volatility higher
stability_direction = pd.DataFrame({
    "users": [user_mech_wide.shape[0]],
    "pct_std_up": [(user_mech_wide["delta_gap_std"] > 0).mean()],
    "pct_std_down": [(user_mech_wide["delta_gap_std"] < 0).mean()],
    "pct_std_same": [(user_mech_wide["delta_gap_std"] == 0).mean()],
})

display(stability_direction)

# =========================
# 4) Median shift vs. tail stretch (shape)
#    - early vs. late gap p50/p75/p90 comparison (already in cap_table)
#    - also output "tail-stretch indicators": (p90 - p50), (p75 - p25)
# =========================
# =========================
# 4) Median shift vs. tail stretch (shape) - fixed version
# =========================

# Optional: confirm half values first
print(hm_orders["half"].value_counts(dropna=False))

shape_table = (
    hm_orders
    .groupby("half")["gap_days_adj"]
    .agg(
        p25=lambda s: s.quantile(0.25),
        p50=lambda s: s.quantile(0.50),
        p75=lambda s: s.quantile(0.75),
        p90=lambda s: s.quantile(0.90),
    )
)

shape_table["tail_p90_p50"] = shape_table["p90"] - shape_table["p50"]
shape_table["iqr_p75_p25"] = shape_table["p75"] - shape_table["p25"]

shape_table = shape_table.reindex(["early", "late"])

print("\n========== 4) Shape: median shift vs tail stretch ==========")
display(shape_table)

print("\nNew tables created:")
print(" - hm_orders          (order-level subset for High->Mid with half + flags)")
print(" - cap_table          (order-level cap/long-gap summary by half)")
print(" - user_cap           (user-half stats: cap counts/shares, gap_med/std)")
print(" - streaks            (user-half longest streaks)")
print(" - user_mech_wide     (user-level wide table: early vs late mechanisms)")
print(" - stability_summary  (gap std summary)")
print(" - shape_table        (distribution shape summary)")

hm_orders: (300414, 8)

========== 1) Cap / long-gap rates (order-level) ==========

       orders  pct_gap30  pct_gap25p  gap_median  gap_p75  gap_p90
half
early  127706   0.035660    0.049810         6.0     10.0     16.0
late   172708   0.141036    0.181845         9.0     19.0     30.0

user_cap: (36214, 9)

user_mech_wide: (18107, 19)

========== 3) Stability (gap std) ==========

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/2922201960.py:91: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({

          metric      mean    median       p25        p75
0  gap_std_early  6.199623  5.241319  2.962801   8.717798
1   gap_std_late  8.176320  8.577059  6.127457  10.405127
2  delta_gap_std  2.001938  2.090527 -0.607304   5.166247

   users  pct_std_up  pct_std_down  pct_std_same
0  18107    0.572099      0.247915      0.000442

half
late     172708
early    127706
Name: count, dtype: int64

========== 4) Shape: median shift vs tail stretch ==========

       p25  p50   p75   p90  tail_p90_p50  iqr_p75_p25
half
early  4.0  6.0  10.0  16.0          10.0          6.0
late   6.0  9.0  19.0  30.0          21.0         13.0

New tables created:
 - hm_orders          (order-level subset for High->Mid with half + flags)
 - cap_table          (order-level cap/long-gap summary by half)
 - user_cap           (user-half stats: cap counts/shares, gap_med/std)
 - streaks            (user-half longest streaks)
 - user_mech_wide     (user-level wide table: early vs late mechanisms)
 - stability_summary  (gap std summary)
 - shape_table        (distribution shape summary)

**Presentation Material**

1. Mid → High Stability Change Over Time

**Analysis Module: High → Mid Gap Deterioration Mechanism Breakdown**

**Question**: Why does gap lengthen significantly for High → Mid users?

**Core observations:**

- pct_gap30: 3.6% → 14.1% (≈4x, sharp rise in long-gap share)
- pct_gap25+: 5.0% → 18.2% (≈3.6x)
- median gap: 6 → 9 (overall center shifts right)
- p75 / p90: 10/16 → 19/30 (tail stretches further)
- gap_std (median): 5.24 → 8.58 (stability declines, 57% of users see std rise)
- IQR (p75-p25): 6 → 13 (distribution widens overall)

**Three mechanisms, ranked by importance:**

1. **Long-tail breaks (most important)** — pct_gap30 rises sharply, p90 stretches significantly; this is a cliff/drop-off pattern, not a uniform slowdown
2. **Cadence instability** — gap_std and IQR rise together, users shift from stable periodic purchasing to random purchasing
3. **Overall frequency shift (secondary)** — median and p25/p75 all move up, indicating even normal orders are slowing down

**Conclusion**: The High → Mid downgrade is not fundamentally about reduced demand — it's a structural shift from "stable repeat purchasing" to "unstable + occasional breaks," driven jointly by long-tail breaks and cadence instability, with overall slowdown as a secondary factor.

**Objective**: Test the temporal characteristics of gap deterioration for High → Mid users, via three tests: jump vs. gradual, deterioration concentration, low-frequency persistence.

In [51]:
import numpy as np
import pandas as pd

# =========================
# High -> Mid user set
# =========================
hm_users = user_half.loc[user_half["path_9"] == "High Down to Mid", "user_id"].unique()

# Keep only necessary columns (avoid polluting the original table)
cols = ["user_id", "order_id", "order_number", "gap_days_adj"]
hm = orders_enriched2.loc[orders_enriched2["user_id"].isin(hm_users), cols].copy()

# Order count per user + position
n_orders = hm.groupby("user_id")["order_id"].nunique().rename("n_orders")
hm = hm.merge(n_orders, on="user_id", how="left")
hm["pos"] = hm["order_number"] / hm["n_orders"]

# Split into three stages (early / mid / late)
hm["seg3"] = pd.cut(
    hm["pos"],
    bins=[0.0, 1/3, 2/3, 1.0],
    labels=["early", "mid", "late"],
    include_lowest=True
)

# Drop anomalies (in case pos=0 or NaN)
hm = hm.dropna(subset=["seg3", "gap_days_adj"]).copy()

# =========================
# Test 1) Jump vs. gradual: median gap for each user's three stages
# =========================
gap3 = (
    hm.groupby(["user_id", "seg3"])["gap_days_adj"]
      .median()
      .unstack("seg3")
      .reset_index()
)

# Keep only users with all three stages present
gap3 = gap3.dropna(subset=["early", "mid", "late"]).copy()

gap3["d_mid_early"] = gap3["mid"] - gap3["early"]
gap3["d_late_mid"]  = gap3["late"] - gap3["mid"]
gap3["d_late_early"] = gap3["late"] - gap3["early"]

# A simple "jump indicator": share of users with a late-stage jump
gap3["jump_ratio"] = gap3["d_late_mid"] / (gap3["d_late_early"].replace(0, np.nan))

# =========================
# Test 2) Break concentration: how much of Δ_gap is contributed by the top 20% of users
# =========================
tmp = gap3[["user_id", "d_late_early"]].copy()
tmp = tmp.sort_values("d_late_early", ascending=False)

# Only look at the "slower" portion (Δ_gap>0), to avoid offsetting by the small number of users who sped up
tmp_pos = tmp[tmp["d_late_early"] > 0].copy()

if len(tmp_pos) > 0:
    k = int(np.ceil(0.2 * len(tmp_pos)))
    top20_share = tmp_pos.head(k)["d_late_early"].sum() / tmp_pos["d_late_early"].sum()
else:
    top20_share = np.nan

# =========================
# Test 3) Low-frequency persistence: does the late stage stay low-frequency (gap>=25 / gap=30 / long consecutive breaks)
# =========================
CAP = 30
LONG = 25

late_orders = hm.loc[hm["seg3"] == "late", ["user_id", "order_number", "gap_days_adj"]].copy()
late_orders = late_orders.sort_values(["user_id", "order_number"])

late_orders["is_long25"] = (late_orders["gap_days_adj"] >= LONG).astype(int)
late_orders["is_cap30"]  = (late_orders["gap_days_adj"] >= CAP).astype(int)

def max_streak_ones(arr: np.ndarray) -> int:
    max_run, run = 0, 0
    for v in arr:
        if v == 1:
            run += 1
            max_run = max(max_run, run)
        else:
            run = 0
    return int(max_run)

late_user = (
    late_orders.groupby("user_id")
    .agg(
        late_orders=("gap_days_adj", "size"),
        pct_long25=("is_long25", "mean"),
        pct_cap30=("is_cap30", "mean"),
        late_gap_med=("gap_days_adj", "median"),
    )
    .reset_index()
)

# Consecutive breaks: longest streak of gap>=25 in the late stage
streaks = (
    late_orders.groupby("user_id")["is_long25"]
    .apply(lambda s: max_streak_ones(s.to_numpy()))
    .rename("max_streak_long25")
    .reset_index()
)

late_user = late_user.merge(streaks, on="user_id", how="left")

# Definition of low-frequency persistence (threshold can be adjusted later)
late_user["is_persistent_lowfreq"] = (
    (late_user["pct_long25"] >= 0.5) | (late_user["max_streak_long25"] >= 2)
).astype(int)

# =========================
# Output a summary table: hm_diagnostics
# =========================
hm_diagnostics = pd.DataFrame({
    "path": ["High Down to Mid"],
    "users_with_3segments": [gap3.shape[0]],

    # Test 1: jump vs. gradual
    "median_d_mid_early": [gap3["d_mid_early"].median()],
    "median_d_late_mid":  [gap3["d_late_mid"].median()],
    "pct_jump_d_late_mid_gt_d_mid_early": [(gap3["d_late_mid"] > gap3["d_mid_early"]).mean()],
    "median_jump_ratio_late_mid_over_total": [gap3["jump_ratio"].median()],

    # Test 2: concentration
    "top20_users_share_of_total_positive_delta_gap": [top20_share],

    # Test 3: low-frequency persistence (late stage)
    "late_orders_total": [late_orders.shape[0]],
    "late_pct_orders_gap25p": [late_orders["is_long25"].mean()],
    "late_pct_orders_gap30": [late_orders["is_cap30"].mean()],
    "pct_users_persistent_lowfreq_late": [late_user["is_persistent_lowfreq"].mean()],
    "pct_users_late_gap_med_30": [(late_user["late_gap_med"] >= 30).mean()],
})

display(hm_diagnostics)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/3726835268.py:33: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  hm.groupby(["user_id", "seg3"])["gap_days_adj"]

,path,users_with_3segments,median_d_mid_early,median_d_late_mid,pct_jump_d_late_mid_gt_d_mid_early,median_jump_ratio_late_mid_over_total,top20_users_share_of_total_positive_delta_gap,late_orders_total,late_pct_orders_gap25p,late_pct_orders_gap30,pct_users_persistent_lowfreq_late,pct_users_late_gap_med_30
0,High Down to Mid,14856,1.0,3.0,0.59168,0.642857,0.463049,106584,0.180656,0.139195,0.331308,0.088474

**Presentation Material**

1. Gap deterioration accelerates from early → late: +1.0 → +3.0
2. Most users show a "late-stage jump": pct_jump (late-mid > mid-early) = 59%
3. Deterioration is amplified by a small subset of users, but not entirely dependent on them: top 20% of users contribute ≈ 46% of the gap increase

**Analysis Module: Gap Deterioration Path Breakdown (High → Mid)**

**Question**: Is gap lengthening a "gradual slowdown" or a "sudden late-stage drop"?

**Core results:**

- median Δ(mid-early) = +1, median Δ(late-mid) = +3 → late-stage deterioration exceeds early-stage, indicating an accelerating late-stage drop rather than linear decline
- pct_jump (late-mid > mid-early) = 59% → over half of users show a sharper gap increase in the late stage
- top 20% of users contribute ≈ 46% of the gap increase → some concentration exists, but it's not solely driven by extreme users (broad-based + locally amplified)
- late-stage pct_gap25+ ≈ 18.1%, pct_gap30 ≈ 13.9% → users clearly enter a low-frequency / long-interval consumption state more often
- persistent low freq ≈ 33%, users with late median gap ≥ 30 ≈ 8.8% → splits into two groups: structurally-downgraded users vs. extreme-break users nearing churn

**Conclusion**: Gap deterioration is fundamentally a late-stage-triggered "jump-style downgrade" (behavioral break), not a smooth natural decay; and once a low-frequency state forms, it exhibits path dependency (stickiness).

**Objective**: Mechanism analysis complete, moving to the early-signal stage — while users are still in the High early stage, is there a behavioral signal that predicts future High → Mid downgrade? Validated by comparing early High Stay vs. High → Mid user groups.

In [52]:
import numpy as np
import pandas as pd

# =========================
# 1) Select High early users
# =========================
high_users = user_half.loc[
    user_half["early_segment"] == "High", "user_id"
].unique()

# Flag future path
risk_flag = user_half.loc[
    user_half["early_segment"] == "High",
    ["user_id", "path_9"]
].copy()

risk_flag["future_drop"] = (
    risk_flag["path_9"] == "High Down to Mid"
).astype(int)

# =========================
# 2) Get early orders
# =========================
cols = ["user_id", "order_id", "order_number",
        "gap_days_adj", "items_per_order"]

df = orders_enriched2.loc[
    orders_enriched2["user_id"].isin(high_users),
    cols
].copy()

# Compute order count per user
n_orders = df.groupby("user_id")["order_id"].nunique().rename("n_orders")
df = df.merge(n_orders, on="user_id", how="left")

df["pos"] = df["order_number"] / df["n_orders"]
df = df.loc[df["pos"] <= 0.5].copy()  # early 50%

# =========================
# 3) User-level early metrics
# =========================
user_early = (
    df.groupby("user_id")
    .agg(
        early_gap_mean=("gap_days_adj", "mean"),
        early_gap_median=("gap_days_adj", "median"),
        early_gap_std=("gap_days_adj", "std"),
        early_pct_gap25p=("gap_days_adj", lambda s: (s>=25).mean()),
        early_pct_gap30=("gap_days_adj", lambda s: (s>=30).mean()),
        early_basket_median=("items_per_order", "median"),
        early_basket_mean=("items_per_order", "mean"),
    )
    .reset_index()
)

# gap coefficient of variation
user_early["early_gap_cv"] = (
    user_early["early_gap_std"] /
    user_early["early_gap_mean"].replace(0, np.nan)
)

# =========================
# 4) Merge in future path label
# =========================
high_early_risk = (
    user_early.merge(risk_flag[["user_id","future_drop"]],
                     on="user_id",
                     how="left")
)

# =========================
# 5) Output comparison summary table
# =========================
risk_summary = (
    high_early_risk.groupby("future_drop")
    .agg(
        users=("user_id","count"),
        gap_median=("early_gap_median","median"),
        gap_std=("early_gap_std","median"),
        gap_cv=("early_gap_cv","median"),
        pct_gap25p=("early_pct_gap25p","mean"),
        pct_gap30=("early_pct_gap30","mean"),
        basket_median=("early_basket_median","median"),
    )
    .reset_index()
)

display(risk_summary)

,future_drop,users,gap_median,gap_std,gap_cv,pct_gap25p,pct_gap30,basket_median
0,0,35994,6.0,4.140672,0.617413,0.044751,0.032162,13.0
1,1,18107,7.0,5.241319,0.650332,0.067607,0.051182,12.0

**Analysis Module: Pre-Downgrade Early Behavioral Signals (Leading Indicators)**

**Question**: Do future_drop=1 (will later downgrade High→Mid) vs. future_drop=0 (stays High) users already show predictable behavioral differences before the downgrade occurs?

**Core results (future_drop=0 → future_drop=1):**

- gap_median: 6 → 7 (cadence already slower)
- gap_std: 4.14 → 5.24, gap_cv: 0.62 → 0.65 (higher volatility, less stable cadence)
- pct_gap25+: 4.5% → 6.8%, pct_gap30: 3.2% → 5.1% (more prone to long gaps)
- basket_median: 13 → 12 (very small difference, indicating the downgrade is not basket-driven)

**Mechanism**: The downgrade is not random — slower cadence, rising instability, and increasing long-gap probability are all present before the downgrade actually happens, and are preconditions for the later "gap jump"; the core driver is frequency, not basket.

**Conclusion**: The High → Mid downgrade is predictable in advance — high-risk users can be identified early via these three signals: slowing cadence, declining stability, and rising long-gap risk.

In [53]:
import numpy as np
import pandas as pd

df = high_early_risk.copy()

# baseline drop rate
baseline = df["future_drop"].mean()

def lift_table_by_quantile(df, value_col, q=4, label_prefix=None):
    x = df[[value_col, "future_drop"]].dropna().copy()
    if label_prefix is None:
        label_prefix = value_col

    # Quantile segmentation (q=4 -> quartile)
    # duplicates='drop' avoids failing to cut enough bins when values are too discrete
    x["risk_group"] = pd.qcut(x[value_col], q=q, duplicates="drop")

    out = (
        x.groupby("risk_group")
        .agg(
            users=("future_drop", "size"),
            drop_rate=("future_drop", "mean"),
            value_median=(value_col, "median"),
            value_p25=(value_col, lambda s: s.quantile(0.25)),
            value_p75=(value_col, lambda s: s.quantile(0.75)),
        )
        .reset_index()
    )

    out["baseline_drop_rate"] = baseline
    out["lift_vs_baseline"] = out["drop_rate"] / baseline
    out["risk_ratio_top_vs_bottom"] = np.nan  # placeholder, filled in later

    # top vs. bottom risk ratio (as long as bin count >= 2)
    if len(out) >= 2:
        out.loc[:, "risk_ratio_top_vs_bottom"] = (
            out["drop_rate"].iloc[-1] / out["drop_rate"].iloc[0]
        )

    out.insert(0, "signal", label_prefix)
    return out

lift_gap_std_q = lift_table_by_quantile(df, "early_gap_std", q=4, label_prefix="early_gap_std (quartiles)")
lift_gap25_q    = lift_table_by_quantile(df, "early_pct_gap25p", q=4, label_prefix="early_pct_gap25p (quartiles)")

print("========== Lift table: early_gap_std quartiles ==========")
display(lift_gap_std_q)

print("\n========== Lift table: early_pct_gap25p quartiles ==========")
display(lift_gap25_q)

print("\nBaseline drop rate =", baseline)

========== Lift table: early_gap_std quartiles ==========

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/2654998617.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  x.groupby("risk_group")
/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/2654998617.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  x.groupby("risk_group")

,signal,risk_group,users,drop_rate,value_median,value_p25,value_p75,baseline_drop_rate,lift_vs_baseline,risk_ratio_top_vs_bottom
0,early_gap_std (quartiles),"(-0.001, 2.609]",11700,0.257009,1.751190,1.154701,2.167948,0.334689,0.767903,1.673761
1,early_gap_std (quartiles),"(2.609, 4.416]",11700,0.278974,3.457235,2.991124,3.906065,0.334689,0.833534,1.673761
2,early_gap_std (quartiles),"(4.416, 7.465]",11699,0.303616,5.718391,5.036995,6.528213,0.334689,0.907158,1.673761
3,early_gap_std (quartiles),"(7.465, 20.506]",11700,0.430171,9.745959,8.477689,11.842719,0.334689,1.285286,1.673761

========== Lift table: early_pct_gap25p quartiles ==========

,signal,risk_group,users,drop_rate,value_median,value_p25,value_p75,baseline_drop_rate,lift_vs_baseline,risk_ratio_top_vs_bottom
0,early_pct_gap25p (quartiles),"(-0.001, 0.04]",40594,0.323250,0.000000,0.000000,0.000000,0.334689,0.965822,1.141742
1,early_pct_gap25p (quartiles),"(0.04, 1.0]",13507,0.369068,0.153846,0.083333,0.285714,0.334689,1.102719,1.141742

Baseline drop rate = 0.33468882275743517

**Presentation Material**

1. Early gap_std (behavioral stability) bucket shows a strong correlation with drop rate

**Analysis Module: Predictive Power of Early Signals (Lift Analysis)**

**Question**: early_gap_std (behavioral stability) vs. early_pct_gap25p (long-gap share) — which more effectively predicts future High → Mid downgrade?

**Signal 1: early_gap_std**

- Bottom 25% (most stable) drop_rate ≈ 25.7% (lift = 0.77)
- Top 25% (least stable) drop_rate ≈ 43.0% (lift = 1.29)
- Risk ratio (top vs. bottom) ≈ 1.67x, and rises monotonically across groups → a strong, clean, reliable signal

**Signal 2: early_pct_gap25p**

- Low group drop_rate ≈ 32.3%, high group drop_rate ≈ 36.9%
- Risk ratio ≈ 1.14x → some signal but weak predictive power

**Why**: gap_std captures a systemic state (whether the user has already lost a stable cadence), a persistent trait; long gap captures a single event, which occurs rarely and noisily in the early stage. The relationship: instability is the root cause, long gap is just a symptom — gap_std rises in the early stage → long gap increases in the mid stage → a jump (break) occurs in the late stage.

**Conclusion**: The most effective early warning signal for predicting High → Mid downgrade is not "whether a long gap has occurred," but "whether the purchase cadence has already become unstable."

In [54]:
import numpy as np
import pandas as pd

df = high_early_risk.copy()

baseline = df["future_drop"].mean()

# Use median as the high/low threshold (can switch to p75 for a stricter "high risk" definition)
std_cut = df["early_gap_std"].median()
gap25_cut = df["early_pct_gap25p"].median()

combo = df[["user_id", "future_drop", "early_gap_std", "early_pct_gap25p"]].dropna().copy()

combo["std_level"] = np.where(combo["early_gap_std"] > std_cut, "High gap_std", "Low gap_std")
combo["gap25_level"] = np.where(combo["early_pct_gap25p"] > gap25_cut, "High gap25p", "Low gap25p")
combo["risk_group"] = combo["std_level"] + " & " + combo["gap25_level"]

lift_combo = (
    combo.groupby("risk_group")
    .agg(
        users=("future_drop", "size"),
        drop_rate=("future_drop", "mean"),
        gap_std_median=("early_gap_std", "median"),
        gap25p_median=("early_pct_gap25p", "median"),
    )
    .reset_index()
)

lift_combo["baseline_drop_rate"] = baseline
lift_combo["lift_vs_baseline"] = lift_combo["drop_rate"] / baseline

# Order the table from low to high risk for clarity: Low&Low → ... → High&High
order = [
    "Low gap_std & Low gap25p",
    "Low gap_std & High gap25p",
    "High gap_std & Low gap25p",
    "High gap_std & High gap25p",
]
lift_combo["risk_group"] = pd.Categorical(lift_combo["risk_group"], categories=order, ordered=True)
lift_combo = lift_combo.sort_values("risk_group").reset_index(drop=True)

print("========== Lift table: 2x2 combo ==========")
display(lift_combo)

========== Lift table: 2x2 combo ==========

,risk_group,users,drop_rate,gap_std_median,gap25p_median,baseline_drop_rate,lift_vs_baseline
0,Low gap_std & Low gap25p,23227,0.268997,2.603417,0.000000,0.334689,0.803724
1,Low gap_std & High gap25p,173,0.132948,4.175027,0.024390,0.334689,0.397229
2,High gap_std & Low gap25p,8996,0.397288,5.656854,0.000000,0.334689,1.187036
3,High gap_std & High gap25p,14403,0.347914,8.681398,0.142857,0.334689,1.039514

**Analysis Module: gap_std × long gap (2×2 Mechanism Breakdown)**

**Question**: Are behavioral instability (gap_std) and long-gap events (pct_gap25p) independent drivers, mutually reinforcing, or is one the root cause and the other a symptom?

**Four-quadrant drop_rate (baseline ≈ 33.5%):**

- Low std & Low gap25p (stable + no long gap): 26.9% (lift 0.80) — healthiest group
- **High std & Low gap25p (unstable but no long gap): 39.7% (lift 1.19) — highest risk**, showing that instability alone significantly raises downgrade risk even with no long gap
- High std & High gap25p (unstable + has long gap): 34.8% (lift 1.04) — close to baseline; long gap does not add extra risk on top of instability
- Low std & High gap25p (stable but occasional long gap): 13.3% (lift 0.40) — counterintuitive: as long as cadence is stable, risk stays low even with a long gap

**Conclusion**: Risk is determined almost entirely by gap_std (instability), independent of whether a long gap occurs; long gap itself is not the root cause of downgrade, but rather a byproduct/noise of the instability state. Full chain: instability (early) → long gap appears (mid, symptom) → gap jump / drop (late, outcome).

**Takeaway**: Risk should not be defined by "whether a long gap occurred," but by "whether cadence is stable (gap_std)" — earlier, more stable, more predictive.

**Diagnosing the Root Cause of the Downgrade**

**I. Building the 2×2 Framework**

Two dimensions split the downgrade mechanism:

- **Dimension 1: Did demand change?** Unchanged (demand still exists) / Changed (demand declined or the task changed)
- **Dimension 2: Did platform standing change?** Unchanged (still the primary channel) / Changed (replaced or marginalized)

**2×2 Mechanism Matrix:**

- Demand unchanged + platform standing unchanged → **C. Platform friction**
- Demand unchanged + platform standing changed → **B. Channel diversion**
- Demand changed + platform standing unchanged → **A. Insufficient habit depth**
- Demand changed + platform standing changed → **D. Demand structure change**

**II. Structural Definitions of the Four Mechanisms**

**A. Insufficient habit depth** — demand is weaker or unstable, but not replaced; fundamentally, a stable usage habit was never formed
- Characteristics: short user lifecycle, high gap_std, no clear difference in early anchor share, no clear change in breadth
- Validation: does gap_std still predict after controlling for order count? Is drop_rate elevated in low-order buckets?

**B. Channel diversion** — demand still exists, but platform standing declines; fundamentally, the primary purchasing channel has shifted
- Characteristics: anchor share declines in late stage, SKU breadth declines, category breadth declines, reorder_rate may rise, gap shows breaks
- Validation: compare early vs. late anchor share and SKU breadth

**C. Platform experience / friction** — demand unchanged, platform still matters, but the trigger mechanism becomes unstable; fundamentally, the cadence-triggering mechanism fails
- Characteristics: anchor share stable, breadth stable, gap volatility rises first, dow stability declines, consecutive-delay count rises
- Validation: lift of gap_std, whether dow entropy rises, whether consecutive-delay count is predictive

**D. Demand structure change** — the user's own demand has decreased; fundamentally, consumption volume declines
- Characteristics: basket declines, SKU breadth declines, category breadth declines, anchor share declines, total item volume declines
- Validation: compare early vs. late basket size and total items per week

**III. Why This 2×2 Is Valuable**

It forces a clear distinction between whether the downgrade is a demand problem, a channel problem, a cadence problem, or a user-maturity problem, rather than vaguely attributing it to "many possible reasons."

**IV. Mapping Existing Evidence Onto the Framework**

Known: 82% of the weekly decline comes from gap; early anchor difference is small; basket change is small; gap_std is a strong predictive signal.

This makes **D (demand structure change)** and **B (channel diversion)** less likely, pointing more toward **C (cadence instability)** or **A (insufficient habit depth)**.

**V. Structured Elimination Path**

Validate in order:
1. Test whether demand has declined (D)
2. Test whether the anchor has disappeared (B)
3. Test dow stability and consecutive-delay count (C)
4. Finally, look at order count / lifecycle (A)

**Metric Definition: Anchor Item**

**Objective**: Identify a class of products that users purchase frequently, consistently, and broadly repurchase — "staple" products that represent core consumption habits and repurchase cadence.

**Construction method (anchor_score)**, combining four dimensions:

1. **Repurchase strength**: reorder_rate — higher means more likely to be a staple product
2. **Purchase frequency**: inverse of median_interval, inv_median_interval = 1 / median_interval — shorter interval means stronger anchor property
3. **Purchase stability**: inverse of interval_std, inv_interval_std = 1 / interval_std — lower volatility means more habitual purchasing
4. **User coverage**: user_coverage — broader user coverage means more universal (not a niche product)

**Standardization & combination**: each of the four dimensions is z-score standardized (z = (x - mean) / std), then simply averaged (equal weights, to avoid overfitting):

    anchor_score = mean(z_reorder, z_inv_median_interval, z_inv_interval_std, z_coverage)

**Threshold definition**: SKUs with anchor_score in the top 30% are flagged as Anchor Items (anchor_flag = 1).

**Methodological notes**: multi-dimensional fusion (frequency + stability + scale), standardization to avoid scale issues, simple averaging for interpretability, quantile cutoff to adapt to the data distribution.

In [55]:
# First score each SKU to determine anchor SKUs

# Build the SKU behavioral base table

import numpy as np
import pandas as pd

print("========== Build SKU Anchor Table ==========")

# 1) Use prior only (historical behavior)
sku_df = prior.merge(
    orders_enriched2[["order_id", "user_id", "gap_days_adj"]],
    on="order_id",
    how="left"
).copy()

print("Merged prior + orders:", sku_df.shape)

# 2) Basic SKU statistics
sku_stats = (
    sku_df.groupby("product_id")
    .agg(
        total_orders=("order_id", "count"),
        reorder_rate=("reordered", "mean"),
        median_interval=("gap_days_adj", "median"),
        interval_std=("gap_days_adj", "std"),
        user_coverage=("user_id", "nunique"),
    )
    .reset_index()
)

print("Raw SKU stats:", sku_stats.shape)

========== Build SKU Anchor Table ==========
Merged prior + orders: (32434489, 6)
Raw SKU stats: (49677, 6)

In [56]:
# Filter out cold SKUs (for statistical stability)
# At least 200 users + at least 500 purchases
sku_stats = sku_stats[
    (sku_stats["user_coverage"] >= 200) &
    (sku_stats["total_orders"] >= 500)
].copy()

print("After filtering:", sku_stats.shape)

After filtering: (7974, 6)

In [57]:
# Step 3: build anchor_score

# Avoid division by zero
sku_stats["interval_std"] = sku_stats["interval_std"].replace(0, np.nan)

# Construct direction-consistent variables
sku_stats["inv_median_interval"] = 1 / sku_stats["median_interval"].replace(0, np.nan)
sku_stats["inv_interval_std"] = 1 / sku_stats["interval_std"]

# Standardization function
def zscore(x):
    return (x - x.mean()) / x.std()

sku_stats["z_reorder"] = zscore(sku_stats["reorder_rate"])
sku_stats["z_inv_median_interval"] = zscore(sku_stats["inv_median_interval"])
sku_stats["z_inv_interval_std"] = zscore(sku_stats["inv_interval_std"])
sku_stats["z_coverage"] = zscore(sku_stats["user_coverage"])

# Simple average (avoid overfitting)
sku_stats["anchor_score"] = (
    sku_stats[[
        "z_reorder",
        "z_inv_median_interval",
        "z_inv_interval_std",
        "z_coverage"
    ]].mean(axis=1)
)
# Step 4: define the top 30% as Anchor SKU

threshold = sku_stats["anchor_score"].quantile(0.70)

sku_stats["anchor_flag"] = (sku_stats["anchor_score"] >= threshold).astype(int)

print("Anchor SKU count:", sku_stats["anchor_flag"].sum())

# Step 5: generate the final table (saved separately)
sku_anchor_table = sku_stats[[
    "product_id",
    "total_orders",
    "user_coverage",
    "reorder_rate",
    "median_interval",
    "interval_std",
    "anchor_score",
    "anchor_flag"
]].copy()

print("\nFinal SKU Anchor Table:", sku_anchor_table.shape)
display(sku_anchor_table.head())

Anchor SKU count: 2392

Final SKU Anchor Table: (7974, 8)

,product_id,total_orders,user_coverage,reorder_rate,median_interval,interval_std,anchor_score,anchor_flag
0,1,1852,664,0.613391,7.0,8.775325,0.323695,0
9,10,2572,1203,0.506998,8.0,8.824402,-0.111120,0
22,23,1068,553,0.448502,8.0,8.719462,-0.221241,0
24,25,2166,734,0.642198,7.0,8.433906,0.553349,1
27,28,706,305,0.522663,10.0,9.110277,-0.671770,0

In [58]:
# Map to department

# ============================================================
# 0) Sanity checks (won't modify source tables)
# ============================================================
required = ["sku_anchor_table", "products", "departments", "prior", "orders_enriched2", "user_half"]
missing = [x for x in required if x not in globals()]
if missing:
    raise ValueError(f"Missing tables in memory: {missing}")

# ============================================================
# 1) Map anchor SKU -> department (create a mapping table)
# ============================================================
sku_dept = (
    sku_anchor_table[["product_id", "anchor_flag", "anchor_score"]]
    .merge(products[["product_id", "department_id"]], on="product_id", how="left")
    .merge(departments[["department_id", "department"]], on="department_id", how="left")
    .copy()
)

print("sku_dept:", sku_dept.shape)
display(sku_dept.head())

# ============================================================
# 2) Anchor SKU distribution by department
#    - share of anchor SKUs within each department
#    - department share among all anchor SKUs
# ============================================================
dept_anchor_dist = (
    sku_dept.groupby("department")
    .agg(
        total_skus=("product_id", "nunique"),
        anchor_skus=("anchor_flag", "sum"),
        mean_anchor_score=("anchor_score", "mean"),
        median_anchor_score=("anchor_score", "median"),
    )
    .reset_index()
)

dept_anchor_dist["anchor_sku_share_within_dept"] = (
    dept_anchor_dist["anchor_skus"] / dept_anchor_dist["total_skus"].replace(0, np.nan)
)

total_anchor_skus = dept_anchor_dist["anchor_skus"].sum()
dept_anchor_dist["dept_share_of_all_anchor_skus"] = (
    dept_anchor_dist["anchor_skus"] / total_anchor_skus if total_anchor_skus else np.nan
)

dept_anchor_dist = dept_anchor_dist.sort_values("dept_share_of_all_anchor_skus", ascending=False)

print("\n========== Anchor SKU distribution by department ==========")
display(dept_anchor_dist)

sku_dept: (7974, 5)

   product_id  anchor_flag  anchor_score  department_id    department
0           1            0      0.323695             19        snacks
1          10            0     -0.111120              7     beverages
2          23            0     -0.221241             12  meat seafood
3          25            1      0.553349             19        snacks
4          28            0     -0.671770             14     breakfast

========== Anchor SKU distribution by department ==========

,department,total_skus,anchor_skus,mean_anchor_score,median_anchor_score,anchor_sku_share_within_dept,dept_share_of_all_anchor_skus
7,dairy eggs,1125,478,0.205581,0.205658,0.424889,0.199833
20,snacks,1088,464,0.191055,0.219081,0.426471,0.193980
3,beverages,759,301,0.208298,0.205962,0.396574,0.125836
19,produce,719,300,0.340206,0.216776,0.417246,0.125418
1,babies,185,162,0.693379,0.718117,0.875676,0.067726
2,bakery,386,145,0.157073,0.176921,0.375648,0.060619
10,frozen,807,104,-0.247844,-0.265557,0.128872,0.043478
8,deli,313,86,0.031504,0.032538,0.274760,0.035953
4,breakfast,289,81,0.022877,0.072902,0.280277,0.033863
16,pantry,732,70,-0.389496,-0.403213,0.095628,0.029264
13,meat seafood,200,40,-0.158469,-0.218475,0.200000,0.016722
6,canned goods,361,36,-0.360846,-0.379353,0.099723,0.015050
9,dry goods pasta,328,34,-0.319203,-0.312267,0.103659,0.014214
11,household,313,24,-0.656476,-0.720819,0.076677,0.010033
17,personal care,121,15,-0.465267,-0.535748,0.123967,0.006271
0,alcohol,57,15,0.118861,0.072261,0.263158,0.006271
14,missing,24,13,0.270615,0.368168,0.541667,0.005435
12,international,125,9,-0.382462,-0.450862,0.072000,0.003763
5,bulk,14,8,0.328042,0.351518,0.571429,0.003344
18,pets,20,5,-0.189633,0.036231,0.250000,0.002090
15,other,8,2,0.007711,-0.054371,0.250000,0.000836

**Presentation Material**

1. Show anchor item category distribution by department, to visually convey the product-type composition of anchor items

In [59]:
# Compute the anchor-share difference among High users

# ============================================================
# 3) High Stay vs High->Mid: EARLY anchor share in items
#    - Build order-level anchor share for EARLY HALF orders only (for users who are early High)
#    - Then aggregate to user-level early_anchor_share
# ============================================================

# 3.1 identify early-High users + label future path
high_users = user_half.loc[user_half["early_segment"] == "High", ["user_id", "path_9"]].copy()
high_users["future_drop"] = (high_users["path_9"] == "High Down to Mid").astype(int)

# 3.2 order positions for these users (early half)
ord = orders_enriched2.loc[orders_enriched2["user_id"].isin(high_users["user_id"]), ["order_id","user_id","order_number"]].copy()
n_orders = ord.groupby("user_id")["order_id"].nunique().rename("n_orders")
ord = ord.merge(n_orders, on="user_id", how="left")
ord["pos"] = ord["order_number"] / ord["n_orders"]
ord_early = ord.loc[ord["pos"] <= 0.5, ["order_id", "user_id"]].copy()

# 3.3 order_products (prior only) for those early orders
op = prior.loc[prior["order_id"].isin(ord_early["order_id"]), ["order_id","product_id"]].copy()

# 3.4 attach anchor_flag to each item line
op = op.merge(
    sku_anchor_table[["product_id", "anchor_flag"]],
    on="product_id",
    how="left"
)
op["anchor_flag"] = op["anchor_flag"].fillna(0).astype(int)

# 3.5 order-level anchor share = anchor items / total items
order_anchor = (
    op.groupby("order_id")
    .agg(
        items=("product_id", "count"),
        anchor_items=("anchor_flag", "sum")
    )
    .reset_index()
)
order_anchor["anchor_item_share"] = order_anchor["anchor_items"] / order_anchor["items"].replace(0, np.nan)

# 3.6 user-level early anchor share (both median/mean provided)
user_early_anchor = (
    ord_early.merge(order_anchor[["order_id","anchor_item_share"]], on="order_id", how="left")
    .groupby("user_id")["anchor_item_share"]
    .agg(
        early_anchor_share_mean="mean",
        early_anchor_share_median="median",
        early_orders="count"
    )
    .reset_index()
)

# 3.7 compare High Stay vs High->Mid
anchor_compare = (
    user_early_anchor.merge(high_users[["user_id","future_drop"]], on="user_id", how="left")
    .groupby("future_drop")
    .agg(
        users=("user_id","count"),
        early_anchor_share_mean=("early_anchor_share_mean","mean"),
        early_anchor_share_median=("early_anchor_share_median","median"),
        p25=("early_anchor_share_median", lambda s: s.quantile(0.25)),
        p75=("early_anchor_share_median", lambda s: s.quantile(0.75)),
        mean_early_orders=("early_orders","mean"),
    )
    .reset_index()
)

print("\n========== Early anchor share: High Stay (0) vs High->Mid (1) ==========")
display(anchor_compare)

========== Early anchor share: High Stay (0) vs High->Mid (1) ==========

,future_drop,users,early_anchor_share_mean,early_anchor_share_median,p25,p75,mean_early_orders
0,0,35994,0.551256,0.620690,0.372674,0.736842,13.804745
1,1,18107,0.509585,0.551724,0.318182,0.700000,7.052852

**Presentation Material**

1. The difference in early anchor product share reflects behavioral instability among Mid → High users

**Analysis Module: Early Anchor Item Share and Downgrade Risk**

**Question**: Does a user's early product structure (anchor item share) affect subsequent downgrade?

**Core results (High Stay vs. High → Mid, early anchor share):**

- mean: 0.551 → 0.510
- median: 0.621 → 0.552
- p25: 0.373 → 0.318
- p75: 0.737 → 0.700

Users who later downgrade already show significantly lower anchor item share in the early stage.

**Order-count difference**: mean early orders — Stay 13.8 vs. Drop 7.0. Users who downgrade have shallower purchase history and less experience, still in an exploratory phase, not yet in a stable repurchase state.

**Mechanism**: Anchor items are the foundation supporting a stable consumption cadence. Low anchor share means the user hasn't yet formed a stable "habit basket" of repeat items — purchase motivation is more random, preventing a stable cadence from forming. This aligns with the previously observed rise in gap_std and increase in long gaps.

**Full chain**: Low anchor share (product layer) → high gap_std (behavioral layer, unstable cadence) → long gap → jump (dynamic path) → High → Mid downgrade (outcome).

**Conclusion**: Users who downgrade already lack an anchor-item-supported stable consumption structure in the early stage — lower anchor share, lower user maturity, more random and unpredictable consumption — making this the most upstream signal in the High → Mid downgrade chain.

In [60]:
# Step 1: lock in High → Mid users
import numpy as np
import pandas as pd

print("========== 1) Build Early/Late Anchor Share for High→Mid ==========")

# 1) Get High Down to Mid users
hm_users = user_half.loc[
    user_half["path_9"] == "High Down to Mid",
    ["user_id"]
].copy()

print("High→Mid users:", hm_users.shape)

# Step 2: build early / late order labels
# 2) Get these users' orders
ord = orders_enriched2.loc[
    orders_enriched2["user_id"].isin(hm_users["user_id"]),
    ["order_id", "user_id", "order_number"]
].copy()

# Total order count per user
n_orders = ord.groupby("user_id")["order_id"].nunique().rename("n_orders")
ord = ord.merge(n_orders, on="user_id", how="left")

# Compute relative position
ord["pos"] = ord["order_number"] / ord["n_orders"]

# Flag early / late
ord["half"] = np.where(ord["pos"] <= 0.5, "early", "late")

print("Orders for HM:", ord.shape)

# Step 3: compute order-level anchor share
# 3) Get the products for these orders from prior
op = prior.loc[
    prior["order_id"].isin(ord["order_id"]),
    ["order_id", "product_id"]
].copy()

# merge anchor_flag
op = op.merge(
    sku_anchor_table[["product_id", "anchor_flag"]],
    on="product_id",
    how="left"
)

op["anchor_flag"] = op["anchor_flag"].fillna(0).astype(int)

# Order-level anchor share
order_anchor = (
    op.groupby("order_id")
    .agg(
        items=("product_id", "count"),
        anchor_items=("anchor_flag", "sum")
    )
    .reset_index()
)

order_anchor["anchor_item_share"] = (
    order_anchor["anchor_items"] /
    order_anchor["items"].replace(0, np.nan)
)

print("Order-level anchor share:", order_anchor.shape)

# Step 4: aggregate to user early / late
# Merge back into the order table
ord_anchor = ord.merge(
    order_anchor[["order_id", "anchor_item_share"]],
    on="order_id",
    how="left"
)

# User-level early / late median
anchor_shift_hm = (
    ord_anchor.groupby(["user_id", "half"])["anchor_item_share"]
    .median()
    .unstack()
    .reset_index()
)

anchor_shift_hm = anchor_shift_hm.rename(
    columns={
        "early": "early_anchor_share_median",
        "late": "late_anchor_share_median"
    }
)

# Compute delta
anchor_shift_hm["delta_anchor_share"] = (
    anchor_shift_hm["late_anchor_share_median"] -
    anchor_shift_hm["early_anchor_share_median"]
)

# Direction flag
anchor_shift_hm["anchor_down_flag"] = (
    anchor_shift_hm["delta_anchor_share"] < 0
).astype(int)

print("User-level anchor shift:", anchor_shift_hm.shape)
display(anchor_shift_hm.head())

# Step 5: output summary
anchor_shift_summary_hm = {
    "users": len(anchor_shift_hm),
    "median_delta": anchor_shift_hm["delta_anchor_share"].median(),
    "mean_delta": anchor_shift_hm["delta_anchor_share"].mean(),
    "p25_delta": anchor_shift_hm["delta_anchor_share"].quantile(0.25),
    "p75_delta": anchor_shift_hm["delta_anchor_share"].quantile(0.75),
    "p90_delta": anchor_shift_hm["delta_anchor_share"].quantile(0.90),
    "pct_users_anchor_down": anchor_shift_hm["anchor_down_flag"].mean()
}

anchor_shift_summary_hm = pd.DataFrame([anchor_shift_summary_hm])

print("\n========== High→Mid Anchor Shift Summary ==========")
display(anchor_shift_summary_hm)

========== 1) Build Early/Late Anchor Share for High→Mid ==========
High→Mid users: (18107, 1)
Orders for HM: (300414, 6)
Order-level anchor share: (282307, 4)
User-level anchor shift: (18107, 5)

half,user_id,early_anchor_share_median,late_anchor_share_median,delta_anchor_share,anchor_down_flag
0,2,0.721429,0.666667,-0.054762,1
1,17,0.200000,0.211111,0.011111,0
2,18,0.633333,0.333333,-0.300000,1
3,20,0.750000,0.428571,-0.321429,1
4,40,0.615385,0.545455,-0.069930,1

========== High→Mid Anchor Shift Summary ==========

,users,median_delta,mean_delta,p25_delta,p75_delta,p90_delta,pct_users_anchor_down
0,18107,0.009091,0.011761,-0.066328,0.087229,0.167832,0.445629

**Presentation Material**

1. Within High → Mid users, the change in anchor product share is essentially 0 (mean / median both near 0), showing anchor products were not shifted to another channel — i.e., no channel diversion

**Analysis Module: Anchor Item Share Change and Channel Diversion Test**

**Question**: Use the change in anchor item share to determine whether the High → Mid downgrade is driven by "channel diversion" (users shifting staple products to another platform)?

**Core results (Anchor Share, Early vs. Late):**

- median Δ ≈ +0.009, mean Δ ≈ +0.012 (both near 0)
- p25 ≈ -0.066, p75 ≈ +0.087
- pct_users_anchor_down ≈ 44.6% (close to half, but the distribution of change direction is symmetric, no systematic decline)

**Interpretation**: If channel diversion were occurring, we'd expect a systematic decline in anchor share and most users showing anchor_down; but the actual median Δ ≈ 0 and symmetric change distribution show users did not systematically move anchor items off the platform.

Combined with earlier results (gap rising, anchor share largely stable): users are still buying the same staple products, just less often and more slowly — meaning **demand structure (what to buy) hasn't changed materially, but behavioral cadence (when to buy) has deteriorated**. The downgrade is "in-platform cadence weakening," not "off-platform migration."

**Full chain**: Anchor share (structure) largely stable → Gap (cadence) deteriorates clearly → long gap / jump → downgrade. Same demand, worse cadence, leading to churn.

**Conclusion**: The High → Mid downgrade is not driven by channel diversion, but by in-platform cadence deterioration — ruling out hypothesis B (channel diversion) in the 2×2 framework.

**A/C Hypothesis Test Method Summary**

1. Select only users who were High in the early stage, split into HS (High Stay) vs. HM (High → Mid)
2. For each user, build early / late two-stage metrics: gap mean/median/std/CV, long-interval share (≥25 / ≥30), day-of-week ordering stability (dominant DOW share, entropy), and compute the late − early change
3. **Test A (early fragility)**: compare cadence stability between HM vs. HS in the early stage, and whether it concentrates among low-order-count users (structurally shallow users)
4. **Test C (cliff structure)**: split HM users' orders into 5 lifecycle quantile segments, and observe whether gap shows a clear jump-like rise in the late stage
5. **Additional check**: whether DOW stability declines from early → late, to determine if cadence breakdown (rather than pure demand decline) is occurring

**Core logic**: if instability is already present in the early stage → supports A (structural fragility / platform friction); if a step-like gap increase appears late → supports C (cliff-type break).

In [61]:
import numpy as np
import pandas as pd

print("========== A/C Joint Tests (High Stay vs High→Mid) ==========")

# ---------------------------
# 0) Sanity checks
# ---------------------------
required = ["user_half", "orders_enriched2"]
missing = [x for x in required if x not in globals()]
if missing:
    raise ValueError(f"Missing tables in memory: {missing}")

# We will not modify any source tables. All outputs are new tables.

# ---------------------------
# 1) Define cohorts (Early High only): High Stay vs High→Mid
# ---------------------------
coh = user_half.loc[user_half["early_segment"] == "High", ["user_id", "path_9"]].copy()

coh = coh[coh["path_9"].isin(["High Stay", "High Down to Mid"])].copy()
coh["group"] = np.where(coh["path_9"] == "High Down to Mid", "HM", "HS")  # HM=High→Mid, HS=High Stay

print("Cohort users (Early High, HS vs HM):", coh.shape)
display(coh["group"].value_counts())

# ---------------------------
# 2) Pull orders for these users + label early/late + quintile
# ---------------------------
ord_cols = ["order_id", "user_id", "order_number", "order_dow", "gap_days_adj"]
ord = orders_enriched2.loc[
    orders_enriched2["user_id"].isin(coh["user_id"]),
    ord_cols
].copy()

# total orders per user
n_orders = ord.groupby("user_id")["order_id"].nunique().rename("n_orders")
ord = ord.merge(n_orders, on="user_id", how="left")

# position + early/late
ord["pos"] = ord["order_number"] / ord["n_orders"].replace(0, np.nan)
ord["half"] = np.where(ord["pos"] <= 0.5, "early", "late")

# 5 segments (quintiles) by pos
bins = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
labels = ["Q1(0-20%)", "Q2(20-40%)", "Q3(40-60%)", "Q4(60-80%)", "Q5(80-100%)"]
ord["quintile"] = pd.cut(ord["pos"], bins=bins, labels=labels, include_lowest=True)

# attach cohort group
ord = ord.merge(coh[["user_id", "group"]], on="user_id", how="left")

print("Orders in cohort:", ord.shape)
display(ord["group"].value_counts())

# ---------------------------
# 3) Helper: entropy + dominant dow share
# ---------------------------
def entropy_from_counts(counts: pd.Series) -> float:
    # counts: value_counts result
    total = counts.sum()
    if total <= 0:
        return np.nan
    p = (counts / total).values
    p = p[p > 0]
    return float(-(p * np.log(p)).sum())

def dominant_share(s: pd.Series) -> float:
    # share of the most common value
    vc = s.value_counts(dropna=True)
    if vc.empty:
        return np.nan
    return float(vc.iloc[0] / vc.sum())

# ---------------------------
# 4) User-level metrics for A/C
#    - early stability (gap_std/cv + dow stability)
#    - late stability
#    - deltas
# ---------------------------
# per user-half
user_half_metrics = (
    ord.groupby(["user_id", "group", "half"])
    .apply(lambda g: pd.Series({
        "orders_in_half": g["order_id"].nunique(),
        "gap_mean": g["gap_days_adj"].mean(),
        "gap_median": g["gap_days_adj"].median(),
        "gap_std": g["gap_days_adj"].std(),
        "gap_cv": (g["gap_days_adj"].std() / g["gap_days_adj"].mean()) if g["gap_days_adj"].mean() not in [0, np.nan] else np.nan,
        "pct_gap25p": (g["gap_days_adj"] >= 25).mean(),
        "pct_gap30": (g["gap_days_adj"] >= 30).mean(),
        "dominant_dow_share": dominant_share(g["order_dow"]),
        "dow_entropy": entropy_from_counts(g["order_dow"].value_counts()),
    }))
    .reset_index()
)

# wide to user-level
uh_wide = (
    user_half_metrics.pivot_table(
        index=["user_id", "group"],
        columns="half",
        values=[
            "orders_in_half",
            "gap_mean","gap_median","gap_std","gap_cv",
            "pct_gap25p","pct_gap30",
            "dominant_dow_share","dow_entropy"
        ],
        aggfunc="first"
    )
)

# flatten columns
uh_wide.columns = [f"{v}_{k}" for v, k in uh_wide.columns]  # e.g., gap_std_early
uh_wide = uh_wide.reset_index()

# deltas (late - early)
for base in ["gap_mean","gap_median","gap_std","gap_cv","pct_gap25p","pct_gap30","dominant_dow_share","dow_entropy"]:
    eh = f"{base}_early"
    lh = f"{base}_late"
    if eh in uh_wide.columns and lh in uh_wide.columns:
        uh_wide[f"delta_{base}"] = uh_wide[lh] - uh_wide[eh]

# attach n_orders
uh_wide = uh_wide.merge(n_orders.reset_index(), on="user_id", how="left")

ac_user_metrics = uh_wide.copy()
print("ac_user_metrics:", ac_user_metrics.shape)
display(ac_user_metrics.head())

# ---------------------------
# 5) Test 1 (A): Early stability compare HM vs HS
# ---------------------------
ac_early_summary = (
    ac_user_metrics.groupby("group")
    .agg(
        users=("user_id","count"),
        n_orders_median=("n_orders","median"),
        early_gap_std_median=("gap_std_early","median"),
        early_gap_cv_median=("gap_cv_early","median"),
        early_gap30_mean=("pct_gap30_early","mean"),
        early_dom_dow_median=("dominant_dow_share_early","median"),
        early_entropy_median=("dow_entropy_early","median"),
    )
    .reset_index()
)

print("\n========== Test 1: Early stability (HM vs HS) ==========")
display(ac_early_summary)

# ---------------------------
# 6) Test 2 (A): Drop concentration by n_orders buckets
#     (Within early-high cohort, share of HM vs HS by bucket)
# ---------------------------
bins = [0, 6, 10, 30, np.inf]
labels = ["<=6", "6-10", "10-30", "30+"]
ac_user_metrics["n_bucket"] = pd.cut(ac_user_metrics["n_orders"], bins=bins, labels=labels, right=True, include_lowest=True)

ac_bucket_table = (
    ac_user_metrics.groupby(["n_bucket","group"])
    .agg(users=("user_id","count"))
    .reset_index()
)

# pivot + compute HM share within bucket
ac_bucket_pivot = ac_bucket_table.pivot(index="n_bucket", columns="group", values="users").fillna(0).astype(int)
ac_bucket_pivot["total"] = ac_bucket_pivot.sum(axis=1)
ac_bucket_pivot["HM_share_in_bucket"] = ac_bucket_pivot["HM"] / ac_bucket_pivot["total"].replace(0, np.nan)
ac_bucket_pivot = ac_bucket_pivot.reset_index()

print("\n========== Test 2: HM concentration by order-count bucket ==========")
display(ac_bucket_pivot)

# ---------------------------
# 7) Test 3 (C): "Cliff" structure for HM (quintile trend)
#     - median gap by quintile
#     - pct gap30 by quintile
# ---------------------------
hm_orders = ord.loc[ord["group"] == "HM"].copy()

hm_quintile_table = (
    hm_orders.groupby("quintile")
    .agg(
        orders=("order_id","count"),
        users=("user_id","nunique"),
        gap_median=("gap_days_adj","median"),
        gap_p75=("gap_days_adj", lambda s: s.quantile(0.75)),
        gap_p90=("gap_days_adj", lambda s: s.quantile(0.90)),
        pct_gap25p=("gap_days_adj", lambda s: (s>=25).mean()),
        pct_gap30=("gap_days_adj", lambda s: (s>=30).mean()),
    )
    .reindex(labels)  # keep Q1..Q5 order
    .reset_index()
)

print("\n========== Test 3: HM cliff pattern (by quintile) ==========")
display(hm_quintile_table)

# ---------------------------
# 8) Test 4 (C): DOW stability breakdown (early->late deltas)
# ---------------------------
ac_dow_delta_summary = (
    ac_user_metrics.groupby("group")
    .agg(
        users=("user_id","count"),
        delta_dom_dow_median=("delta_dominant_dow_share","median"),
        delta_entropy_median=("delta_dow_entropy","median"),
        pct_dom_dow_down=("delta_dominant_dow_share", lambda s: (s < 0).mean()),
        pct_entropy_up=("delta_dow_entropy", lambda s: (s > 0).mean()),
    )
    .reset_index()
)

print("\n========== Test 4: DOW stability breakdown (HM vs HS) ==========")
display(ac_dow_delta_summary)

# ---------------------------
# 9) Outputs created (no source table modified)
# ---------------------------
print("\nNew tables created:")
print(" - ac_user_metrics        (user-level early/late metrics + deltas + n_orders)")
print(" - ac_early_summary       (HM vs HS early stability summary)")
print(" - ac_bucket_pivot        (HM concentration by n_orders bucket)")
print(" - hm_quintile_table      (HM cliff pattern by quintile)")
print(" - ac_dow_delta_summary   (HM vs HS DOW stability delta summary)")

========== A/C Joint Tests (High Stay vs High→Mid) ==========
Cohort users (Early High, HS vs HM): (50452, 3)

group
HS    32345
HM    18107
Name: count, dtype: int64

Orders in cohort: (1353617, 10)

group
HS    1053203
HM     300414
Name: count, dtype: int64

ac_user_metrics: (50452, 29)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/2245044389.py:83: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({

,user_id,group,dominant_dow_share_early,dominant_dow_share_late,dow_entropy_early,dow_entropy_late,gap_cv_early,gap_cv_late,gap_mean_early,gap_mean_late,...,pct_gap30_late,delta_gap_mean,delta_gap_median,delta_gap_std,delta_gap_cv,delta_pct_gap25p,delta_pct_gap30,delta_dominant_dow_share,delta_dow_entropy,n_orders
0,2,HM,0.500000,0.625000,1.242453,1.073543,0.426782,0.492233,9.333333,21.500000,...,0.375000,12.166667,18.5,6.599707,0.065451,0.625000,0.375000,0.125000,-0.168910,14
1,10,HS,1.000000,0.500000,-0.000000,1.039721,NaN,0.422363,30.000000,19.750000,...,0.250000,-10.250000,-11.5,NaN,NaN,-0.750000,-0.750000,-0.500000,1.039721,5
2,17,HM,0.210526,0.190476,1.895420,1.872451,0.273464,0.906239,4.947368,10.809524,...,0.142857,5.862155,1.0,8.443089,0.632775,0.190476,0.142857,-0.020050,-0.022969,40
3,18,HM,0.500000,0.500000,0.693147,1.039721,1.099944,0.320256,4.500000,6.500000,...,0.000000,2.000000,2.0,-2.868081,-0.779688,0.000000,0.000000,0.000000,0.346574,6
4,19,HS,0.666667,0.333333,0.636514,1.098612,0.675863,0.547975,9.000000,9.500000,...,0.000000,0.500000,2.0,-0.876996,-0.127887,0.000000,0.000000,-0.333333,0.462098,9

========== Test 1: Early stability (HM vs HS) ==========

,group,users,n_orders_median,early_gap_std_median,early_gap_cv_median,early_gap30_mean,early_dom_dow_median,early_entropy_median
0,HM,18107,11.0,5.241319,0.650332,0.051182,0.500000,1.039721
1,HS,32345,26.0,4.040520,0.608036,0.028880,0.366667,1.425555

========== Test 2: HM concentration by order-count bucket ==========

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/2245044389.py:159: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ac_user_metrics.groupby(["n_bucket","group"])

group n_bucket    HM     HS  total  HM_share_in_bucket
0          <=6  4757   4058   8815            0.539648
1         6-10  3769   3719   7488            0.503339
2        10-30  6977  10472  17449            0.399851
3          30+  2604  14096  16700            0.155928

========== Test 3: HM cliff pattern (by quintile) ==========

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/2245044389.py:181: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  hm_orders.groupby("quintile")

  quintile  orders  users  gap_median  gap_p75  gap_p90  pct_gap25p  pct_gap30
0      <=6     NaN    NaN         NaN      NaN      NaN         NaN        NaN
1     6-10     NaN    NaN         NaN      NaN      NaN         NaN        NaN
2    10-30     NaN    NaN         NaN      NaN      NaN         NaN        NaN
3      30+     NaN    NaN         NaN      NaN      NaN         NaN        NaN

========== Test 4: DOW stability breakdown (HM vs HS) ==========

,group,users,delta_dom_dow_median,delta_entropy_median,pct_dom_dow_down,pct_entropy_up
0,HM,18107,-0.071429,0.257123,0.598664,0.726570
1,HS,32345,-0.021429,0.082879,0.542742,0.633576

New tables created:
 - ac_user_metrics        (user-level early/late metrics + deltas + n_orders)
 - ac_early_summary       (HM vs HS early stability summary)
 - ac_bucket_pivot        (HM concentration by n_orders bucket)
 - hm_quintile_table      (HM cliff pattern by quintile)
 - ac_dow_delta_summary   (HM vs HS DOW stability delta summary)

**Presentation Material**

Further confirms that shallow habit drives the rhythm-breakdown problem — reinforces the 2×2 attribution logic; shows the characteristic differences between early High → Mid vs. High Stay users, and how rhythm breakdown actually unfolds.

1. **Early Stability (most critical)**: early_gap_std — HM 5.24 vs. HS 4.04 → HM users are already less stable in the early stage, more prone to long gaps
2. **Behavioral stability (DOW pattern)**: HM users' behavior becomes more "random" later on (no longer ordering on a fixed day)
   - dominant_dow change: HM -0.071 vs. HS -0.021
   - entropy change: HM +0.257 vs. HS +0.083
   - pct_dom_dow_down: HM 59.9% vs. HS 54.3%

**Analysis Module: A (Structural Fragility) vs. C (Cliff Break) Mechanism Validation**

**Question**: Validate two hypotheses — A: structural fragility (users are unstable from the start, high early gap_std/CV); C: cliff break (a step-like gap increase appears late).

**Test 1: Early Stability (most critical)** — HM (downgrade) vs. HS (stable):
- early_gap_std: 5.24 vs. 4.04
- early_gap_cv: 0.65 vs. 0.61
- early_gap30: 5.1% vs. 2.9%

→ HM users are already less stable in the early stage and more prone to long gaps, strongly supporting A.

**Test 2: Order-depth distribution (maturity)** — HM users clearly concentrate among low-order users: 54% have ≤6 orders, only 16% have 30+. This shows downgrading users concentrate among low-maturity users, further reinforcing A: it's not "users getting worse," but "dropping before ever stabilizing."

**Test 3: Cliff Pattern** — No result this run (NaN), but earlier evidence (late jump > mid, long gap rising, tail stretch rising) supports C — though C is a "consequence," not the "starting point."

**Test 4: Behavioral stability (DOW pattern)** — HM vs. HS: dominant_dow change -0.071 vs. -0.021; entropy change +0.257 vs. +0.083; pct_dom_dow_down 59.9% vs. 54.3%. Shows HM users' behavior becomes more random later, habits are breaking down.

**Full causal chain**: Early (A: gap_std↑, anchor share↓, shallow orders) → Mid (instability amplifies, DOW entropy↑) → Late (C: long gap↑, gap jump, user falls into low-frequency state).

**Conclusion**: **A is the root cause, C is the symptom** — users don't "suddenly downgrade," they were "unstable from the start, and eventually broke." Ruled out: channel diversion, demand change, natural lifecycle change. Confirmed mechanism: cadence formation failure.

**Objective**: Examine the temporal pattern of the High → Mid downgrade — is it a gradual decline, or a structural cadence break occurring late?

In [62]:
import numpy as np
import pandas as pd

# =========================
# High → Mid Stability Check
# =========================

# ---------- 1) Select High → Mid users ----------
hmd_users = user_half.loc[
    user_half["path_9"] == "High Down to Mid",
    "user_id"
].unique()

print("High→Mid users:", len(hmd_users))

# ---------- 2) Pull order-level data ----------
cols = ["user_id", "order_id", "order_number", "active_score_week"]
hmd_orders = orders_enriched2.loc[
    orders_enriched2["user_id"].isin(hmd_users),
    cols
].copy()

# Order count per user
n_orders = hmd_orders.groupby("user_id")["order_id"].nunique().rename("n_orders")
hmd_orders = hmd_orders.merge(n_orders, on="user_id", how="left")

# Order relative position
hmd_orders["pos"] = (
    hmd_orders["order_number"] /
    hmd_orders["n_orders"].replace(0, np.nan)
)

# ---------- 3) Three-stage split ----------
def seg30(p):
    if p <= 0.3:
        return "first30"
    elif p <= 0.6:
        return "mid30"
    else:
        return "last30"

hmd_orders["seg30"] = hmd_orders["pos"].apply(seg30)

# User × stage median weekly
hmd_user_30 = (
    hmd_orders.groupby(["user_id","n_orders","seg30"])["active_score_week"]
    .median()
    .rename("weekly_med")
    .reset_index()
    .pivot_table(index=["user_id","n_orders"],
                 columns="seg30",
                 values="weekly_med",
                 aggfunc="first")
    .reset_index()
)

# Compute delta
hmd_user_30["delta_mid_first"] = (
    hmd_user_30["mid30"] - hmd_user_30["first30"]
)
hmd_user_30["delta_last_mid"] = (
    hmd_user_30["last30"] - hmd_user_30["mid30"]
)
hmd_user_30["delta_last_first"] = (
    hmd_user_30["last30"] - hmd_user_30["first30"]
)

print("hmd_user_30:", hmd_user_30.shape)
display(hmd_user_30.head())

# ---------- 4) Stability determination ----------
hmd_user_30["monotonic_down"] = (
    (hmd_user_30["first30"] >= hmd_user_30["mid30"]) &
    (hmd_user_30["mid30"] >= hmd_user_30["last30"])
)

hmd_user_30["last_cliff"] = (
    hmd_user_30["delta_last_mid"] <
    hmd_user_30["delta_mid_first"]
)

hmd_seg30_summary = pd.DataFrame({
    "users": [hmd_user_30["user_id"].nunique()],
    "pct_monotonic_down": [hmd_user_30["monotonic_down"].mean()],
    "pct_last_cliff": [hmd_user_30["last_cliff"].mean()],
    "median_delta_mid_first": [hmd_user_30["delta_mid_first"].median()],
    "median_delta_last_mid": [hmd_user_30["delta_last_mid"].median()],
    "median_delta_last_first": [hmd_user_30["delta_last_first"].median()],
})

print("\n========== High→Mid stability summary ==========")
display(hmd_seg30_summary)

# ---------- 5) 20%×5 trend ----------
bins = [0,0.2,0.4,0.6,0.8,1.0]
labels = ["Q1","Q2","Q3","Q4","Q5"]

hmd_orders["quintile"] = pd.cut(
    hmd_orders["pos"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

hmd_quintile_trend = (
    hmd_orders.groupby("quintile")["active_score_week"]
    .agg(
        orders="count",
        users=lambda s: hmd_orders.loc[s.index,"user_id"].nunique(),
        weekly_median="median",
        weekly_p75=lambda s: s.quantile(0.75),
        weekly_p90=lambda s: s.quantile(0.90)
    )
    .reindex(labels)
    .reset_index()
)

print("\n========== High→Mid trend by quintile ==========")
display(hmd_quintile_trend)

print("\nNew tables created:")
print(" - hmd_orders")
print(" - hmd_user_30")
print(" - hmd_seg30_summary")
print(" - hmd_quintile_trend")

High→Mid users: 18107
hmd_user_30: (18107, 8)

seg30,user_id,n_orders,first30,last30,mid30,delta_mid_first,delta_last_mid,delta_last_first
0,2,14,11.375,7.233333,9.153846,-2.221154,-1.920513,-4.141667
1,17,40,9.800,7.000000,8.750000,-1.050000,-1.750000,-2.800000
2,18,6,NaN,8.555556,18.812500,NaN,-10.256944,NaN
3,20,4,NaN,7.583333,14.000000,NaN,-6.416667,NaN
4,40,9,11.375,5.100000,8.750000,-2.625000,-3.650000,-6.275000

========== High→Mid stability summary ==========

,users,pct_monotonic_down,pct_last_cliff,median_delta_mid_first,median_delta_last_mid,median_delta_last_first
0,18107,0.347821,0.420445,-2.1,-5.25,-6.125

========== High→Mid trend by quintile ==========

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/2766104814.py:106: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  hmd_orders.groupby("quintile")["active_score_week"]

  quintile  orders  users  weekly_median  weekly_p75  weekly_p90
0       Q1   36486  10299         12.250       19.25   31.500000
1       Q2   58198  16395         12.250       19.60   31.500000
2       Q3   60637  18107          9.625       16.00   27.000000
3       Q4   59910  18107          7.000       11.00   19.833333
4       Q5   67076  18107          6.125       10.50   18.666667

New tables created:
 - hmd_orders
 - hmd_user_30
 - hmd_seg30_summary
 - hmd_quintile_trend

**Analysis Module: High → Mid Dynamic Path (Final Validation)**

**Question**: Verify whether High → Mid is a gradual decline (linear decay) or a staged break (cliff)

**Core results:**

- Three-stage median change: Δ(mid-first) ≈ -2.1, Δ(last-mid) ≈ -5.25, Δ(last-first) ≈ -6.13 → the late-stage decline is far larger than the early-stage decline
- pct_last_cliff ≈ 42% (about 42% of users show a significant accelerated decline in the final stage)
- pct_monotonic_down ≈ 35% (smooth decline) — the cliff-type path (42%) is more common than linear decline (35%)
- Weekly Active Item by quintile: Q1/Q2 ~12.25 → Q3 9.6 → Q4 7.0 → Q5 6.1, continuously shifting down with tail compression, indicating an overall systemic decline, not just a tail-user issue

**Conclusion**: This data further confirms the previous conclusion — High → Mid is not a uniform linear decay, but a two-stage process of "early loosening + late-stage break," with cliff as the dominant downgrade path rather than the exception.

**Next step**: Build the complete High → Mid master table, for finer-grained analysis.

In [63]:
import pandas as pd

# =========================
# 0) Starting point: make sure these tables exist
# =========================
# lever_user_hm
# user_mech_wide
# late_user
# gap3 (three-stage analysis)
# high_early_risk

# =========================
# 1) Outcome layer
# =========================
hm_master = lever_user_hm.copy()

# =========================
# 2) Mechanism layer
# =========================
# Select key fields, avoid excessive width
mech_cols = [
    "user_id",
    "gap_std_early", "gap_std_late",
    "cap30_share_early", "cap30_share_late",
    "long25_share_early", "long25_share_late",
    "max_streak_gap25p_early", "max_streak_gap25p_late",
]

# Some column names may differ slightly; handled defensively
mech_cols = [c for c in mech_cols if c in user_mech_wide.columns]

hm_master = hm_master.merge(
    user_mech_wide[mech_cols],
    on="user_id",
    how="left"
)

# =========================
# 3) Dynamics layer
# =========================

# Extract jump info from gap3 (three-stage)
dyn_cols = [
    "user_id",
    "d_mid_early",
    "d_late_mid",
    "d_late_early",
    "jump_ratio"
]

dyn_cols = [c for c in dyn_cols if c in gap3.columns]

hm_master = hm_master.merge(
    gap3[dyn_cols],
    on="user_id",
    how="left"
)

# =========================
# 4) Persistent low freq (key dynamic)
# =========================
late_cols = [
    "user_id",
    "pct_long25",
    "pct_cap30",
    "late_gap_med",
    "max_streak_long25",
    "is_persistent_lowfreq"
]

late_cols = [c for c in late_cols if c in late_user.columns]

hm_master = hm_master.merge(
    late_user[late_cols],
    on="user_id",
    how="left"
)

# =========================
# 5) Early signal (predictive layer)
# =========================
early_cols = [
    "user_id",
    "early_gap_std",
    "early_gap_cv",
    "early_pct_gap25p",
    "early_pct_gap30",
    "future_drop"
]

early_cols = [c for c in early_cols if c in high_early_risk.columns]

hm_master = hm_master.merge(
    high_early_risk[early_cols],
    on="user_id",
    how="left"
)

# =========================
# 6) Derived fields (recommended additions)
# =========================

# gap-dominant vs. basket-dominant
hm_master["gap_dominant"] = (
    hm_master["delta_gap"].abs() > hm_master["delta_basket"].abs()
).astype(int)

# whether accelerated deterioration occurred
hm_master["is_accelerating"] = (
    hm_master["d_late_mid"] > hm_master["d_mid_early"]
).astype(int)

# =========================
# 7) Final check
# =========================
print("hm_master_table shape:", hm_master.shape)
display(hm_master.head())

hm_master_table shape: (18107, 33)

,user_id,basket_med_early,basket_med_late,gap_med_early,gap_med_late,n_orders_half_early,n_orders_half_late,delta_gap,delta_basket,gap_std_early,...,late_gap_med,max_streak_long25,is_persistent_lowfreq,early_gap_std,early_gap_cv,early_pct_gap25p,early_pct_gap30,future_drop,gap_dominant,is_accelerating
0,2,13.0,16.0,9.0,27.5,6,8,18.5,3.0,3.983298,...,28.0,3,1,3.983298,0.426782,0.0,0.0,1,1,1
1,17,7.0,7.0,5.0,6.0,19,21,1.0,0.0,1.352926,...,8.5,1,0,1.352926,0.273464,0.0,0.0,1,1,1
2,18,4.0,8.5,4.5,6.5,2,4,2.0,4.5,4.949747,...,6.5,0,0,4.949747,1.099944,0.0,0.0,1,0,0
3,20,4.0,7.0,2.0,7.0,1,3,5.0,3.0,NaN,...,6.5,0,0,NaN,NaN,0.0,0.0,1,1,0
4,40,13.0,11.0,8.0,14.5,3,6,6.5,-2.0,2.309401,...,14.0,0,0,2.309401,0.247436,0.0,0.0,1,1,0

**Objective**: Compute the dominant day-of-week distribution for High → Mid users, to observe changes in fixed shopping-day cadence.

In [64]:
# First split into two halves

import numpy as np
import pandas as pd

hm_users = hm_master["user_id"].unique()

df = orders_enriched2.loc[
    orders_enriched2["user_id"].isin(hm_users),
    ["user_id", "order_number", "order_dow"]
].copy()

# Order count per user
n_orders = df.groupby("user_id")["order_number"].max().rename("n_orders")
df = df.merge(n_orders, on="user_id", how="left")

# Split early / late
df["pos"] = df["order_number"] / df["n_orders"]
df["half"] = np.where(df["pos"] <= 0.5, "early", "late")
# Compute DOW distribution

dow_dist = (
    df.groupby(["user_id", "half", "order_dow"])
    .size()
    .rename("cnt")
    .reset_index()
)

# Total orders per user-half
total = dow_dist.groupby(["user_id", "half"])["cnt"].sum().rename("total")
dow_dist = dow_dist.merge(total, on=["user_id", "half"])

# Probability
dow_dist["p"] = dow_dist["cnt"] / dow_dist["total"]
# entropy
dow_entropy = (
    dow_dist.groupby(["user_id", "half"])["p"]
    .apply(lambda s: -(s * np.log(s + 1e-9)).sum())
    .rename("dow_entropy")
)

# dominant share
dominant = (
    dow_dist.groupby(["user_id", "half"])["p"]
    .max()
    .rename("dominant_dow_share")
)

dow_metrics = pd.concat([dow_entropy, dominant], axis=1).reset_index()
dow_wide = dow_metrics.pivot(index="user_id", columns="half")
dow_wide.columns = [f"{a}_{b}" for a,b in dow_wide.columns]
dow_wide = dow_wide.reset_index()
hm_master = hm_master.merge(dow_wide, on="user_id", how="left")
hm_master["delta_entropy"] = (
    hm_master["dow_entropy_late"] - hm_master["dow_entropy_early"]
)

hm_master["delta_dominant"] = (
    hm_master["dominant_dow_share_late"] - hm_master["dominant_dow_share_early"]
)
hm_master[[
    "user_id",
    "dow_entropy_early",
    "dow_entropy_late",
    "delta_entropy",
    "dominant_dow_share_early",
    "dominant_dow_share_late",
    "delta_dominant"
]].head(10)

,user_id,dow_entropy_early,dow_entropy_late,delta_entropy,dominant_dow_share_early,dominant_dow_share_late,delta_dominant
0,2,1.242453e+00,1.073543e+00,-0.168910,0.500000,0.625000,0.125000
1,17,1.895420e+00,1.872451e+00,-0.022969,0.210526,0.190476,-0.020050
2,18,6.931472e-01,1.039721e+00,0.346574,0.500000,0.500000,0.000000
3,20,-1.000000e-09,6.365142e-01,0.636514,1.000000,0.666667,-0.333333
4,40,1.039721e+00,-1.000000e-09,-1.039721,0.500000,1.000000,0.500000
5,58,1.153742e+00,1.386294e+00,0.232552,0.571429,0.250000,-0.321429
6,63,1.867880e+00,1.825199e+00,-0.042681,0.210526,0.300000,0.089474
7,71,1.546599e+00,1.863680e+00,0.317081,0.272727,0.250000,-0.022727
8,74,6.931472e-01,1.098612e+00,0.405465,0.500000,0.333333,-0.166667
9,111,6.365142e-01,1.039721e+00,0.403207,0.666667,0.500000,-0.166667

In [65]:
(hm_master["delta_entropy"] > 0).mean()

np.float64(0.6274369028552493)

In [66]:
(hm_master["delta_dominant"] < 0).mean()

np.float64(0.5635389628320538)

**Conclusion**: Over 60% of users progressively lose a fixed shopping cadence, with purchase behavior becoming more random — a key leading indicator of frequency collapse.

**Objective**: Test whether downgrading users show gap recovery in the late stage. Threshold set at 80% (close to, but not requiring, full recovery to 100% of historical frequency).

In [67]:
import pandas as pd

# =========================
# 1) Compute recovery ratio
# =========================
hm_master["recovery_ratio"] = (
    hm_master["gap_med_early"] / hm_master["gap_med_late"]
)

# =========================
# 2) Define recovery status (usable for segmentation)
# =========================
hm_master["recovery_bucket"] = pd.cut(
    hm_master["recovery_ratio"],
    bins=[-float("inf"), 0.5, 0.8, 1.2, float("inf")],
    labels=[
        "Severely not recovered (<0.5)",
        "Not recovered (0.5-0.8)",
        "Partially recovered (0.8-1.2)",
        "Over recovered (>1.2)"
    ]
)

# =========================
# 3) Summary (🔥 core table for PPT)
# =========================
recovery_summary = pd.DataFrame({
    "metric": [
        "median_recovery_ratio",
        "pct_recovered_>=0.8",
        "pct_not_recovered_<0.8",
        "pct_severely_not_recovered_<0.5"
    ],
    "value": [
        hm_master["recovery_ratio"].median(),
        (hm_master["recovery_ratio"] >= 0.8).mean(),
        (hm_master["recovery_ratio"] < 0.8).mean(),
        (hm_master["recovery_ratio"] < 0.5).mean()
    ]
})

print("========== Recovery Summary ==========")
display(recovery_summary)

# =========================
# 4) Distribution (optional, for charting)
# =========================
recovery_dist = (
    hm_master["recovery_bucket"]
    .value_counts(normalize=True)
    .rename("share")
    .reset_index()
    .rename(columns={"index": "recovery_bucket"})
)

print("\n========== Recovery Distribution ==========")
display(recovery_dist)

========== Recovery Summary ==========

                            metric     value
0            median_recovery_ratio  0.571429
1              pct_recovered_>=0.8  0.262827
2           pct_not_recovered_<0.8  0.737173
3  pct_severely_not_recovered_<0.5  0.382559

========== Recovery Distribution ==========

                 recovery_bucket     share
0  Severely not recovered (<0.5)  0.425968
1        Not recovered (0.5-0.8)  0.325068
2  Partially recovered (0.8-1.2)  0.199812
3          Over recovered (>1.2)  0.049152

In [68]:
# ============================================================
# Augment lever_user_hm with ge10 / ge30 / d_log_weekly
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Step 1: augment with d_log_weekly / d_log_gap from path_growth_user
# ----------------------------------------
hm_weekly = path_growth_user[
    path_growth_user["path_9"] == "High Down to Mid"
][["user_id", "d_log_weekly", "d_log_gap"]].copy()

print(f"High→Mid user count in path_growth_user: {len(hm_weekly):,}")
print(f"lever_user_hm user count: {len(lever_user_hm):,}")

# merge
hm_master = lever_user_hm.merge(
    hm_weekly, on="user_id", how="inner"
)
print(f"User count after merge: {len(hm_master):,}")

# ----------------------------------------
# Step 2: compute ge10 / ge30 from orders_enriched2
# ----------------------------------------

# Get orders for High→Mid users
hm_orders_ge = (
    orders_enriched2
    .merge(hm_master[["user_id"]], on="user_id", how="inner")
    .sort_values(["user_id", "order_number"])
    .copy()
)

# Add pos and half
user_n = (
    hm_orders_ge
    .groupby("user_id")["order_number"]
    .max()
    .reset_index()
    .rename(columns={"order_number": "n_orders"})
)
hm_orders_ge = hm_orders_ge.merge(user_n, on="user_id", how="left")
hm_orders_ge["pos"]  = hm_orders_ge["order_number"] / hm_orders_ge["n_orders"]
hm_orders_ge["half"] = np.where(
    hm_orders_ge["pos"] <= 0.5, "early", "late"
)

hm_early = hm_orders_ge[hm_orders_ge["half"] == "early"]
hm_late  = hm_orders_ge[hm_orders_ge["half"] == "late"]

# Compute ge10 / ge30
for cutoff in [10, 30]:
    for half_name, df_half in [("early", hm_early), ("late", hm_late)]:
        col = f"ge{cutoff}_{half_name}"
        pct = (
            df_half
            .groupby("user_id")["gap_days_adj"]
            .apply(lambda x: (x >= cutoff).mean())
            .reset_index()
            .rename(columns={"gap_days_adj": col})
        )
        hm_master = hm_master.merge(pct, on="user_id", how="left")

hm_master["delta_ge10"] = hm_master["ge10_late"] - hm_master["ge10_early"]
hm_master["delta_ge30"] = hm_master["ge30_late"] - hm_master["ge30_early"]

print(f"\nhm_master shape: {hm_master.shape}")
print(f"columns: {hm_master.columns.tolist()}")

# ========================================
# Layer 1: ge10 did indeed deteriorate
# ========================================
print("\n" + "="*70)
print("Layer 1: ge10 vs. ge30 change among High→Mid users")
print("="*70)

print(f"\n{'Metric':<20} {'Early':>8} {'Late':>8} {'Delta':>8} {'Worse%':>8}")
print("-"*55)

for label, early_col, late_col, delta_col in [
    ("ge10 (10+ days)", "ge10_early", "ge10_late", "delta_ge10"),
    ("ge30 (30+ days)", "ge30_early", "ge30_late", "delta_ge30"),
]:
    early_med = hm_master[early_col].median()
    late_med  = hm_master[late_col].median()
    delta_med = hm_master[delta_col].median()
    worsen_pct = (hm_master[delta_col] > 0).mean()
    print(f"{label:<20} {early_med:>8.3f} {late_med:>8.3f} "
          f"{delta_med:>+8.3f} {worsen_pct:>8.1%}")

print(f"\nShare of users with ge10 deterioration: {(hm_master['delta_ge10'] > 0).mean():.1%}")
print(f"Share of users with ge30 deterioration: {(hm_master['delta_ge30'] > 0).mean():.1%}")

# ========================================
# Layer 3: correlation of ge10 vs. ge30 with weekly decline
# ========================================
print("\n" + "="*70)
print("Layer 3: correlation of ge10 vs. ge30 with weekly decline")
print("="*70)

valid = hm_master.dropna(subset=["delta_ge10", "delta_ge30", "d_log_weekly"])
print(f"\nValid sample: {len(valid):,}")

print(f"\n{'Metric':<25} {'Spearman':>10} {'Sig':>6}")
print("-"*45)

for col, label in [
    ("delta_ge10", "ge10 change (10+ days)"),
    ("delta_ge30", "ge30 change (30+ days)"),
    ("d_log_gap",  "overall gap change"),
]:
    r, p = stats.spearmanr(valid[col], valid["d_log_weekly"])
    sig = "***" if p < 0.001 else ("**" if p < 0.01 else
          ("*" if p < 0.05 else "ns"))
    print(f"  {col:<23} {r:>10.4f} {sig:>6}  {label}")

# Bucket validation
for col, label in [
    ("delta_ge10", "ge10"),
    ("delta_ge30", "ge30"),
]:
    valid_tmp = valid[[col, "d_log_weekly"]].dropna().copy()
    valid_tmp["bucket"] = pd.qcut(
        valid_tmp[col].rank(method="first"),
        q=5,
        labels=["Q1", "Q2", "Q3", "Q4", "Q5"],
        duplicates="drop"
    )
    bucket = (
        valid_tmp.groupby("bucket", observed=True)
        .agg(
            users=(col, "count"),
            x_mean=(col, "mean"),
            weekly_mean=("d_log_weekly", "mean"),
        )
        .reset_index()
    )
    print(f"\n--- {label} Uplift Curve ---")
    print(f"{'Bucket':<8} {'x_mean':>10} {'weekly_mean':>12}")
    for _, row in bucket.iterrows():
        print(f"{row['bucket']:<8} {row['x_mean']:>10.4f} "
              f"{row['weekly_mean']:>12.4f}")

# ----------------------------------------
# Symmetry summary
# ----------------------------------------
print("\n" + "="*70)
print("Symmetry validation: Mid→High vs. High→Mid")
print("="*70)

r_ge10, _ = stats.spearmanr(valid["delta_ge10"], valid["d_log_weekly"])
r_ge30, _ = stats.spearmanr(valid["delta_ge30"], valid["d_log_weekly"])

print(f"""
                    Mid→High (growth)    High→Mid (decline)
ge10 Spearman：      -0.345              {r_ge10:.4f}
ge30 Spearman：      -0.244              {r_ge30:.4f}
""")

print("✅ New tables created:")
print("  - hm_master  (High→Mid full master table)")

path_growth_user 中 High→Mid 用户数: 17,502
lever_user_hm 用户数: 18,107
merge 后用户数: 17,502

hm_master shape: (17502, 17)
columns: ['user_id', 'basket_med_early', 'basket_med_late', 'gap_med_early', 'gap_med_late', 'n_orders_half_early', 'n_orders_half_late', 'delta_gap', 'delta_basket', 'd_log_weekly', 'd_log_gap', 'ge10_early', 'ge10_late', 'ge30_early', 'ge30_late', 'delta_ge10', 'delta_ge30']

======================================================================
第一层：ge10 vs ge30 在 High→Mid 用户里的变化
======================================================================

指标                      Early     Late    Delta      恶化%
-------------------------------------------------------
ge10（10天+）              0.333    0.625   +0.250    79.6%
ge30（30天+）              0.000    0.143   +0.077    57.3%

ge10 恶化用户比例：79.6%
ge30 恶化用户比例：57.3%

======================================================================
第三层：ge10 vs ge30 和 weekly decline 的相关性
======================================================================

有效样本：17,502

指标                          Spearman    Sig
---------------------------------------------
  delta_ge10                 -0.3611    ***  ge10 变化（10天+）
  delta_ge30                 -0.2577    ***  ge30 变化（30天+）
  d_log_gap                  -0.6075    ***  整体 gap 变化

--- ge10 Uplift Curve ---
Bucket       x_mean  weekly_mean
Q1          -0.1210      -0.6263
Q2           0.0965      -0.6984
Q3           0.2427      -0.7431
Q4           0.4068      -0.9171
Q5           0.6924      -1.1135

--- ge30 Uplift Curve ---
Bucket       x_mean  weekly_mean
Q1          -0.1023      -0.7133
Q2           0.0000      -0.7337
Q3           0.0761      -0.6967
Q4           0.2288      -0.8904
Q5           0.5120      -1.0643

======================================================================
对称性验证：Mid→High vs High→Mid
======================================================================

                    Mid→High（增长）    High→Mid（下降）
ge10 Spearman：      -0.345              -0.3611
ge30 Spearman：      -0.244              -0.2577

✅ New tables created:
  - hm_master  (High→Mid 完整主表)

In [69]:
# ============================================================
# High→Mid: Zone correlation + X day+ cutoff analysis
# Symmetric validation against Mid→High
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Confirm hm_master already has the needed columns
# ----------------------------------------
print("hm_master columns:")
print(hm_master.columns.tolist())
print(f"shape: {hm_master.shape}")

# ----------------------------------------
# Part 1: Zone correlation analysis
# Need to compute the Zone distribution for High→Mid users first
# ----------------------------------------
print("\n" + "="*70)
print("Part 1: Zone correlation analysis")
print("="*70)

# Define Zone
def assign_zone(gap):
    if pd.isna(gap):
        return np.nan
    elif gap <= 7:
        return "Zone1_weekly"
    elif gap <= 14:
        return "Zone2_biweekly"
    elif gap <= 21:
        return "Zone3_warning"
    elif gap <= 29:
        return "Zone4_danger"
    else:
        return "Zone5_cliff"

# Tag each order with a Zone label
hm_orders_ge["gap_zone"] = hm_orders_ge["gap_days_adj"].apply(assign_zone)

# Compute each user's early/late Zone share
zone_cols = [
    "Zone1_weekly", "Zone2_biweekly",
    "Zone3_warning", "Zone4_danger", "Zone5_cliff"
]

# early Zone share
early_zone = (
    hm_orders_ge[hm_orders_ge["half"] == "early"]
    .groupby("user_id")["gap_zone"]
    .value_counts(normalize=True)
    .unstack(fill_value=0)
    .reset_index()
)
early_zone.columns = (
    ["user_id"] +
    [f"early_{c}" for c in early_zone.columns[1:]]
)

# late Zone share
late_zone = (
    hm_orders_ge[hm_orders_ge["half"] == "late"]
    .groupby("user_id")["gap_zone"]
    .value_counts(normalize=True)
    .unstack(fill_value=0)
    .reset_index()
)
late_zone.columns = (
    ["user_id"] +
    [f"late_{c}" for c in late_zone.columns[1:]]
)

# Merge
hm_zone = hm_master[["user_id", "d_log_weekly"]].merge(
    early_zone, on="user_id", how="left"
).merge(
    late_zone, on="user_id", how="left"
)

# Compute delta
for zone in zone_cols:
    early_col = f"early_{zone}"
    late_col  = f"late_{zone}"
    if early_col in hm_zone.columns and late_col in hm_zone.columns:
        hm_zone[f"delta_{zone}"] = (
            hm_zone[late_col] - hm_zone[early_col]
        )

# Correlation analysis
print(f"\n{'Zone':<20} {'Early':>8} {'Late':>8} {'Delta':>8} "
      f"{'Spearman':>10} {'Sig':>6}")
print("-"*65)

zone_results = []
for zone in zone_cols:
    early_col = f"early_{zone}"
    late_col  = f"late_{zone}"
    delta_col = f"delta_{zone}"

    if delta_col not in hm_zone.columns:
        continue

    valid = hm_zone[[early_col, late_col,
                     delta_col, "d_log_weekly"]].dropna()

    early_med = valid[early_col].mean()
    late_med  = valid[late_col].mean()
    delta_med = valid[delta_col].mean()

    r, p = stats.spearmanr(valid[delta_col], valid["d_log_weekly"])
    sig = "***" if p < 0.001 else ("**" if p < 0.01 else
          ("*" if p < 0.05 else "ns"))

    zone_results.append({
        "zone": zone, "spearman": r, "sig": sig
    })

    print(f"  {zone:<18} {early_med:>8.1%} {late_med:>8.1%} "
          f"{delta_med:>+8.1%} {r:>10.4f} {sig:>6}")

# ----------------------------------------
# Part 2: X day+ cutoff analysis
# ----------------------------------------
print("\n" + "="*70)
print("Part 2: X day+ cutoff vs. weekly decline correlation")
print("="*70)

cutoff_results = []

for cutoff in range(7, 31):
    early_pct = (
        hm_orders_ge[hm_orders_ge["half"] == "early"]
        .groupby("user_id")["gap_days_adj"]
        .apply(lambda x: (x >= cutoff).mean())
        .reset_index()
        .rename(columns={"gap_days_adj": f"early_ge{cutoff}"})
    )
    late_pct = (
        hm_orders_ge[hm_orders_ge["half"] == "late"]
        .groupby("user_id")["gap_days_adj"]
        .apply(lambda x: (x >= cutoff).mean())
        .reset_index()
        .rename(columns={"gap_days_adj": f"late_ge{cutoff}"})
    )

    merged = (
        hm_master[["user_id", "d_log_weekly"]]
        .merge(early_pct, on="user_id", how="inner")
        .merge(late_pct,  on="user_id", how="inner")
        .dropna()
    )
    merged[f"delta_ge{cutoff}"] = (
        merged[f"late_ge{cutoff}"] - merged[f"early_ge{cutoff}"]
    )

    r, p = stats.spearmanr(
        merged[f"delta_ge{cutoff}"], merged["d_log_weekly"]
    )
    sig = "***" if p < 0.001 else ("ns")

    cutoff_results.append({
        "cutoff"     : cutoff,
        "early_mean" : merged[f"early_ge{cutoff}"].mean(),
        "late_mean"  : merged[f"late_ge{cutoff}"].mean(),
        "delta_mean" : merged[f"delta_ge{cutoff}"].mean(),
        "spearman_r" : round(r, 4),
        "sig"        : sig,
    })

cutoff_df = pd.DataFrame(cutoff_results)

# Find the strongest cutoff
best_idx    = cutoff_df["spearman_r"].idxmin()
best_cutoff = cutoff_df.loc[best_idx, "cutoff"]
best_r      = cutoff_df.loc[best_idx, "spearman_r"]

print(f"\n{'Cutoff':>8} {'Early':>8} {'Late':>8} "
      f"{'Delta':>8} {'Spearman':>10} {'Sig':>6}")
print("-"*55)

for _, row in cutoff_df.iterrows():
    marker = " ← strongest" if row["cutoff"] == best_cutoff else ""
    print(f"ge{row['cutoff']:>2}d    "
          f"{row['early_mean']:>8.3f} "
          f"{row['late_mean']:>8.3f} "
          f"{row['delta_mean']:>+8.3f} "
          f"{row['spearman_r']:>10.4f} "
          f"{row['sig']:>6}{marker}")

print(f"\n→ Strongest cutoff: Day {best_cutoff}")
print(f"→ Spearman r = {best_r:.4f}")

# ----------------------------------------
# Symmetry summary
# ----------------------------------------
print("\n" + "="*70)
print("Symmetry summary: Mid→High vs. High→Mid")
print("="*70)

hm_ge10_r = cutoff_df[cutoff_df["cutoff"] == 10]["spearman_r"].values[0]
hm_ge30_r = cutoff_df[cutoff_df["cutoff"] == 30]["spearman_r"].values[0]

print(f"""
                    Mid→High (growth)    High→Mid (decline)
ge10 Spearman：      -0.345              {hm_ge10_r:.4f}
ge30 Spearman：      -0.244              {hm_ge30_r:.4f}
Strongest cutoff:      Day 10              Day {best_cutoff}

Zone1 Spearman:      +0.330              TBD
Zone5 Spearman:      -0.244              TBD
""")

# Copyable table
print("\nCopyable table for Excel:")
print("Cutoff\tEarly\tLate\tDelta\tSpearman\tSig")
for _, row in cutoff_df.iterrows():
    print(f"ge{row['cutoff']}d\t"
          f"{row['early_mean']:.3f}\t"
          f"{row['late_mean']:.3f}\t"
          f"{row['delta_mean']:+.3f}\t"
          f"{row['spearman_r']:.4f}\t"
          f"{row['sig']}")

print("\n✅ New tables created:")
print("  - hm_zone     (High→Mid Zone distribution)")
print("  - cutoff_df   (X day+ cutoff correlation)")

hm_master columns:
['user_id', 'basket_med_early', 'basket_med_late', 'gap_med_early', 'gap_med_late', 'n_orders_half_early', 'n_orders_half_late', 'delta_gap', 'delta_basket', 'd_log_weekly', 'd_log_gap', 'ge10_early', 'ge10_late', 'ge30_early', 'ge30_late', 'delta_ge10', 'delta_ge30']
shape: (17502, 17)

======================================================================
Part 1：Zone 相关性分析
======================================================================

Zone                    Early     Late    Delta   Spearman    Sig
-----------------------------------------------------------------
  Zone1_weekly          54.9%    31.3%   -23.6%     0.3584    ***
  Zone2_biweekly        26.4%    25.1%    -1.3%    -0.0523    ***
  Zone3_warning          8.2%    13.8%    +5.7%    -0.0985    ***
  Zone4_danger           3.9%     8.8%    +4.9%    -0.0948    ***
  Zone5_cliff            6.7%    21.0%   +14.3%    -0.2577    ***

======================================================================
Part 2：X day+ cutoff vs weekly decline 相关性
======================================================================

  Cutoff    Early     Late    Delta   Spearman    Sig
-------------------------------------------------------
ge 7d       0.567    0.765   +0.199    -0.3228    ***
ge 8d       0.451    0.687   +0.236    -0.3585    ***
ge 9d       0.380    0.635   +0.255    -0.3706    *** ← 最强
ge10d       0.335    0.598   +0.263    -0.3611    ***
ge11d       0.300    0.567   +0.267    -0.3607    ***
ge12d       0.271    0.538   +0.267    -0.3541    ***
ge13d       0.247    0.509   +0.262    -0.3464    ***
ge14d       0.219    0.476   +0.257    -0.3399    ***
ge15d       0.188    0.436   +0.248    -0.3317    ***
ge16d       0.168    0.408   +0.240    -0.3288    ***
ge17d       0.155    0.387   +0.233    -0.3195    ***
ge18d       0.144    0.370   +0.225    -0.3149    ***
ge19d       0.134    0.354   +0.219    -0.3124    ***
ge20d       0.126    0.337   +0.211    -0.3058    ***
ge21d       0.117    0.319   +0.202    -0.2985    ***
ge22d       0.106    0.298   +0.192    -0.2902    ***
ge23d       0.098    0.283   +0.184    -0.2858    ***
ge24d       0.093    0.271   +0.178    -0.2829    ***
ge25d       0.088    0.261   +0.173    -0.2783    ***
ge26d       0.084    0.252   +0.168    -0.2744    ***
ge27d       0.081    0.243   +0.163    -0.2699    ***
ge28d       0.076    0.233   +0.157    -0.2665    ***
ge29d       0.071    0.219   +0.148    -0.2610    ***
ge30d       0.067    0.210   +0.143    -0.2577    ***

→ 最强 cutoff：Day 9
→ Spearman r = -0.3706

======================================================================
对称性总结：Mid→High vs High→Mid
======================================================================

                    Mid→High（增长）    High→Mid（下降）
ge10 Spearman：      -0.345              -0.3611
ge30 Spearman：      -0.244              -0.2577
最强 cutoff：         Day 10              Day 9

Zone1 Spearman：     +0.330              待填入
Zone5 Spearman：     -0.244              待填入


可复制到 Excel 的表格：
Cutoff	Early	Late	Delta	Spearman	Sig
ge7d	0.567	0.765	+0.199	-0.3228	***
ge8d	0.451	0.687	+0.236	-0.3585	***
ge9d	0.380	0.635	+0.255	-0.3706	***
ge10d	0.335	0.598	+0.263	-0.3611	***
ge11d	0.300	0.567	+0.267	-0.3607	***
ge12d	0.271	0.538	+0.267	-0.3541	***
ge13d	0.247	0.509	+0.262	-0.3464	***
ge14d	0.219	0.476	+0.257	-0.3399	***
ge15d	0.188	0.436	+0.248	-0.3317	***
ge16d	0.168	0.408	+0.240	-0.3288	***
ge17d	0.155	0.387	+0.233	-0.3195	***
ge18d	0.144	0.370	+0.225	-0.3149	***
ge19d	0.134	0.354	+0.219	-0.3124	***
ge20d	0.126	0.337	+0.211	-0.3058	***
ge21d	0.117	0.319	+0.202	-0.2985	***
ge22d	0.106	0.298	+0.192	-0.2902	***
ge23d	0.098	0.283	+0.184	-0.2858	***
ge24d	0.093	0.271	+0.178	-0.2829	***
ge25d	0.088	0.261	+0.173	-0.2783	***
ge26d	0.084	0.252	+0.168	-0.2744	***
ge27d	0.081	0.243	+0.163	-0.2699	***
ge28d	0.076	0.233	+0.157	-0.2665	***
ge29d	0.071	0.219	+0.148	-0.2610	***
ge30d	0.067	0.210	+0.143	-0.2577	***

✅ New tables created:
  - hm_zone     (High→Mid Zone 分布)
  - cutoff_df   (X day+ cutoff 相关性)

In [70]:
print("===== DOW Stability Summary =====")
print(f"% users entropy UP  (more random) : {((dow_wide['dow_entropy_late'] - dow_wide['dow_entropy_early']) > 0).mean():.1%}")
print(f"% users dominant DOW DOWN (less fixed): {((dow_wide['dominant_dow_share_late'] - dow_wide['dominant_dow_share_early']) < 0).mean():.1%}")

===== DOW Stability Summary =====
% users entropy UP  (more random) : 62.7%
% users dominant DOW DOWN (less fixed): 56.4%

# 📈 Section 7: Mid → High Analysis — Table Setup

> Build the master analysis tables: order_items_full / mid_struct_user / basket_master_user_wk / analysis_mid_user_master

---

**Objective**: Mid → High spans multiple analytical dimensions; first build the required base tables. Core analysis: gap (purchase frequency) × basket (order size) × role shift (category-role change).

In [71]:
# No item-level info within orders yet - first merge a master table, needed for the later detailed role-shift analysis
# ===============================
# Build order_items_full
# ===============================

import pandas as pd

# -------- 1) Merge prior + train --------
order_products = pd.concat(
    [prior, train],
    axis=0,
    ignore_index=True
)

print("order_products:", order_products.shape)

# -------- 2) Keep only necessary orders columns --------
orders_small = orders[[
    "order_id",
    "user_id",
    "order_number",
    "order_dow",
    "order_hour_of_day",
    "days_since_prior_order"
]].copy()

print("orders_small:", orders_small.shape)

# -------- 3) Merge order structure --------
order_items = order_products.merge(
    orders_small,
    on="order_id",
    how="left"
)

print("after merge orders:", order_items.shape)

# -------- 4) Keep only necessary products columns --------
products_small = products[[
    "product_id",
    "aisle_id",
    "department_id"
]].copy()

# -------- 5) Merge product structure --------
order_items_full = order_items.merge(
    products_small,
    on="product_id",
    how="left"
)

print("after merge products:", order_items_full.shape)

# -------- 6) Clean up nulls --------
order_items_full = order_items_full.dropna(
    subset=["user_id", "department_id"]
).copy()

print("final order_items_full:", order_items_full.shape)

# -------- 7) Simple sanity check --------
print("\nColumns:")
print(order_items_full.columns.tolist())

order_items_full.head()

order_products: (33819106, 4)
orders_small: (3421083, 6)
after merge orders: (33819106, 9)
after merge products: (33819106, 11)
final order_items_full: (33819106, 11)

Columns:
['order_id', 'product_id', 'add_to_cart_order', 'reordered', 'user_id', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', 'aisle_id', 'department_id']

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,aisle_id,department_id
0,2,33120,1,1,202279,3,5,9,8.0,86,16
1,2,28985,2,1,202279,3,5,9,8.0,83,4
2,2,9327,3,0,202279,3,5,9,8.0,104,13
3,2,45918,4,1,202279,3,5,9,8.0,19,13
4,2,30035,5,0,202279,3,5,9,8.0,17,13

In [72]:
# Build the structure index table

# =========================================================
# Dept → structural tag index table (overlapping tags allowed, not mutually exclusive)
# Purpose:
#   1) Map department_id to multiple structural tags in the lightest way possible
#   2) So later order-level aggregation can directly sum / compute share
# Note:
#   - These are "structural tags," not hard buckets
#   - The same department can belong to multiple tags (e.g. Core ∩ Consumable)
# =========================================================

# ---------- Input dependencies ----------
# departments: (21,2) [department_id, department]
if "departments" not in globals():
    raise ValueError("Missing table: departments (department_id, department)")

# =========================================================
# 1) Define the four structural tags (latest version)
# =========================================================

# 🟦 ① Consumable (high-frequency consumables):
# Drives frequency / shortens gap: replenished as soon as it runs out
CONSUMABLE_DEPTS = {4, 16, 12, 14, 19, 7, 20}

# 🟩 ② Core Grocery (primary shopping core):
# Platform share grows / shifts from top-up to primary shopping: purchase structure looks more like a "big basket"
# ⚠️ Can overlap with consumable (allowed)
CORE_DEPTS = {4, 16, 12, 13, 9, 15, 3}

# 🟨 ③ Variety / Breadth Expansion:
# Buys a wider range, demand complexity↑, platform trust↑
VARIETY_DEPTS = {1, 6, 10, 5, 19, 7, 3}

# 🟥 ④ Durable / Low-Frequency:
# Doesn't drive frequency, long cycle, general household top-up
DURABLE_DEPTS = {17, 11, 8, 18, 2, 21}


# =========================================================
# 2) Build a small 21-row index table, dept_tag_map_struct
#    (department names kept only in the small table, doesn't pollute the large table)
# =========================================================
dept_tag_map_struct = departments[["department_id", "department"]].drop_duplicates().copy()
dept_tag_map_struct["department_id"] = pd.to_numeric(
    dept_tag_map_struct["department_id"], errors="coerce"
).astype("Int64")
dept_tag_map_struct = dept_tag_map_struct.dropna(subset=["department_id"]).copy()
dept_tag_map_struct["department_id"] = dept_tag_map_struct["department_id"].astype(int)

# Generate tag columns (0/1) in the small table, for easy checking
dept_tag_map_struct["is_consumable"] = dept_tag_map_struct["department_id"].isin(CONSUMABLE_DEPTS).astype("uint8")
dept_tag_map_struct["is_core"]       = dept_tag_map_struct["department_id"].isin(CORE_DEPTS).astype("uint8")
dept_tag_map_struct["is_variety"]    = dept_tag_map_struct["department_id"].isin(VARIETY_DEPTS).astype("uint8")
dept_tag_map_struct["is_durable"]    = dept_tag_map_struct["department_id"].isin(DURABLE_DEPTS).astype("uint8")

# "Whether at least one tag was hit" (helps identify gaps / uncovered rows)
dept_tag_map_struct["hit_any_tag"] = (
    dept_tag_map_struct[["is_consumable","is_core","is_variety","is_durable"]].sum(axis=1) > 0
).astype("uint8")

dept_tag_map_struct = dept_tag_map_struct.sort_values("department_id").reset_index(drop=True)

print("✅ dept_tag_map_struct created:", dept_tag_map_struct.shape)
display(dept_tag_map_struct)

print("\n✅ Check: departments not covered by any tag (hit_any_tag==0)")
display(dept_tag_map_struct.loc[dept_tag_map_struct["hit_any_tag"] == 0])


# =========================================================
# 3) Generate a mapping dict (ultra-lightweight, fastest)
#    For the 33-million-row master table, only needs map → uint8
# =========================================================
dept_to_is_consumable = {did: 1 for did in CONSUMABLE_DEPTS}
dept_to_is_core       = {did: 1 for did in CORE_DEPTS}
dept_to_is_variety    = {did: 1 for did in VARIETY_DEPTS}
dept_to_is_durable    = {did: 1 for did in DURABLE_DEPTS}

# Note:
# - The dict stores only dept_ids that hit 1; anything not present defaults to 0
# - This avoids merging string columns into the large table or duplicating department names

✅ dept_tag_map_struct created: (21, 7)

,department_id,department,is_consumable,is_core,is_variety,is_durable,hit_any_tag
0,1,frozen,0,0,1,0,1
1,2,other,0,0,0,1,1
2,3,bakery,0,1,1,0,1
3,4,produce,1,1,0,0,1
4,5,alcohol,0,0,1,0,1
5,6,international,0,0,1,0,1
6,7,beverages,1,0,1,0,1
7,8,pets,0,0,0,1,1
8,9,dry goods pasta,0,1,0,0,1
9,10,bulk,0,0,1,0,1
10,11,personal care,0,0,0,1,1
11,12,meat seafood,1,1,0,0,1
12,13,pantry,0,1,0,0,1
13,14,breakfast,1,0,0,0,1
14,15,canned goods,0,1,0,0,1
15,16,dairy eggs,1,1,0,0,1
16,17,household,0,0,0,1,1
17,18,babies,0,0,0,1,1
18,19,snacks,1,0,1,0,1
19,20,deli,1,0,0,0,1
20,21,missing,0,0,0,1,1

✅ Check: departments not covered by any tag (hit_any_tag==0)

Empty DataFrame
Columns: [department_id, department, is_consumable, is_core, is_variety, is_durable, hit_any_tag]
Index: []

In [73]:
# Build a detailed table to help analyze basket item * breadth * role shift
#
# ===========================================
# Order-level structural metric aggregation (non-destructive version)
# Input:
#   - order_items_full : (order_id, product_id, user_id, aisle_id, department_id, reordered, ...)
#   - dept_tag_map_struct: small table / dict mapping department_id -> structural tag (consumable/core/variety/durable)
#
# Output (new table, original table untouched):
#   - order_metrics_struct: one row per order_id, containing all the required metrics
#
# Metric list (as requested):
#   1) total_items                total items in the order (row count)
#   2) n_unique_products          distinct SKU count in the order (deduplicated product_id)
#   3) n_unique_aisles            distinct aisle count in the order
#   4) n_unique_departments       distinct department count in the order
#   5) consumable_count           number of consumable-category items
#   6) consumable_share           consumable_count / total_items
#   7) core_count                 number of core-category items
#   8) core_share                 core_count / total_items
#   9) variety_count              number of variety-category items
#  10) variety_share              variety_count / total_items
#  11) durable_count              number of durable-category items
#  12) durable_share              durable_count / total_items
#  13) reorder_ratio (optional)   share with reordered==1 (if the table has a reordered column)
#
# Note:
# - This code only aggregates (groupby order_id); it does not merge string columns into the large table, so memory usage stays more stable.
# - dept_tag_map_struct should contain at least two columns:
#       department_id, struct_tag
#   where struct_tag ∈ {"consumable","core","variety","durable"}
# ===========================================

# ----------------------------
# 0) Basic check
# ----------------------------
if "order_items_full" not in globals():
    raise ValueError("Missing table: order_items_full")

if "dept_tag_map_struct" not in globals():
    raise ValueError("Missing table: dept_tag_map_struct")

needed_cols = ["order_id", "product_id", "aisle_id", "department_id"]
missing = [c for c in needed_cols if c not in order_items_full.columns]
if missing:
    raise ValueError(f"order_items_full missing columns: {missing}")

needed_map_cols = ["department_id", "is_consumable", "is_core", "is_variety", "is_durable"]
missing_map = [c for c in needed_map_cols if c not in dept_tag_map_struct.columns]
if missing_map:
    raise ValueError(f"dept_tag_map_struct missing columns: {missing_map}")
# ===========================================
# Order-level structural metric aggregation (compatible with the 4-flag version of dept_tag_map_struct)
# Input:
#   - order_items_full: large table, one row per order_id×product_id (item row)
#       required columns: order_id, product_id, aisle_id, department_id
#       optional column: reordered
#   - dept_tag_map_struct: small table (21 rows), containing:
#       department_id, is_consumable, is_core, is_variety, is_durable
#
# Output (new table, original table untouched):
#   - order_metrics_struct: one row per order_id, containing order structural metrics
# ===========================================

import numpy as np
import pandas as pd

# ----------------------------
# 0) Basic check
# ----------------------------
if "order_items_full" not in globals():
    raise ValueError("Missing table: order_items_full")

if "dept_tag_map_struct" not in globals():
    raise ValueError("Missing table: dept_tag_map_struct")

needed_cols = ["order_id", "product_id", "aisle_id", "department_id"]
missing = [c for c in needed_cols if c not in order_items_full.columns]
if missing:
    raise ValueError(f"order_items_full missing columns: {missing}")

needed_map_cols = ["department_id", "is_consumable", "is_core", "is_variety", "is_durable"]
missing_map = [c for c in needed_map_cols if c not in dept_tag_map_struct.columns]
if missing_map:
    raise ValueError(f"dept_tag_map_struct missing columns: {missing_map}")

# ----------------------------
# 1) Build 4 dept_id -> flag dicts (very lightweight, won't bloat the master table)
# ----------------------------
# Note:
# - Each department_id in the small table has 4 flags
# - flags are 0/1 (or True/False)
# - Convert this into a dict: dept_id -> 0/1
# - Later, use Series.map() to map onto each item row, then aggregate sum() by order_id

m = dept_tag_map_struct.copy()
m["department_id"] = m["department_id"].astype(int)

dept_to_consumable = dict(zip(m["department_id"], m["is_consumable"].astype(int)))
dept_to_core       = dict(zip(m["department_id"], m["is_core"].astype(int)))
dept_to_variety    = dict(zip(m["department_id"], m["is_variety"].astype(int)))
dept_to_durable    = dict(zip(m["department_id"], m["is_durable"].astype(int)))

# ----------------------------
# 2) Select the minimal columns from the large table, to avoid memory blowup
# ----------------------------
# Note: copy() here is to add a few flag columns later, but since we only take 4-5 columns it's relatively controlled
x = order_items_full[["order_id", "product_id", "aisle_id", "department_id"]].copy()

# reordered is optional: if present, compute reorder_ratio (share of reorders)
has_reordered = "reordered" in order_items_full.columns
if has_reordered:
    x["reordered"] = order_items_full["reordered"].fillna(0).astype(int)

# ----------------------------
# 3) Map department_id to the 4 flags (no string merge)
# ----------------------------
# Explanation:
# - Each item row will get:
#     is_consumable = 1/0
#     is_core = 1/0
#     is_variety = 1/0
#     is_durable = 1/0
#
# - The current definition allows overlap:
#     e.g. bakery is both core and variety
#   this is fine, since we're building "structural share tags," not mutually exclusive buckets.
#
# - If some department_id is not in the dict (in theory all 21 are covered)
#   map would produce NaN; fillna(0) is used as a fallback.

x["is_consumable"] = x["department_id"].map(dept_to_consumable).fillna(0).astype(np.int8)
x["is_core"]       = x["department_id"].map(dept_to_core).fillna(0).astype(np.int8)
x["is_variety"]    = x["department_id"].map(dept_to_variety).fillna(0).astype(np.int8)
x["is_durable"]    = x["department_id"].map(dept_to_durable).fillna(0).astype(np.int8)

# ----------------------------
# 4) Basic order metrics (scale & breadth complexity)
# ----------------------------
# total_items：
#   - total items in the order (= number of rows for that order in order_items_full)
# n_unique_products：
#   - number of distinct product_ids (SKU variety count)
# n_unique_aisles / n_unique_departments：
#   - a coarser-grained breadth-expansion metric
base_agg = (
    x.groupby("order_id", as_index=False)
     .agg(
         total_items=("product_id", "size"),
         n_unique_products=("product_id", "nunique"),
         n_unique_aisles=("aisle_id", "nunique"),
         n_unique_departments=("department_id", "nunique"),
     )
)

# ----------------------------
# 5) Structural tag counts (four categories) + optional reorder count
# ----------------------------
# Key explanation (as requested, spelling out "consumable"):
# Definition of consumable_count (under the current tag system):
#   - If an item row belongs to a consumable dept (e.g. produce / dairy / meat / beverages...)
#     then that row's is_consumable=1
#   - consumable_count = sum of is_consumable across all item rows in that order
#
# Intuitive meaning:
#   - a higher consumable_count means the order contains more items that "get consumed and need frequent replenishment"
#   - this structure typically leads more easily to:
#       1) a shorter gap (faster repurchase)
#       2) a more stable cadence (habit formation)
#
# consumable_share：
#   - consumable_count / total_items
#   - reason for using share instead of count: it allows comparing structure across order sizes, rather than being naturally inflated by large orders

agg_kwargs = dict(
    consumable_count=("is_consumable", "sum"),
    core_count=("is_core", "sum"),
    variety_count=("is_variety", "sum"),
    durable_count=("is_durable", "sum"),
)
if has_reordered:
    agg_kwargs["reordered_count"] = ("reordered", "sum")

tag_agg = x.groupby("order_id", as_index=False).agg(**agg_kwargs)

# ----------------------------
# 6) Merge and compute share
# ----------------------------
order_metrics_struct = base_agg.merge(tag_agg, on="order_id", how="left")

den = order_metrics_struct["total_items"].replace(0, np.nan)

order_metrics_struct["consumable_share"] = order_metrics_struct["consumable_count"] / den
order_metrics_struct["core_share"]       = order_metrics_struct["core_count"]       / den
order_metrics_struct["variety_share"]    = order_metrics_struct["variety_count"]    / den
order_metrics_struct["durable_share"]    = order_metrics_struct["durable_count"]    / den

if has_reordered:
    order_metrics_struct["reorder_ratio"] = order_metrics_struct["reordered_count"] / den

# fill NaN in share (rare edge case where total_items=0) with 0
share_cols = ["consumable_share", "core_share", "variety_share", "durable_share"]
if has_reordered:
    share_cols.append("reorder_ratio")
order_metrics_struct[share_cols] = order_metrics_struct[share_cols].fillna(0.0)

# fill NaN in count with 0 and cast to int
count_cols = ["consumable_count", "core_count", "variety_count", "durable_count"]
if has_reordered:
    count_cols.append("reordered_count")
order_metrics_struct[count_cols] = order_metrics_struct[count_cols].fillna(0).astype(int)

print("✅ New table created: order_metrics_struct", order_metrics_struct.shape)
display(order_metrics_struct.head(10))

✅ New table created: order_metrics_struct (3346083, 15)

,order_id,total_items,n_unique_products,n_unique_aisles,n_unique_departments,consumable_count,core_count,variety_count,durable_count,reordered_count,consumable_share,core_share,variety_share,durable_share,reorder_ratio
0,1,8,8,6,3,7,8,0,0,4,0.875000,1.000000,0.000000,0.000000,0.500000
1,2,9,9,8,3,4,9,0,0,6,0.444444,1.000000,0.000000,0.000000,0.666667
2,3,8,8,6,4,7,8,1,0,8,0.875000,1.000000,0.125000,0.000000,1.000000
3,4,13,13,9,5,11,1,8,1,12,0.846154,0.076923,0.615385,0.076923,0.923077
4,5,26,26,19,11,17,15,6,4,21,0.653846,0.576923,0.230769,0.153846,0.807692
5,6,3,3,3,2,1,0,1,2,0,0.333333,0.000000,0.333333,0.666667,0.000000
6,7,2,2,2,2,1,0,2,0,0,0.500000,0.000000,1.000000,0.000000,0.000000
7,8,1,1,1,1,0,1,1,0,1,0.000000,1.000000,1.000000,0.000000,1.000000
8,9,15,15,12,8,11,11,5,0,10,0.733333,0.733333,0.333333,0.000000,0.666667
9,10,15,15,7,5,12,13,0,2,8,0.800000,0.866667,0.000000,0.133333,0.533333

**Build the Gap-Side Analysis Master Table**

In [77]:
import numpy as np
import pandas as pd

# =========================================================
# 0) Input tables: these DataFrames should already exist in your current environment
# =========================================================
# path_growth_user: user-level, contains path_9 + d_log_weekly/d_log_gap etc. (definitions verified consistent)
# orders_enriched2: order-level, contains user_id + order_number + gap_days_adj

# To avoid polluting the original table: only reference it here, no inplace modification
PG = path_growth_user
OE = orders_enriched2

# =========================================================
# 1) Filter Mid-pool user_ids from path_growth_user
#    (the pool definition can be expanded/narrowed per business needs)
# =========================================================
MID_PATHS = ["Mid Stay", "Mid Up to High", "Mid Down to Low"]

mid_users = (
    PG.loc[PG["path_9"].isin(MID_PATHS), ["user_id", "path_9"]]
      .drop_duplicates()
      .copy()
)

print("✅ mid_users:", mid_users.shape)
print(mid_users["path_9"].value_counts(dropna=False))

# =========================================================
# 2) Use orders_enriched2 to compute for mid_users:
#    - pct_gap30_early / pct_gap30_late
#    - gap_std_early / gap_std_late
#
#    Key point: early/late is split by the first 50%/last 50% of each user's order sequence (order_number)
# =========================================================

# 2.1 Take only orders relevant to the mid pool (minimal columns to save memory)
need_cols = ["order_id", "user_id", "order_number", "gap_days_adj"]
missing = [c for c in need_cols if c not in OE.columns]
if missing:
    raise ValueError(f"❌ orders_enriched2 is missing required columns: {missing}; current columns: {list(OE.columns)}")

o = (
    OE.loc[OE["user_id"].isin(mid_users["user_id"]), need_cols]
      .copy()
)

print("✅ mid orders:", o.shape)

# 2.2 Clean gap: gap_days_adj needs to be >0 to be meaningful (consistent with earlier log treatment)
#     Note: the first order's gap may be NaN or may have been filled; here NaN/<=0 are uniformly dropped
o = o.dropna(subset=["gap_days_adj", "order_number"]).copy()
o = o[o["gap_days_adj"] > 0].copy()

# 2.3 Compute n_orders per user, and split half by order_number
#     Rule: order_number <= ceil(n_orders/2) is early; the rest is late
#     This gives early one extra order when n_orders is odd, which is more stable (avoids early being too small)
user_n = (
    o.groupby("user_id", as_index=False)
     .agg(n_orders=("order_number", "max"))   # Instacart order_number increments starting from 1
)

o = o.merge(user_n, on="user_id", how="left")

# Split half
o["early_cut"] = np.ceil(o["n_orders"] / 2.0)
o["half"] = np.where(o["order_number"] <= o["early_cut"], "early", "late")

# 2.4 Generate the cliff flag at the order level
o["is_gap30"] = (o["gap_days_adj"] >= 30).astype(int)

# 2.5 Aggregate to user × half: std, median, pct_gap30
#     std will be NaN when there are too few orders; handled later
uh = (
    o.groupby(["user_id", "half"], as_index=False)
     .agg(
         gap_std=("gap_days_adj", "std"),
         gap_med=("gap_days_adj", "median"),
         pct_gap30=("is_gap30", "mean"),
         n_orders_half=("order_id", "count")
     )
)

# std is NaN with only 1 order: means "volatility can't be estimated," treated as 0 here
uh["gap_std"] = uh["gap_std"].fillna(0)

print("✅ user×half metrics:", uh.shape)
print(uh["half"].value_counts())

# 2.6 pivot to wide: *_early / *_late
uh_wide = (
    uh.pivot(index="user_id", columns="half", values=["gap_std", "pct_gap30", "gap_med", "n_orders_half"])
      .copy()
)

# Flatten into column names
uh_wide.columns = [f"{a}_{b}" for a, b in uh_wide.columns]
uh_wide = uh_wide.reset_index()

# 2.7 Keep only the structural metric fields we need (aligned with the earlier dl_user)
mid_gap_struct = uh_wide[[
    "user_id",
    "pct_gap30_early", "pct_gap30_late",
    "gap_std_early", "gap_std_late",
    "gap_med_early", "gap_med_late",          # optional: useful for alignment/validation
    "n_orders_half_early", "n_orders_half_late"
]].copy()

# delta (optional, but frequently needed later for monotonicity/elasticity work)
mid_gap_struct["delta_pct_gap30"] = mid_gap_struct["pct_gap30_late"] - mid_gap_struct["pct_gap30_early"]
mid_gap_struct["delta_gap_std"]   = mid_gap_struct["gap_std_late"]   - mid_gap_struct["gap_std_early"]

print("✅ mid_gap_struct:", mid_gap_struct.shape)
print(mid_gap_struct.head())

# =========================================================
# 3) Merge back into path_growth_user: produces mid_struct_user
#    Note: does not modify the original table, creates a new table
# =========================================================

# 3.1 Take core growth metrics for the mid pool from path_growth_user (minimal columns)
#     Additional columns can be added as needed: d_log_weekly, d_log_gap, d_log_basket, basket_med_*, gap_med_*, etc.
keep_cols = [
    "user_id", "path_9",
    "d_log_weekly", "d_log_gap", "d_log_basket",
    "basket_med_early", "basket_med_late",
    "gap_med_early", "gap_med_late",
    "weekly_med_early", "weekly_med_late"
]
missing_pg = [c for c in keep_cols if c not in PG.columns]
if missing_pg:
    raise ValueError(f"❌ path_growth_user is missing columns: {missing_pg}\nSample of current columns: {list(PG.columns)[:50]}")

mid_growth = (
    PG.loc[PG["path_9"].isin(MID_PATHS), keep_cols]
      .drop_duplicates(subset=["user_id"])
      .copy()
)

# 3.2 merge：mid_growth + mid_gap_struct
mid_struct_user = (
    mid_growth.merge(mid_gap_struct, on="user_id", how="left")
)

print("✅ mid_struct_user:", mid_struct_user.shape)
print("missing pct_gap30_early:", mid_struct_user["pct_gap30_early"].isna().mean())

# 3.3 Finally, a sanity check is recommended: whether gap_med definitions are consistent (optional)
#     If concerned that gap_med_early/late exist on both sides: check whether the difference is 0
#     mid_growth already carries gap_med_early/late, and mid_gap_struct carries fields with the same name
#     so a suffix is automatically added after merge (if there's a conflict).
#     mid_gap_struct retains gap_med_early/late above for validation purposes,
#     if you want to avoid the conflict, drop mid_gap_struct's gap_med_* before merging.

# If after merging the column names become gap_med_early_x / gap_med_early_y:
# The snippet below can be used to quickly check the difference (adjust actual column names as needed)
# cols = [c for c in mid_struct_user.columns if "gap_med_early" in c or "gap_med_late" in c]
# print(cols)

# =========================================================
# 4) (Optional) merge in the dynamics label from path_dyn_step
#    this allows subgroup monotonicity validation for stepper/drifter etc. within Mid→High
# =========================================================
if "path_dyn_step" in globals():
    mid_struct_user = mid_struct_user.merge(
        path_dyn_step[["user_id", "label", "stepper_subtype"]],
        on="user_id",
        how="left"
    )
    print("✅ mid_struct_user + dynamics:", mid_struct_user.shape)

# Final output: mid_struct_user
# What comes next (not code):
# - Filter Mid Up to High + label=drifter / stepper / ...
# - Check the bucketed monotonicity & elasticity of Δpct_gap30 or cliff_improve against d_log_weekly

✅ mid_users: (73367, 2)
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64
✅ mid orders: (1210493, 4)
✅ user×half metrics: (146734, 6)
half
early    73367
late     73367
Name: count, dtype: int64
✅ mid_gap_struct: (73367, 11)
   user_id  pct_gap30_early  pct_gap30_late  gap_std_early  gap_std_late  \
0        3         0.000000        0.000000       6.345602      4.082483
1        5         0.000000        0.000000       0.707107      9.192388
2        7         0.200000        0.000000       9.946524      7.818070
3       11         0.333333        0.500000       9.865766     12.996794
4       12         0.500000        0.666667      11.313708      2.309401

   gap_med_early  gap_med_late  n_orders_half_early  n_orders_half_late  \
0           10.5          11.0                  6.0                 6.0
1           10.5          12.5                  2.0                 2.0
2            8.5           7.0                 10.0                10.0
3           14.0          19.0                  3.0                 4.0
4           22.0          30.0                  2.0                 3.0

   delta_pct_gap30  delta_gap_std
0         0.000000      -2.263119
1         0.000000       8.485281
2        -0.200000      -2.128453
3         0.166667       3.131029
4         0.166667      -9.004307
✅ mid_struct_user: (73367, 21)
missing pct_gap30_early: 0.0
✅ mid_struct_user + dynamics: (73367, 23)

**Build the Basket-Side Analysis Master Table**

In [78]:
import numpy as np
import pandas as pd

# ============================================================
# Mid Pool · Basket Master User builder (excludes gap / frequency)
# - Output: user-level early/late (median) + delta + d_log + path label
# - Auto-fallback: if order_metrics_struct lacks dept_entropy/dominant_dept_share, compute from order_items_full instead (only for the target order set)
# ============================================================

EPS = 1e-6

# ------------------------------------------------------------
# 0) Define here which user group to analyze
#    Method A: by path
#    Method B: by a pool table (e.g. the mid pool's user_id list)
# ------------------------------------------------------------

# Method A: example, analyze only one path (adjustable)
USER_SELECTOR = {
    "mode": "list",
    "df": mid_struct_user,          # ✅ the Mid-pool table (73367) has user_id
    "user_col": "user_id"
}

# Method B: example, assuming you already have a mid_users_df (with user_id)
# USER_SELECTOR = {
#     "mode": "list",
#     "df": mid_users_df,        # a df with at least a user_id column
#     "user_col": "user_id"
# }


# ------------------------------------------------------------
# 1) Input table check
# ------------------------------------------------------------
required_tables = ["path_dyn_step", "orders_enriched2", "order_metrics_struct"]
for t in required_tables:
    if t not in globals():
        raise NameError(f"❌ Missing table: {t}")

# order_items_full is only needed when backfilling dept metrics
HAS_ITEMS = "order_items_full" in globals()

# ------------------------------------------------------------
# 2) Get the user set + label layer
# ------------------------------------------------------------
label_df = path_dyn_step.copy()

# Standardize column name (the label column is called "label" in path_dyn_step)
LABEL_COL = "label" if "label" in label_df.columns else None

need_label_cols = ["user_id", "path_9"]
if "stepper_subtype" in label_df.columns:
    need_label_cols.append("stepper_subtype")
if LABEL_COL:
    need_label_cols.append(LABEL_COL)

label_df = label_df[need_label_cols].drop_duplicates()

if USER_SELECTOR["mode"] == "path":
    target_users = label_df.loc[label_df["path_9"] == USER_SELECTOR["path_9"], ["user_id"]].drop_duplicates()
    print(f"✅ User selection: path_9 == {USER_SELECTOR['path_9']} | users={target_users.shape[0]}")
else:
    ucol = USER_SELECTOR.get("user_col", "user_id")
    target_users = USER_SELECTOR["df"][[ucol]].drop_duplicates().rename(columns={ucol: "user_id"})
    print(f"✅ User selection: custom list | users={target_users.shape[0]}")

# Merge in the labels (the output table needs path/label/subtype)
user_tags = target_users.merge(label_df, on="user_id", how="left")
print("✅ user_tags shape:", user_tags.shape)

# ------------------------------------------------------------
# 3) Get these users' orders + tag half (early/late)
# ------------------------------------------------------------
oe = orders_enriched2[["order_id", "user_id", "order_number"]].copy()
oe = oe.merge(target_users, on="user_id", how="inner")
print("✅ orders_enriched2 filtered:", oe.shape)

# Order count per user (max(order_number) or nunique(order_id) both work; nunique used here for stability)
n_orders = oe.groupby("user_id")["order_id"].nunique().rename("n_orders").reset_index()
oe = oe.merge(n_orders, on="user_id", how="left")

oe["pos"] = oe["order_number"] / oe["n_orders"].replace(0, np.nan)
oe["half"] = np.where(oe["pos"] <= 0.5, "early", "late")

print("half distribution:")
print(oe["half"].value_counts())

# ------------------------------------------------------------
# 4) Merge in order structural metrics (order_metrics_struct)
# ------------------------------------------------------------
oms = order_metrics_struct.copy()

# The order-level metrics to keep (as needed for the basket mechanism)
# Note: the consumable/core/variety/durable counts should already exist in order_metrics_struct
KEEP_ORDER_METRICS = [
    "total_items",
    "n_unique_products",
    "n_unique_departments",
    "reordered_count",
    "consumable_count",
    "core_count",
    "variety_count",
    "durable_count",
]

# Optional metrics (use if present)
OPTIONAL = [
    "dept_entropy",
    "dominant_dept_share",
    "n_unique_aisles",
    "new_sku_rate",
]

keep_cols = ["order_id"] + [c for c in KEEP_ORDER_METRICS if c in oms.columns] + [c for c in OPTIONAL if c in oms.columns]
missing_hard = [c for c in KEEP_ORDER_METRICS if c not in oms.columns]
if missing_hard:
    raise KeyError(f"❌ order_metrics_struct is missing key columns: {missing_hard}")

order_df = oe.merge(oms[keep_cols], on="order_id", how="left")
print("✅ order_df after merge struct:", order_df.shape)

# ------------------------------------------------------------
# 5) If dept_entropy / dominant_dept_share is missing, compute it from order_items_full (target orders only)
# ------------------------------------------------------------
need_dept_entropy = "dept_entropy" not in order_df.columns
need_dom_share = "dominant_dept_share" not in order_df.columns

if (need_dept_entropy or need_dom_share):
    print("\n⚠️ order_metrics_struct lacks dept_entropy / dominant_dept_share (or one of them), computing as fallback…")
    if not HAS_ITEMS:
        print("❌ order_items_full not available in this environment, cannot backfill dept metrics. These two columns will be skipped.")
    else:
        oi = order_items_full[["order_id", "department_id"]].copy()
        target_order_ids = order_df[["order_id"]].drop_duplicates()
        oi = oi.merge(target_order_ids, on="order_id", how="inner")
        print("✅ order_items_full filtered:", oi.shape)

        # order×dept item count
        dept_cnt = (
            oi.groupby(["order_id", "department_id"], as_index=False)
              .size()
              .rename(columns={"size": "dept_item_cnt"})
        )
        order_tot = (
            dept_cnt.groupby("order_id", as_index=False)["dept_item_cnt"].sum()
            .rename(columns={"dept_item_cnt": "dept_total"})
        )
        dept_cnt = dept_cnt.merge(order_tot, on="order_id", how="left")
        dept_cnt["p"] = dept_cnt["dept_item_cnt"] / np.maximum(dept_cnt["dept_total"], 1)

        # dominant_dept_share
        dept_max = (
            dept_cnt.groupby("order_id", as_index=False)["dept_item_cnt"].max()
            .rename(columns={"dept_item_cnt": "dept_max"})
        )
        dept_dom = dept_max.merge(order_tot, on="order_id", how="left")
        dept_dom["dominant_dept_share"] = dept_dom["dept_max"] / np.maximum(dept_dom["dept_total"], 1)

        # dept_entropy（Shannon）
        def shannon_entropy(p: np.ndarray) -> float:
            p = p[p > 0]
            if len(p) == 0:
                return 0.0
            return float(-(p * np.log(p)).sum())

        dept_entropy = (
            dept_cnt.groupby("order_id")
                    .apply(lambda g: shannon_entropy(g["p"].to_numpy(dtype=float)))
                    .reset_index()
                    .rename(columns={0: "dept_entropy"})
        )

        dept_metrics = dept_dom[["order_id", "dominant_dept_share"]].merge(
            dept_entropy[["order_id", "dept_entropy"]],
            on="order_id",
            how="left"
        )

        order_df = order_df.merge(dept_metrics, on="order_id", how="left")
        print("✅ order_df after dept metrics:", order_df.shape)

# ------------------------------------------------------------
# 6) Construct share / depth derived metrics (order level)
# ------------------------------------------------------------
# share
order_df["consumable_share"] = order_df["consumable_count"] / np.maximum(order_df["total_items"], 1)
order_df["core_share"]       = order_df["core_count"]       / np.maximum(order_df["total_items"], 1)
order_df["variety_share"]    = order_df["variety_count"]    / np.maximum(order_df["total_items"], 1)
order_df["durable_share"]    = order_df["durable_count"]    / np.maximum(order_df["total_items"], 1)

# reorder_ratio
order_df["reorder_ratio"] = order_df["reordered_count"] / np.maximum(order_df["total_items"], 1)

# items_per_unique_product
order_df["items_per_unique_product"] = order_df["total_items"] / np.maximum(order_df["n_unique_products"], 1)

# (Optional) repeat_product_ratio
if "new_sku_rate" in order_df.columns:
    order_df["repeat_product_ratio"] = 1.0 - order_df["new_sku_rate"]

# ------------------------------------------------------------
# 7) Aggregate by user × half (median), then pivot into early/late
# ------------------------------------------------------------
user_half_metrics = [
    "total_items",
    "n_unique_products",
    "n_unique_departments",
    "reorder_ratio",
    "items_per_unique_product",
    "consumable_share",
    "core_share",
    "variety_share",
    "durable_share",
]
if "dept_entropy" in order_df.columns:
    user_half_metrics.append("dept_entropy")
if "dominant_dept_share" in order_df.columns:
    user_half_metrics.append("dominant_dept_share")
if "repeat_product_ratio" in order_df.columns:
    user_half_metrics.append("repeat_product_ratio")

uh = (
    order_df.groupby(["user_id", "half"], as_index=False)[user_half_metrics]
            .median()
)

wide = uh.pivot_table(index="user_id", columns="half", values=user_half_metrics, aggfunc="first")
wide.columns = [f"{m}_{h}" for m, h in wide.columns]
wide = wide.reset_index()

# Keep only users with both early and late present (avoid missing-half orders)
need_both = [f"{m}_early" for m in user_half_metrics] + [f"{m}_late" for m in user_half_metrics]
wide = wide.dropna(subset=need_both).copy()

print("✅ user-level wide shape:", wide.shape)

# ------------------------------------------------------------
# 8) delta layer (late - early)
# ------------------------------------------------------------
for m in user_half_metrics:
    wide[f"delta_{m}"] = wide[f"{m}_late"] - wide[f"{m}_early"]

# ------------------------------------------------------------
# 9) d_log layer (no +1 offset; add eps for ratios that could be 0)
# ------------------------------------------------------------
def safe_dlog(late: pd.Series, early: pd.Series, eps: float = EPS) -> pd.Series:
    # For ratio-type metrics that could be 0: log((late+eps)/(early+eps))
    return np.log((late + eps) / (early + eps))

# Basket proxy: here basket_med is the median of items_per_order
# but this basket master is a "structural table"; basket_med is not in order_metrics_struct
# if basket_med_early/late is needed, compute it separately from orders_enriched2 (items_per_order) and merge it in
# For now, only log-transform total_items & unique here
wide["d_log_total_items"] = np.log(wide["total_items_late"] / wide["total_items_early"])
wide["d_log_unique_products"] = np.log(wide["n_unique_products_late"] / wide["n_unique_products_early"])

# For ratio-type metrics: eps is recommended
wide["d_log_reorder_ratio"] = safe_dlog(wide["reorder_ratio_late"], wide["reorder_ratio_early"], EPS)

if "dept_entropy_early" in wide.columns:
    # entropy is theoretically >0, but can be very small, so eps is used defensively too
    wide["d_log_dept_entropy"] = safe_dlog(wide["dept_entropy_late"], wide["dept_entropy_early"], EPS)

# ------------------------------------------------------------
# 9.5) Backfill basket_med_early/late (replicating the earlier definition: median(items_per_order))
# ------------------------------------------------------------
tmp = orders_enriched2.loc[
    orders_enriched2["order_id"].isin(oe["order_id"]),
    ["order_id", "user_id", "items_per_order"]
].merge(
    oe[["order_id", "half"]], on="order_id", how="inner"
)

basket_user_half = (
    tmp.groupby(["user_id", "half"])["items_per_order"]
       .median()
       .unstack("half")
       .rename(columns={"early":"basket_med_early","late":"basket_med_late"})
       .reset_index()
)

# Merge back into wide (rather than back into basket_master_user)
wide = wide.merge(basket_user_half, on="user_id", how="left")

# Keep only rows where both early and late exist (consistent with the logic above)
wide = wide.dropna(subset=["basket_med_early","basket_med_late"]).copy()

# delta + d_log (basket can be small, eps used)
wide["delta_basket_med"] = wide["basket_med_late"] - wide["basket_med_early"]
wide["d_log_basket_med"] = np.log(
    (wide["basket_med_late"] + EPS) / (wide["basket_med_early"] + EPS)
)

# ------------------------------------------------------------
# 10) Merge in the label layer (path/label/subtype) to produce the final Basket Master User
# ------------------------------------------------------------
basket_master_user = wide.merge(user_tags, on="user_id", how="left")

print("\n" + "="*90)
print("✅ Basket Master User build complete (excludes gap)")
print("shape:", basket_master_user.shape)
print("columns preview:", list(basket_master_user.columns)[:30])

# Used later: basket_master_user

✅ 用户选择：自定义列表 | users=73367
✅ user_tags shape: (73367, 4)
✅ orders_enriched2 filtered: (1210493, 3)
half 分布：
half
late     696417
early    514076
Name: count, dtype: int64
✅ order_df after merge struct: (1210493, 15)

⚠️ order_metrics_struct 没有 dept_entropy / dominant_dept_share（或缺其一），准备补算…
✅ order_items_full filtered: (10674537, 2)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/4059551101.py:169: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: shannon_entropy(g["p"].to_numpy(dtype=float)))

✅ order_df after dept metrics: (1210493, 17)
✅ user-level wide shape: (73367, 23)

==========================================================================================
✅ Basket Master User 构建完成（不含 gap）
shape: (73367, 45)
columns preview: ['user_id', 'consumable_share_early', 'consumable_share_late', 'core_share_early', 'core_share_late', 'dept_entropy_early', 'dept_entropy_late', 'dominant_dept_share_early', 'dominant_dept_share_late', 'durable_share_early', 'durable_share_late', 'items_per_unique_product_early', 'items_per_unique_product_late', 'n_unique_departments_early', 'n_unique_departments_late', 'n_unique_products_early', 'n_unique_products_late', 'reorder_ratio_early', 'reorder_ratio_late', 'total_items_early', 'total_items_late', 'variety_share_early', 'variety_share_late', 'delta_total_items', 'delta_n_unique_products', 'delta_n_unique_departments', 'delta_reorder_ratio', 'delta_items_per_unique_product', 'delta_consumable_share', 'delta_core_share']

In [79]:
# Add weekly delta, for future full regression

import numpy as np
import pandas as pd

# 1) Copy, avoid polluting the original table
bm = basket_master_user.copy()

# 2) Merge weekly early/late (does not require delta_weekly to already exist)
wk_cols = ["user_id", "path_9", "weekly_med_early", "weekly_med_late"]
missing = [c for c in wk_cols if c not in path_growth_user.columns]
if missing:
    raise KeyError(f"path_growth_user missing columns: {missing}")

bm = bm.merge(path_growth_user[wk_cols], on=["user_id", "path_9"], how="left")

# 3) Compute delta_weekly / d_log_weekly (eps added to guard against 0)
EPS = 1e-6
bm["delta_weekly"] = bm["weekly_med_late"] - bm["weekly_med_early"]
bm["d_log_weekly"] = np.log((bm["weekly_med_late"] + EPS) / (bm["weekly_med_early"] + EPS))

# 4) Optional: check the missing rate
print("bm shape:", bm.shape)
print("weekly early NA rate:", bm["weekly_med_early"].isna().mean())
print("weekly late  NA rate:", bm["weekly_med_late"].isna().mean())
print("delta_weekly NA rate:", bm["delta_weekly"].isna().mean())

# 5) Output the analysis-specific table (new object)
basket_master_user_wk = bm

print("✅ New table created: basket_master_user_wk")

bm shape: (73367, 49)
weekly early NA rate: 0.0
weekly late  NA rate: 0.0
delta_weekly NA rate: 0.0
✅ New table created: basket_master_user_wk

In [80]:
# Merge the Mid-pool master table

# ===== Step 1: find columns in mid_struct_user that are missing from the master table =====
gap_only_cols = [
    c for c in mid_struct_user.columns
    if c not in basket_master_user_wk.columns
]

# ===== Step 2: construct the table to merge (keep only user_id + gap-specific columns) =====
gap_df = mid_struct_user[["user_id"] + gap_only_cols].copy()

# ===== Step 3: merge (with basket as the master table) =====
analysis_user_master = basket_master_user_wk.merge(
    gap_df,
    on="user_id",
    how="left"
)

# ===== Step 4: check the result =====
print("Final shape:", analysis_user_master.shape)
print("New columns added:", len(gap_only_cols))

Final shape: (73367, 63)
New columns added: 14

In [81]:
list(analysis_user_master.columns)

['user_id',
 'consumable_share_early',
 'consumable_share_late',
 'core_share_early',
 'core_share_late',
 'dept_entropy_early',
 'dept_entropy_late',
 'dominant_dept_share_early',
 'dominant_dept_share_late',
 'durable_share_early',
 'durable_share_late',
 'items_per_unique_product_early',
 'items_per_unique_product_late',
 'n_unique_departments_early',
 'n_unique_departments_late',
 'n_unique_products_early',
 'n_unique_products_late',
 'reorder_ratio_early',
 'reorder_ratio_late',
 'total_items_early',
 'total_items_late',
 'variety_share_early',
 'variety_share_late',
 'delta_total_items',
 'delta_n_unique_products',
 'delta_n_unique_departments',
 'delta_reorder_ratio',
 'delta_items_per_unique_product',
 'delta_consumable_share',
 'delta_core_share',
 'delta_variety_share',
 'delta_durable_share',
 'delta_dept_entropy',
 'delta_dominant_dept_share',
 'd_log_total_items',
 'd_log_unique_products',
 'd_log_reorder_ratio',
 'd_log_dept_entropy',
 'basket_med_early',
 'basket_med_late',
 'delta_basket_med',
 'd_log_basket_med',
 'path_9',
 'stepper_subtype',
 'label',
 'weekly_med_early',
 'weekly_med_late',
 'delta_weekly',
 'd_log_weekly',
 'd_log_gap',
 'd_log_basket',
 'gap_med_early_x',
 'gap_med_late_x',
 'pct_gap30_early',
 'pct_gap30_late',
 'gap_std_early',
 'gap_std_late',
 'gap_med_early_y',
 'gap_med_late_y',
 'n_orders_half_early',
 'n_orders_half_late',
 'delta_pct_gap30',
 'delta_gap_std']

**Gap Definition Versions (Old vs. New)**

Two definitions of gap (order interval) exist across the analysis, differing materially in values and usage — they need to be clearly distinguished.

**Old Gap (`gap_med_*_x`)** — from earlier user-level aggregation (`path_growth_user`), based on raw `days_since_prior_order`, not uniformly processed (may contain 0/NaN, no lower-bound clip, not necessarily consistent with the weekly definition). Fundamentally describes the user's "raw historical interval," suitable for segmentation, path classification (path_9), and other descriptive analysis.

**New Gap (`gap_med_*_y`)** — rebuilt later from order-level data (orders_enriched2 pipeline), standardized as `gap_days_adj = clip(days_since_prior_order, lower=1)`, strictly ensuring gap > 0 and consistent with the `weekly = basket / gap` definition. Fundamentally a structured behavioral variable for modeling, suitable for growth decomposition, weekly intensity modeling, regression/elasticity analysis, and scenario simulation.

**Risk**: Mixing the two gap definitions (e.g. the new weekly definition + the old gap_x) causes decomposition to not close, regression coefficient bias, and incorrect attribution of growth drivers (e.g. underestimating gap's role).

**Current standard**: All growth / mechanism / modeling analysis uses **New Gap (`_y`)** exclusively; Old Gap (`_x`) is kept only for historical reference and is no longer used in core analysis.

# 🔬 Section 8: Mid → High Analysis — Mechanism

> Dual Engine 2×2 / Breadth-Depth / Zone / Basket & Gap Lever Scan

---

In [82]:
# ============================================
# Step 1: rename the table (standardize to the analysis-layer naming)
# ============================================

# Rename the former master analysis table to the unified analysis table
analysis_mid_user_master = analysis_user_master.copy()


# ============================================
# Step 2: add documentation for this table (data-dictionary comments)
# ============================================

analysis_mid_user_master_desc = """
[Table Name] analysis_mid_user_master

[Table Type]
Mid-pool user-level unified analysis table (analysis layer)

[Data Source]
Produced by merging the following two tables:
- basket_master_user_wk (basket / weekly master table)
- mid_struct_user (gap / decision-cadence structural table)

[Granularity]
user_id (user level)

[Contents]
1. early / late / Δ metrics
2. basket expansion (unique / items)
3. frequency metrics (gap / weekly)
4. decision lag metrics (gap_std / pct_gap30 / entropy)

[Purpose]
- used for unified analysis of the three mechanisms: basket × gap × weekly
- supports correlation / uplift / bucketing / 2x2 / regression / causal-order analysis

[Important Notes]
- basket and gap metrics have been deduplicated and consolidated
- serves as the "Single Source of Truth" for Mid→High mechanism analysis
"""
print(analysis_mid_user_master_desc)

【表名】analysis_mid_user_master

【表类型】
Mid母池用户级统一分析表（analysis layer）

【数据来源】
由以下两张表合并得到：
- basket_master_user_wk（basket / weekly 主表）
- mid_struct_user（gap / 决策节奏结构表）

【粒度】
user_id（用户级）

【包含内容】
1. early / late / Δ 指标
2. basket 扩张（unique / items）
3. frequency 指标（gap / weekly）
4. decision lag 指标（gap_std / pct_gap30 / entropy）

【用途】
- 用于统一分析 basket × gap × weekly 三大机制
- 支持 correlation / uplift / 分桶 / 2x2 / 回归 / 因果顺序分析

【重要说明】
- basket 与 gap 指标已去重整合
- 是 Mid→High 机制分析的“唯一主表（Single Source of Truth）”

In [83]:
print(f"Shape: {analysis_mid_user_master.shape}")
print("\nAll columns:")
for col in analysis_mid_user_master.columns:
    print(f"  {col}")

Shape: (73367, 63)

All columns:
  user_id
  consumable_share_early
  consumable_share_late
  core_share_early
  core_share_late
  dept_entropy_early
  dept_entropy_late
  dominant_dept_share_early
  dominant_dept_share_late
  durable_share_early
  durable_share_late
  items_per_unique_product_early
  items_per_unique_product_late
  n_unique_departments_early
  n_unique_departments_late
  n_unique_products_early
  n_unique_products_late
  reorder_ratio_early
  reorder_ratio_late
  total_items_early
  total_items_late
  variety_share_early
  variety_share_late
  delta_total_items
  delta_n_unique_products
  delta_n_unique_departments
  delta_reorder_ratio
  delta_items_per_unique_product
  delta_consumable_share
  delta_core_share
  delta_variety_share
  delta_durable_share
  delta_dept_entropy
  delta_dominant_dept_share
  d_log_total_items
  d_log_unique_products
  d_log_reorder_ratio
  d_log_dept_entropy
  basket_med_early
  basket_med_late
  delta_basket_med
  d_log_basket_med
  path_9
  stepper_subtype
  label
  weekly_med_early
  weekly_med_late
  delta_weekly
  d_log_weekly
  d_log_gap
  d_log_basket
  gap_med_early_x
  gap_med_late_x
  pct_gap30_early
  pct_gap30_late
  gap_std_early
  gap_std_late
  gap_med_early_y
  gap_med_late_y
  n_orders_half_early
  n_orders_half_late
  delta_pct_gap30
  delta_gap_std

In [84]:
# Mid pool definition (consistent with before)
mid_paths = ["Mid Stay", "Mid Up to High", "Mid Down to Low"]
mid_pool = user_half[user_half["path_9"].isin(mid_paths)]["user_id"].nunique()

master_users = analysis_mid_user_master["user_id"].nunique()

print(f"Mid pool user count:         {mid_pool:,}")
print(f"analysis_mid_user_master:   {master_users:,}")
print(f"Coverage:                     {master_users/mid_pool:.1%}")
print(f"Missing user count:           {mid_pool - master_users:,}")

Mid 母池用户数:              75,790
analysis_mid_user_master:   73,367
覆盖率:                      96.8%
缺失用户数:                  2,423

In [85]:
# Check the order-count distribution of missing users
mid_paths = ["Mid Stay", "Mid Up to High", "Mid Down to Low"]
mid_all = user_half[user_half["path_9"].isin(mid_paths)][["user_id", "path_9"]].copy()

missing_users = mid_all[~mid_all["user_id"].isin(analysis_mid_user_master["user_id"])]

n_orders = orders_enriched2.groupby("user_id")["order_id"].nunique().rename("n_orders")
missing_check = missing_users.merge(n_orders, on="user_id", how="left")

print("Order-count distribution of missing users:")
print(missing_check["n_orders"].describe())
print(f"\nShare with order count <= 2: {(missing_check['n_orders'] <= 2).mean():.1%}")

缺失用户的订单数分布：
count    2423.0
mean        4.0
std         0.0
min         4.0
25%         4.0
50%         4.0
75%         4.0
max         4.0
Name: n_orders, dtype: float64

订单数 <= 2 的占比: 0.0%

**Data quality note**: The 2,423 missing users are all exactly 4-order users (std=0, no exceptions). The cause is the split logic, not "too few orders" — for 4-order users, a 50% split gives 2 orders each in early/late, and certain aggregation steps (e.g. gap_std requiring at least 2 values) produce NaN, which gets filtered by dropna. These users' early/late behavior is inherently unstable anyway, so excluding them is reasonable. **96.8% coverage is fine to use directly for further analysis.**

In [86]:
# ============================================================
# 2×2 Dual Engine Analysis — Mid→High full population
# Basket Expansion × Frequency Improvement
# ============================================================

import numpy as np
import pandas as pd

# -------------------------
# Step 1: get all Mid→High users
# -------------------------
mh_all = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"All Mid→High users: {len(mh_all):,}")

# -------------------------
# Step 2: define event
# has_basket_event: basket expansion (late > early)
# has_gap_event: frequency improvement (gap shortens, late < early)
# -------------------------
mh_all["has_basket_event"] = (
    mh_all["basket_med_late"] > mh_all["basket_med_early"]
).astype(int)

mh_all["has_gap_event"] = (
    mh_all["gap_med_late_y"] < mh_all["gap_med_early_y"]
).astype(int)

print(f"\nhas_basket_event = 1: {mh_all['has_basket_event'].mean():.1%}")
print(f"has_gap_event    = 1: {mh_all['has_gap_event'].mean():.1%}")

# -------------------------
# Step 3: assign the 2×2 group label
# -------------------------
def assign_group(r):
    b = int(r["has_basket_event"])
    g = int(r["has_gap_event"])
    if b == 1 and g == 1: return "Dual Engine"
    if b == 0 and g == 1: return "Frequency-Driven"
    if b == 1 and g == 0: return "Basket-Driven"
    return "Neither"

mh_all["event_group"] = mh_all.apply(assign_group, axis=1)

# Share distribution
share = mh_all["event_group"].value_counts(normalize=True)
print("\nGroup distribution:")
for grp, pct in share.items():
    print(f"  {grp:<20} {pct:.1%}")

# -------------------------
# Step 4: compute weekly growth per group
# -------------------------
group_order = ["Dual Engine", "Frequency-Driven", "Basket-Driven", "Neither"]

results = []
for grp in group_order:
    subset = mh_all[mh_all["event_group"] == grp]
    n = len(subset)
    share_pct = n / len(mh_all)
    d_log = subset["d_log_weekly"].mean()
    growth_x = np.exp(d_log)

    results.append({
        "group"       : grp,
        "users"       : n,
        "share"       : share_pct,
        "d_log_weekly": round(d_log, 4),
        "growth_x"    : round(growth_x, 2),
    })

result_df = pd.DataFrame(results)

print("\n" + "="*70)
print("2×2 Dual Engine: all Mid→High users")
print("="*70)
print(f"\n{'Group':<22} {'Users':>7} {'Share':>7} {'d_log':>8} {'Growth':>8}")
print("-"*55)
for _, row in result_df.iterrows():
    print(f"  {row['group']:<20} {row['users']:>7,} "
          f"{row['share']:>7.1%} {row['d_log_weekly']:>8.4f} "
          f"{row['growth_x']:>7.2f}x")

# -------------------------
# Step 5: incremental decomposition
# -------------------------
pivot = result_df.set_index("group")["d_log_weekly"]

inc_gap_given_basket = pivot["Dual Engine"] - pivot["Basket-Driven"]
inc_basket_given_gap = pivot["Dual Engine"] - pivot["Frequency-Driven"]

print("\n" + "="*70)
print("Incremental decomposition")
print("="*70)
print(f"  Dual Engine              : {pivot['Dual Engine']:>8.4f}")
print(f"  Frequency-Driven         : {pivot['Frequency-Driven']:>8.4f}")
print(f"  Basket-Driven            : {pivot['Basket-Driven']:>8.4f}")
print(f"  Neither                  : {pivot['Neither']:>8.4f}")
print(f"\n  Gap increment (given basket) : {inc_gap_given_basket:>+8.4f}")
print(f"  Basket increment (given gap) : {inc_basket_given_gap:>+8.4f}")

print("\n✅ New tables created:")
print("  - mh_all       (all Mid→High users + event label)")
print("  - result_df    (2×2 summary results)")

Mid→High 全体用户数: 14,217

has_basket_event = 1: 68.8%
has_gap_event    = 1: 72.7%

Group 分布：
  Dual Engine          47.0%
  Frequency-Driven     25.7%
  Basket-Driven        21.9%
  Neither              5.5%

======================================================================
2×2 Dual Engine：Mid→High 全体
======================================================================

Group                    Users   Share    d_log   Growth
-------------------------------------------------------
  Dual Engine            6,676   47.0%   0.8553    2.35x
  Frequency-Driven       3,654   25.7%   0.6713    1.96x
  Basket-Driven          3,108   21.9%   0.6014    1.82x
  Neither                  779    5.5%   0.4672    1.60x

======================================================================
增量拆解
======================================================================
  Dual Engine              :   0.8553
  Frequency-Driven         :   0.6713
  Basket-Driven            :   0.6014
  Neither                  :   0.4672

  Gap 增量（given basket） :  +0.2539
  Basket 增量（given gap） :  +0.1840

✅ New tables created:
  - mh_all       (Mid→High 全体 + event 标签)
  - result_df    (2×2 汇总结果)

In [87]:
# ============================================================
# Basket Growth decomposition: Breadth vs. Depth
# Analysis corresponding to Slide 34
# ============================================================

mh = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

# Breadth：unique products
breadth_delta = (mh["n_unique_products_late"] - mh["n_unique_products_early"]).median()

# Depth：items per unique product
depth_early = mh["items_per_unique_product_early"].median()
depth_late  = mh["items_per_unique_product_late"].median()
depth_delta = (mh["items_per_unique_product_late"] - mh["items_per_unique_product_early"]).median()

# Total items
total_delta = (mh["total_items_late"] - mh["total_items_early"]).median()

print("===== Basket Growth decomposition: Breadth vs. Depth =====")
print(f"Total items increase (median)  : +{total_delta:.1f} items")
print(f"Breadth increase (unique SKUs) : +{breadth_delta:.1f} SKUs")
print(f"Depth change (items per SKU)   : {depth_delta:+.2f} (early: {depth_early:.2f} → late: {depth_late:.2f})")

===== Basket Growth 拆解：Breadth vs Depth =====
Total items 增加（median）     : +2.0 items
Breadth 增加（unique SKUs）    : +2.0 SKUs
Depth 变化（items per SKU）    : +0.00 (early: 1.00 → late: 1.00)

**Basket-Side Growth Analysis — Layer 1: Department Granularity**

The coarsest granularity, answering "did the broad category change." For each user, compare early vs. late: what share of newly added SKUs come from a department already visited (existing_dept_sku_share) vs. a brand-new department (new_dept_sku_share).

**Result**: existing_dept_sku_share ≈ **87.7%** — the vast majority of newly added SKUs come from departments the user already shops in, indicating the broad category is largely unchanged and growth mainly occurs at a finer granularity (within-category expansion rather than cross-department expansion).

In [88]:
# ============================================================
# Layer 1: Department granularity analysis
# Answers: do newly added SKUs come from an existing department or a new department?
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# Step 0: prepare the Mid→High user list
# ----------------------------------------
mh_users = (
    analysis_mid_user_master[
        analysis_mid_user_master["path_9"] == "Mid Up to High"
    ][["user_id"]].copy()
)
print(f"Mid→High users: {len(mh_users)}")

# ----------------------------------------
# Step 1: tag each user's orders early/late
# Split using order_number / n_orders <= 0.5
# ----------------------------------------

# First compute each user's total order count
user_n_orders = (
    orders_enriched2
    .groupby("user_id")["order_number"]
    .max()
    .reset_index()
    .rename(columns={"order_number": "n_orders"})
)

# Keep only Mid→High users
mh_orders = (
    orders_enriched2
    .merge(mh_users, on="user_id", how="inner")
    .merge(user_n_orders, on="user_id", how="left")
)

# Tag early/late
mh_orders["pos"] = mh_orders["order_number"] / mh_orders["n_orders"]
mh_orders["half"] = np.where(mh_orders["pos"] <= 0.5, "early", "late")

print(f"Mid→High orders: {len(mh_orders)}")
print(mh_orders["half"].value_counts())

# ----------------------------------------
# Step 2: join in order item info
# Keep only Mid→High users' orders
# ----------------------------------------
# Fix for Step 2: avoid duplicate user_id during merge
mh_items = (
    order_items_full
    .merge(
        mh_orders[["order_id", "user_id", "half"]],
        on=["order_id", "user_id"],  # join on both order_id + user_id, to avoid duplicate columns
        how="inner"
    )
)
print(f"Mid→High order items: {len(mh_items)}")
print(mh_items.columns.tolist())
# ----------------------------------------
# Step 3: for each user, find the departments seen in the early stage
# ----------------------------------------
early_depts = (
    mh_items[mh_items["half"] == "early"]
    .groupby("user_id")["department_id"]
    .apply(set)
    .reset_index()
    .rename(columns={"department_id": "early_dept_set"})
)

# ----------------------------------------
# Step 4: find each user's newly added SKUs in the late stage
# New SKU = product_id that appears in late but not in early
# ----------------------------------------
early_skus = (
    mh_items[mh_items["half"] == "early"]
    .groupby("user_id")["product_id"]
    .apply(set)
    .reset_index()
    .rename(columns={"product_id": "early_sku_set"})
)

late_items = mh_items[mh_items["half"] == "late"].copy()

# Join the early SKU set onto late items
late_items = late_items.merge(early_skus, on="user_id", how="left")

# Flag: whether this SKU appeared in early
late_items["is_new_sku"] = late_items.apply(
    lambda r: r["product_id"] not in r["early_sku_set"]
    if isinstance(r["early_sku_set"], set) else True,
    axis=1
)

# Look only at newly added SKUs
new_skus = late_items[late_items["is_new_sku"]].copy()
print(f"\nTotal new SKUs (item rows): {len(new_skus)}")

# ----------------------------------------
# Step 5: determine whether new SKUs come from an existing dept or a new dept
# ----------------------------------------
new_skus = new_skus.merge(early_depts, on="user_id", how="left")

new_skus["from_existing_dept"] = new_skus.apply(
    lambda r: r["department_id"] in r["early_dept_set"]
    if isinstance(r["early_dept_set"], set) else False,
    axis=1
)

# ----------------------------------------
# Step 6: overall summary
# ----------------------------------------
total_new_skus = len(new_skus)
existing_dept_count = new_skus["from_existing_dept"].sum()
new_dept_count = total_new_skus - existing_dept_count

print("\n========== Layer 1: Department granularity summary ==========")
print(f"Total new unique SKU rows : {total_new_skus:,}")
print(f"From existing department  : {existing_dept_count:,} "
      f"({existing_dept_count/total_new_skus*100:.1f}%)")
print(f"From new department       : {new_dept_count:,} "
      f"({new_dept_count/total_new_skus*100:.1f}%)")

# ----------------------------------------
# Step 7: user-level summary (distribution)
# ----------------------------------------
# Fix for Step 7: deduplicate at the SKU level before computing share
# Keep only one row per user per new SKU (deduplicated)
new_skus_dedup = (
    new_skus
    .drop_duplicates(subset=["user_id", "product_id"])
)

user_dept_summary = (
    new_skus_dedup
    .groupby("user_id")
    .agg(
        total_new_sku=("product_id", "count"),
        existing_dept_sku=("from_existing_dept", "sum"),
    )
    .reset_index()
)

user_dept_summary["new_dept_sku"] = (
    user_dept_summary["total_new_sku"] - user_dept_summary["existing_dept_sku"]
)
user_dept_summary["existing_dept_share"] = (
    user_dept_summary["existing_dept_sku"] / user_dept_summary["total_new_sku"]
)

print("\n========== User-level existing_dept_share distribution (fixed) ==========")
print(user_dept_summary["existing_dept_share"].describe(
    percentiles=[.1, .25, .5, .75, .9]
))
print(f"\n% users where >80% new SKU from existing dept: "
      f"{(user_dept_summary['existing_dept_share'] > 0.8).mean()*100:.1f}%")
print(f"% users where >50% new SKU from existing dept: "
      f"{(user_dept_summary['existing_dept_share'] > 0.5).mean()*100:.1f}%")

print("\n========== User-level existing_dept_share distribution ==========")
print(user_dept_summary["existing_dept_share"].describe(
    percentiles=[.1, .25, .5, .75, .9]
))
print(f"\n% users where >80% new SKU from existing dept: "
      f"{(user_dept_summary['existing_dept_share'] > 0.8).mean()*100:.1f}%")
print(f"% users where >50% new SKU from existing dept: "
      f"{(user_dept_summary['existing_dept_share'] > 0.5).mean()*100:.1f}%")

# Saved for use in the next layer
print("\n✅ New tables created:")
print("  - mh_items        (Mid→High order items with half label)")
print("  - early_depts     (user early dept sets)")
print("  - early_skus      (user early SKU sets)")
print("  - new_skus        (late new SKUs with dept label)")
print("  - user_dept_summary (user-level Layer 1 result)")

Mid→High users: 14217
Mid→High orders: 306575
half
late     163978
early    142597
Name: count, dtype: int64
Mid→High order items: 3270303
['order_id', 'product_id', 'add_to_cart_order', 'reordered', 'user_id', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', 'aisle_id', 'department_id', 'half']

Total new SKUs (item rows): 984129

========== Layer 1: Department 粒度汇总 ==========
Total new unique SKU rows : 984,129
From existing department  : 881,542 (89.6%)
From new department       : 102,587 (10.4%)

========== 用户级 existing_dept_share 分布（修复后）==========
count    14208.000000
mean         0.859985
std          0.145112
min          0.000000
10%          0.666667
25%          0.806452
50%          0.903978
75%          0.960784
90%          1.000000
max          1.000000
Name: existing_dept_share, dtype: float64

% users where >80% new SKU from existing dept: 75.5%
% users where >50% new SKU from existing dept: 96.6%

========== 用户级 existing_dept_share 分布 ==========
count    14208.000000
mean         0.859985
std          0.145112
min          0.000000
10%          0.666667
25%          0.806452
50%          0.903978
75%          0.960784
90%          1.000000
max          1.000000
Name: existing_dept_share, dtype: float64

% users where >80% new SKU from existing dept: 75.5%
% users where >50% new SKU from existing dept: 96.6%

✅ New tables created:
  - mh_items        (Mid→High order items with half label)
  - early_depts     (user early dept sets)
  - early_skus      (user early SKU sets)
  - new_skus        (late new SKUs with dept label)
  - user_dept_summary (user-level Layer 1 result)

**Basket-Side Growth Analysis — Layer 2: Aisle Granularity (Key New Analysis)**

A finer granularity, answering "within the same broad category, is the user buying a new sub-category or items from the same shelf." For each user, compare early vs. late: share of newly added SKUs from an aisle already visited (existing_aisle_sku_share) vs. from a brand-new aisle (new_aisle_sku_share).

**Result**: existing_aisle_sku_share ≈ **56%**, new_aisle_sku_share ≈ **44%**. This 44% is the key finding — it shows that within the same department, users are exploring new sub-category aisles; growth is not just "buying more of the same thing" but reflects genuine category exploration.

In [89]:
# ============================================================
# Layer 2: Aisle granularity analysis
# Answers: do newly added SKUs come from an existing aisle or a new aisle?
# Further split: is the new aisle within an existing dept, or a new dept?
# ============================================================

# ----------------------------------------
# Step 1: find each user's early-stage aisle set
# ----------------------------------------
early_aisles = (
    mh_items[mh_items["half"] == "early"]
    .groupby("user_id")["aisle_id"]
    .apply(set)
    .reset_index()
    .rename(columns={"aisle_id": "early_aisle_set"})
)

# ----------------------------------------
# Step 2: add aisle info into new_skus_dedup
# new_skus_dedup is already the deduplicated set of new SKUs
# ----------------------------------------
new_skus_l2 = new_skus_dedup.merge(early_aisles, on="user_id", how="left")

# Determine whether this new SKU's aisle appeared in early
new_skus_l2["from_existing_aisle"] = new_skus_l2.apply(
    lambda r: r["aisle_id"] in r["early_aisle_set"]
    if isinstance(r["early_aisle_set"], set) else False,
    axis=1
)

# ----------------------------------------
# Step 3: break down into four cases
# existing dept + existing aisle → true consolidation
# existing dept + new aisle      → intra-category expansion
# new dept + new aisle           → true new-category expansion
# new dept + existing aisle      → theoretically rare, but still counted
# ----------------------------------------
new_skus_l2["sku_type"] = "unknown"
new_skus_l2.loc[
     new_skus_l2["from_existing_dept"] &  new_skus_l2["from_existing_aisle"],
    "sku_type"
] = "existing_dept_existing_aisle"
new_skus_l2.loc[
     new_skus_l2["from_existing_dept"] & ~new_skus_l2["from_existing_aisle"],
    "sku_type"
] = "existing_dept_new_aisle"
new_skus_l2.loc[
    ~new_skus_l2["from_existing_dept"] &  new_skus_l2["from_existing_aisle"],
    "sku_type"
] = "new_dept_existing_aisle"
new_skus_l2.loc[
    ~new_skus_l2["from_existing_dept"] & ~new_skus_l2["from_existing_aisle"],
    "sku_type"
] = "new_dept_new_aisle"

# ----------------------------------------
# Step 4: overall summary
# ----------------------------------------
total = len(new_skus_l2)
type_summary = (
    new_skus_l2.groupby("sku_type")
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
)
type_summary["share"] = type_summary["count"] / total

print("========== Layer 2: Aisle granularity summary ==========")
print(f"Total new unique SKUs: {total:,}")
print()
print(type_summary.to_string(index=False))

# Condensed summary
print("\n========== Condensed: three categories combined ==========")
consolidation = new_skus_l2["sku_type"].eq("existing_dept_existing_aisle").sum()
intra_expansion = new_skus_l2["sku_type"].eq("existing_dept_new_aisle").sum()
new_category = new_skus_l2["sku_type"].isin(
    ["new_dept_existing_aisle", "new_dept_new_aisle"]
).sum()

print(f"Consolidation        (existing dept + existing aisle): "
      f"{consolidation:,} ({consolidation/total*100:.1f}%)")
print(f"Intra-cat expansion  (existing dept + new aisle)      : "
      f"{intra_expansion:,} ({intra_expansion/total*100:.1f}%)")
print(f"New category         (new dept)                       : "
      f"{new_category:,} ({new_category/total*100:.1f}%)")

# ----------------------------------------
# Step 5: user-level distribution
# ----------------------------------------
user_aisle_summary = (
    new_skus_l2.groupby("user_id")
    .agg(
        total_new_sku=("product_id", "count"),
        consolidation_sku=("sku_type",
            lambda x: (x == "existing_dept_existing_aisle").sum()),
        intra_expansion_sku=("sku_type",
            lambda x: (x == "existing_dept_new_aisle").sum()),
        new_category_sku=("sku_type",
            lambda x: x.isin(
                ["new_dept_existing_aisle", "new_dept_new_aisle"]
            ).sum()),
    )
    .reset_index()
)

user_aisle_summary["consolidation_share"] = (
    user_aisle_summary["consolidation_sku"] /
    user_aisle_summary["total_new_sku"]
)
user_aisle_summary["intra_expansion_share"] = (
    user_aisle_summary["intra_expansion_sku"] /
    user_aisle_summary["total_new_sku"]
)
user_aisle_summary["new_category_share"] = (
    user_aisle_summary["new_category_sku"] /
    user_aisle_summary["total_new_sku"]
)

print("\n========== User-level consolidation_share distribution ==========")
print(user_aisle_summary["consolidation_share"].describe(
    percentiles=[.1, .25, .5, .75, .9]
))

print("\n========== User-level intra_expansion_share distribution ==========")
print(user_aisle_summary["intra_expansion_share"].describe(
    percentiles=[.1, .25, .5, .75, .9]
))

print("\n========== User-level new_category_share distribution ==========")
print(user_aisle_summary["new_category_share"].describe(
    percentiles=[.1, .25, .5, .75, .9]
))

# ----------------------------------------
# Step 6: typical user profiles (share of users dominated by each category)
# ----------------------------------------
print("\n========== User profile: dominant growth type ==========")
print(f"Consolidation-dominant (>60% new SKU from existing aisle): "
      f"{(user_aisle_summary['consolidation_share'] > 0.6).mean()*100:.1f}%")
print(f"Intra-expansion-dominant (>40% new SKU from new aisle in existing dept): "
      f"{(user_aisle_summary['intra_expansion_share'] > 0.4).mean()*100:.1f}%")
print(f"New-category-dominant (>30% new SKU from new dept): "
      f"{(user_aisle_summary['new_category_share'] > 0.3).mean()*100:.1f}%")

print("\n✅ New tables created:")
print("  - new_skus_l2          (new SKUs with aisle + type label)")
print("  - user_aisle_summary   (user-level Layer 2 result)")

========== Layer 2: Aisle 粒度汇总 ==========
Total new unique SKUs: 640,784

                    sku_type  count    share
existing_dept_existing_aisle 374071 0.583771
     existing_dept_new_aisle 192339 0.300162
          new_dept_new_aisle  74374 0.116067

========== 简洁版：三类合并 ==========
Consolidation        (existing dept + existing aisle): 374,071 (58.4%)
Intra-cat expansion  (existing dept + new aisle)      : 192,339 (30.0%)
New category         (new dept)                       : 74,374 (11.6%)

========== 用户级 consolidation_share 分布 ==========
count    14208.000000
mean         0.554665
std          0.177639
min          0.000000
10%          0.312500
25%          0.452266
50%          0.576923
75%          0.682927
90%          0.760563
max          1.000000
Name: consolidation_share, dtype: float64

========== 用户级 intra_expansion_share 分布 ==========
count    14208.000000
mean         0.305320
std          0.135538
min          0.000000
10%          0.145161
25%          0.214286
50%          0.294118
75%          0.384615
90%          0.480000
max          1.000000
Name: intra_expansion_share, dtype: float64

========== 用户级 new_category_share 分布 ==========
count    14208.000000
mean         0.140015
std          0.145112
min          0.000000
10%          0.000000
25%          0.039216
50%          0.096022
75%          0.193548
90%          0.333333
max          1.000000
Name: new_category_share, dtype: float64

========== 用户画像：主导增长类型 ==========
Consolidation 主导 (>60% new SKU from existing aisle): 44.0%
Intra-expansion 主导 (>40% new SKU from new aisle in existing dept): 21.1%
New category 主导 (>30% new SKU from new dept): 11.8%

✅ New tables created:
  - new_skus_l2          (new SKUs with aisle + type label)
  - user_aisle_summary   (user-level Layer 2 result)

In [90]:
# Additional analysis: category composition of past departments

# ============================================================
# Supplementary analysis: top Department/Aisle distribution of new SKUs
# Compare against the user's early-stage top Department/Aisle
# Purpose: see what users bought early vs. what's newly added, and whether there's a directional tendency
# ============================================================

# ----------------------------------------
# Part 1: Top Department in the early stage
# See which broad categories users mainly shopped in before upgrading
# ----------------------------------------
early_items = mh_items[mh_items["half"] == "early"].copy()

# Overall level: SKU counts per department in the early stage
# drop_duplicates ensures each user-SKU pair is only counted once (deduplicated)
early_dept_dist = (
    early_items
    .drop_duplicates(subset=["user_id", "product_id"])
    .groupby("department_id")
    .size()
    .reset_index(name="early_sku_count")
)

# Compute each department's share of total early-stage SKUs
early_dept_dist["early_share"] = (
    early_dept_dist["early_sku_count"] /
    early_dept_dist["early_sku_count"].sum()
)

# Join department names (for readability)
early_dept_dist = early_dept_dist.merge(
    departments[["department_id", "department"]],
    on="department_id", how="left"
)

# Sort by share, descending
early_dept_dist = early_dept_dist.sort_values(
    "early_share", ascending=False
).reset_index(drop=True)

print("========== Top Department in the Early Stage ==========")
print("(which broad categories users mainly shopped in before upgrading)")
print(early_dept_dist[["department", "early_sku_count", "early_share"]]
      .head(10).to_string(index=False))

# ----------------------------------------
# Part 2: Top Department of newly added SKUs
# See which broad categories the newly purchased items concentrate in after upgrading
# new_skus_l2 is the new-SKU table produced by the layer-2 analysis (already deduplicated)
# ----------------------------------------
new_dept_dist = (
    new_skus_l2
    .groupby("department_id")
    .size()
    .reset_index(name="new_sku_count")
)

# Compute each department's share of total new SKUs
new_dept_dist["new_share"] = (
    new_dept_dist["new_sku_count"] /
    new_dept_dist["new_sku_count"].sum()
)

# Join department names
new_dept_dist = new_dept_dist.merge(
    departments[["department_id", "department"]],
    on="department_id", how="left"
)

new_dept_dist = new_dept_dist.sort_values(
    "new_share", ascending=False
).reset_index(drop=True)

print("\n========== Top Department of New SKUs ==========")
print("(which broad categories the newly purchased items concentrate in after upgrading)")
print(new_dept_dist[["department", "new_sku_count", "new_share"]]
      .head(10).to_string(index=False))

# ----------------------------------------
# Part 3: comparison table (early vs. new SKU share)
# See which broad categories rose or fell in share among new SKUs
# share_diff > 0: this category has a higher share among new SKUs than in early (increasing tendency)
# share_diff < 0: this category has a lower share among new SKUs than in early (decreasing tendency)
# ----------------------------------------
dept_compare = early_dept_dist[
    ["department_id", "department", "early_share"]
].merge(
    new_dept_dist[["department_id", "new_share"]],
    on="department_id", how="outer"
).fillna(0)

# Compute the difference between new-SKU share and early share
dept_compare["share_diff"] = (
    dept_compare["new_share"] - dept_compare["early_share"]
)

# Sort by early_share descending, for easier comparison of major categories
dept_compare = dept_compare.sort_values(
    "early_share", ascending=False
).reset_index(drop=True)

print("\n========== Department Comparison: Early vs. New SKU ==========")
print("(share_diff > 0 means this category has a higher share among new SKUs)")
print(dept_compare[
    ["department", "early_share", "new_share", "share_diff"]
].to_string(index=False))

# ----------------------------------------
# Part 4: Top Aisle in the early stage
# Finer granularity: which aisles users mainly shopped in before upgrading
# ----------------------------------------
early_aisle_dist = (
    early_items
    .drop_duplicates(subset=["user_id", "product_id"])
    .groupby("aisle_id")
    .size()
    .reset_index(name="early_sku_count")
)

# Compute each aisle's share of total early-stage SKUs
early_aisle_dist["early_share"] = (
    early_aisle_dist["early_sku_count"] /
    early_aisle_dist["early_sku_count"].sum()
)

# Join aisle names
early_aisle_dist = early_aisle_dist.merge(
    aisles[["aisle_id", "aisle"]],
    on="aisle_id", how="left"
)

early_aisle_dist = early_aisle_dist.sort_values(
    "early_share", ascending=False
).reset_index(drop=True)

print("\n========== Top 15 Aisle in the Early Stage ==========")
print("(which aisles users mainly shopped in before upgrading)")
print(early_aisle_dist[["aisle", "early_sku_count", "early_share"]]
      .head(15).to_string(index=False))

# ----------------------------------------
# Part 5: Top Aisle of newly added SKUs
# See which aisles the newly purchased items concentrate in after upgrading
# ----------------------------------------
new_aisle_dist = (
    new_skus_l2
    .groupby("aisle_id")
    .size()
    .reset_index(name="new_sku_count")
)

# Compute each aisle's share of total new SKUs
new_aisle_dist["new_share"] = (
    new_aisle_dist["new_sku_count"] /
    new_aisle_dist["new_sku_count"].sum()
)

# Join aisle names
new_aisle_dist = new_aisle_dist.merge(
    aisles[["aisle_id", "aisle"]],
    on="aisle_id", how="left"
)

new_aisle_dist = new_aisle_dist.sort_values(
    "new_share", ascending=False
).reset_index(drop=True)

print("\n========== Top 15 Aisle of New SKUs ==========")
print("(which aisles the newly purchased items concentrate in after upgrading)")
print(new_aisle_dist[["aisle", "new_sku_count", "new_share"]]
      .head(15).to_string(index=False))

# ----------------------------------------
# Part 6: Aisle comparison (early vs. new)
# See which aisles show a notably rising or falling share among new SKUs
# Largest share_diff = aisle where new SKUs concentrate the most (strongest growth tendency)
# Smallest share_diff = aisle with less share among new SKUs than in early
# ----------------------------------------
aisle_compare = early_aisle_dist[
    ["aisle_id", "aisle", "early_share"]
].merge(
    new_aisle_dist[["aisle_id", "new_share"]],
    on="aisle_id", how="outer"
).fillna(0)

# Compute the difference
aisle_compare["share_diff"] = (
    aisle_compare["new_share"] - aisle_compare["early_share"]
)

# Aisles with the largest share increase among new SKUs
# → these are the categories users are most inclined to add when upgrading
print("\n========== Aisle Comparison: Top 10 Largest New-SKU Share Increases ==========")
print("(these are the aisles users are most inclined to newly explore when upgrading)")
print(aisle_compare.sort_values("share_diff", ascending=False)
      [["aisle", "early_share", "new_share", "share_diff"]]
      .head(10).to_string(index=False))

# Aisles with the largest share decrease among new SKUs
# → these are categories users bought a lot of in early but add less of now (already saturated)
print("\n========== Aisle Comparison: Top 10 Largest New-SKU Share Decreases ==========")
print("(these aisles had a high share in early but see less new addition, indicating near-saturation)")
print(aisle_compare.sort_values("share_diff", ascending=True)
      [["aisle", "early_share", "new_share", "share_diff"]]
      .head(10).to_string(index=False))

========== Early 阶段 Top Department ==========
（用户升级前，主要在哪些大类购物）
     department  early_sku_count  early_share
        produce           195851     0.271378
     dairy eggs           104819     0.145241
         snacks            63035     0.087344
         pantry            59989     0.083123
         frozen            54142     0.075021
      beverages            48989     0.067881
   canned goods            29841     0.041349
dry goods pasta            24529     0.033988
         bakery            24340     0.033726
           deli            23253     0.032220

========== 新增 SKU Top Department ==========
（用户升级后，新买的商品主要在哪些大类）
     department  new_sku_count  new_share
        produce         156968   0.244962
     dairy eggs          77763   0.121356
         pantry          67832   0.105858
         snacks          58800   0.091763
         frozen          48278   0.075342
      beverages          40211   0.062753
   canned goods          31980   0.049908
dry goods pasta          24806   0.038712
      household          20367   0.031785
         bakery          19324   0.030157

========== Department 对比：Early vs 新增 SKU ==========
（share_diff > 0 表示新增 SKU 中该大类比例更高）
     department  early_share  new_share  share_diff
        produce     0.271378   0.244962   -0.026416
     dairy eggs     0.145241   0.121356   -0.023885
         snacks     0.087344   0.091763    0.004419
         pantry     0.083123   0.105858    0.022735
         frozen     0.075021   0.075342    0.000321
      beverages     0.067881   0.062753   -0.005128
   canned goods     0.041349   0.049908    0.008559
dry goods pasta     0.033988   0.038712    0.004724
         bakery     0.033726   0.030157   -0.003570
           deli     0.032220   0.029195   -0.003025
      household     0.027911   0.031785    0.003874
   meat seafood     0.023955   0.022006   -0.001949
      breakfast     0.022759   0.022511   -0.000248
  personal care     0.019050   0.024765    0.005715
         babies     0.013075   0.016458    0.003383
  international     0.011257   0.015643    0.004386
        alcohol     0.003815   0.002985   -0.000829
           pets     0.002753   0.002519   -0.000234
        missing     0.001714   0.008110    0.006396
          other     0.001325   0.001985    0.000660
           bulk     0.001115   0.001227    0.000111

========== Early 阶段 Top 15 Aisle ==========
（用户升级前，主要在哪些货架购物）
                        aisle  early_sku_count  early_share
             fresh vegetables            82733     0.114638
                 fresh fruits            62594     0.086733
   packaged vegetables fruits            37189     0.051530
                       yogurt            27138     0.037603
              packaged cheese            22594     0.031307
               chips pretzels            15858     0.021973
               frozen produce            13037     0.018065
                ice cream ice            12882     0.017850
water seltzer sparkling water            12613     0.017477
                         milk            12338     0.017096
              soy lactosefree            11887     0.016471
                        bread            11237     0.015570
           baking ingredients            11230     0.015561
                 refrigerated            10893     0.015094
                  fresh herbs            10777     0.014933

========== 新增 SKU Top 15 Aisle ==========
（用户升级后，新买的商品主要在哪些货架）
                     aisle  new_sku_count  new_share
          fresh vegetables          71607   0.111749
              fresh fruits          42298   0.066010
packaged vegetables fruits          30458   0.047532
                    yogurt          19581   0.030558
           packaged cheese          19293   0.030108
            chips pretzels          13578   0.021190
        baking ingredients          12409   0.019365
            frozen produce          11878   0.018537
             ice cream ice          11861   0.018510
         spices seasonings          11546   0.018019
       soup broth bouillon          11216   0.017504
               fresh herbs          10338   0.016133
  canned jarred vegetables           9875   0.015411
                  crackers           9590   0.014966
         baby food formula           9426   0.014710

========== Aisle 对比：新增 SKU share 提升最大 Top 10 ==========
（这些货架是用户升级时最倾向于新探索的）
                   aisle  early_share  new_share  share_diff
                 missing     0.001714   0.008110    0.006396
       spices seasonings     0.011631   0.018019    0.006388
      baking ingredients     0.015561   0.019365    0.003805
     soup broth bouillon     0.014070   0.017504    0.003434
       baby food formula     0.011516   0.014710    0.003194
canned jarred vegetables     0.012266   0.015411    0.003145
           oils vinegars     0.010869   0.013694    0.002825
              condiments     0.010347   0.013086    0.002739
             asian foods     0.007082   0.009793    0.002711
  nuts seeds dried fruit     0.010295   0.012371    0.002076

========== Aisle 对比：新增 SKU share 下降最大 Top 10 ==========
（这些货架在 early 阶段占比高，但新增较少，说明已接近饱和）
                        aisle  early_share  new_share  share_diff
                 fresh fruits     0.086733   0.066010   -0.020723
                       yogurt     0.037603   0.030558   -0.007046
                         milk     0.017096   0.010325   -0.006771
water seltzer sparkling water     0.017477   0.013279   -0.004198
   packaged vegetables fruits     0.051530   0.047532   -0.003998
                         eggs     0.011551   0.007652   -0.003899
                        bread     0.015570   0.012592   -0.002978
             fresh vegetables     0.114638   0.111749   -0.002889
              soy lactosefree     0.016471   0.013735   -0.002736
                 refrigerated     0.015094   0.013615   -0.001479

**Basket-Side Growth Analysis — Layer 3: Structural Tags × Aisle Expansion (New Analysis)**

Break down layer 2's 44% new-aisle expansion by the four structural tags: Consumable / Core / Variety / Durable.

**Core question**: Which product category primarily drives the 44% new-aisle expansion?

- If mainly from **Consumable / Core** → users are rounding out their daily restocking list
- If mainly from **Variety** → users are genuinely exploring new categories
- If mainly from **Durable** → occasional supplemental purchases

Only this layer of breakdown can truly distinguish **consolidation (reinforcing existing demand)** from **expansion (genuine category expansion)**.

In [91]:
# ============================================================
# Layer 3: structural tag analysis
# Break down new SKUs by Consumable / Core / Variety / Durable
# Core question: which product category do new SKUs mainly come from?
# Further split: three growth types (consolidation / intra-expansion / new category)
# What is the category composition within each?
# ============================================================

# ----------------------------------------
# Step 1: add the four department tags to new_skus_l2
# new_skus_l2 already has department_id and sku_type (from layer 2)
# ----------------------------------------

# Tag using the previously defined department sets
# Overlap allowed (a dept can be both consumable and core)
new_skus_l3 = new_skus_l2.copy()

new_skus_l3["is_consumable"] = new_skus_l3["department_id"].isin(
    CONSUMABLE_DEPTS
).astype(int)

new_skus_l3["is_core"] = new_skus_l3["department_id"].isin(
    CORE_DEPTS
).astype(int)

new_skus_l3["is_variety"] = new_skus_l3["department_id"].isin(
    VARIETY_DEPTS
).astype(int)

new_skus_l3["is_durable"] = new_skus_l3["department_id"].isin(
    DURABLE_DEPTS
).astype(int)

# Quick check of tag coverage
print("========== Tag Coverage Check ==========")
print(f"is_consumable = 1 : {new_skus_l3['is_consumable'].mean()*100:.1f}%")
print(f"is_core       = 1 : {new_skus_l3['is_core'].mean()*100:.1f}%")
print(f"is_variety    = 1 : {new_skus_l3['is_variety'].mean()*100:.1f}%")
print(f"is_durable    = 1 : {new_skus_l3['is_durable'].mean()*100:.1f}%")

# ----------------------------------------
# Step 2: overall level
# What share does each of the four categories hold among all new SKUs?
# ----------------------------------------
total = len(new_skus_l3)

print("\n========== Overall Four-Category Share of New SKUs ==========")
print("(note: overlap allowed, so totals may exceed 100%)")
for tag in ["is_consumable", "is_core", "is_variety", "is_durable"]:
    label = tag.replace("is_", "")
    cnt = new_skus_l3[tag].sum()
    print(f"{label:12s}: {cnt:,} ({cnt/total*100:.1f}%)")

# ----------------------------------------
# Step 3: split by sku_type, to see the category composition of the three growth types
# sku_type：
#   existing_dept_existing_aisle → consolidation
#   existing_dept_new_aisle      → intra-category expansion
#   new_dept_new_aisle           → new category expansion
# ----------------------------------------
print("\n========== Three Growth Types × Four Tags ==========")
print("(within each growth type, the share of each of the four categories)")

for sku_type in [
    "existing_dept_existing_aisle",
    "existing_dept_new_aisle",
    "new_dept_new_aisle"
]:
    subset = new_skus_l3[new_skus_l3["sku_type"] == sku_type]
    n = len(subset)

    if sku_type == "existing_dept_existing_aisle":
        label = "Consolidation"
    elif sku_type == "existing_dept_new_aisle":
        label = "Intra-cat expansion"
    else:
        label = "New category"

    print(f"\n--- {label} (n={n:,}) ---")
    for tag in ["is_consumable", "is_core", "is_variety", "is_durable"]:
        tag_label = tag.replace("is_", "")
        cnt = subset[tag].sum()
        print(f"  {tag_label:12s}: {cnt:,} ({cnt/n*100:.1f}%)")

# ----------------------------------------
# Step 4: focused analysis of intra-category expansion
# Which product category primarily drives this 30% new-aisle expansion?
# ----------------------------------------
intra = new_skus_l3[
    new_skus_l3["sku_type"] == "existing_dept_new_aisle"
].copy()

print("\n========== Intra-cat Expansion Detailed Analysis ==========")
print("(this is the key 30%, need to clarify its business meaning)")

# View the distribution by department
intra_dept = (
    intra
    .groupby("department_id")
    .agg(sku_count=("product_id", "count"))
    .reset_index()
    .merge(departments[["department_id", "department"]], on="department_id", how="left")
)
intra_dept["share"] = intra_dept["sku_count"] / len(intra)
intra_dept = intra_dept.sort_values("share", ascending=False)

print("\nTop 10 Department in Intra-cat expansion:")
print(intra_dept[["department", "sku_count", "share"]].head(10).to_string(index=False))

# Also apply the four tags, to see intra-expansion's category composition
print("\nIntra-cat expansion four-category share:")
for tag in ["is_consumable", "is_core", "is_variety", "is_durable"]:
    tag_label = tag.replace("is_", "")
    cnt = intra[tag].sum()
    print(f"  {tag_label:12s}: {cnt:,} ({cnt/len(intra)*100:.1f}%)")

# ----------------------------------------
# Step 5: user-level analysis
# View each user's new-SKU category composition
# ----------------------------------------
user_tag_summary = (
    new_skus_l3
    .groupby("user_id")
    .agg(
        total_new_sku=("product_id", "count"),
        consumable_count=("is_consumable", "sum"),
        core_count=("is_core", "sum"),
        variety_count=("is_variety", "sum"),
        durable_count=("is_durable", "sum"),
    )
    .reset_index()
)

# Compute each category's share
for tag in ["consumable", "core", "variety", "durable"]:
    user_tag_summary[f"{tag}_share"] = (
        user_tag_summary[f"{tag}_count"] /
        user_tag_summary["total_new_sku"]
    )

print("\n========== User-Level Four-Category Share Distribution ==========")
for tag in ["consumable", "core", "variety", "durable"]:
    print(f"\n--- {tag}_share ---")
    print(user_tag_summary[f"{tag}_share"].describe(
        percentiles=[.1, .25, .5, .75, .9]
    ))

# ----------------------------------------
# Step 6: merge into user_aisle_summary
# Combine category composition and growth type into one table, for easier downstream analysis
# ----------------------------------------
user_l3_summary = user_aisle_summary.merge(
    user_tag_summary[[
        "user_id",
        "consumable_share", "core_share",
        "variety_share", "durable_share"
    ]],
    on="user_id", how="left"
)

print("\n✅ New tables created:")
print("  - new_skus_l3      (new SKUs with four tags + sku_type)")
print("  - user_tag_summary (user-level four-category share)")
print("  - user_l3_summary  (user-level full Layer 2+3 summary)")

========== 标签覆盖检查 ==========
is_consumable = 1 : 59.5%
is_core       = 1 : 61.3%
is_variety    = 1 : 28.0%
is_durable    = 1 : 8.6%

========== 整体新增 SKU 四类占比 ==========
（注意：允许交叉，所以加总可能超过100%）
consumable  : 380,976 (59.5%)
core        : 392,774 (61.3%)
variety     : 179,336 (28.0%)
durable     : 54,865 (8.6%)

========== 三种增长类型 × 四类标签 ==========
（每种增长类型里，四类商品各占多少）

--- Consolidation (n=374,071) ---
  consumable  : 263,580 (70.5%)
  core        : 261,364 (69.9%)
  variety     : 89,067 (23.8%)
  durable     : 17,847 (4.8%)

--- Intra-cat expansion (n=192,339) ---
  consumable  : 94,658 (49.2%)
  core        : 104,887 (54.5%)
  variety     : 68,157 (35.4%)
  durable     : 16,229 (8.4%)

--- New category (n=74,374) ---
  consumable  : 22,738 (30.6%)
  core        : 26,523 (35.7%)
  variety     : 22,112 (29.7%)
  durable     : 20,789 (28.0%)

========== Intra-cat expansion 详细分析 ==========
（这是最关键的 30%，需要搞清楚业务含义）

Top 10 Department in Intra-cat expansion:
     department  sku_count    share
         pantry      33392 0.173610
     dairy eggs      26339 0.136941
         snacks      23904 0.124281
         frozen      19422 0.100978
      beverages      15859 0.082453
        produce      13221 0.068738
   canned goods      10627 0.055251
dry goods pasta       9039 0.046995
      household       8483 0.044104
  personal care       6961 0.036191

Intra-cat expansion 四类占比:
  consumable  : 94,658 (49.2%)
  core        : 104,887 (54.5%)
  variety     : 68,157 (35.4%)
  durable     : 16,229 (8.4%)

========== 用户级四类 share 分布 ==========

--- consumable_share ---
count    14208.000000
mean         0.608281
std          0.141433
min          0.000000
10%          0.432715
25%          0.517647
50%          0.607595
75%          0.697674
90%          0.785714
max          1.000000
Name: consumable_share, dtype: float64

--- core_share ---
count    14208.000000
mean         0.611619
std          0.169244
min          0.000000
10%          0.386364
25%          0.510638
50%          0.626506
75%          0.730445
90%          0.812500
max          1.000000
Name: core_share, dtype: float64

--- variety_share ---
count    14208.000000
mean         0.281248
std          0.140766
min          0.000000
10%          0.122300
25%          0.186047
50%          0.264706
75%          0.356677
90%          0.458333
max          1.000000
Name: variety_share, dtype: float64

--- durable_share ---
count    14208.000000
mean         0.084440
std          0.095671
min          0.000000
10%          0.000000
25%          0.016949
50%          0.056604
75%          0.120534
90%          0.204147
max          1.000000
Name: durable_share, dtype: float64

✅ New tables created:
  - new_skus_l3      (新增SKU with 四类标签 + sku_type)
  - user_tag_summary (用户级四类 share)
  - user_l3_summary  (用户级完整 Layer 2+3 汇总)

In [92]:
# Compare early vs. newly added share

# ============================================================
# Comparison of the four category tags: early vs. new SKUs
# Answers: did category composition change systematically before vs. after upgrading?
# ============================================================

# Share of the four categories in the early stage
early_items_tagged = (
    early_items
    .drop_duplicates(subset=["user_id", "product_id"])
    .copy()
)

early_items_tagged["is_consumable"] = early_items_tagged["department_id"].isin(CONSUMABLE_DEPTS).astype(int)
early_items_tagged["is_core"]       = early_items_tagged["department_id"].isin(CORE_DEPTS).astype(int)
early_items_tagged["is_variety"]    = early_items_tagged["department_id"].isin(VARIETY_DEPTS).astype(int)
early_items_tagged["is_durable"]    = early_items_tagged["department_id"].isin(DURABLE_DEPTS).astype(int)

total_early = len(early_items_tagged)
total_new   = len(new_skus_l3)

print("========== Early vs. New SKU Four-Category Share Comparison ==========")
print(f"{'Tag':<12} {'Early':>10} {'New SKU':>10} {'Diff':>10} {'Interpretation'}")
print("-" * 65)

for tag in ["consumable", "core", "variety", "durable"]:
    early_share = early_items_tagged[f"is_{tag}"].sum() / total_early
    new_share   = new_skus_l3[f"is_{tag}"].sum() / total_new
    diff        = new_share - early_share

    if diff > 0.02:
        interpretation = "↑ more new additions"
    elif diff < -0.02:
        interpretation = "↓ relatively saturated"
    else:
        interpretation = "≈ roughly flat"

    print(f"{tag:<12} {early_share:>9.1%} {new_share:>9.1%} {diff:>+9.1%}  {interpretation}")

========== Early vs 新增 SKU 四类占比对比 ==========
标签                Early      新增SKU         差值 解读
-----------------------------------------------------------------
consumable       65.1%     59.5%     -5.6%  ↓ 相对饱和
core             63.3%     61.3%     -2.0%  ≈ 基本持平
variety          28.0%     28.0%     -0.0%  ≈ 基本持平
durable           6.6%      8.6%     +2.0%  ≈ 基本持平

**Next step**: Begin the Gap-side analysis.

**Gap Zone Definitions**

Designed on three principles: aligns with grocery shopping's natural cadence (weekly/biweekly/monthly); fits the data characteristics (capped at 30 days, pct_gap30 is the strongest predictive variable, median gap early≈7-8 days/late≈6 days); is business-meaningful (each range maps to a different user state and intervention strategy).

- **Zone 1 (1-7 days)**: high-frequency habitual users, weekly cadence. For stable_up users, late-stage pct_gap≤7 rises from 48.2% (early) to 67.6%, the typical cadence of upgrading users; 7 days is the natural boundary of "weekly habit"
- **Zone 2 (8-14 days)**: biweekly cadence, healthy but not high-frequency, between weekly and monthly cadence, still an "active" state
- **Zone 3 (15-21 days)**: cadence starts loosening, a warning zone. For High→Mid users, early gap p75 = 15 days, late gap p90 = 30 days; instability signals begin to appear above 15 days
- **Zone 4 (22-29 days)**: approaching monthly restocking, high churn-risk zone
- **Zone 5 (30+ days)**: the data cap, the lowest-frequency state, lowest upgrade probability

In [93]:
# ============================================================
# Gap Zone analysis: change in each Zone's share, Early vs. Late
# Population: all Mid→High users (14,217)
# Purpose: see how the purchase-interval distribution changes before vs. after upgrading
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# Step 1: prepare order data for Mid→High users
# Reuse the previously built mh_orders (has user_id, order_id, half, gap_days_adj)
# ----------------------------------------

# Confirm mh_orders has gap_days_adj
print("mh_orders columns:", mh_orders.columns.tolist())
print("mh_orders shape:", mh_orders.shape)

# ----------------------------------------
# Step 2: define Gap Zone
# Zone 1: 1-7   days → weekly cadence, habitual users
# Zone 2: 8-14  days → biweekly cadence, active users
# Zone 3: 15-21 days → warning zone, cadence starts loosening
# Zone 4: 22-29 days → danger zone, approaching monthly restocking
# Zone 5: 30    days → the cap, low-frequency state
# ----------------------------------------
def assign_gap_zone(gap):
    if pd.isna(gap):
        return None
    elif gap <= 7:
        return "Zone1_weekly"
    elif gap <= 14:
        return "Zone2_biweekly"
    elif gap <= 21:
        return "Zone3_warning"
    elif gap <= 29:
        return "Zone4_danger"
    else:
        return "Zone5_cliff"

mh_orders["gap_zone"] = mh_orders["gap_days_adj"].apply(assign_gap_zone)

# The first order has no gap, dropped
mh_orders_gap = mh_orders.dropna(subset=["gap_zone"]).copy()

print(f"\nOrder count after dropping first orders: {len(mh_orders_gap):,}")
print("\nOverall Gap Zone distribution:")
print(mh_orders_gap["gap_zone"].value_counts().sort_index())

# ----------------------------------------
# Step 3: compute each user's order count and share per Zone, for early/late
# ----------------------------------------
zone_order = [
    "Zone1_weekly",
    "Zone2_biweekly",
    "Zone3_warning",
    "Zone4_danger",
    "Zone5_cliff"
]

# Order count per user × early/late × zone
user_zone = (
    mh_orders_gap
    .groupby(["user_id", "half", "gap_zone"])
    .size()
    .reset_index(name="order_count")
)

# Total order count per user × early/late (used as denominator)
user_half_total = (
    mh_orders_gap
    .groupby(["user_id", "half"])
    .size()
    .reset_index(name="total_orders")
)

# Merge and compute share
user_zone = user_zone.merge(user_half_total, on=["user_id", "half"], how="left")
user_zone["zone_share"] = user_zone["order_count"] / user_zone["total_orders"]

# ----------------------------------------
# Step 4: overall level - each Zone's share, Early vs. Late
# ----------------------------------------
zone_summary = (
    user_zone
    .groupby(["half", "gap_zone"])["zone_share"]
    .mean()
    .reset_index()
    .pivot(index="gap_zone", columns="half", values="zone_share")
    .reindex(zone_order)
)

zone_summary["delta"] = zone_summary["late"] - zone_summary["early"]
zone_summary["delta_pct"] = zone_summary["delta"] / zone_summary["early"] * 100

print("\n========== Early vs. Late Gap Zone Share (Overall) ==========")
print("(average user share for each Zone)")
print(zone_summary.round(4).to_string())

# ----------------------------------------
# Step 5: user level - pivot to wide, compute delta
# ----------------------------------------

# First pivot: user × zone, early and late separated
user_zone_wide = user_zone.pivot_table(
    index="user_id",
    columns=["half", "gap_zone"],
    values="zone_share",
    fill_value=0
).reset_index()

# Flatten column names
user_zone_wide.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in user_zone_wide.columns
]

# Compute each Zone's delta (late - early)
for zone in zone_order:
    early_col = f"early_{zone}"
    late_col  = f"late_{zone}"
    delta_col = f"delta_{zone}"

    # If a column doesn't exist (user has no orders in that zone for that half), fill with 0
    if early_col not in user_zone_wide.columns:
        user_zone_wide[early_col] = 0
    if late_col not in user_zone_wide.columns:
        user_zone_wide[late_col] = 0

    user_zone_wide[delta_col] = (
        user_zone_wide[late_col] - user_zone_wide[early_col]
    )

print("\n========== User-Level Delta Zone Share Distribution ==========")
print("(delta > 0 = this Zone has a higher share in the late stage)")
for zone in zone_order:
    delta_col = f"delta_{zone}"
    print(f"\n--- {zone} ---")
    print(user_zone_wide[delta_col].describe(
        percentiles=[.1, .25, .5, .75, .9]
    ).round(4))

# ----------------------------------------
# Step 6: visualization - overall Zone distribution comparison, Early vs. Late
# ----------------------------------------
print("\n========== Early vs. Late Zone Distribution Comparison (Visual) ==========")
print(f"{'Zone':<20} {'Early':>8} {'Late':>8} {'Delta':>8} {'Direction'}")
print("-" * 60)

for zone in zone_order:
    early_val = zone_summary.loc[zone, "early"]
    late_val  = zone_summary.loc[zone, "late"]
    delta_val = zone_summary.loc[zone, "delta"]
    direction = "↑ increase" if delta_val > 0.01 else ("↓ decrease" if delta_val < -0.01 else "≈ flat")
    print(f"{zone:<20} {early_val:>7.1%} {late_val:>7.1%} {delta_val:>+7.1%}  {direction}")

print("\n✅ New tables created:")
print("  - mh_orders_gap    (Mid→High orders with gap_zone label)")
print("  - user_zone        (user × half × zone share)")
print("  - user_zone_wide   (user-level wide table, with delta)")
print("  - zone_summary     (overall early vs. late comparison)")

mh_orders columns: ['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', 'items_per_order', 'active_score_week', 'gap_days_adj', 'n_orders', 'pos', 'half']
mh_orders shape: (306575, 13)

去掉第一单后的订单数: 306,575

Gap Zone 整体分布:
gap_zone
Zone1_weekly      173443
Zone2_biweekly     75712
Zone3_warning      26269
Zone4_danger       12595
Zone5_cliff        18556
Name: count, dtype: int64

========== Early vs Late Gap Zone Share（整体）==========
（每个 Zone 的平均用户 share）
half             early    late   delta  delta_pct
gap_zone
Zone1_weekly    0.4702  0.5839  0.1137    24.1884
Zone2_biweekly  0.3415  0.3027 -0.0389   -11.3818
Zone3_warning   0.2227  0.1724 -0.0503   -22.5883
Zone4_danger    0.1865  0.1476 -0.0390   -20.8861
Zone5_cliff     0.2784  0.2035 -0.0749   -26.9150

========== 用户级 Delta Zone Share 分布 ==========
（delta > 0 = late 阶段这个 Zone 占比更高）

--- Zone1_weekly ---
count    14217.0000
mean         0.1778
std          0.2614
min         -1.0000
10%         -0.1333
25%          0.0000
50%          0.1667
75%          0.3333
90%          0.5000
max          1.0000
Name: delta_Zone1_weekly, dtype: float64

--- Zone2_biweekly ---
count    14217.0000
mean        -0.0156
std          0.2697
min         -1.0000
10%         -0.3333
25%         -0.1667
50%         -0.0157
75%          0.1442
90%          0.3333
max          1.0000
Name: delta_Zone2_biweekly, dtype: float64

--- Zone3_warning ---
count    14217.0000
mean        -0.0458
std          0.1997
min         -1.0000
10%         -0.2628
25%         -0.1250
50%         -0.0035
75%          0.0000
90%          0.1667
max          1.0000
Name: delta_Zone3_warning, dtype: float64

--- Zone4_danger ---
count    14217.0000
mean        -0.0355
std          0.1522
min         -1.0000
10%         -0.2000
25%         -0.0714
50%          0.0000
75%          0.0000
90%          0.0909
max          0.7500
Name: delta_Zone4_danger, dtype: float64

--- Zone5_cliff ---
count    14217.0000
mean        -0.0809
std          0.2175
min         -1.0000
10%         -0.3333
25%         -0.1528
50%          0.0000
75%          0.0000
90%          0.1000
max          0.8333
Name: delta_Zone5_cliff, dtype: float64

========== Early vs Late Zone 分布对比（直观版）==========
Zone                    Early     Late    Delta 方向
------------------------------------------------------------
Zone1_weekly           47.0%   58.4%  +11.4%  ↑ 增加
Zone2_biweekly         34.2%   30.3%   -3.9%  ↓ 减少
Zone3_warning          22.3%   17.2%   -5.0%  ↓ 减少
Zone4_danger           18.7%   14.8%   -3.9%  ↓ 减少
Zone5_cliff            27.8%   20.3%   -7.5%  ↓ 减少

✅ New tables created:
  - mh_orders_gap    (Mid→High 订单 with gap_zone 标签)
  - user_zone        (用户 × half × zone 的 share)
  - user_zone_wide   (用户级宽表，含 delta)
  - zone_summary     (整体 early vs late 对比)

In [94]:
# ============================================================
# Gap Zone × Weekly upgrade correlation analysis
# Angle 1: correlation
# Core question: which Zone's delta correlates most with weekly growth?
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Step 1: prepare the analysis table
# Needs: user_zone_wide (each Zone's delta)
#       + analysis_mid_user_master（delta_weekly）
# ----------------------------------------

# Get the weekly growth metric from the master table
weekly_cols = analysis_mid_user_master[
    ["user_id", "delta_weekly", "d_log_weekly", "d_log_gap", "d_log_basket"]
].copy()

# Merge
corr_df = user_zone_wide.merge(weekly_cols, on="user_id", how="inner")

print(f"Analysis sample size: {len(corr_df):,}")

# ----------------------------------------
# Step 2: compute the correlation between each Zone's delta and weekly
# Compute both Pearson and Spearman
# Pearson: linear correlation
# Spearman: monotonic correlation (more robust, not affected by extreme values)
# ----------------------------------------

zone_deltas = [
    "delta_Zone1_weekly",
    "delta_Zone2_biweekly",
    "delta_Zone3_warning",
    "delta_Zone4_danger",
    "delta_Zone5_cliff",
]

# Two definitions used for the weekly target variable
targets = {
    "delta_weekly"  : "absolute growth (late - early weekly)",
    "d_log_weekly"  : "relative growth (log scale)",
}

results = []

for zone_col in zone_deltas:
    for target_col, target_label in targets.items():

        # Drop NaN
        valid = corr_df[[zone_col, target_col]].dropna()

        # Pearson
        pearson_r, pearson_p = stats.pearsonr(
            valid[zone_col], valid[target_col]
        )

        # Spearman
        spearman_r, spearman_p = stats.spearmanr(
            valid[zone_col], valid[target_col]
        )

        results.append({
            "zone"          : zone_col.replace("delta_", ""),
            "target"        : target_col,
            "pearson_r"     : round(pearson_r, 4),
            "pearson_p"     : round(pearson_p, 4),
            "spearman_r"    : round(spearman_r, 4),
            "spearman_p"    : round(spearman_p, 4),
            "n"             : len(valid),
        })

corr_results = pd.DataFrame(results)

# ----------------------------------------
# Step 3: output results
# View separately by target, sorted by |spearman_r|
# ----------------------------------------
for target_col, target_label in targets.items():
    subset = (
        corr_results[corr_results["target"] == target_col]
        .sort_values("spearman_r", key=abs, ascending=False)
        .reset_index(drop=True)
    )

    print(f"\n========== {target_label} ==========")
    print(f"{'Zone':<25} {'Pearson_r':>10} {'Spearman_r':>12} {'Sig':>10}")
    print("-" * 65)

    for _, row in subset.iterrows():
        sig = "***" if row["spearman_p"] < 0.001 else (
              "**"  if row["spearman_p"] < 0.01  else (
              "*"   if row["spearman_p"] < 0.05  else "ns"))
        print(f"{row['zone']:<25} {row['pearson_r']:>10.4f} "
              f"{row['spearman_r']:>12.4f} {sig:>10}")

# ----------------------------------------
# Step 4: compare against the original d_log_gap
# See whether the new Zone analysis has more explanatory power than the original gap metric
# ----------------------------------------
print("\n========== Comparison: Original d_log_gap vs. Each Zone Delta ==========")
print("(validate whether Zone analysis is more precise than the overall gap metric)")

for target_col, target_label in targets.items():
    valid = corr_df[["d_log_gap", target_col]].dropna()
    pearson_r, _ = stats.pearsonr(valid["d_log_gap"], valid[target_col])
    spearman_r, _ = stats.spearmanr(valid["d_log_gap"], valid[target_col])
    print(f"\n{target_label}:")
    print(f"  d_log_gap → Pearson: {pearson_r:.4f}  Spearman: {spearman_r:.4f}")

# ----------------------------------------
# Step 5: check correlation among the various Zone deltas
# Confirm whether they're independent (high correlation would mean the same mechanism)
# ----------------------------------------
print("\n========== Correlation Matrix Among Zone Deltas ==========")
print("(confirm whether each Zone is independent, avoiding multicollinearity)")
zone_corr_matrix = corr_df[zone_deltas].corr(method="spearman").round(3)
print(zone_corr_matrix.to_string())

print("\n✅ New tables created:")
print("  - corr_df      (analysis master table, with Zone delta + weekly)")
print("  - corr_results (correlation summary table)")

分析样本量: 14,217

========== 绝对增长（late - early weekly） ==========
Zone                       Pearson_r   Spearman_r        显著性
-----------------------------------------------------------------
Zone1_weekly                  0.2516       0.3172        ***
Zone5_cliff                  -0.1308      -0.1978        ***
Zone4_danger                 -0.0722      -0.1136        ***
Zone3_warning                -0.0715      -0.0888        ***
Zone2_biweekly               -0.0445      -0.0317        ***

========== 相对增长（log scale） ==========
Zone                       Pearson_r   Spearman_r        显著性
-----------------------------------------------------------------
Zone1_weekly                  0.3111       0.3295        ***
Zone5_cliff                  -0.2294      -0.2444        ***
Zone4_danger                 -0.1060      -0.1175        ***
Zone3_warning                -0.0814      -0.0773        ***
Zone2_biweekly                0.0037       0.0081         ns

========== 对比：原来的 d_log_gap vs 各 Zone delta ==========
（验证 Zone 分析是否比整体 gap 指标更精确）

绝对增长（late - early weekly）:
  d_log_gap → Pearson: -0.4678  Spearman: -0.4848

相对增长（log scale）:
  d_log_gap → Pearson: -0.5377  Spearman: -0.5244

========== Zone delta 之间的相关性矩阵 ==========
（确认各 Zone 是否独立，避免多重共线性）
                      delta_Zone1_weekly  delta_Zone2_biweekly  delta_Zone3_warning  delta_Zone4_danger  delta_Zone5_cliff
delta_Zone1_weekly                 1.000                -0.473               -0.262              -0.169             -0.227
delta_Zone2_biweekly              -0.473                 1.000               -0.179              -0.129             -0.270
delta_Zone3_warning               -0.262                -0.179                1.000              -0.053             -0.144
delta_Zone4_danger                -0.169                -0.129               -0.053               1.000             -0.062
delta_Zone5_cliff                 -0.227                -0.270               -0.144              -0.062              1.000

✅ New tables created:
  - corr_df      (分析主表，含 Zone delta + weekly)
  - corr_results (相关性汇总表)

In [95]:
# ============================================================
# Gap Zone × Weekly upgrade correlation analysis
# Angle 2: Uplift Curve
# Focus on Zone1 and Zone5
# Core question: is there a monotonic relationship between Zone1/Zone5 change magnitude and weekly growth?
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Step 1：Zone1 Uplift Curve
# Split into Q1-Q5 by delta_Zone1
# Check whether weekly growth rises monotonically across buckets
# ----------------------------------------
df_z1 = corr_df[
    ["user_id", "delta_Zone1_weekly", "delta_weekly", "d_log_weekly"]
].dropna().copy()

df_z1["bucket"] = pd.qcut(
    df_z1["delta_Zone1_weekly"],
    q=5,
    labels=["Q1", "Q2", "Q3", "Q4", "Q5"],
    duplicates="drop"
)

zone1_uplift = (
    df_z1.groupby("bucket")
    .agg(
        users=("user_id", "count"),
        delta_zone1_mean=("delta_Zone1_weekly", "mean"),
        delta_zone1_median=("delta_Zone1_weekly", "median"),
        delta_weekly_mean=("delta_weekly", "mean"),
        delta_weekly_median=("delta_weekly", "median"),
        d_log_weekly_mean=("d_log_weekly", "mean"),
        d_log_weekly_median=("d_log_weekly", "median"),
    )
    .reset_index()
)

print("========== Zone1 Uplift Curve ==========")
print("(Q1 = Zone1 increased least/decreased, Q5 = Zone1 increased most)")
print("(expected: weekly rises monotonically from Q1→Q5)")
print(zone1_uplift.round(4).to_string(index=False))

# Marginal elasticity: slope across the Q2-Q4 range
# How much extra weekly growth per 1% increase in Zone1 share?
q2q4_z1 = df_z1[df_z1["bucket"].isin(["Q2", "Q3", "Q4"])]
slope_z1, intercept_z1, r_z1, _, _ = stats.linregress(
    q2q4_z1["delta_Zone1_weekly"],
    q2q4_z1["d_log_weekly"]
)
print(f"\nMarginal elasticity (Q2-Q4):")
print(f"  Every +0.1 Zone1 share → d_log_weekly +{slope_z1*0.1:.4f}")
print(f"  R² = {r_z1**2:.4f}")

# ----------------------------------------
# Step 2：Zone5 Uplift Curve
# Split into Q1-Q5 by delta_Zone5
# Q1 = Zone5 decreased the most (best), Q5 = Zone5 increased the most (worst)
# Expectation: weekly declines monotonically from Q1→Q5
# ----------------------------------------
# ----------------------------------------
# Fix for Step 2: Zone5 Uplift Curve
# Use rank-based bucketing instead of qcut, to avoid duplicate-value issues
# ----------------------------------------
df_z5 = corr_df[
    ["user_id", "delta_Zone5_cliff", "delta_weekly", "d_log_weekly"]
].dropna().copy()

# Use the rank method for bucketing, to avoid qcut errors caused by duplicate values
df_z5["bucket"] = pd.qcut(
    df_z5["delta_Zone5_cliff"].rank(method="first"),
    q=5,
    labels=["Q1", "Q2", "Q3", "Q4", "Q5"]
)

zone5_uplift = (
    df_z5.groupby("bucket", observed=True)
    .agg(
        users=("user_id", "count"),
        delta_zone5_mean=("delta_Zone5_cliff", "mean"),
        delta_zone5_median=("delta_Zone5_cliff", "median"),
        delta_weekly_mean=("delta_weekly", "mean"),
        delta_weekly_median=("delta_weekly", "median"),
        d_log_weekly_mean=("d_log_weekly", "mean"),
        d_log_weekly_median=("d_log_weekly", "median"),
    )
    .reset_index()
)

print("\n========== Zone5 Uplift Curve ==========")
print("(Q1 = Zone5 decreased most, Q5 = Zone5 increased most)")
print("(expected: weekly declines monotonically from Q1→Q5)")
print(zone5_uplift.round(4).to_string(index=False))

# Marginal elasticity: slope across the Q2-Q4 range
q2q4_z5 = df_z5[df_z5["bucket"].isin(["Q2", "Q3", "Q4"])]
slope_z5, intercept_z5, r_z5, _, _ = stats.linregress(
    q2q4_z5["delta_Zone5_cliff"],
    q2q4_z5["d_log_weekly"]
)
print(f"\nMarginal elasticity (Q2-Q4):")
print(f"  Every -0.1 Zone5 share → d_log_weekly +{-slope_z5*0.1:.4f}")
print(f"  R² = {r_z5**2:.4f}")

# ----------------------------------------
# Step 3: 2×2 analysis
# Zone1 high/low × Zone5 high/low
# View weekly growth under the four combinations
# ----------------------------------------
df_2x2 = corr_df[
    ["user_id", "delta_Zone1_weekly",
     "delta_Zone5_cliff", "delta_weekly", "d_log_weekly"]
].dropna().copy()

# Split by median
z1_median = df_2x2["delta_Zone1_weekly"].median()
z5_median = df_2x2["delta_Zone5_cliff"].median()

df_2x2["z1_group"] = np.where(
    df_2x2["delta_Zone1_weekly"] >= z1_median, "Zone1_high", "Zone1_low"
)
df_2x2["z5_group"] = np.where(
    df_2x2["delta_Zone5_cliff"] <= z5_median, "Zone5_low", "Zone5_high"
)
# Zone5_low = Zone5 decreased a lot (good), Zone5_high = Zone5 decreased little (bad)

df_2x2["group"] = df_2x2["z1_group"] + " × " + df_2x2["z5_group"]

result_2x2 = (
    df_2x2.groupby("group")
    .agg(
        users=("user_id", "count"),
        delta_weekly_mean=("delta_weekly", "mean"),
        delta_weekly_median=("delta_weekly", "median"),
        d_log_weekly_mean=("d_log_weekly", "mean"),
        d_log_weekly_median=("d_log_weekly", "median"),
    )
    .reset_index()
    .sort_values("d_log_weekly_mean", ascending=False)
)

print("\n========== 2×2 Analysis: Zone1 × Zone5 ==========")
print("(Zone1_high = Zone1 increased a lot, Zone5_low = Zone5 decreased a lot)")
print("(expected: Zone1_high × Zone5_low is the strongest growth combination)")
print(result_2x2.round(4).to_string(index=False))

# ----------------------------------------
# Step 4: incremental analysis
# How much does each of Zone1 and Zone5 independently contribute?
# ----------------------------------------
# ----------------------------------------
# Fix for Step 4: incremental analysis
# Pull values from result_2x2, not from df_2x2
# ----------------------------------------

def get_weekly(group_name):
    row = result_2x2[result_2x2["group"] == group_name]
    if len(row) > 0:
        return row["d_log_weekly_mean"].values[0]
    return np.nan

both    = get_weekly("Zone1_high × Zone5_low")
z1_only = get_weekly("Zone1_high × Zone5_high")
z5_only = get_weekly("Zone1_low × Zone5_low")
neither = get_weekly("Zone1_low × Zone5_high")

print("\n========== Incremental Analysis ==========")
print(f"Both    (Zone1↑ + Zone5↓) : {both:.4f}")
print(f"Z1 only (Zone1↑ only)     : {z1_only:.4f}")
print(f"Z5 only (Zone5↓ only)     : {z5_only:.4f}")
print(f"Neither                   : {neither:.4f}")
print(f"\nIncremental Zone1 (given Zone5↓): {both - z5_only:.4f}")
print(f"Incremental Zone5 (given Zone1↑): {both - z1_only:.4f}")

print("\n✅ New tables created:")
print("  - zone1_uplift  (Zone1 uplift curve)")
print("  - zone5_uplift  (Zone5 uplift curve)")
print("  - result_2x2    (2×2 analysis results)")

========== Zone1 Uplift Curve ==========
（Q1 = Zone1 增加最少/减少，Q5 = Zone1 增加最多）
（预期：Q1→Q5 weekly 单调上升）
bucket  users  delta_zone1_mean  delta_zone1_median  delta_weekly_mean  delta_weekly_median  d_log_weekly_mean  d_log_weekly_median
    Q1   2844           -0.1728             -0.1333             5.3179               4.3971             0.5726               0.5044
    Q2   2856            0.0425              0.0417             5.6941               4.9000             0.6168               0.5570
    Q3   2843            0.1731              0.1667             6.8091               5.6389             0.7094               0.6563
    Q4   2831            0.3001              0.3000             7.3219               6.3000             0.7876               0.7538
    Q5   2843            0.5472              0.5000             9.5277               7.8558             0.9707               0.9496

边际弹性（Q2-Q4）：
  每 +0.1 Zone1 share → d_log_weekly +0.0662
  R² = 0.0329

========== Zone5 Uplift Curve ==========
（Q1 = Zone5 减少最多，Q5 = Zone5 增加最多）
（预期：Q1→Q5 weekly 单调下降）
bucket  users  delta_zone5_mean  delta_zone5_median  delta_weekly_mean  delta_weekly_median  d_log_weekly_mean  d_log_weekly_median
    Q1   2844           -0.4152             -0.3333             8.2263               6.9864             0.9193               0.9078
    Q2   2843           -0.1164             -0.1111             7.2109               6.1250             0.7592               0.7134
    Q3   2843           -0.0128              0.0000             6.6088               5.4444             0.6757               0.6162
    Q4   2843            0.0000              0.0000             6.8398               5.5152             0.6852               0.6190
    Q5   2844            0.1400              0.1000             5.7773               4.8333             0.6169               0.5596

边际弹性（Q2-Q4）：
  每 -0.1 Zone5 share → d_log_weekly +0.0803
  R² = 0.0124

========== 2×2 分析：Zone1 × Zone5 ==========
（Zone1_high = Zone1 增加多，Zone5_low = Zone5 减少多）
（预期：Zone1_high × Zone5_low 是最强增长组合）
                  group  users  delta_weekly_mean  delta_weekly_median  d_log_weekly_mean  d_log_weekly_median
 Zone1_high × Zone5_low   6390             8.2792               7.0000             0.8629               0.8318
Zone1_high × Zone5_high    779             6.5377               5.5491             0.7085               0.6665
  Zone1_low × Zone5_low   5661             5.9573               5.0000             0.6321               0.5605
 Zone1_low × Zone5_high   1387             4.9312               4.1591             0.5421               0.4700

========== 增量分析 ==========
Both    (Zone1↑ + Zone5↓) : 0.8629
Z1 only (Zone1↑ only)     : 0.7085
Z5 only (Zone5↓ only)     : 0.6321
Neither                   : 0.5421

增量 Zone1（given Zone5↓）: 0.2308
增量 Zone5（given Zone1↑）: 0.1544

✅ New tables created:
  - zone1_uplift  (Zone1 uplift curve)
  - zone5_uplift  (Zone5 uplift curve)
  - result_2x2    (2×2 分析结果)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/4007760242.py:29: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_z1.groupby("bucket")

In [96]:
# ============================================================
# Re-validate: correlation between Basket and Gap
# Using the full analysis_mid_user_master data
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Step 1: prepare data
# Using metrics from analysis_mid_user_master
# ----------------------------------------
df_corr = analysis_mid_user_master[[
    "user_id",
    "path_9",
    # basket metric
    "delta_n_unique_products",  # basket change (absolute)
    "d_log_basket",             # basket change (relative)
    "delta_basket_med",         # basket median change
    # gap metric
    "d_log_gap",                # gap change (relative, negative=improvement)
    "delta_pct_gap30",          # Zone5 change
    "delta_gap_std",            # gap stability change
    # weekly outcome
    "delta_weekly",
    "d_log_weekly",
]].copy()

# Only look at Mid→High users
df_mh = df_corr[df_corr["path_9"] == "Mid Up to High"].copy()
print(f"Mid→High user count: {len(df_mh):,}")

# ----------------------------------------
# Step 2: Basket × Gap correlation
# Core question: are changes in basket and gap negatively correlated?
# ----------------------------------------
basket_metrics = {
    "delta_n_unique_products" : "Basket absolute change (SKU count)",
    "d_log_basket"            : "Basket relative change (log)",
}

gap_metrics = {
    "d_log_gap"        : "Gap relative change (log, negative=improvement)",
    "delta_pct_gap30"  : "Zone5 share change",
    "delta_gap_std"    : "Gap stability change",
}

print("\n========== Basket × Gap Correlation ==========")
print(f"{'Basket Metric':<30} {'Gap Metric':<25} {'Pearson':>8} {'Spearman':>10} {'Sig':>8}")
print("-" * 90)

corr_results = []
for b_col, b_label in basket_metrics.items():
    for g_col, g_label in gap_metrics.items():
        valid = df_mh[[b_col, g_col]].dropna()
        pearson_r,  pearson_p  = stats.pearsonr(valid[b_col],  valid[g_col])
        spearman_r, spearman_p = stats.spearmanr(valid[b_col], valid[g_col])
        sig = "***" if spearman_p < 0.001 else (
              "**"  if spearman_p < 0.01  else (
              "*"   if spearman_p < 0.05  else "ns"))

        corr_results.append({
            "basket_metric" : b_col,
            "gap_metric"    : g_col,
            "pearson_r"     : round(pearson_r,  4),
            "spearman_r"    : round(spearman_r, 4),
            "sig"           : sig,
        })

        print(f"{b_col:<30} {g_col:<25} {pearson_r:>8.4f} {spearman_r:>10.4f} {sig:>8}")

# ----------------------------------------
# Step 3: bucketed validation
# basket high/low → is gap improvement systematically different?
# ----------------------------------------
print("\n========== Bucketed Validation: Basket Change → Gap Improvement ==========")
print("(basket split into Q1-Q5 by delta_n_unique_products)")
print("(check whether d_log_gap changes monotonically across buckets)")

df_bucket = df_mh[
    ["user_id", "delta_n_unique_products", "d_log_gap",
     "delta_pct_gap30", "d_log_weekly"]
].dropna().copy()

df_bucket["basket_bucket"] = pd.qcut(
    df_bucket["delta_n_unique_products"].rank(method="first"),
    q=5,
    labels=["Q1", "Q2", "Q3", "Q4", "Q5"]
)

bucket_summary = (
    df_bucket.groupby("basket_bucket", observed=True)
    .agg(
        users=("user_id", "count"),
        delta_unique_mean=("delta_n_unique_products", "mean"),
        d_log_gap_mean=("d_log_gap", "mean"),
        d_log_gap_median=("d_log_gap", "median"),
        delta_pct_gap30_mean=("delta_pct_gap30", "mean"),
        d_log_weekly_mean=("d_log_weekly", "mean"),
    )
    .reset_index()
)

print(bucket_summary.round(4).to_string(index=False))

# ----------------------------------------
# Step 4: 2×2 analysis
# basket high/low × gap improvement high/low
# View user distribution and weekly growth for the four combinations
# ----------------------------------------
print("\n========== 2×2: Basket × Gap Improvement ==========")

df_2x2 = df_mh[[
    "user_id", "delta_n_unique_products",
    "d_log_gap", "d_log_weekly", "delta_weekly"
]].dropna().copy()

# Split by median
basket_median = df_2x2["delta_n_unique_products"].median()
gap_median    = df_2x2["d_log_gap"].median()

df_2x2["basket_group"] = np.where(
    df_2x2["delta_n_unique_products"] >= basket_median,
    "basket_high", "basket_low"
)
# d_log_gap negative = gap improvement, so <= median means more improvement
df_2x2["gap_group"] = np.where(
    df_2x2["d_log_gap"] <= gap_median,
    "gap_improve_high", "gap_improve_low"
)

df_2x2["group"] = df_2x2["basket_group"] + " × " + df_2x2["gap_group"]

result_2x2 = (
    df_2x2.groupby("group")
    .agg(
        users=("user_id", "count"),
        share=("user_id", lambda x: len(x)/len(df_2x2)),
        delta_weekly_mean=("delta_weekly", "mean"),
        d_log_weekly_mean=("d_log_weekly", "mean"),
        d_log_weekly_median=("d_log_weekly", "median"),
    )
    .reset_index()
    .sort_values("d_log_weekly_mean", ascending=False)
)

print(result_2x2.round(4).to_string(index=False))

# Incremental analysis
def get_val(group_name):
    row = result_2x2[result_2x2["group"] == group_name]
    return row["d_log_weekly_mean"].values[0] if len(row) > 0 else np.nan

both    = get_val("basket_high × gap_improve_high")
b_only  = get_val("basket_high × gap_improve_low")
g_only  = get_val("basket_low × gap_improve_high")
neither = get_val("basket_low × gap_improve_low")

print("\n========== Incremental Analysis ==========")
print(f"Both    (basket↑ + gap↑) : {both:.4f}")
print(f"Basket  only             : {b_only:.4f}")
print(f"Gap     only             : {g_only:.4f}")
print(f"Neither                  : {neither:.4f}")
print(f"\nIncremental Basket (given gap↑): {both - g_only:.4f}")
print(f"Incremental Gap    (given basket↑): {both - b_only:.4f}")

print("\n✅ New tables created:")
print("  - df_mh         (Mid→High analysis master table)")
print("  - df_bucket     (basket bucket table)")
print("  - result_2x2    (2×2 analysis results)")

Mid→High 用户数: 14,217

========== Basket × Gap 相关性 ==========
Basket 指标                      Gap 指标                     Pearson   Spearman      显著性
------------------------------------------------------------------------------------------
delta_n_unique_products        d_log_gap                   0.3355     0.3248      ***
delta_n_unique_products        delta_pct_gap30             0.0764     0.0385      ***
delta_n_unique_products        delta_gap_std               0.0614     0.0515      ***
d_log_basket                   d_log_gap                   0.3806     0.3592      ***
d_log_basket                   delta_pct_gap30             0.1055     0.0814      ***
d_log_basket                   delta_gap_std               0.0539     0.0478      ***

========== 分桶验证：Basket 变化 → Gap 改善 ==========
（basket 按 delta_n_unique_products 分 Q1-Q5）
（看每桶的 d_log_gap 是否单调变化）
basket_bucket  users  delta_unique_mean  d_log_gap_mean  d_log_gap_median  delta_pct_gap30_mean  d_log_weekly_mean
           Q1   2844            -3.6693         -0.7664           -0.6931               -0.1122             0.6407
           Q2   2843             0.2058         -0.5124           -0.4595               -0.0515             0.6280
           Q3   2843             1.9555         -0.4143           -0.3567               -0.0530             0.6828
           Q4   2843             4.0304         -0.3561           -0.3185               -0.0591             0.7619
           Q5   2844             9.3272         -0.2629           -0.2231               -0.0716             0.9428

========== 2×2：Basket × Gap 改善 ==========
                         group  users  share  delta_weekly_mean  d_log_weekly_mean  d_log_weekly_median
basket_high × gap_improve_high   3040 0.2138            10.4669             1.0753               1.0442
 basket_low × gap_improve_high   4078 0.2868             7.6159             0.8032               0.7603
 basket_high × gap_improve_low   4579 0.3221             5.9424             0.6355               0.5878
  basket_low × gap_improve_low   2520 0.1773             3.3625             0.3738               0.3483

========== 增量分析 ==========
Both    (basket↑ + gap↑) : 1.0753
Basket  only             : 0.6355
Gap     only             : 0.8032
Neither                  : 0.3738

增量 Basket（given gap↑）: 0.2721
增量 Gap   （given basket↑）: 0.4398

✅ New tables created:
  - df_mh         (Mid→High 分析主表)
  - df_bucket     (basket 分桶表)
  - result_2x2    (2×2 分析结果)

In [97]:
# Finally, compare Mid → High vs. Mid Stay users

# ============================================================
# Full comparison analysis: Mid→High vs. Mid Stay
# Purpose: verify whether upgrading users' behavior is systematically different from staying users
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Step 1: prepare the two user groups
# ----------------------------------------
df_mh = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

df_ms = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Stay"
].copy()

print(f"Mid→High user count: {len(df_mh):,}")
print(f"Mid Stay  user count: {len(df_ms):,}")

# ----------------------------------------
# Step 2: add in Zone delta
# Merge Zone info in from user_zone_wide
# ----------------------------------------
zone_cols = [
    "user_id",
    "delta_Zone1_weekly",
    "delta_Zone5_cliff",
]

df_mh = df_mh.merge(user_zone_wide[zone_cols], on="user_id", how="left")
df_ms = df_ms.merge(user_zone_wide[zone_cols], on="user_id", how="left")

print(f"\nMid→High after Zone merge: {len(df_mh):,}")
print(f"Mid Stay after Zone merge:  {len(df_ms):,}")

# ----------------------------------------
# Step 3: define the full comparison metrics
# ----------------------------------------
metrics = {
    # Outcome
    "d_log_weekly"              : ("Outcome", "overall activity change (log)"),
    "delta_weekly"              : ("Outcome", "absolute growth (weekly items)"),
    # Basket
    "delta_n_unique_products"   : ("Basket", "SKU expansion"),
    "delta_basket_med"          : ("Basket", "basket size change"),
    "delta_n_unique_departments": ("Basket", "category expansion"),
    # Gap
    "d_log_gap"                 : ("Gap", "overall frequency improvement (log, negative=improvement)"),
    "delta_pct_gap30"           : ("Gap", "Zone5 change (pct_gap30)"),
    "delta_gap_std"             : ("Gap", "cadence stability change"),
    # Zone
    "delta_Zone1_weekly"        : ("Zone", "weekly cadence formation (Zone1↑)"),
    "delta_Zone5_cliff"         : ("Zone", "cliff improvement (Zone5↓)"),
    # Behavioral structure
    "delta_reorder_ratio"       : ("Behavioral Structure", "reorder behavior change"),
    # User maturity
    "n_orders_half_early"       : ("User Structure", "early-stage order count (maturity)"),
}

# ----------------------------------------
# Step 4: compute comparison statistics for each metric
# mean / median + t-test + Cohen's d
# ----------------------------------------
results = []

for col, (category, description) in metrics.items():
    mh_vals = df_mh[col].dropna()
    ms_vals = df_ms[col].dropna()

    # Statistics
    mh_mean   = mh_vals.mean()
    ms_mean   = ms_vals.mean()
    mh_median = mh_vals.median()
    ms_median = ms_vals.median()
    diff_mean = mh_mean - ms_mean

    # t-test
    t_stat, p_val = stats.ttest_ind(mh_vals, ms_vals, equal_var=False)

    # Cohen's d (effect size)
    pooled_std = np.sqrt(
        (mh_vals.std()**2 + ms_vals.std()**2) / 2
    )
    cohens_d = diff_mean / pooled_std if pooled_std > 0 else np.nan

    # Significance
    sig = "***" if p_val < 0.001 else (
          "**"  if p_val < 0.01  else (
          "*"   if p_val < 0.05  else "ns"))

    results.append({
        "category"    : category,
        "metric"      : col,
        "description" : description,
        "mh_mean"     : round(mh_mean,   4),
        "ms_mean"     : round(ms_mean,   4),
        "mh_median"   : round(mh_median, 4),
        "ms_median"   : round(ms_median, 4),
        "diff_mean"   : round(diff_mean, 4),
        "cohens_d"    : round(cohens_d,  4),
        "p_value"     : round(p_val,     4),
        "sig"         : sig,
        "n_mh"        : len(mh_vals),
        "n_ms"        : len(ms_vals),
    })

results_df = pd.DataFrame(results)

# ----------------------------------------
# Step 5: output results by category
# ----------------------------------------
print("\n" + "="*90)
print("Full comparison: Mid→High vs. Mid Stay")
print("="*90)
print(f"{'Category':<10} {'Metric':<30} {'MH Mean':>9} {'MS Mean':>9} "
      f"{'Diff':>8} {'Cohen_d':>9} {'Sig':>6}")
print("-"*90)

current_category = ""
for _, row in results_df.iterrows():
    if row["category"] != current_category:
        current_category = row["category"]
        print(f"\n【{current_category}】")

    direction = "↑" if row["diff_mean"] > 0 else "↓"
    print(f"  {row['metric']:<30} {row['mh_mean']:>9.4f} {row['ms_mean']:>9.4f} "
          f"{row['diff_mean']:>+8.4f} {row['cohens_d']:>9.4f} "
          f"{row['sig']:>4} {direction}")

# ----------------------------------------
# Step 6: median-based comparison
# ----------------------------------------
print("\n" + "="*90)
print("Median-based comparison (more robust)")
print("="*90)
print(f"{'Category':<10} {'Metric':<30} {'MH Median':>10} {'MS Median':>10} {'Diff':>8}")
print("-"*90)

current_category = ""
for _, row in results_df.iterrows():
    if row["category"] != current_category:
        current_category = row["category"]
        print(f"\n【{current_category}】")

    diff_median = row["mh_median"] - row["ms_median"]
    direction = "↑" if diff_median > 0 else "↓"
    print(f"  {row['metric']:<30} {row['mh_median']:>10.4f} {row['ms_median']:>10.4f} "
          f"{diff_median:>+8.4f} {direction}")

# ----------------------------------------
# Step 7: label distribution comparison (user structure)
# ----------------------------------------
print("\n" + "="*60)
print("[User Structure] Label Distribution Comparison")
print("="*60)

label_mh = (
    df_mh["label"].value_counts(normalize=True)
    .rename("Mid→High")
    .reset_index()
)
label_ms = (
    df_ms["label"].value_counts(normalize=True)
    .rename("Mid Stay")
    .reset_index()
)

label_compare = label_mh.merge(label_ms, on="label", how="outer").fillna(0)
label_compare["diff"] = label_compare["Mid→High"] - label_compare["Mid Stay"]
label_compare = label_compare.sort_values("Mid→High", ascending=False)

print(f"{'Label':<15} {'Mid→High':>10} {'Mid Stay':>10} {'Diff':>8}")
print("-"*50)
for _, row in label_compare.iterrows():
    direction = "↑" if row["diff"] > 0 else "↓"
    print(f"{row['label']:<15} {row['Mid→High']:>9.1%} "
          f"{row['Mid Stay']:>9.1%} {row['diff']:>+7.1%} {direction}")

# ----------------------------------------
# Step 8: effect-size interpretation
# ----------------------------------------
print("\n" + "="*60)
print("Effect Size Interpretation (Cohen's d)")
print("="*60)
print("< 0.2  : negligible difference")
print("0.2~0.5: small effect")
print("0.5~0.8: medium effect")
print("> 0.8  : large effect")
print()

significant = results_df[results_df["sig"] != "ns"].sort_values(
    "cohens_d", key=abs, ascending=False
)
print("Metrics with the largest effect size (Top 5):")
print(significant[["category", "metric", "cohens_d", "sig"]]
      .head(5).to_string(index=False))

print("\n✅ New tables created:")
print("  - results_df    (full comparison statistics table)")
print("  - label_compare (label distribution comparison)")

Mid→High 用户数: 14,217
Mid Stay  用户数: 43,780

Zone merge 后 Mid→High: 14,217
Zone merge 后 Mid Stay:  43,780

==========================================================================================
Mid→High vs Mid Stay 完整对比
==========================================================================================
类别         指标                               MH Mean   MS Mean       差值   Cohen_d    显著性
------------------------------------------------------------------------------------------

【结果】
  d_log_weekly                      0.7313   -0.0174  +0.7487    1.7484  *** ↑
  delta_weekly                      6.9326   -0.1354  +7.0680    1.5899  *** ↑

【Basket】
  delta_n_unique_products           2.3700    0.0320  +2.3380    0.5287  *** ↑
  delta_basket_med                  2.3700    0.0320  +2.3380    0.5287  *** ↑
  delta_n_unique_departments        0.6439    0.0083  +0.6357    0.4121  *** ↑

【Gap】
  d_log_gap                        -0.4624    0.0361  -0.4986   -0.9853  *** ↓
  delta_pct_gap30                  -0.0695    0.0347  -0.1042   -0.4478  *** ↓
  delta_gap_std                    -1.2829    0.5228  -1.8057   -0.4173  *** ↓

【Zone】
  delta_Zone1_weekly                0.1778       nan     +nan       nan   ns ↓
  delta_Zone5_cliff                -0.0809       nan     +nan       nan   ns ↓

【行为结构】
  delta_reorder_ratio               0.1439    0.1708  -0.0269   -0.1369  *** ↓

【用户结构】
  n_orders_half_early              10.5339    8.1118  +2.4221    0.3238  *** ↑

==========================================================================================
Median 版本对比（更稳健）
==========================================================================================
类别         指标                              MH Median  MS Median       差值
------------------------------------------------------------------------------------------

【结果】
  d_log_weekly                       0.6872    -0.0085  +0.6957 ↑
  delta_weekly                       5.8042    -0.0443  +5.8485 ↑

【Basket】
  delta_n_unique_products            2.0000     0.0000  +2.0000 ↑
  delta_basket_med                   2.0000     0.0000  +2.0000 ↑
  delta_n_unique_departments         0.5000     0.0000  +0.5000 ↑

【Gap】
  d_log_gap                         -0.4055     0.0000  -0.4055 ↓
  delta_pct_gap30                    0.0000     0.0000  +0.0000 ↓
  delta_gap_std                     -1.3734     0.3453  -1.7187 ↓

【Zone】
  delta_Zone1_weekly                 0.1667        nan     +nan ↓
  delta_Zone5_cliff                  0.0000        nan     +nan ↓

【行为结构】
  delta_reorder_ratio                0.1523     0.1693  -0.0170 ↓

【用户结构】
  n_orders_half_early                8.0000     6.0000  +2.0000 ↑

============================================================
【用户结构】Label 分布对比
============================================================
Label             Mid→High   Mid Stay       差值
--------------------------------------------------
immature            36.0%     46.8%  -10.8% ↓
stepper             32.5%     21.0%  +11.5% ↑
drifter             26.8%     21.1%   +5.8% ↑
oscillator           2.9%      6.2%   -3.3% ↓
mixed                1.8%      5.0%   -3.2% ↓

============================================================
效应量解读（Cohen's d）
============================================================
< 0.2  : 微小差异
0.2~0.5: 小效应
0.5~0.8: 中效应
> 0.8  : 大效应

效应量最大的指标（Top 5）：
category                  metric  cohens_d sig
      结果            d_log_weekly    1.7484 ***
      结果            delta_weekly    1.5899 ***
     Gap               d_log_gap   -0.9853 ***
  Basket delta_n_unique_products    0.5287 ***
  Basket        delta_basket_med    0.5287 ***

✅ New tables created:
  - results_df    (完整对比统计表)
  - label_compare (Label 分布对比)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/scipy/_lib/deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)

In [98]:
# ============================================================
# Add Zone data for Mid Stay users
# Then do the Zone comparison, Mid→High vs. Mid Stay
# ============================================================

# ----------------------------------------
# Step 1: prepare order data for Mid Stay users
# ----------------------------------------
ms_users = (
    analysis_mid_user_master[
        analysis_mid_user_master["path_9"] == "Mid Stay"
    ][["user_id"]].copy()
)
print(f"Mid Stay users: {len(ms_users):,}")

# Combine both user groups, process together
all_users = pd.concat([
    mh_users.assign(path="Mid→High"),
    ms_users.assign(path="Mid Stay")
], ignore_index=True)

print(f"Total users: {len(all_users):,}")

# ----------------------------------------
# Step 2: get all users' orders + early/late labels
# ----------------------------------------

# Compute each user's total order count
all_n_orders = (
    orders_enriched2
    .groupby("user_id")["order_number"]
    .max()
    .reset_index()
    .rename(columns={"order_number": "n_orders"})
)

# Filter to the orders of both groups
all_orders = (
    orders_enriched2
    .merge(all_users, on="user_id", how="inner")
    .merge(all_n_orders, on="user_id", how="left")
)

# Tag early/late
all_orders["pos"] = all_orders["order_number"] / all_orders["n_orders"]
all_orders["half"] = np.where(all_orders["pos"] <= 0.5, "early", "late")

print(f"\nTotal orders: {len(all_orders):,}")
print(all_orders.groupby("path")["order_id"].count())

# ----------------------------------------
# Step 3: tag Gap Zone
# ----------------------------------------
all_orders["gap_zone"] = all_orders["gap_days_adj"].apply(assign_gap_zone)
all_orders_gap = all_orders.dropna(subset=["gap_zone"]).copy()

print(f"\nAfter dropping first orders: {len(all_orders_gap):,}")

# ----------------------------------------
# Step 4: compute each user's early/late Zone share
# ----------------------------------------
zone_order = [
    "Zone1_weekly",
    "Zone2_biweekly",
    "Zone3_warning",
    "Zone4_danger",
    "Zone5_cliff"
]

# Order count per user × half × zone
all_user_zone = (
    all_orders_gap
    .groupby(["user_id", "path", "half", "gap_zone"])
    .size()
    .reset_index(name="order_count")
)

# Total order count per user × half
all_half_total = (
    all_orders_gap
    .groupby(["user_id", "half"])
    .size()
    .reset_index(name="total_orders")
)

# Compute share
all_user_zone = all_user_zone.merge(
    all_half_total, on=["user_id", "half"], how="left"
)
all_user_zone["zone_share"] = (
    all_user_zone["order_count"] / all_user_zone["total_orders"]
)

# ----------------------------------------
# Step 5: pivot to wide, compute delta
# ----------------------------------------
all_zone_wide = all_user_zone.pivot_table(
    index=["user_id", "path"],
    columns=["half", "gap_zone"],
    values="zone_share",
    fill_value=0
).reset_index()

# Flatten column names
all_zone_wide.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in all_zone_wide.columns
]

# Compute delta for each Zone
for zone in zone_order:
    early_col = f"early_{zone}"
    late_col  = f"late_{zone}"
    delta_col = f"delta_{zone}"

    if early_col not in all_zone_wide.columns:
        all_zone_wide[early_col] = 0
    if late_col not in all_zone_wide.columns:
        all_zone_wide[late_col] = 0

    all_zone_wide[delta_col] = (
        all_zone_wide[late_col] - all_zone_wide[early_col]
    )

print(f"\nall_zone_wide shape: {all_zone_wide.shape}")

# ----------------------------------------
# Step 6: Zone comparison, Mid→High vs. Mid Stay
# ----------------------------------------
mh_zone = all_zone_wide[all_zone_wide["path"] == "Mid→High"]
ms_zone = all_zone_wide[all_zone_wide["path"] == "Mid Stay"]

print(f"\nMid→High zone users: {len(mh_zone):,}")
print(f"Mid Stay  zone users: {len(ms_zone):,}")

# ----------------------------------------
# Step 7: overall Zone distribution comparison
# Early vs. Late, separated by group
# ----------------------------------------
print("\n" + "="*80)
print("Zone Distribution Comparison: Early vs. Late (Overall Average)")
print("="*80)

for path, df_path in [("Mid→High", mh_zone), ("Mid Stay", ms_zone)]:
    print(f"\n--- {path} ---")
    print(f"{'Zone':<22} {'Early':>8} {'Late':>8} {'Delta':>8} {'Direction'}")
    print("-"*55)
    for zone in zone_order:
        early_col = f"early_{zone}"
        late_col  = f"late_{zone}"
        delta_col = f"delta_{zone}"
        e = df_path[early_col].mean()
        l = df_path[late_col].mean()
        d = df_path[delta_col].mean()
        direction = "↑" if d > 0.01 else ("↓" if d < -0.01 else "≈")
        print(f"{zone:<22} {e:>7.1%} {l:>7.1%} {d:>+7.1%}  {direction}")

# ----------------------------------------
# Step 8: delta comparison between the two groups (core)
# ----------------------------------------
print("\n" + "="*80)
print("Zone Delta Comparison: Mid→High vs. Mid Stay")
print("="*80)
print(f"{'Zone':<22} {'MH Delta':>10} {'MS Delta':>10} {'Diff':>8} "
      f"{'Cohen_d':>9} {'Sig':>6}")
print("-"*75)

zone_compare_results = []

for zone in zone_order:
    delta_col = f"delta_{zone}"

    mh_vals = mh_zone[delta_col].dropna()
    ms_vals = ms_zone[delta_col].dropna()

    mh_mean = mh_vals.mean()
    ms_mean = ms_vals.mean()
    diff    = mh_mean - ms_mean

    # t-test
    t_stat, p_val = stats.ttest_ind(mh_vals, ms_vals, equal_var=False)

    # Cohen's d
    pooled_std = np.sqrt(
        (mh_vals.std()**2 + ms_vals.std()**2) / 2
    )
    cohens_d = diff / pooled_std if pooled_std > 0 else np.nan

    sig = "***" if p_val < 0.001 else (
          "**"  if p_val < 0.01  else (
          "*"   if p_val < 0.05  else "ns"))

    direction = "↑" if diff > 0 else "↓"

    zone_compare_results.append({
        "zone"     : zone,
        "mh_mean"  : round(mh_mean,  4),
        "ms_mean"  : round(ms_mean,  4),
        "diff"     : round(diff,     4),
        "cohens_d" : round(cohens_d, 4),
        "sig"      : sig,
    })

    print(f"{zone:<22} {mh_mean:>10.4f} {ms_mean:>10.4f} {diff:>+8.4f} "
          f"{cohens_d:>9.4f} {sig:>4} {direction}")

# ----------------------------------------
# Step 9: median version
# ----------------------------------------
print("\n" + "="*80)
print("Zone Delta Comparison (Median Version)")
print("="*80)
print(f"{'Zone':<22} {'MH Median':>11} {'MS Median':>11} {'Diff':>8}")
print("-"*60)

for zone in zone_order:
    delta_col = f"delta_{zone}"
    mh_med = mh_zone[delta_col].median()
    ms_med = ms_zone[delta_col].median()
    diff   = mh_med - ms_med
    direction = "↑" if diff > 0 else "↓"
    print(f"{zone:<22} {mh_med:>11.4f} {ms_med:>11.4f} {diff:>+8.4f} {direction}")

# ----------------------------------------
# Step 10: early Zone distribution comparison
# Check whether the two groups start from the same baseline
# ----------------------------------------
print("\n" + "="*80)
print("Early Zone Distribution Comparison (Same Starting Point?)")
print("="*80)
print(f"{'Zone':<22} {'MH Early':>10} {'MS Early':>10} {'Diff':>8}")
print("-"*55)

for zone in zone_order:
    early_col = f"early_{zone}"
    mh_e = mh_zone[early_col].mean()
    ms_e = ms_zone[early_col].mean()
    diff = mh_e - ms_e
    direction = "↑" if diff > 0.01 else ("↓" if diff < -0.01 else "≈")
    print(f"{zone:<22} {mh_e:>9.1%} {ms_e:>9.1%} {diff:>+7.1%}  {direction}")

print("\n✅ New tables created:")
print("  - all_zone_wide      (all-user Zone wide table)")
print("  - mh_zone            (Mid→High Zone data)")
print("  - ms_zone            (Mid Stay Zone data)")
print("  - zone_compare_results (Zone comparison summary)")

Mid Stay users: 43,780
Total users: 57,997

Total orders: 1,038,163
path
Mid Stay    731588
Mid→High    306575
Name: order_id, dtype: int64

去掉第一单后: 1,038,163

all_zone_wide shape: (57997, 17)

Mid→High zone users: 14,217
Mid Stay  zone users: 43,780

================================================================================
Zone 分布对比：Early vs Late（整体平均）
================================================================================

--- Mid→High ---
Zone                      Early     Late    Delta 方向
-------------------------------------------------------
Zone1_weekly             37.3%   55.1%  +17.8%  ↑
Zone2_biweekly           27.3%   25.7%   -1.6%  ↓
Zone3_warning            13.2%    8.6%   -4.6%  ↓
Zone4_danger              7.5%    3.9%   -3.5%  ↓
Zone5_cliff              14.7%    6.7%   -8.1%  ↓

--- Mid Stay ---
Zone                      Early     Late    Delta 方向
-------------------------------------------------------
Zone1_weekly             30.7%   30.1%   -0.6%  ≈
Zone2_biweekly           28.1%   26.3%   -1.8%  ↓
Zone3_warning            14.9%   14.2%   -0.6%  ≈
Zone4_danger              9.0%    9.1%   +0.1%  ≈
Zone5_cliff              17.4%   20.4%   +3.0%  ↑

================================================================================
Zone Delta 对比：Mid→High vs Mid Stay
================================================================================
Zone                     MH Delta   MS Delta       差值   Cohen_d    显著性
---------------------------------------------------------------------------
Zone1_weekly               0.1778    -0.0062  +0.1840    0.7260  *** ↑
Zone2_biweekly            -0.0156    -0.0185  +0.0029    0.0106   ns ↑
Zone3_warning             -0.0458    -0.0064  -0.0394   -0.1819  *** ↓
Zone4_danger              -0.0355     0.0010  -0.0364   -0.2098  *** ↓
Zone5_cliff               -0.0809     0.0301  -0.1110   -0.4607  *** ↓

================================================================================
Zone Delta 对比（Median 版本）
================================================================================
Zone                     MH Median   MS Median       差值
------------------------------------------------------------
Zone1_weekly                0.1667      0.0000  +0.1667 ↑
Zone2_biweekly             -0.0157      0.0000  -0.0157 ↓
Zone3_warning              -0.0035      0.0000  -0.0035 ↓
Zone4_danger                0.0000      0.0000  +0.0000 ↓
Zone5_cliff                 0.0000      0.0000  +0.0000 ↓

================================================================================
Early Zone 分布对比（起点是否相同）
================================================================================
Zone                     MH Early   MS Early       差值
-------------------------------------------------------
Zone1_weekly               37.3%     30.7%   +6.6%  ↑
Zone2_biweekly             27.3%     28.1%   -0.8%  ≈
Zone3_warning              13.2%     14.9%   -1.7%  ↓
Zone4_danger                7.5%      9.0%   -1.5%  ↓
Zone5_cliff                14.7%     17.4%   -2.6%  ↓

✅ New tables created:
  - all_zone_wide      (所有用户 Zone 宽表)
  - mh_zone            (Mid→High Zone 数据)
  - ms_zone            (Mid Stay Zone 数据)
  - zone_compare_results (Zone 对比汇总)

In [99]:
# ============================================================
# Immature growth mechanism validation
# Core question: is Immature users' growth lifecycle-driven or behavior-change-driven?
# Three-layer validation framework
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Step 0: prepare data
# Only look at Immature users within the Mid→High path
# ----------------------------------------
df_imm = analysis_mid_user_master[
    (analysis_mid_user_master["path_9"] == "Mid Up to High") &
    (analysis_mid_user_master["label"] == "immature")
].copy()

df_mature = analysis_mid_user_master[
    (analysis_mid_user_master["path_9"] == "Mid Up to High") &
    (analysis_mid_user_master["label"].isin(["stepper", "drifter"]))
].copy()

print(f"Immature users (Mid→High): {len(df_imm):,}")
print(f"Mature users   (Mid→High): {len(df_mature):,}")

# ============================================================
# Layer 1: order count vs. growth
# If lifecycle-driven, more orders should mean stronger growth
# ============================================================
print("\n" + "="*70)
print("Layer 1: Order Count vs. Growth (lifecycle-driven validation)")
print("="*70)

# Bucket by order count
df_imm["order_bucket"] = pd.qcut(
    df_imm["n_orders_half_early"].rank(method="first"),
    q=5,
    labels=["Q1\n(fewest)", "Q2", "Q3", "Q4", "Q5\n(most)"]
)

layer1 = (
    df_imm.groupby("order_bucket", observed=True)
    .agg(
        users=("user_id", "count"),
        n_orders_mean=("n_orders_half_early", "mean"),
        d_log_weekly_mean=("d_log_weekly", "mean"),
        d_log_weekly_median=("d_log_weekly", "median"),
        delta_weekly_mean=("delta_weekly", "mean"),
    )
    .reset_index()
)

print("\nOrder-count bucket → weekly growth (expected: monotonic increase if lifecycle-driven)")
print(layer1.round(4).to_string(index=False))

# Correlation
valid = df_imm[["n_orders_half_early", "d_log_weekly"]].dropna()
pearson_r, pearson_p = stats.pearsonr(
    valid["n_orders_half_early"], valid["d_log_weekly"]
)
spearman_r, spearman_p = stats.spearmanr(
    valid["n_orders_half_early"], valid["d_log_weekly"]
)
print(f"\nOrder count vs. d_log_weekly correlation:")
print(f"  Pearson  = {pearson_r:.4f} (p={pearson_p:.4f})")
print(f"  Spearman = {spearman_r:.4f} (p={spearman_p:.4f})")

if abs(spearman_r) < 0.1:
    print("  → Very weak correlation, does not support lifecycle-driven")
elif abs(spearman_r) < 0.3:
    print("  → Weak correlation, insufficient evidence for lifecycle-driven")
else:
    print("  → Moderate-or-higher correlation, supports lifecycle-driven")

# ============================================================
# Layer 2: behavior change vs. growth
# If behavior-change-driven, basket/gap change should strongly correlate with growth
# ============================================================
print("\n" + "="*70)
print("Layer 2: Behavior Change vs. Growth (behavior-driven validation)")
print("="*70)

behavior_metrics = {
    "delta_n_unique_products" : "Basket SKU expansion",
    "d_log_basket"            : "Basket relative change",
    "d_log_gap"               : "Gap improvement",
    "delta_pct_gap30"         : "Zone5 change",
    "delta_gap_std"           : "cadence stability",
}

print(f"\n{'Metric':<30} {'Pearson':>8} {'Spearman':>10} {'Sig':>6} {'Interpretation'}")
print("-"*75)

behavior_corr_results = []
for col, label in behavior_metrics.items():
    valid = df_imm[[col, "d_log_weekly"]].dropna()
    p_r, p_p = stats.pearsonr(valid[col], valid["d_log_weekly"])
    s_r, s_p = stats.spearmanr(valid[col], valid["d_log_weekly"])
    sig = "***" if s_p < 0.001 else ("**" if s_p < 0.01 else
          ("*" if s_p < 0.05 else "ns"))

    if abs(s_r) > 0.3:
        interpretation = "strong correlation → behavior-driven"
    elif abs(s_r) > 0.15:
        interpretation = "moderate correlation"
    else:
        interpretation = "weak correlation"

    behavior_corr_results.append({
        "metric": col, "label": label,
        "spearman_r": s_r, "sig": sig
    })

    print(f"{label:<30} {p_r:>8.4f} {s_r:>10.4f} {sig:>6}  {interpretation}")

# Behavior-change bucketing (basket)
print("\n--- Basket Expansion Bucket → Weekly Growth ---")
df_imm["basket_bucket"] = pd.qcut(
    df_imm["delta_n_unique_products"].rank(method="first"),
    q=5, labels=["Q1", "Q2", "Q3", "Q4", "Q5"]
)
basket_layer2 = (
    df_imm.groupby("basket_bucket", observed=True)
    .agg(
        users=("user_id", "count"),
        delta_unique_mean=("delta_n_unique_products", "mean"),
        d_log_weekly_mean=("d_log_weekly", "mean"),
    )
    .reset_index()
)
print(basket_layer2.round(4).to_string(index=False))

# Behavior-change bucketing (gap)
print("\n--- Gap Improvement Bucket → Weekly Growth ---")
df_imm["gap_bucket"] = pd.qcut(
    df_imm["d_log_gap"].rank(method="first"),
    q=5, labels=["Q1", "Q2", "Q3", "Q4", "Q5"]
)
gap_layer2 = (
    df_imm.groupby("gap_bucket", observed=True)
    .agg(
        users=("user_id", "count"),
        d_log_gap_mean=("d_log_gap", "mean"),
        d_log_weekly_mean=("d_log_weekly", "mean"),
    )
    .reset_index()
)
print(gap_layer2.round(4).to_string(index=False))

# ============================================================
# Layer 3: Immature vs. Stepper/Drifter comparison
# Does the same behavior change produce the same growth effect?
# ============================================================
print("\n" + "="*70)
print("Layer 3: Immature vs. Mature Behavior-Driven Comparison")
print("(does the same basket/gap change produce the same growth effect in both groups?)")
print("="*70)

# Compute the behavior-change correlation separately for both groups
print(f"\n{'Metric':<30} {'Immature Spearman':>18} {'Mature Spearman':>16} {'Diff':>8}")
print("-"*75)

for col, label in behavior_metrics.items():
    # Immature
    v_imm = df_imm[[col, "d_log_weekly"]].dropna()
    s_imm, _ = stats.spearmanr(v_imm[col], v_imm["d_log_weekly"])

    # Mature
    v_mat = df_mature[[col, "d_log_weekly"]].dropna()
    s_mat, _ = stats.spearmanr(v_mat[col], v_mat["d_log_weekly"])

    diff = s_imm - s_mat
    direction = "≈ similar" if abs(diff) < 0.05 else (
                "Immature stronger" if diff > 0 else "Mature stronger")

    print(f"{label:<30} {s_imm:>18.4f} {s_mat:>16.4f} {diff:>+8.4f}  {direction}")

# ----------------------------------------
# Overall: behavior change vs. order count, which better explains Immature users' growth?
# ----------------------------------------
print("\n" + "="*70)
print("Overall Comparison: Which Factor Better Explains Immature Growth?")
print("="*70)

factors = {
    "n_orders_half_early"     : "order count (lifecycle proxy)",
    "delta_n_unique_products" : "Basket SKU expansion",
    "d_log_gap"               : "Gap improvement",
}

print(f"\n{'Factor':<35} {'Spearman':>10} {'Explanatory Power'}")
print("-"*60)

factor_results = []
for col, label in factors.items():
    valid = df_imm[[col, "d_log_weekly"]].dropna()
    s_r, s_p = stats.spearmanr(valid[col], valid["d_log_weekly"])
    sig = "***" if s_p < 0.001 else ("**" if s_p < 0.01 else
          ("*" if s_p < 0.05 else "ns"))

    factor_results.append({"factor": label, "spearman": s_r})
    print(f"{label:<35} {s_r:>10.4f} {sig}")

# Sort
factor_results_df = pd.DataFrame(factor_results).sort_values(
    "spearman", key=abs, ascending=False
)
print(f"\nExplanatory power ranking (by |Spearman|, descending):")
print(factor_results_df.to_string(index=False))

print("\n✅ New tables created:")
print("  - df_imm        (Immature Mid→High users)")
print("  - df_mature     (Mature Mid→High users)")
print("  - layer1        (Layer 1: order-count bucketing)")
print("  - basket_layer2 (Layer 2: basket bucketing)")
print("  - gap_layer2    (Layer 2: gap bucketing)")

Immature users (Mid→High): 5,119
Mature users   (Mid→High): 8,436

======================================================================
第一层：订单数 vs 增长（lifecycle driven 验证）
======================================================================

订单数分桶 → weekly 增长（预期：如果lifecycle driven则单调递增）
order_bucket  users  n_orders_mean  d_log_weekly_mean  d_log_weekly_median  delta_weekly_mean
    Q1\n(最少)   1024         2.0000             0.8941               0.8370             9.0271
          Q2   1024         2.5703             0.8353               0.7920             7.9387
          Q3   1023         3.3030             0.7960               0.7386             7.3672
          Q4   1024         4.1211             0.7171               0.7237             6.4360
    Q5\n(最多)   1024         5.1816             0.7242               0.6895             6.5835

订单数 vs d_log_weekly 相关性:
  Pearson  = -0.1414 (p=0.0000)
  Spearman = -0.1318 (p=0.0000)
  → 相关性弱，lifecycle driven 证据不足

======================================================================
第二层：行为变化 vs 增长（行为驱动验证）
======================================================================

指标                              Pearson   Spearman    显著性 解读
---------------------------------------------------------------------------
Basket SKU 扩张                    0.1516     0.1582    ***  中等相关
Basket 相对变化                      0.2177     0.1934    ***  中等相关
Gap 改善                          -0.5646    -0.5623    ***  强相关 → 行为驱动
Zone5 变化                        -0.1690    -0.1785    ***  中等相关
节奏稳定性                           -0.1719    -0.1905    ***  中等相关

--- Basket 扩张分桶 → weekly 增长 ---
basket_bucket  users  delta_unique_mean  d_log_weekly_mean
           Q1   1024            -5.7417             0.7214
           Q2   1024            -0.6479             0.7201
           Q3   1023             1.6569             0.7727
           Q4   1024             4.2666             0.8157
           Q5   1024            10.1816             0.9369

--- Gap 改善分桶 → weekly 增长 ---
gap_bucket  users  d_log_gap_mean  d_log_weekly_mean
        Q1   1024         -1.4588             1.2449
        Q2   1024         -0.8836             0.9198
        Q3   1023         -0.5698             0.7618
        Q4   1024         -0.2656             0.5984
        Q5   1024          0.2416             0.4419

======================================================================
第三层：Immature vs Mature 行为驱动对比
（同样的 basket/gap 变化，两组增长效果是否一样？）
======================================================================

指标                              Immature Spearman  Mature Spearman       差异
---------------------------------------------------------------------------
Basket SKU 扩张                              0.1582           0.3250  -0.1669  Mature 更强
Basket 相对变化                                0.1934           0.3493  -0.1558  Mature 更强
Gap 改善                                    -0.5623          -0.4845  -0.0778  Mature 更强
Zone5 变化                                  -0.1785          -0.3005  +0.1219  Immature 更强
节奏稳定性                                     -0.1905          -0.3202  +0.1297  Immature 更强

======================================================================
综合对比：哪个因素更能解释 Immature 的增长？
======================================================================

因素                                    Spearman 解释力
------------------------------------------------------------
订单数（lifecycle proxy）                   -0.1318 ***
Basket SKU 扩张                           0.1582 ***
Gap 改善                                 -0.5623 ***

解释力排序（按 |Spearman| 从高到低）：
              factor  spearman
              Gap 改善 -0.562320
       Basket SKU 扩张  0.158163
订单数（lifecycle proxy） -0.131815

✅ New tables created:
  - df_imm        (Immature Mid→High 用户)
  - df_mature     (Mature Mid→High 用户)
  - layer1        (第一层：订单数分桶)
  - basket_layer2 (第二层：basket 分桶)
  - gap_layer2    (第二层：gap 分桶)

In [100]:
# Re-segment Mid → High's three main user groups to see what insight emerges

# ============================================================
# Layer 2: growth mechanism comparison across the three user types
# Basket/gap driver weight for Immature / Stepper / Drifter
# Population: all Mid→High users, split into three groups by label
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Step 0: prepare data for the three groups
# ----------------------------------------
df_base = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

groups = {
    "Immature" : df_base[df_base["label"] == "immature"],
    "Stepper"  : df_base[df_base["label"] == "stepper"],
    "Drifter"  : df_base[df_base["label"] == "drifter"],
}

print("========== Sample Size ==========")
for name, df in groups.items():
    print(f"{name:<12}: {len(df):,} users")

# ----------------------------------------
# Step 1: Basket / Gap correlation comparison
# Core question: which engine matters more for which user type?
# ----------------------------------------
print("\n" + "="*80)
print("Step 1: Basket / Gap Correlation Comparison")
print("="*80)

metrics = {
    "d_log_basket"            : "Basket (relative change)",
    "delta_n_unique_products" : "Basket (SKU expansion)",
    "d_log_gap"               : "Gap (overall improvement)",
    "delta_pct_gap30"         : "Gap (Zone5 change)",
    "delta_gap_std"           : "Gap (cadence stability)",
}

corr_results = []

for metric_col, metric_label in metrics.items():
    row = {"metric": metric_label}
    for name, df in groups.items():
        valid = df[[metric_col, "d_log_weekly"]].dropna()
        s_r, s_p = stats.spearmanr(valid[metric_col], valid["d_log_weekly"])
        sig = "***" if s_p < 0.001 else ("**" if s_p < 0.01 else
              ("*" if s_p < 0.05 else "ns"))
        row[f"{name}_spearman"] = round(s_r, 4)
        row[f"{name}_sig"] = sig
    corr_results.append(row)

corr_df = pd.DataFrame(corr_results)

print(f"\n{'Metric':<25} {'Immature':>12} {'Stepper':>12} {'Drifter':>12}")
print("-"*65)
for _, row in corr_df.iterrows():
    print(f"{row['metric']:<25} "
          f"{row['Immature_spearman']:>8.4f}{row['Immature_sig']:>4} "
          f"{row['Stepper_spearman']:>8.4f}{row['Stepper_sig']:>4} "
          f"{row['Drifter_spearman']:>8.4f}{row['Drifter_sig']:>4}")

# ----------------------------------------
# Step 2: bucketed validation
# Bucket Basket and Gap, check whether monotonicity is consistent across the three groups
# ----------------------------------------
print("\n" + "="*80)
print("Step 2: Bucketed Validation (Basket + Gap → weekly)")
print("="*80)

for bucket_col, bucket_label in [
    ("delta_n_unique_products", "Basket SKU expansion"),
    ("d_log_gap", "Gap improvement"),
]:
    print(f"\n--- {bucket_label} bucketing ---")
    print(f"{'Bucket':<8} ", end="")
    for name in groups:
        print(f"{'x_mean':>10} {'weekly':>10} ", end="")
        if name != "Drifter":
            print(f"{'|':>3}", end="")
    print()
    print(f"{'':8} " + "  ".join([f"{'--- '+n+' ---':>23}" for n in groups.keys()]))

    # Combine the three groups for unified bucketing
    df_combined = pd.concat([
        df.assign(group=name)
        for name, df in groups.items()
    ])

    df_combined["bucket"] = pd.qcut(
        df_combined[bucket_col].rank(method="first"),
        q=5,
        labels=["Q1", "Q2", "Q3", "Q4", "Q5"]
    )

    bucket_summary = (
        df_combined.groupby(["bucket", "group"], observed=True)
        .agg(
            x_mean=(bucket_col, "mean"),
            weekly_mean=("d_log_weekly", "mean"),
        )
        .reset_index()
    )

    for bucket in ["Q1", "Q2", "Q3", "Q4", "Q5"]:
        print(f"{bucket:<8} ", end="")
        for name in ["Immature", "Stepper", "Drifter"]:
            row = bucket_summary[
                (bucket_summary["bucket"] == bucket) &
                (bucket_summary["group"] == name)
            ]
            if len(row) > 0:
                print(f"{row['x_mean'].values[0]:>10.3f} "
                      f"{row['weekly_mean'].values[0]:>10.4f} ", end="")
            else:
                print(f"{'N/A':>10} {'N/A':>10} ", end="")
            if name != "Drifter":
                print(f"{'|':>3}", end="")
        print()

# ----------------------------------------
# Step 3: 2×2 analysis
# Basket high/low × Gap high/low
# Do the four-quadrant distribution and growth differ across the three groups?
# ----------------------------------------
print("\n" + "="*80)
print("Step 3: 2×2 Analysis (Basket × Gap)")
print("="*80)

# Use the overall median as the split point (unified standard)
basket_median = df_base["delta_n_unique_products"].median()
gap_median    = df_base["d_log_gap"].median()

df_2x2 = df_base[
    ["user_id", "label", "delta_n_unique_products",
     "d_log_gap", "d_log_weekly"]
].dropna().copy()

df_2x2["basket_group"] = np.where(
    df_2x2["delta_n_unique_products"] >= basket_median,
    "basket_high", "basket_low"
)
df_2x2["gap_group"] = np.where(
    df_2x2["d_log_gap"] <= gap_median,
    "gap_high", "gap_low"
)
df_2x2["quadrant"] = df_2x2["basket_group"] + " × " + df_2x2["gap_group"]

result_2x2 = (
    df_2x2[df_2x2["label"].isin(["immature", "stepper", "drifter"])]
    .groupby(["label", "quadrant"])
    .agg(
        users=("user_id", "count"),
        d_log_weekly_mean=("d_log_weekly", "mean"),
        d_log_weekly_median=("d_log_weekly", "median"),
    )
    .reset_index()
)

quadrant_order = [
    "basket_high × gap_high",
    "basket_low × gap_high",
    "basket_high × gap_low",
    "basket_low × gap_low",
]

for label in ["immature", "stepper", "drifter"]:
    subset = result_2x2[result_2x2["label"] == label]
    total  = subset["users"].sum()

    print(f"\n--- {label.capitalize()} ---")
    print(f"{'Quadrant':<30} {'Users':>8} {'Share':>8} {'d_log_weekly':>14}")
    print("-"*65)

    for q in quadrant_order:
        row = subset[subset["quadrant"] == q]
        if len(row) > 0:
            u = row["users"].values[0]
            w = row["d_log_weekly_mean"].values[0]
            print(f"{q:<30} {u:>8,} {u/total:>7.1%} {w:>14.4f}")

# ----------------------------------------
# Step 4: incremental analysis
# Compute basket / gap's incremental contribution separately for each of the three groups
# ----------------------------------------
print("\n" + "="*80)
print("Step 4: Incremental Analysis (basket / gap individual contribution)")
print("="*80)
print(f"{'':30} {'Immature':>12} {'Stepper':>12} {'Drifter':>12}")
print("-"*70)

def get_2x2_val(df, label, quadrant):
    row = df[(df["label"] == label) & (df["quadrant"] == quadrant)]
    return row["d_log_weekly_mean"].values[0] if len(row) > 0 else np.nan

incremental_results = []
for label in ["immature", "stepper", "drifter"]:
    both    = get_2x2_val(result_2x2, label, "basket_high × gap_high")
    b_only  = get_2x2_val(result_2x2, label, "basket_high × gap_low")
    g_only  = get_2x2_val(result_2x2, label, "basket_low × gap_high")
    neither = get_2x2_val(result_2x2, label, "basket_low × gap_low")

    inc_basket = both - g_only
    inc_gap    = both - b_only

    incremental_results.append({
        "label"     : label,
        "both"      : both,
        "basket_only": b_only,
        "gap_only"  : g_only,
        "neither"   : neither,
        "inc_basket": inc_basket,
        "inc_gap"   : inc_gap,
    })

inc_df = pd.DataFrame(incremental_results)

for metric, label in [
    ("both",       "Both（basket↑ + gap↑）"),
    ("basket_only","Basket only"),
    ("gap_only",   "Gap only"),
    ("neither",    "Neither"),
    ("inc_basket", "Incremental Basket (given gap↑)"),
    ("inc_gap",    "Incremental Gap    (given basket↑)"),
]:
    print(f"{label:<30}", end="")
    for _, row in inc_df.iterrows():
        print(f"{row[metric]:>12.4f}", end="")
    print()

# ----------------------------------------
# Step 5: overall summary
# What is the dominant engine for each of the three user types?
# ----------------------------------------
print("\n" + "="*80)
print("Step 5: Overall Summary - Dominant Engine per User Type")
print("="*80)

print(f"\n{'':30} {'Immature':>12} {'Stepper':>12} {'Drifter':>12}")
print("-"*70)

for _, row in corr_df.iterrows():
    if row["metric"] in ["Basket (relative change)", "Gap (overall improvement)"]:
        print(f"{row['metric']:<30} "
              f"{row['Immature_spearman']:>12.4f} "
              f"{row['Stepper_spearman']:>12.4f} "
              f"{row['Drifter_spearman']:>12.4f}")

for _, row in inc_df.iterrows():
    pass

print(f"\n{'Incremental Basket':30}", end="")
for _, row in inc_df.iterrows():
    print(f"{row['inc_basket']:>12.4f}", end="")
print()

print(f"{'Incremental Gap':30}", end="")
for _, row in inc_df.iterrows():
    print(f"{row['inc_gap']:>12.4f}", end="")
print()

print(f"\n{'Dominant Engine':30}", end="")
for _, row in inc_df.iterrows():
    if abs(row["inc_gap"]) > abs(row["inc_basket"]) * 1.5:
        engine = "Gap-dominant"
    elif abs(row["inc_basket"]) > abs(row["inc_gap"]) * 1.5:
        engine = "Basket-dominant"
    else:
        engine = "Both engines balanced"
    print(f"{engine:>12}", end="")
print()

print("\n✅ New tables created:")
print("  - corr_df      (three-group correlation comparison)")
print("  - result_2x2   (three-group 2×2 analysis)")
print("  - inc_df       (three-group incremental analysis)")

========== 样本量 ==========
Immature    : 5,119 users
Stepper     : 4,619 users
Drifter     : 3,817 users

================================================================================
Step 1：Basket / Gap 相关性对比
================================================================================

指标                            Immature      Stepper      Drifter
-----------------------------------------------------------------
Basket（相对变化）                0.1934 ***   0.3842 ***   0.3037 ***
Basket（SKU 扩张）              0.1582 ***   0.3681 ***   0.2710 ***
Gap（整体改善）                  -0.5623 ***  -0.4875 ***  -0.4767 ***
Gap（Zone5 变化）              -0.1785 ***  -0.3186 ***  -0.2841 ***
Gap（节奏稳定性）                 -0.1905 ***  -0.3490 ***  -0.2936 ***

================================================================================
Step 2：分桶验证（Basket + Gap → weekly）
================================================================================

--- Basket SKU 扩张 分桶 ---
Bucket       x_mean     weekly   |    x_mean     weekly   |    x_mean     weekly
                --- Immature ---          --- Stepper ---          --- Drifter ---
Q1           -4.374     0.7235   |    -2.632     0.6018   |    -3.129     0.5808
Q2            0.395     0.7419   |     0.371     0.6106   |    -0.094     0.5972
Q3            2.288     0.7767   |     2.138     0.6922   |     1.714     0.6451
Q4            4.417     0.8063   |     4.117     0.7980   |     3.905     0.7095
Q5            9.858     0.9348   |     9.417     1.0361   |     8.917     0.8895

--- Gap 改善 分桶 ---
Bucket       x_mean     weekly   |    x_mean     weekly   |    x_mean     weekly
                --- Immature ---          --- Stepper ---          --- Drifter ---
Q1           -1.295     1.1543   |    -1.181     1.1285   |    -1.183     1.0699
Q2           -0.704     0.8140   |    -0.701     0.8868   |    -0.708     0.8154
Q3           -0.427     0.6855   |    -0.422     0.7144   |    -0.431     0.6814
Q4           -0.171     0.5608   |    -0.181     0.6101   |    -0.180     0.5638
Q5            0.286     0.4377   |     0.112     0.5417   |     0.143     0.5085

================================================================================
Step 3：2×2 分析（Basket × Gap）
================================================================================

--- Immature ---
象限                                  用户数    Share   d_log_weekly
-----------------------------------------------------------------
basket_high × gap_high            1,202   23.5%         1.1368
basket_low × gap_high             1,927   37.6%         0.8641
basket_high × gap_low             1,344   26.3%         0.6034
basket_low × gap_low                646   12.6%         0.3385

--- Stepper ---
象限                                  用户数    Share   d_log_weekly
-----------------------------------------------------------------
basket_high × gap_high            1,024   22.2%         1.0786
basket_low × gap_high             1,106   23.9%         0.7831
basket_high × gap_low             1,618   35.0%         0.7082
basket_low × gap_low                871   18.9%         0.3921

--- Drifter ---
象限                                  用户数    Share   d_log_weekly
-----------------------------------------------------------------
basket_high × gap_high              776   20.3%         0.9941
basket_low × gap_high               905   23.7%         0.7517
basket_high × gap_low             1,408   36.9%         0.6237
basket_low × gap_low                728   19.1%         0.4161

================================================================================
Step 4：增量分析（basket / gap 各自贡献）
================================================================================
                                   Immature      Stepper      Drifter
----------------------------------------------------------------------
Both（basket↑ + gap↑）                1.1368      1.0786      0.9941
Basket only                         0.6034      0.7082      0.6237
Gap only                            0.8641      0.7831      0.7517
Neither                             0.3385      0.3921      0.4161
增量 Basket（given gap↑）               0.2728      0.2955      0.2425
增量 Gap   （given basket↑）            0.5334      0.3704      0.3704

================================================================================
Step 5：综合总结 - 三类用户主导引擎
================================================================================

                                   Immature      Stepper      Drifter
----------------------------------------------------------------------
Basket（相对变化）                         0.1934       0.3842       0.3037
Gap（整体改善）                           -0.5623      -0.4875      -0.4767

增量 Basket                           0.2728      0.2955      0.2425
增量 Gap                              0.5334      0.3704      0.3704

主导引擎                                Gap 主导       双引擎均衡      Gap 主导

✅ New tables created:
  - corr_df      (三组相关性对比)
  - result_2x2   (三组 2×2 分析)
  - inc_df       (三组增量分析)

In [101]:
# Add an overall timing analysis

# ============================================================
# Growth trajectory analysis for all Mid→High users
# Using three stages (early/mid/late), check whether growth accelerates later
# Compare trajectory shapes across the three user types (Immature/Stepper/Drifter)
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# Step 0: prepare data
# Needs: all orders + label for Mid→High users
# ----------------------------------------
mh_label = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
][["user_id", "label"]].copy()

print(f"Mid→High users: {len(mh_label):,}")
print(mh_label["label"].value_counts())

# ----------------------------------------
# Step 1: split orders into three stages by lifecycle position
# early : pos <= 0.30
# mid   : 0.30 < pos <= 0.60
# late  : pos > 0.60
# Consistent with the earlier 30/30/40 split
# ----------------------------------------

# Reuse mh_orders (already has user_id, order_number, gap_days_adj, n_orders, pos)
mh_orders_label = mh_orders.merge(mh_label, on="user_id", how="inner")

# Tag the three stages
def assign_segment(pos):
    if pos <= 0.30:
        return "1_early"
    elif pos <= 0.60:
        return "2_mid"
    else:
        return "3_late"

mh_orders_label["segment"] = mh_orders_label["pos"].apply(assign_segment)

print(f"\nThree-stage order distribution:")
print(mh_orders_label["segment"].value_counts().sort_index())

# ----------------------------------------
# Step 2: compute weekly active score for each order
# weekly = items_per_order / gap_days_adj * 7
# active_score_week already exists in orders_enriched2
# ----------------------------------------

# Confirm active_score_week is present in mh_orders
print(f"\nmh_orders columns: {mh_orders.columns.tolist()}")

# ----------------------------------------
# Step 3: median weekly per user per stage
# ----------------------------------------
user_segment = (
    mh_orders_label
    .dropna(subset=["active_score_week", "segment"])
    .groupby(["user_id", "label", "segment"])["active_score_week"]
    .median()
    .reset_index()
    .rename(columns={"active_score_week": "weekly_med"})
)

# Pivot to wide
user_segment_wide = user_segment.pivot_table(
    index=["user_id", "label"],
    columns="segment",
    values="weekly_med"
).reset_index()

user_segment_wide.columns = [
    "user_id", "label",
    "weekly_early", "weekly_mid", "weekly_late"
]

# Compute change across stages
user_segment_wide["delta_mid_early"] = (
    user_segment_wide["weekly_mid"] - user_segment_wide["weekly_early"]
)
user_segment_wide["delta_late_mid"] = (
    user_segment_wide["weekly_late"] - user_segment_wide["weekly_mid"]
)
user_segment_wide["delta_late_early"] = (
    user_segment_wide["weekly_late"] - user_segment_wide["weekly_early"]
)

print(f"\nuser_segment_wide shape: {user_segment_wide.shape}")

# ----------------------------------------
# Step 4: overall three-stage trajectory for Mid→High
# ----------------------------------------
print("\n" + "="*70)
print("Overall Mid→High Three-Stage Growth Trajectory")
print("="*70)

overall = (
    user_segment_wide
    .dropna(subset=["weekly_early", "weekly_mid", "weekly_late"])
    .agg({
        "weekly_early"    : ["mean", "median"],
        "weekly_mid"      : ["mean", "median"],
        "weekly_late"     : ["mean", "median"],
        "delta_mid_early" : ["mean", "median"],
        "delta_late_mid"  : ["mean", "median"],
        "delta_late_early": ["mean", "median"],
    })
)

print(overall.round(4))

# Condensed version
df_valid = user_segment_wide.dropna(
    subset=["weekly_early", "weekly_mid", "weekly_late"]
)

print(f"\n--- Condensed version (median) ---")
print(f"Early  median: {df_valid['weekly_early'].median():.3f}")
print(f"Mid    median: {df_valid['weekly_mid'].median():.3f}")
print(f"Late   median: {df_valid['weekly_late'].median():.3f}")
print(f"delta Early→Mid : {df_valid['delta_mid_early'].median():+.3f}")
print(f"delta Mid→Late  : {df_valid['delta_late_mid'].median():+.3f}")
print(f"Acceleration ratio (Late/Early delta): "
      f"{df_valid['delta_late_mid'].median() / df_valid['delta_mid_early'].median():.2f}x")

# ----------------------------------------
# Step 5: three-stage trajectory comparison across the three user types
# ----------------------------------------
print("\n" + "="*70)
print("Three-Stage Trajectory Comparison Across User Types (median)")
print("="*70)

labels = ["immature", "stepper", "drifter"]
segment_cols = ["weekly_early", "weekly_mid", "weekly_late",
                "delta_mid_early", "delta_late_mid", "delta_late_early"]

print(f"\n{'Metric':<25} {'Immature':>12} {'Stepper':>12} {'Drifter':>12}")
print("-"*65)

segment_results = {}
for label in labels:
    subset = df_valid[df_valid["label"] == label]
    segment_results[label] = {
        col: subset[col].median() for col in segment_cols
    }
    segment_results[label]["n"] = len(subset)

for col in segment_cols:
    print(f"{col:<25}", end="")
    for label in labels:
        print(f"{segment_results[label][col]:>12.3f}", end="")
    print()

# Acceleration ratio
print(f"\n{'Acceleration ratio (Late/Early delta)':<25}", end="")
for label in labels:
    early_delta = segment_results[label]["delta_mid_early"]
    late_delta  = segment_results[label]["delta_late_mid"]
    ratio = late_delta / early_delta if early_delta != 0 else np.nan
    print(f"{ratio:>12.2f}x", end="")
print()

# ----------------------------------------
# Step 6: growth-pattern classification
# Determine whether each user's growth is "late-stage acceleration" or "uniform growth"
# ----------------------------------------
print("\n" + "="*70)
print("Growth Pattern Classification")
print("="*70)

# Define growth pattern
def classify_growth(row):
    if pd.isna(row["delta_mid_early"]) or pd.isna(row["delta_late_mid"]):
        return "unknown"
    # Late-stage acceleration: late delta > early delta * 1.5
    if row["delta_late_mid"] > row["delta_mid_early"] * 1.5:
        return "back_loaded"    # late-stage acceleration
    # Early-stage acceleration: early delta > late delta * 1.5
    elif row["delta_mid_early"] > row["delta_late_mid"] * 1.5:
        return "front_loaded"   # early-stage acceleration
    # Uniform growth
    else:
        return "linear"         # uniform growth

df_valid["growth_shape"] = df_valid.apply(classify_growth, axis=1)

# Overall distribution
print("\nOverall Growth Pattern Distribution:")
print(df_valid["growth_shape"].value_counts(normalize=True).round(3))

# Growth-pattern distribution across the three user types
print("\nGrowth Pattern Distribution Across User Types:")
shape_by_label = (
    df_valid[df_valid["label"].isin(labels)]
    .groupby(["label", "growth_shape"])
    .size()
    .unstack(fill_value=0)
)
shape_by_label_pct = shape_by_label.div(shape_by_label.sum(axis=1), axis=0)
print(shape_by_label_pct.round(3))

# ----------------------------------------
# Step 7: comparison, late-accelerating users vs. uniform-growth users
# Check whether late-stage acceleration leads to a better outcome
# ----------------------------------------
print("\n" + "="*70)
print("Late-Loaded vs. Uniform vs. Front-Loaded Growth Comparison")
print("="*70)

shape_comparison = (
    df_valid.groupby("growth_shape")
    .agg(
        users=("user_id", "count"),
        weekly_late_mean=("weekly_late", "mean"),
        weekly_late_median=("weekly_late", "median"),
        delta_total_mean=("delta_late_early", "mean"),
        delta_total_median=("delta_late_early", "median"),
    )
    .reset_index()
    .sort_values("weekly_late_median", ascending=False)
)

print(shape_comparison.round(3).to_string(index=False))

print("\n✅ New tables created:")
print("  - user_segment_wide  (user three-stage weekly wide table)")
print("  - shape_comparison   (growth pattern comparison)")

Mid→High users: 14,217
label
immature      5119
stepper       4619
drifter       3817
oscillator     409
mixed          253
Name: count, dtype: int64

订单三段分布：
segment
1_early     75538
2_mid       97129
3_late     133908
Name: count, dtype: int64

mh_orders columns: ['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', 'items_per_order', 'active_score_week', 'gap_days_adj', 'n_orders', 'pos', 'half', 'gap_zone']

user_segment_wide shape: (14217, 8)

======================================================================
整体 Mid→High 三段增长轨迹
======================================================================
        weekly_early  weekly_mid  weekly_late  delta_mid_early  \
mean          6.9674      9.3937      13.7549           2.4263
median        6.3000      8.3125      12.2500           1.9621

        delta_late_mid  delta_late_early
mean            4.3611            6.7875
median          4.2045            6.1250

--- 简洁版（median）---
Early  median: 6.300
Mid    median: 8.312
Late   median: 12.250
delta Early→Mid : +1.962
delta Mid→Late  : +4.205
加速比（Late/Early delta）: 2.14x

======================================================================
三类用户三段轨迹对比（median）
======================================================================

指标                            Immature      Stepper      Drifter
-----------------------------------------------------------------
weekly_early                    5.882       6.125       6.496
weekly_mid                      8.603       8.167       8.167
weekly_late                    12.000      12.833      12.425
delta_mid_early                 2.683       2.021       1.647
delta_late_mid                  3.537       4.861       4.492
delta_late_early                5.950       6.899       6.250

加速比(Late/Early delta)            1.32x        2.41x        2.73x

======================================================================
增长形态分类
======================================================================

整体增长形态分布：
growth_shape
back_loaded     0.568
front_loaded    0.339
linear          0.093
Name: proportion, dtype: float64

三类用户增长形态分布：
growth_shape  back_loaded  front_loaded  linear
label
drifter             0.601         0.303   0.096
immature            0.518         0.405   0.078
stepper             0.582         0.312   0.107

======================================================================
后期加速 vs 均匀增长 vs 前期加速 对比
======================================================================
growth_shape  users  weekly_late_mean  weekly_late_median  delta_total_mean  delta_total_median
 back_loaded   7245            15.082              13.462             6.878               6.300
      linear   1180            14.516              13.000             9.456               8.141
front_loaded   4328            11.326              10.500             5.908               5.357

✅ New tables created:
  - user_segment_wide  (用户三段 weekly 宽表)
  - shape_comparison   (增长形态对比)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/1603576449.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_valid["growth_shape"] = df_valid.apply(classify_growth, axis=1)

In [102]:
# Check which users are included in user_zone_wide
print("user_zone_wide shape:", user_zone_wide.shape)
print("\ncolumns:", user_zone_wide.columns.tolist())

# Check whether a path column exists
if "path" in user_zone_wide.columns:
    print("\npath distribution:")
    print(user_zone_wide["path"].value_counts())
else:
    print("\nNo path column, checking how many users")
    print("unique users:", user_zone_wide["user_id"].nunique())
    
    # Compare against analysis_mid_user_master
    mh_users_set = set(
        analysis_mid_user_master[
            analysis_mid_user_master["path_9"] == "Mid Up to High"
        ]["user_id"]
    )
    ms_users_set = set(
        analysis_mid_user_master[
            analysis_mid_user_master["path_9"] == "Mid Stay"
        ]["user_id"]
    )
    zone_users_set = set(user_zone_wide["user_id"])
    
    print(f"\nMid→High user count: {len(mh_users_set):,}")
    print(f"Mid Stay  user count: {len(ms_users_set):,}")
    print(f"Zone table user count: {len(zone_users_set):,}")
    print(f"\nZone ∩ Mid→High: {len(zone_users_set & mh_users_set):,}")
    print(f"Zone ∩ Mid Stay:  {len(zone_users_set & ms_users_set):,}")
    print(f"Other Zone users:    {len(zone_users_set - mh_users_set - ms_users_set):,}")

user_zone_wide shape: (14217, 16)

columns: ['user_id', 'early_Zone1_weekly', 'early_Zone2_biweekly', 'early_Zone3_warning', 'early_Zone4_danger', 'early_Zone5_cliff', 'late_Zone1_weekly', 'late_Zone2_biweekly', 'late_Zone3_warning', 'late_Zone4_danger', 'late_Zone5_cliff', 'delta_Zone1_weekly', 'delta_Zone2_biweekly', 'delta_Zone3_warning', 'delta_Zone4_danger', 'delta_Zone5_cliff']

没有 path 列，看看有多少用户
unique users: 14217

Mid→High 用户数: 14,217
Mid Stay  用户数: 43,780
Zone 表用户数:    14,217

Zone ∩ Mid→High: 14,217
Zone ∩ Mid Stay:  0
Zone 其他用户:    0

In [103]:
# Check which users are included in user_zone_wide
print("user_zone_wide shape:", user_zone_wide.shape)
print("\ncolumns:", user_zone_wide.columns.tolist())

# Check whether a path column exists
if "path" in user_zone_wide.columns:
    print("\npath distribution:")
    print(user_zone_wide["path"].value_counts())
else:
    print("\nNo path column, checking how many users")
    print("unique users:", user_zone_wide["user_id"].nunique())
    
    # Compare against analysis_mid_user_master
    mh_users_set = set(
        analysis_mid_user_master[
            analysis_mid_user_master["path_9"] == "Mid Up to High"
        ]["user_id"]
    )
    ms_users_set = set(
        analysis_mid_user_master[
            analysis_mid_user_master["path_9"] == "Mid Stay"
        ]["user_id"]
    )
    zone_users_set = set(user_zone_wide["user_id"])
    
    print(f"\nMid→High user count: {len(mh_users_set):,}")
    print(f"Mid Stay  user count: {len(ms_users_set):,}")
    print(f"Zone table user count: {len(zone_users_set):,}")
    print(f"\nZone ∩ Mid→High: {len(zone_users_set & mh_users_set):,}")
    print(f"Zone ∩ Mid Stay:  {len(zone_users_set & ms_users_set):,}")
    print(f"Other Zone users:    {len(zone_users_set - mh_users_set - ms_users_set):,}")

user_zone_wide shape: (14217, 16)

columns: ['user_id', 'early_Zone1_weekly', 'early_Zone2_biweekly', 'early_Zone3_warning', 'early_Zone4_danger', 'early_Zone5_cliff', 'late_Zone1_weekly', 'late_Zone2_biweekly', 'late_Zone3_warning', 'late_Zone4_danger', 'late_Zone5_cliff', 'delta_Zone1_weekly', 'delta_Zone2_biweekly', 'delta_Zone3_warning', 'delta_Zone4_danger', 'delta_Zone5_cliff']

没有 path 列，看看有多少用户
unique users: 14217

Mid→High 用户数: 14,217
Mid Stay  用户数: 43,780
Zone 表用户数:    14,217

Zone ∩ Mid→High: 14,217
Zone ∩ Mid Stay:  0
Zone 其他用户:    0

In [104]:
# ============================================================
# Behavioral stabilization analysis
# Verify whether Mid→High users' upgrade is accompanied by behavioral structuring
# Five signals: gap_std / Zone1&5 / reorder / basket_std / dow_entropy
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import entropy

# ----------------------------------------
# Step 0: prepare base data
# ----------------------------------------
mh_base = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"Mid→High users: {len(mh_base):,}")

# ----------------------------------------
# Step 1: compute from mh_orders
# basket_std and dow_entropy (early vs. late)
# ----------------------------------------

# 1a. Basket std (std of items_per_order for each user's early/late stage)
basket_stability = (
    mh_orders
    .dropna(subset=["items_per_order"])
    .groupby(["user_id", "half"])["items_per_order"]
    .agg(
        basket_mean="mean",
        basket_std="std",
        basket_cv=lambda x: x.std() / x.mean() if x.mean() > 0 else np.nan
    )
    .reset_index()
)

basket_wide = basket_stability.pivot_table(
    index="user_id",
    columns="half",
    values=["basket_mean", "basket_std", "basket_cv"]
).reset_index()

basket_wide.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in basket_wide.columns
]

# Compute delta
basket_wide["delta_basket_std"] = (
    basket_wide["basket_std_late"] - basket_wide["basket_std_early"]
)
basket_wide["delta_basket_cv"] = (
    basket_wide["basket_cv_late"] - basket_wide["basket_cv_early"]
)

print(f"\nbasket_wide shape: {basket_wide.shape}")

# 1b. DOW entropy (Shannon entropy of purchase day-of-week for each user's early/late stage)
def calc_dow_entropy(dow_series):
    counts = dow_series.value_counts(normalize=True)
    return entropy(counts, base=2)

dow_entropy = (
    mh_orders
    .dropna(subset=["order_dow"])
    .groupby(["user_id", "half"])["order_dow"]
    .apply(calc_dow_entropy)
    .reset_index()
    .rename(columns={"order_dow": "dow_entropy"})
)

dow_wide = dow_entropy.pivot_table(
    index="user_id",
    columns="half",
    values="dow_entropy"
).reset_index()

dow_wide.columns = ["user_id", "dow_entropy_early", "dow_entropy_late"]
dow_wide["delta_dow_entropy"] = (
    dow_wide["dow_entropy_late"] - dow_wide["dow_entropy_early"]
)

print(f"dow_wide shape: {dow_wide.shape}")

# ----------------------------------------
# Step 2: consolidate all stabilization metrics into one master table
# ----------------------------------------
stability_df = (
    mh_base[[
        "user_id", "label",
        # gap stability (already available)
        "gap_std_early", "gap_std_late", "delta_gap_std",
        # reorder (already available)
        "reorder_ratio_early", "reorder_ratio_late", "delta_reorder_ratio",
        # weekly (outcome variable)
        "weekly_med_early", "weekly_med_late", "delta_weekly", "d_log_weekly",
    ]]
    .merge(basket_wide[[
        "user_id",
        "basket_std_early", "basket_std_late",
        "delta_basket_std", "delta_basket_cv"
    ]], on="user_id", how="left")
    .merge(dow_wide[[
        "user_id",
        "dow_entropy_early", "dow_entropy_late",
        "delta_dow_entropy"
    ]], on="user_id", how="left")
    .merge(user_zone_wide[[
        "user_id",
        "early_Zone1_weekly", "late_Zone1_weekly", "delta_Zone1_weekly",
        "early_Zone5_cliff",  "late_Zone5_cliff",  "delta_Zone5_cliff",
    ]], on="user_id", how="left")
)

print(f"\nstability_df shape: {stability_df.shape}")
print(f"columns: {stability_df.columns.tolist()}")

# ----------------------------------------
# Step 3: Early vs. Late comparison for the five signals
# Validate: do users actually become more structured later on?
# ----------------------------------------
print("\n" + "="*70)
print("Step 3: Five Behavioral Stabilization Signals, Early vs. Late Comparison")
print("="*70)

signals = {
    "gap_std"       : ("gap_std_early",        "gap_std_late",
                       "delta_gap_std",         "↓ good",  "more regular purchase intervals"),
    "Zone5_cliff"   : ("early_Zone5_cliff",     "late_Zone5_cliff",
                       "delta_Zone5_cliff",     "↓ good",  "less low-frequency state"),
    "Zone1_weekly"  : ("early_Zone1_weekly",    "late_Zone1_weekly",
                       "delta_Zone1_weekly",    "↑ good",  "weekly cadence established"),
    "reorder_ratio" : ("reorder_ratio_early",   "reorder_ratio_late",
                       "delta_reorder_ratio",   "↑ good",  "fixed shopping list formed"),
    "basket_std"    : ("basket_std_early",      "basket_std_late",
                       "delta_basket_std",      "↓ good",  "shopping content stabilizes"),
    "dow_entropy"   : ("dow_entropy_early",     "dow_entropy_late",
                       "delta_dow_entropy",     "↓ good",  "shopping timing becomes regular"),
}

print(f"\n{'Signal':<16} {'Early':>8} {'Late':>8} {'Delta':>8} "
      f"{'Direction':>6} {'Improve%':>8} {'Meaning'}")
print("-"*75)

signal_results = []
for name, (early_col, late_col, delta_col, good_dir, meaning) in signals.items():
    early_med = stability_df[early_col].median()
    late_med  = stability_df[late_col].median()
    delta_med = stability_df[delta_col].median()

    # Share of users improving in the expected direction
    if good_dir == "↓ good":
        improve_pct = (stability_df[delta_col] < 0).mean()
        direction = "↓" if delta_med < 0 else "↑"
    else:
        improve_pct = (stability_df[delta_col] > 0).mean()
        direction = "↑" if delta_med > 0 else "↓"

    # Whether it matches expectations
    is_good = (good_dir == "↓ good" and delta_med < 0) or \
              (good_dir == "↑ good" and delta_med > 0)
    status = "✅" if is_good else "❌"

    signal_results.append({
        "signal"     : name,
        "early_med"  : early_med,
        "late_med"   : late_med,
        "delta_med"  : delta_med,
        "improve_pct": improve_pct,
        "is_good"    : is_good,
    })

    print(f"{status} {name:<14} {early_med:>8.3f} {late_med:>8.3f} "
          f"{delta_med:>+8.3f} {direction:>6} {improve_pct:>7.1%}  {meaning}")

# ----------------------------------------
# Step 4: degree of stabilization vs. growth strength
# Validate: do more-stabilized users show stronger growth?
# ----------------------------------------
print("\n" + "="*70)
print("Step 4: Degree of Stabilization vs. Weekly Growth (bucketed validation)")
print("="*70)

key_signals = {
    "delta_gap_std"      : ("gap_std↓",       "↓ good"),
    "delta_Zone1_weekly" : ("Zone1↑",          "↑ good"),
    "delta_Zone5_cliff"  : ("Zone5↓",          "↓ good"),
    "delta_reorder_ratio": ("reorder↑",        "↑ good"),
    "delta_basket_std"   : ("basket_std↓",     "↓ good"),
    "delta_dow_entropy"  : ("dow_entropy↓",    "↓ good"),
}

for col, (label, good_dir) in key_signals.items():
    df_bucket = stability_df[[col, "d_log_weekly"]].dropna().copy()

    df_bucket["bucket"] = pd.qcut(
        df_bucket[col].rank(method="first"),
        q=5,
        labels=["Q1", "Q2", "Q3", "Q4", "Q5"]
    )

    bucket_result = (
        df_bucket.groupby("bucket", observed=True)
        .agg(
            users=(col, "count"),
            x_mean=(col, "mean"),
            weekly_mean=("d_log_weekly", "mean"),
        )
        .reset_index()
    )

    # If good_dir is ↓, Q1 is best (most negative change)
    # If good_dir is ↑, Q5 is best
    print(f"\n--- {label} ---")
    print(f"{'Bucket':<8} {'x_mean':>10} {'weekly_mean':>12}")
    for _, row in bucket_result.iterrows():
        print(f"{row['bucket']:<8} {row['x_mean']:>10.4f} {row['weekly_mean']:>12.4f}")

    # Correlation
    s_r, s_p = stats.spearmanr(df_bucket[col], df_bucket["d_log_weekly"])
    sig = "***" if s_p < 0.001 else ("**" if s_p < 0.01 else
          ("*" if s_p < 0.05 else "ns"))
    print(f"Spearman = {s_r:.4f} {sig}")

# ----------------------------------------
# Step 5: composite stabilization score
# Combine the five signals into one "stabilization score"
# Compare growth between high-score and low-score users
# ----------------------------------------
print("\n" + "="*70)
print("Step 5: Composite Stabilization Score vs. Growth")
print("="*70)

# For each signal, compute a standardized score for the "improvement direction"
# Standardize so that "higher = more stabilized"
score_df = stability_df[["user_id", "d_log_weekly"]].copy()

score_cols = []
for col, (label, good_dir) in key_signals.items():
    valid = stability_df[col].dropna()
    z = (stability_df[col] - valid.mean()) / valid.std()

    # If good_dir is ↓, flip the direction
    if good_dir == "↓ good":
        z = -z

    score_col = f"score_{col}"
    score_df[score_col] = z
    score_cols.append(score_col)

# Composite score = average of each signal's z-score
score_df["stability_score"] = score_df[score_cols].mean(axis=1)

# Bucket by composite score
score_df["score_bucket"] = pd.qcut(
    score_df["stability_score"].rank(method="first"),
    q=5,
    labels=["Q1\n(least stable)", "Q2", "Q3", "Q4", "Q5\n(most stable)"]
)

score_summary = (
    score_df.groupby("score_bucket", observed=True)
    .agg(
        users=("user_id", "count"),
        stability_score_mean=("stability_score", "mean"),
        weekly_mean=("d_log_weekly", "mean"),
        weekly_median=("d_log_weekly", "median"),
    )
    .reset_index()
)

print("\nComposite stabilization score bucket → weekly growth:")
print(f"{'Bucket':<15} {'users':>6} {'stability':>12} "
      f"{'weekly_mean':>12} {'weekly_median':>14}")
print("-"*65)
for _, row in score_summary.iterrows():
    print(f"{str(row['score_bucket']):<15} {row['users']:>6,} "
          f"{row['stability_score_mean']:>12.4f} "
          f"{row['weekly_mean']:>12.4f} "
          f"{row['weekly_median']:>14.4f}")

# Correlation
s_r, s_p = stats.spearmanr(
    score_df["stability_score"].dropna(),
    score_df.loc[score_df["stability_score"].notna(), "d_log_weekly"]
)
print(f"\nComposite stabilization score vs. d_log_weekly:")
print(f"Spearman = {s_r:.4f} ({'***' if s_p < 0.001 else 'ns'})")

# ----------------------------------------
# Step 6: stabilization-degree comparison across the three user types
# ----------------------------------------
print("\n" + "="*70)
print("Step 6: Stabilization Signal Comparison Across User Types")
print("="*70)

stability_with_label = stability_df.merge(
    score_df[["user_id", "stability_score"]],
    on="user_id", how="left"
)

print(f"\n{'Signal':<20} {'Immature':>12} {'Stepper':>12} {'Drifter':>12}")
print("-"*60)

for col, (label, good_dir) in key_signals.items():
    print(f"{label:<20}", end="")
    for grp in ["immature", "stepper", "drifter"]:
        val = stability_with_label[
            stability_with_label["label"] == grp
        ][col].median()
        print(f"{val:>12.4f}", end="")
    print()

# Composite stabilization score
print(f"\n{'Composite Stabilization Score':<20}", end="")
for grp in ["immature", "stepper", "drifter"]:
    val = stability_with_label[
        stability_with_label["label"] == grp
    ]["stability_score"].median()
    print(f"{val:>12.4f}", end="")
print()

print("\n✅ New tables created:")
print("  - stability_df        (five stabilization signals + weekly, user level)")
print("  - score_df            (composite stabilization score)")
print("  - score_summary       (score bucket vs. weekly)")

Mid→High users: 14,217

basket_wide shape: (14217, 9)
dow_wide shape: (14217, 4)

stability_df shape: (14217, 25)
columns: ['user_id', 'label', 'gap_std_early', 'gap_std_late', 'delta_gap_std', 'reorder_ratio_early', 'reorder_ratio_late', 'delta_reorder_ratio', 'weekly_med_early', 'weekly_med_late', 'delta_weekly', 'd_log_weekly', 'basket_std_early', 'basket_std_late', 'delta_basket_std', 'delta_basket_cv', 'dow_entropy_early', 'dow_entropy_late', 'delta_dow_entropy', 'early_Zone1_weekly', 'late_Zone1_weekly', 'delta_Zone1_weekly', 'early_Zone5_cliff', 'late_Zone5_cliff', 'delta_Zone5_cliff']

======================================================================
Step 3：五个行为稳定化信号 Early vs Late 对比
======================================================================

信号                  Early     Late    Delta     方向      改善% 含义
---------------------------------------------------------------------------
✅ gap_std           7.694    5.630   -1.373      ↓   65.9%  购买间隔更规律
❌ Zone5_cliff       0.050    0.000   +0.000      ↑   49.2%  低频状态减少
✅ Zone1_weekly      0.364    0.571   +0.167      ↑   74.0%  周节奏建立
✅ reorder_ratio     0.500    0.667   +0.152      ↑   78.6%  固定清单形成
❌ basket_std        4.243    4.680   +0.371      ↑   40.6%  购物内容稳定化
❌ dow_entropy       1.918    2.000   +0.109      ↑   39.6%  购物时间规律化

======================================================================
Step 4：稳定化程度 vs weekly 增长（分桶验证）
======================================================================

--- gap_std↓ ---
Bucket       x_mean  weekly_mean
Q1          -6.9296       0.9333
Q2          -3.3070       0.7570
Q3          -1.3801       0.6953
Q4           0.4302       0.6274
Q5           4.7719       0.6433
Spearman = -0.2447 ***

--- Zone1↑ ---
Bucket       x_mean  weekly_mean
Q1          -0.1728       0.5726
Q2           0.0422       0.6169
Q3           0.1725       0.7089
Q4           0.2998       0.7874
Q5           0.5471       0.9705
Spearman = 0.3295 ***

--- Zone5↓ ---
Bucket       x_mean  weekly_mean
Q1          -0.4152       0.9193
Q2          -0.1164       0.7592
Q3          -0.0128       0.6757
Q4           0.0000       0.6852
Q5           0.1400       0.6169
Spearman = -0.2444 ***

--- reorder↑ ---
Bucket       x_mean  weekly_mean
Q1          -0.1379       0.8181
Q2           0.0573       0.6882
Q3           0.1528       0.6864
Q4           0.2441       0.7035
Q5           0.4032       0.7600
Spearman = -0.0381 ***

--- basket_std↓ ---
Bucket       x_mean  weekly_mean
Q1          -3.4873       0.7649
Q2          -0.7038       0.6865
Q3           0.3696       0.6820
Q4           1.5211       0.7031
Q5           4.5533       0.7791
Spearman = 0.0236 **

--- dow_entropy↓ ---
Bucket       x_mean  weekly_mean
Q1          -0.5023       0.7174
Q2          -0.0824       0.7340
Q3           0.1175       0.6992
Q4           0.4178       0.7253
Q5           1.0103       0.7803
Spearman = 0.0339 ***

======================================================================
Step 5：综合稳定化得分 vs 增长
======================================================================

综合稳定化得分分桶 → weekly 增长：
Bucket           users    stability  weekly_mean  weekly_median
-----------------------------------------------------------------
Q1
(最不稳定)        2,844      -0.7090       0.6721         0.6105
Q2               2,843      -0.2368       0.6286         0.5596
Q3               2,843      -0.0031       0.6735         0.6190
Q4               2,843       0.2386       0.7527         0.7024
Q5
(最稳定)         2,844       0.7034       0.9295         0.9163

综合稳定化得分 vs d_log_weekly:
Spearman = 0.2221 (***)

======================================================================
Step 6：三类用户的稳定化信号对比
======================================================================

信号                       Immature      Stepper      Drifter
------------------------------------------------------------
gap_std↓                 -0.5351     -1.6411     -1.8689
Zone1↑                    0.2000      0.1806      0.1581
Zone5↓                    0.0000     -0.0111     -0.0317
reorder↑                  0.1857      0.1250      0.1487
basket_std↓               0.4617      0.4499      0.2598
dow_entropy↓              0.4714      0.0342      0.0482

综合稳定化得分                  -0.0376      0.0006      0.0281

✅ New tables created:
  - stability_df        (五个稳定化信号 + weekly，用户级）
  - score_df            (综合稳定化得分）
  - score_summary       (得分分桶 vs weekly）

In [105]:
# ============================================================
# Mid→High vs. Mid Stay: full comparison of early-stage metrics
# Purpose: see how different the two groups already are at the starting point
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Step 1: prepare early-stage metrics for both groups
# Extracted from analysis_mid_user_master
# ----------------------------------------
df_mh = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

df_ms = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Stay"
].copy()

print(f"Mid→High: {len(df_mh):,} users")
print(f"Mid Stay:  {len(df_ms):,} users")

# ----------------------------------------
# Step 2: define all early-stage metrics
# ----------------------------------------
early_metrics = {
    # Outcome
    "weekly_med_early"              : ("Outcome", "Weekly Items (early)"),
    # Basket
    "n_unique_products_early"       : ("Basket",  "Unique SKU (early)"),
    "n_unique_departments_early"    : ("Basket",  "Department count (early)"),
    "basket_med_early"              : ("Basket",  "Basket Size (early)"),
    "reorder_ratio_early"           : ("Basket",  "Reorder Ratio (early)"),
    "items_per_unique_product_early": ("Basket",  "Depth (early)"),
    # Gap
    "gap_med_early_x"               : ("Gap",     "Gap Median (early)"),
    "gap_std_early"                 : ("Gap",     "Gap Std (early)"),
    "pct_gap30_early"               : ("Gap",     "Pct Gap 30 days (early)"),
    # Order count
    "n_orders_half_early"           : ("User Structure", "order count (early)"),
}

# ----------------------------------------
# Step 3: compute comparison statistics for each metric
# Mean / Median + t-test + Cohen's d
# ----------------------------------------
results = []

for col, (category, description) in early_metrics.items():
    if col not in df_mh.columns:
        print(f"⚠️  {col} not in table, skipped")
        continue

    mh_vals = df_mh[col].dropna()
    ms_vals = df_ms[col].dropna()

    mh_mean   = mh_vals.mean()
    ms_mean   = ms_vals.mean()
    mh_median = mh_vals.median()
    ms_median = ms_vals.median()
    diff_mean = mh_mean - ms_mean

    # t-test
    t_stat, p_val = stats.ttest_ind(mh_vals, ms_vals, equal_var=False)

    # Cohen's d
    pooled_std = np.sqrt((mh_vals.std()**2 + ms_vals.std()**2) / 2)
    cohens_d   = diff_mean / pooled_std if pooled_std > 0 else np.nan

    sig = "***" if p_val < 0.001 else (
          "**"  if p_val < 0.01  else (
          "*"   if p_val < 0.05  else "ns"))

    direction = "↑" if diff_mean > 0 else "↓"

    results.append({
        "category"   : category,
        "metric"     : col,
        "description": description,
        "mh_mean"    : round(mh_mean,   4),
        "ms_mean"    : round(ms_mean,   4),
        "mh_median"  : round(mh_median, 4),
        "ms_median"  : round(ms_median, 4),
        "diff_mean"  : round(diff_mean, 4),
        "cohens_d"   : round(cohens_d,  4),
        "sig"        : sig,
        "direction"  : direction,
    })

results_df = pd.DataFrame(results)

# ----------------------------------------
# Step 4: mean-based output
# ----------------------------------------
print("\n" + "="*80)
print("Early-Stage Metric Comparison (Mean Version)")
print("="*80)
print(f"{'Category':<10} {'Metric':<35} {'MH Mean':>9} {'MS Mean':>9} "
      f"{'Diff':>8} {'Cohen_d':>9} {'Sig':>6}")
print("-"*85)

current_cat = ""
for _, row in results_df.iterrows():
    if row["category"] != current_cat:
        current_cat = row["category"]
        print(f"\n【{current_cat}】")
    print(f"  {row['description']:<33} "
          f"{row['mh_mean']:>9.4f} "
          f"{row['ms_mean']:>9.4f} "
          f"{row['diff_mean']:>+8.4f} "
          f"{row['cohens_d']:>9.4f} "
          f"{row['sig']:>4} {row['direction']}")

# ----------------------------------------
# Step 5: median-based output
# ----------------------------------------
print("\n" + "="*80)
print("Early-Stage Metric Comparison (Median Version, more robust)")
print("="*80)
print(f"{'Category':<10} {'Metric':<35} {'MH Median':>10} {'MS Median':>10} {'Diff':>8}")
print("-"*75)

current_cat = ""
for _, row in results_df.iterrows():
    if row["category"] != current_cat:
        current_cat = row["category"]
        print(f"\n【{current_cat}】")
    diff_med = row["mh_median"] - row["ms_median"]
    direction = "↑" if diff_med > 0 else "↓"
    print(f"  {row['description']:<33} "
          f"{row['mh_median']:>10.4f} "
          f"{row['ms_median']:>10.4f} "
          f"{diff_med:>+8.4f} {direction}")

# ----------------------------------------
# Step 6: Zone early-stage comparison
# Extracted from all_zone_wide (if available)
# ----------------------------------------
print("\n" + "="*80)
print("Zone Distribution Early Comparison")
print("="*80)

zone_early_cols = [
    "early_Zone1_weekly",
    "early_Zone2_biweekly",
    "early_Zone3_warning",
    "early_Zone4_danger",
    "early_Zone5_cliff",
]

# Merge in zone data
mh_zone_early = mh_zone[["user_id"] + zone_early_cols].copy()
ms_zone_early = ms_zone[["user_id"] + zone_early_cols].copy()

print(f"\n{'Zone':<25} {'MH Early':>10} {'MS Early':>10} {'Diff':>8} {'Cohen_d':>9}")
print("-"*65)

for col in zone_early_cols:
    mh_vals = mh_zone_early[col].dropna()
    ms_vals = ms_zone_early[col].dropna()

    mh_med = mh_vals.median()
    ms_med = ms_vals.median()
    mh_mean = mh_vals.mean()
    ms_mean = ms_vals.mean()
    diff = mh_mean - ms_mean

    pooled_std = np.sqrt((mh_vals.std()**2 + ms_vals.std()**2) / 2)
    cohens_d = diff / pooled_std if pooled_std > 0 else np.nan

    _, p_val = stats.ttest_ind(mh_vals, ms_vals, equal_var=False)
    sig = "***" if p_val < 0.001 else ("ns")

    direction = "↑" if diff > 0 else "↓"
    zone_name = col.replace("early_", "").replace("_", " ")
    print(f"  {zone_name:<23} {mh_mean:>10.1%} {ms_mean:>10.1%} "
          f"{diff:>+8.1%} {cohens_d:>9.4f} {sig} {direction}")

# ----------------------------------------
# Step 7: label distribution comparison (already available)
# ----------------------------------------
print("\n" + "="*60)
print("Label Distribution Comparison (Early User Structure)")
print("="*60)

label_mh = (
    df_mh["label"].value_counts(normalize=True)
    .rename("Mid→High").reset_index()
)
label_ms = (
    df_ms["label"].value_counts(normalize=True)
    .rename("Mid Stay").reset_index()
)

label_compare = label_mh.merge(
    label_ms, on="label", how="outer"
).fillna(0)
label_compare["diff"] = (
    label_compare["Mid→High"] - label_compare["Mid Stay"]
)
label_compare = label_compare.sort_values(
    "Mid→High", ascending=False
)

print(f"\n{'Label':<15} {'Mid→High':>10} {'Mid Stay':>10} {'Diff':>8}")
print("-"*48)
for _, row in label_compare.iterrows():
    direction = "↑" if row["diff"] > 0 else "↓"
    print(f"{row['label']:<15} {row['Mid→High']:>9.1%} "
          f"{row['Mid Stay']:>9.1%} {row['diff']:>+7.1%} {direction}")

# ----------------------------------------
# Step 8: effect-size summary
# ----------------------------------------
print("\n" + "="*60)
print("Effect Size Summary (sorted by |Cohen's d|)")
print("="*60)
print("< 0.2  : negligible difference")
print("0.2~0.5: small effect")
print("0.5~0.8: medium effect")
print("> 0.8  : large effect")

print("\nTop metrics by effect size:")
top = results_df.dropna(subset=["cohens_d"]).sort_values(
    "cohens_d", key=abs, ascending=False
)
print(top[["category", "description", "cohens_d", "sig"]]
      .head(8).to_string(index=False))

print("\n✅ New tables created:")
print("  - results_df     (full early-metric comparison)")
print("  - label_compare  (label distribution comparison)")

Mid→High: 14,217 users
Mid Stay:  43,780 users

================================================================================
Early 阶段指标对比（Mean 版本）
================================================================================
类别         指标                                    MH Mean   MS Mean       差值   Cohen_d    显著性
-------------------------------------------------------------------------------------

【结果】
  Weekly Items（早期）                     6.3778    5.6451  +0.7327    0.3738  *** ↑

【Basket】
  Unique SKU（早期）                      10.9340   10.1828  +0.7511    0.1375  *** ↑
  Department 数（早期）                     5.1961    5.0206  +0.1756    0.0885  *** ↑
  Basket Size（早期）                     10.9340   10.1828  +0.7511    0.1375  *** ↑
  Reorder Ratio（早期）                    0.4961    0.4598  +0.0363    0.1455  *** ↑
  Depth（早期）                            1.0000    1.0000  +0.0000       nan   ns ↓

【Gap】
  Gap Median（早期）                      13.0124   14.0831  -1.0707   -0.1395  *** ↓
  Gap Std（早期）                          7.5236    7.1661  +0.3575    0.1028  *** ↑
  Pct Gap 30天（早期）                      0.1365    0.1733  -0.0368   -0.1727  *** ↓

【用户结构】
  订单数（早期）                             10.5339    8.1118  +2.4221    0.3238  *** ↑

================================================================================
Early 阶段指标对比（Median 版本，更稳健）
================================================================================
类别         指标                                   MH Median  MS Median       差值
---------------------------------------------------------------------------

【结果】
  Weekly Items（早期）                      6.5333     5.4250  +1.1083 ↑

【Basket】
  Unique SKU（早期）                       10.0000     9.0000  +1.0000 ↑
  Department 数（早期）                      5.0000     5.0000  +0.0000 ↓
  Basket Size（早期）                      10.0000     9.0000  +1.0000 ↑
  Reorder Ratio（早期）                     0.5000     0.4500  +0.0500 ↑
  Depth（早期）                             1.0000     1.0000  +0.0000 ↓

【Gap】
  Gap Median（早期）                       11.0000    12.0000  -1.0000 ↓
  Gap Std（早期）                           7.6942     7.4464  +0.2478 ↑
  Pct Gap 30天（早期）                       0.0526     0.0769  -0.0243 ↓

【用户结构】
  订单数（早期）                               8.0000     6.0000  +2.0000 ↑

================================================================================
Zone 分布 Early 对比
================================================================================

Zone                        MH Early   MS Early       差值   Cohen_d
-----------------------------------------------------------------
  Zone1 weekly                 37.3%      30.7%    +6.6%    0.2351 *** ↑
  Zone2 biweekly               27.3%      28.1%    -0.8%   -0.0365 *** ↓
  Zone3 warning                13.2%      14.9%    -1.7%   -0.0905 *** ↓
  Zone4 danger                  7.5%       9.0%    -1.5%   -0.0992 *** ↓
  Zone5 cliff                  14.7%      17.4%    -2.6%   -0.1117 *** ↓

============================================================
Label 分布对比（Early 用户结构）
============================================================

Label             Mid→High   Mid Stay       差值
------------------------------------------------
immature            36.0%     46.8%  -10.8% ↓
stepper             32.5%     21.0%  +11.5% ↑
drifter             26.8%     21.1%   +5.8% ↑
oscillator           2.9%      6.2%   -3.3% ↓
mixed                1.8%      5.0%   -3.2% ↓

============================================================
效应量总结（按 |Cohen's d| 排序）
============================================================
< 0.2  : 微小差异
0.2~0.5: 小效应
0.5~0.8: 中效应
> 0.8  : 大效应

Top 效应量指标：
category       description  cohens_d sig
      结果  Weekly Items（早期）    0.3738 ***
    用户结构           订单数（早期）    0.3238 ***
     Gap   Pct Gap 30天（早期）   -0.1727 ***
  Basket Reorder Ratio（早期）    0.1455 ***
     Gap    Gap Median（早期）   -0.1395 ***
  Basket    Unique SKU（早期）    0.1375 ***
  Basket   Basket Size（早期）    0.1375 ***
     Gap       Gap Std（早期）    0.1028 ***

✅ New tables created:
  - results_df     (Early 指标完整对比)
  - label_compare  (Label 分布对比)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/scipy/stats/_axis_nan_policy.py:579: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

In [106]:
# ============================================================
# Mid→High vs. Mid Stay: full Early / Late / Delta comparison
# Purpose: show that starting points are similar but later stages diverge completely
# ============================================================

import pandas as pd
import numpy as np
from scipy import stats

# ----------------------------------------
# Step 1: prepare the two user groups
# ----------------------------------------
df_mh = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

df_ms = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Stay"
].copy()

print(f"Mid→High: {len(df_mh):,} users")
print(f"Mid Stay:  {len(df_ms):,} users")

# ----------------------------------------
# Step 2: define Early / Late / Delta metric pairs
# ----------------------------------------
metric_pairs = {
    # Outcome
    "weekly" : {
        "early" : "weekly_med_early",
        "late"  : "weekly_med_late",
        "delta" : "delta_weekly",
        "cat"   : "Outcome",
        "label" : "Weekly Items",
    },
    # Basket
    "unique_sku" : {
        "early" : "n_unique_products_early",
        "late"  : "n_unique_products_late",
        "delta" : "delta_n_unique_products",
        "cat"   : "Basket",
        "label" : "Unique SKU",
    },
    "basket_med" : {
        "early" : "basket_med_early",
        "late"  : "basket_med_late",
        "delta" : "delta_basket_med",
        "cat"   : "Basket",
        "label" : "Basket Size",
    },
    "departments" : {
        "early" : "n_unique_departments_early",
        "late"  : "n_unique_departments_late",
        "delta" : "delta_n_unique_departments",
        "cat"   : "Basket",
        "label" : "Departments",
    },
    "reorder" : {
        "early" : "reorder_ratio_early",
        "late"  : "reorder_ratio_late",
        "delta" : "delta_reorder_ratio",
        "cat"   : "Basket",
        "label" : "Reorder Ratio",
    },
    # Gap
    "gap_std" : {
        "early" : "gap_std_early",
        "late"  : "gap_std_late",
        "delta" : "delta_gap_std",
        "cat"   : "Gap",
        "label" : "Gap Std",
    },
    "pct_gap30" : {
        "early" : "pct_gap30_early",
        "late"  : "pct_gap30_late",
        "delta" : "delta_pct_gap30",
        "cat"   : "Gap",
        "label" : "Pct Gap 30 days",
    },
}

# ----------------------------------------
# Step 3: compute Early / Late / Delta for
# MH vs. MS comparison (Mean + Median + Cohen's d)
# ----------------------------------------

def compare_metric(col, df_mh, df_ms):
    """Compute the MH vs. MS comparison for one metric"""
    if col not in df_mh.columns or col not in df_ms.columns:
        return None, None, None, None, None

    mh_vals = df_mh[col].dropna()
    ms_vals = df_ms[col].dropna()

    mh_mean   = mh_vals.mean()
    ms_mean   = ms_vals.mean()
    mh_median = mh_vals.median()
    ms_median = ms_vals.median()
    diff_mean = mh_mean - ms_mean

    pooled_std = np.sqrt((mh_vals.std()**2 + ms_vals.std()**2) / 2)
    cohens_d   = diff_mean / pooled_std if pooled_std > 0 else np.nan

    _, p_val = stats.ttest_ind(mh_vals, ms_vals, equal_var=False)
    sig = "***" if p_val < 0.001 else (
          "**"  if p_val < 0.01  else (
          "*"   if p_val < 0.05  else "ns"))

    return (
        round(mh_median, 3),
        round(ms_median, 3),
        round(mh_median - ms_median, 3),
        round(cohens_d, 3),
        sig
    )

# ----------------------------------------
# Step 4: output the full comparison table
# ----------------------------------------
print("\n" + "="*100)
print("Full Early vs. Late Comparison: Mid→High vs. Mid Stay (Median Version)")
print("="*100)
print(f"{'Category':<8} {'Metric':<16} "
      f"{'MH Early':>9} {'MS Early':>9} {'Early Diff':>9} {'Early_d':>8} "
      f"{'MH Late':>9} {'MS Late':>9} {'Late Diff':>9} {'Late_d':>8} "
      f"{'MH Delta':>9} {'MS Delta':>9} {'Delta Diff':>9}")
print("-"*130)

current_cat = ""
summary_rows = []

for key, info in metric_pairs.items():
    if info["cat"] != current_cat:
        current_cat = info["cat"]
        print(f"\n【{current_cat}】")

    # Early
    mh_e, ms_e, diff_e, cd_e, sig_e = compare_metric(
        info["early"], df_mh, df_ms
    )
    # Late
    mh_l, ms_l, diff_l, cd_l, sig_l = compare_metric(
        info["late"], df_mh, df_ms
    )
    # Delta
    mh_d, ms_d, diff_d, cd_d, sig_d = compare_metric(
        info["delta"], df_mh, df_ms
    )

    # Determine direction
    dir_e = "↑" if diff_e and diff_e > 0 else "↓"
    dir_l = "↑" if diff_l and diff_l > 0 else "↓"
    dir_d = "↑" if diff_d and diff_d > 0 else "↓"

    print(f"  {info['label']:<14} "
          f"{mh_e:>9} {ms_e:>9} {diff_e:>+9} {cd_e:>7}{sig_e:>3} "
          f"{mh_l:>9} {ms_l:>9} {diff_l:>+9} {cd_l:>7}{sig_l:>3} "
          f"{mh_d:>9} {ms_d:>9} {diff_d:>+9}")

    summary_rows.append({
        "category"  : info["cat"],
        "metric"    : info["label"],
        "early_diff": diff_e,
        "early_cd"  : cd_e,
        "late_diff" : diff_l,
        "late_cd"   : cd_l,
        "delta_diff": diff_d,
    })

# ----------------------------------------
# Step 5: Zone Early vs. Late comparison
# ----------------------------------------
print("\n" + "="*80)
print("Zone Distribution: Early vs. Late (MH vs. MS)")
print("="*80)

zone_pairs = [
    ("Zone1 Weekly",   "early_Zone1_weekly",   "late_Zone1_weekly"),
    ("Zone2 Biweekly", "early_Zone2_biweekly", "late_Zone2_biweekly"),
    ("Zone3 Warning",  "early_Zone3_warning",  "late_Zone3_warning"),
    ("Zone4 Danger",   "early_Zone4_danger",   "late_Zone4_danger"),
    ("Zone5 Cliff",    "early_Zone5_cliff",    "late_Zone5_cliff"),
]

print(f"\n{'Zone':<18} "
      f"{'MH Early':>9} {'MS Early':>9} {'Early Diff':>9} "
      f"{'MH Late':>9} {'MS Late':>9} {'Late Diff':>9}")
print("-"*75)

for zone_label, early_col, late_col in zone_pairs:
    # Early
    mh_e = mh_zone[early_col].mean() if early_col in mh_zone.columns else None
    ms_e = ms_zone[early_col].mean() if early_col in ms_zone.columns else None
    diff_e = mh_e - ms_e if mh_e and ms_e else None

    # Late
    mh_l = mh_zone[late_col].mean() if late_col in mh_zone.columns else None
    ms_l = ms_zone[late_col].mean() if late_col in ms_zone.columns else None
    diff_l = mh_l - ms_l if mh_l and ms_l else None

    dir_e = "↑" if diff_e and diff_e > 0 else "↓"
    dir_l = "↑" if diff_l and diff_l > 0 else "↓"

    print(f"  {zone_label:<16} "
          f"{mh_e:>8.1%} {ms_e:>8.1%} {diff_e:>+8.1%} {dir_e} "
          f"{mh_l:>8.1%} {ms_l:>8.1%} {diff_l:>+8.1%} {dir_l}")

# ----------------------------------------
# Step 6: effect-size comparison
# Early Cohen's d vs Late Cohen's d
# Validate: is the late-stage difference much larger than the early-stage difference?
# ----------------------------------------
print("\n" + "="*70)
print("Effect Size Comparison: Early vs. Late Cohen's d")
print("(validate whether the late-stage difference is significantly larger than early)")
print("="*70)
print(f"{'Metric':<16} {'Early Cohen_d':>14} {'Late Cohen_d':>13} {'Amplification':>10}")
print("-"*58)

for row in summary_rows:
    if row["early_cd"] and row["late_cd"]:
        amplification = abs(row["late_cd"]) / abs(row["early_cd"]) \
                        if row["early_cd"] != 0 else np.nan
        print(f"  {row['metric']:<14} "
              f"{row['early_cd']:>14.3f} "
              f"{row['late_cd']:>13.3f} "
              f"{amplification:>9.1f}x")

# ----------------------------------------
# Step 7: core conclusion
# ----------------------------------------
print("\n" + "="*70)
print("Core Conclusion: Starting Point vs. Late-Stage Difference Comparison")
print("="*70)
print("\nMetrics with the largest Early-stage difference:")
top_early = sorted(
    summary_rows,
    key=lambda x: abs(x["early_cd"]) if x["early_cd"] else 0,
    reverse=True
)[:3]
for row in top_early:
    print(f"  {row['metric']:<16} Cohen's d = {row['early_cd']:.3f}")

print("\nMetrics with the largest Late-stage difference:")
top_late = sorted(
    summary_rows,
    key=lambda x: abs(x["late_cd"]) if x["late_cd"] else 0,
    reverse=True
)[:3]
for row in top_late:
    print(f"  {row['metric']:<16} Cohen's d = {row['late_cd']:.3f}")

print("\n✅ New tables created:")
print("  - summary_rows  (Early vs. Late effect-size comparison)")

Mid→High: 14,217 users
Mid Stay:  43,780 users

====================================================================================================
Early vs Late 完整对比：Mid→High vs Mid Stay（Median 版本）
====================================================================================================
类别       指标                MH Early  MS Early   Early差值  Early_d   MH Late   MS Late    Late差值   Late_d  MH Delta  MS Delta   Delta差值
----------------------------------------------------------------------------------------------------------------------------------

【结果】
  Weekly Items       6.533     5.425    +1.108   0.374***    11.667      5.25    +6.417   1.937***     5.804    -0.044    +5.848

【Basket】
  Unique SKU          10.0       9.0      +1.0   0.138***      12.0       9.0      +3.0    0.55***       2.0       0.0      +2.0
  Basket Size         10.0       9.0      +1.0   0.138***      12.0       9.0      +3.0    0.55***       2.0       0.0      +2.0
  Departments          5.0       5.0      +0.0   0.089***       6.0       5.0      +1.0    0.42***       0.5       0.0      +0.5
  Reorder Ratio        0.5      0.45     +0.05   0.146***     0.667     0.641    +0.026   0.044***     0.152     0.169    -0.017

【Gap】
  Gap Std            7.694     7.446    +0.248   0.103***      5.63     8.025    -2.395  -0.413***    -1.373     0.345    -1.719
  Pct Gap 30天        0.053     0.077    -0.024  -0.173***       0.0     0.125    -0.125  -0.726***       0.0       0.0      +0.0

================================================================================
Zone 分布：Early vs Late（MH vs MS）
================================================================================

Zone                MH Early  MS Early   Early差值   MH Late   MS Late    Late差值
---------------------------------------------------------------------------
  Zone1 Weekly        37.3%    30.7%    +6.6% ↑    55.1%    30.1%   +25.0% ↑
  Zone2 Biweekly      27.3%    28.1%    -0.8% ↓    25.7%    26.3%    -0.5% ↓
  Zone3 Warning       13.2%    14.9%    -1.7% ↓     8.6%    14.2%    -5.6% ↓
  Zone4 Danger         7.5%     9.0%    -1.5% ↓     3.9%     9.1%    -5.1% ↓
  Zone5 Cliff         14.7%    17.4%    -2.6% ↓     6.7%    20.4%   -13.7% ↓

======================================================================
效应量对比：Early vs Late Cohen's d
（验证后期差异是否显著大于早期）
======================================================================
指标                Early Cohen_d  Late Cohen_d       放大倍数
----------------------------------------------------------
  Weekly Items            0.374         1.937       5.2x
  Unique SKU              0.138         0.550       4.0x
  Basket Size             0.138         0.550       4.0x
  Departments             0.089         0.420       4.7x
  Reorder Ratio           0.146         0.044       0.3x
  Gap Std                 0.103        -0.413       4.0x
  Pct Gap 30天            -0.173        -0.726       4.2x

======================================================================
核心结论：起点 vs 后期差异对比
======================================================================

早期（Early）差异最大的指标：
  Weekly Items     Cohen's d = 0.374
  Pct Gap 30天      Cohen's d = -0.173
  Reorder Ratio    Cohen's d = 0.146

后期（Late）差异最大的指标：
  Weekly Items     Cohen's d = 1.937
  Pct Gap 30天      Cohen's d = -0.726
  Unique SKU       Cohen's d = 0.550

✅ New tables created:
  - summary_rows  (Early vs Late 效应量对比)

In [107]:
# Directly compare the correlation between the two metrics
# If they're the same thing, correlation should be close to 1.0

from scipy import stats

valid = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
][["user_id", "pct_gap30_early"]].merge(
    user_zone_wide[["user_id", "early_Zone5_cliff"]],
    on="user_id", how="inner"
).dropna()

r, p = stats.pearsonr(
    valid["pct_gap30_early"],
    valid["early_Zone5_cliff"]
)
print(f"Pearson correlation: {r:.4f}")
print(f"\nMean pct_gap30_early:    {valid['pct_gap30_early'].mean():.4f}")
print(f"Mean early_Zone5_cliff:  {valid['early_Zone5_cliff'].mean():.4f}")

Pearson correlation: 0.9528

Mean pct_gap30_early:    0.1365
Mean early_Zone5_cliff:  0.1475

In [108]:
# Directly look at both metrics' distributions
print("pct_gap30_early distribution:")
print(analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
]["pct_gap30_early"].describe())

print("\nearly_Zone5_cliff distribution:")
print(mh_zone["early_Zone5_cliff"].describe())

pct_gap30_early 分布：
count    14217.000000
mean         0.136476
std          0.191724
min          0.000000
25%          0.000000
50%          0.052632
75%          0.214286
max          1.000000
Name: pct_gap30_early, dtype: float64

early_Zone5_cliff 分布：
count    14217.000000
mean         0.147496
std          0.218423
min          0.000000
25%          0.000000
50%          0.050000
75%          0.222222
max          1.000000
Name: early_Zone5_cliff, dtype: float64

In [109]:
# ============================================================
# Conditional repurchase-rate analysis
# For Mid→High users only
# Find the optimal intervention timing
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# Step 0: prepare data
# Keep only Mid→High users
# ----------------------------------------

# Get the list of Mid→High users
mh_users = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
][["user_id"]].copy()

print(f"Mid→High users: {len(mh_users):,}")

# Keep only Mid→High users' orders
mh_orders_full = (
    orders_enriched2
    .merge(mh_users, on="user_id", how="inner")
    .sort_values(["user_id", "order_number"])
    .copy()
)

print(f"Mid→High orders: {len(mh_orders_full):,}")

# Compute next_gap (days until the next order)
mh_orders_full["next_gap"] = (
    mh_orders_full
    .groupby("user_id")["gap_days_adj"]
    .shift(-1)
)

print(f"Orders with next_gap: {mh_orders_full['next_gap'].notna().sum():,}")

# ----------------------------------------
# Step 1: coarse scan (10-30 days, 5-day increments)
# ----------------------------------------
print("\n" + "="*60)
print("Step 1: Coarse-Grained Scan")
print("="*60)

coarse_cutoffs = [10, 15, 20, 25, 30]
recovery_window = 7

coarse_results = []

for cutoff in coarse_cutoffs:
    at_risk = mh_orders_full[
        mh_orders_full["gap_days_adj"] >= cutoff
    ].copy()

    recovered = at_risk[
        at_risk["next_gap"] <= recovery_window
    ]

    n_at_risk   = len(at_risk)
    n_recovered = len(recovered)
    rate = n_recovered / n_at_risk if n_at_risk > 0 else 0

    coarse_results.append({
        "cutoff_day"    : cutoff,
        "n_at_risk"     : n_at_risk,
        "n_recovered"   : n_recovered,
        "recovery_rate" : rate,
    })

    print(f"Day {cutoff:>3}: "
          f"at_risk={n_at_risk:>7,} "
          f"recovered={n_recovered:>7,} "
          f"rate={rate:.1%}")

coarse_df = pd.DataFrame(coarse_results)

# Find the approximate inflection range
coarse_df["rate_drop"] = coarse_df["recovery_rate"].diff().abs()
peak_drop_idx = coarse_df["rate_drop"].idxmax()
approx_range_start = coarse_df.loc[
    peak_drop_idx - 1, "cutoff_day"
] if peak_drop_idx > 0 else 10
approx_range_end = coarse_df.loc[peak_drop_idx, "cutoff_day"]

print(f"\n→ Largest decline range: Day {approx_range_start} ~ Day {approx_range_end}")
print(f"→ Entering fine-grained scan: Day {approx_range_start - 2} ~ Day {approx_range_end + 2}")

# ----------------------------------------
# Step 2: fine-grained scan (within the locked range, day by day)
# ----------------------------------------
print("\n" + "="*60)
print("Step 2: Fine-Grained Scan (day by day)")
print("="*60)

fine_start = max(7,  approx_range_start - 3)
fine_end   = min(30, approx_range_end   + 3)
fine_cutoffs = list(range(fine_start, fine_end + 1))

fine_results = []

for cutoff in fine_cutoffs:
    at_risk = mh_orders_full[
        mh_orders_full["gap_days_adj"] >= cutoff
    ].copy()

    recovered = at_risk[
        at_risk["next_gap"] <= recovery_window
    ]

    n_at_risk   = len(at_risk)
    n_recovered = len(recovered)
    rate = n_recovered / n_at_risk if n_at_risk > 0 else 0

    fine_results.append({
        "cutoff_day"    : cutoff,
        "n_at_risk"     : n_at_risk,
        "n_recovered"   : n_recovered,
        "recovery_rate" : rate,
    })

    print(f"Day {cutoff:>3}: "
          f"at_risk={n_at_risk:>7,} "
          f"rate={rate:.1%}")

fine_df = pd.DataFrame(fine_results)

# ----------------------------------------
# Step 3: find the precise inflection point
# ----------------------------------------
print("\n" + "="*60)
print("Step 3: Precise Inflection Point Analysis")
print("="*60)

fine_df["rate_drop"] = fine_df["recovery_rate"].diff().abs()
fine_df["rate_drop_pct"] = (
    fine_df["recovery_rate"].pct_change().abs()
)

print("\nDay-by-day repurchase rate change:")
print(f"{'Day':>5} {'Rate':>8} {'Drop':>8} {'Drop%':>8}")
print("-"*35)
for _, row in fine_df.iterrows():
    print(f"{row['cutoff_day']:>5} "
          f"{row['recovery_rate']:>8.1%} "
          f"{row['rate_drop']:>8.1%} "
          f"{row['rate_drop_pct']:>8.1%}")

best_cutoff_idx  = fine_df["rate_drop"].idxmax()
best_cutoff_day  = fine_df.loc[best_cutoff_idx, "cutoff_day"]
best_cutoff_rate = fine_df.loc[best_cutoff_idx, "recovery_rate"]

print(f"\n→ Precise inflection point: Day {best_cutoff_day}")
print(f"→ Repurchase rate at inflection: {best_cutoff_rate:.1%}")
print(f"→ Recommended intervention timing: Day {best_cutoff_day - 1} ~ Day {best_cutoff_day}")

# ----------------------------------------
# Step 4: full curve (Day 7-30)
# ----------------------------------------
print("\n" + "="*60)
print("Step 4: Full Conditional Repurchase-Rate Curve (Day 7-30)")
print("="*60)

all_results = []
for cutoff in range(7, 31):
    at_risk = mh_orders_full[
        mh_orders_full["gap_days_adj"] >= cutoff
    ]
    recovered = at_risk[
        at_risk["next_gap"] <= recovery_window
    ]
    n_at_risk = len(at_risk)
    rate = len(recovered) / n_at_risk if n_at_risk > 0 else 0

    all_results.append({
        "cutoff_day"    : cutoff,
        "n_at_risk"     : n_at_risk,
        "recovery_rate" : rate,
    })

all_df = pd.DataFrame(all_results)

print(f"\n{'Day':>5} {'At Risk':>10} {'Recovery Rate':>15}")
print("-"*35)
for _, row in all_df.iterrows():
    marker = " ← inflection" if row["cutoff_day"] == best_cutoff_day else ""
    print(f"{row['cutoff_day']:>5} "
          f"{row['n_at_risk']:>10,} "
          f"{row['recovery_rate']:>14.1%}{marker}")

# ----------------------------------------
# Step 5: business recommendation
# ----------------------------------------
print("\n" + "="*60)
print("Step 5: Business Recommendation")
print("="*60)

intervention_day = best_cutoff_day - 1
rate_at_intervention = all_df[
    all_df["cutoff_day"] == intervention_day
]["recovery_rate"].values[0]

rate_at_30 = all_df[
    all_df["cutoff_day"] == 30
]["recovery_rate"].values[0]

print(f"""
Optimal intervention timing for Mid→High users: Day {intervention_day}

Intervening at Day {intervention_day}:
→ Repurchase rate = {rate_at_intervention:.1%}

Intervening only at Day 30:
→ Repurchase rate = {rate_at_30:.1%}

Value of early intervention:
→ Repurchase rate improves {rate_at_intervention - rate_at_30:.1%}
→ Recommend sending a "Running Low" reminder on Day {intervention_day}
""")

print("\n✅ New tables created:")
print("  - coarse_df   (coarse-grained scan results)")
print("  - fine_df     (fine-grained scan results)")
print("  - all_df      (full curve, Day 7-30)")

Mid→High users: 14,217
Mid→High orders: 306,575
Orders with next_gap: 292,358

============================================================
Step 1：粗粒度扫描
============================================================
Day  10: at_risk=100,829 recovered= 39,211 rate=38.9%
Day  15: at_risk= 57,420 recovered= 20,273 rate=35.3%
Day  20: at_risk= 37,711 recovered= 12,456 rate=33.0%
Day  25: at_risk= 25,448 recovered=  7,893 rate=31.0%
Day  30: at_risk= 18,556 recovered=  5,531 rate=29.8%

→ 最大下降区间：Day 10 ~ Day 15
→ 进入细粒度扫描：Day 8 ~ Day 17

============================================================
Step 2：细粒度扫描（逐天）
============================================================
Day   7: at_risk=167,132 rate=45.5%
Day   8: at_risk=133,132 rate=42.5%
Day   9: at_risk=113,496 rate=40.3%
Day  10: at_risk=100,829 rate=38.9%
Day  11: at_risk= 90,690 rate=37.9%
Day  12: at_risk= 82,290 rate=37.2%
Day  13: at_risk= 74,719 rate=36.6%
Day  14: at_risk= 66,597 rate=36.2%
Day  15: at_risk= 57,420 rate=35.3%
Day  16: at_risk= 51,321 rate=34.5%
Day  17: at_risk= 47,179 rate=33.9%
Day  18: at_risk= 43,681 rate=33.4%

============================================================
Step 3：精确拐点分析
============================================================

逐天回购率变化：
  Day     Rate     Drop    Drop%
-----------------------------------
  7.0    45.5%     nan%     nan%
  8.0    42.5%     3.0%     6.7%
  9.0    40.3%     2.2%     5.2%
 10.0    38.9%     1.4%     3.4%
 11.0    37.9%     1.0%     2.5%
 12.0    37.2%     0.7%     1.9%
 13.0    36.6%     0.6%     1.7%
 14.0    36.2%     0.4%     1.0%
 15.0    35.3%     0.9%     2.5%
 16.0    34.5%     0.8%     2.3%
 17.0    33.9%     0.6%     1.8%
 18.0    33.4%     0.5%     1.3%

→ 精确拐点：Day 8
→ 拐点回购率：42.5%
→ 建议干预时机：Day 7 ~ Day 8

============================================================
Step 4：完整条件回购率曲线（Day 7-30）
============================================================

  Day    At Risk   Recovery Rate
-----------------------------------
  7.0  167,132.0          45.5%
  8.0  133,132.0          42.5% ← 拐点
  9.0  113,496.0          40.3%
 10.0  100,829.0          38.9%
 11.0   90,690.0          37.9%
 12.0   82,290.0          37.2%
 13.0   74,719.0          36.6%
 14.0   66,597.0          36.2%
 15.0   57,420.0          35.3%
 16.0   51,321.0          34.5%
 17.0   47,179.0          33.9%
 18.0   43,681.0          33.4%
 19.0   40,561.0          33.1%
 20.0   37,711.0          33.0%
 21.0   34,639.0          32.8%
 22.0   31,151.0          32.2%
 23.0   28,731.0          31.8%
 24.0   26,938.0          31.3%
 25.0   25,448.0          31.0%
 26.0   24,100.0          30.8%
 27.0   22,783.0          30.6%
 28.0   21,407.0          30.4%
 29.0   19,713.0          30.2%
 30.0   18,556.0          29.8%

============================================================
Step 5：业务建议
============================================================

Mid→High 用户最优干预时机：Day 7

在 Day 7 干预：
→ 回购率 = 45.5%

在 Day 30 才干预：
→ 回购率 = 29.8%

提前干预的价值：
→ 回购率提升 15.7%
→ 建议在 Day 7 发送 Running Low 提醒


✅ New tables created:
  - coarse_df   (粗粒度扫描结果)
  - fine_df     (细粒度扫描结果)
  - all_df      (完整曲线 Day 7-30)

_Find the strongest cutoff day via delta_

In [110]:
# ============================================================
# Step 0: first add pos and half columns to mh_orders_full
# ============================================================

# Compute total order count per user
user_n_orders = (
    mh_orders_full
    .groupby("user_id")["order_number"]
    .max()
    .reset_index()
    .rename(columns={"order_number": "n_orders"})
)

# Add n_orders
mh_orders_full = mh_orders_full.merge(
    user_n_orders, on="user_id", how="left"
)

# Compute pos (the order's position within the user's lifecycle)
mh_orders_full["pos"] = (
    mh_orders_full["order_number"] /
    mh_orders_full["n_orders"]
)

# Tag early / late (first 50% / last 50%)
mh_orders_full["half"] = np.where(
    mh_orders_full["pos"] <= 0.5, "early", "late"
)

# Validate
print(f"mh_orders_full shape: {mh_orders_full.shape}")
print(f"columns: {mh_orders_full.columns.tolist()}")
print(f"\nhalf distribution:")
print(mh_orders_full["half"].value_counts())
print(f"\npos distribution:")
print(mh_orders_full["pos"].describe())

mh_orders_full shape: (306575, 14)
columns: ['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', 'items_per_order', 'active_score_week', 'gap_days_adj', 'next_gap', 'n_orders', 'pos', 'half']

half 分布：
half
late     163978
early    142597
Name: count, dtype: int64

pos 分布：
count    306575.000000
mean          0.542998
std           0.278084
min           0.020000
25%           0.305556
50%           0.545455
75%           0.783784
max           1.000000
Name: pos, dtype: float64

In [111]:
# ============================================================
# Find the strongest gap cutoff (delta version)
# For each cutoff X:
# Compute delta_pct_gap_geX = late - early
# See which one correlates most strongly with d_log_weekly
# ============================================================

from scipy import stats
import pandas as pd
import numpy as np

# ----------------------------------------
# Step 1: prepare data
# For each user, compute the early/late stage separately
# Share of orders with gap >= X
# ----------------------------------------
mh_base = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
][["user_id", "d_log_weekly"]].copy()

print(f"Mid→High users: {len(mh_base):,}")

# Split into early / late
mh_early = mh_orders_full[mh_orders_full["half"] == "early"].copy()
mh_late  = mh_orders_full[mh_orders_full["half"] == "late"].copy()

print(f"Early orders: {len(mh_early):,}")
print(f"Late orders:  {len(mh_late):,}")

# ----------------------------------------
# Step 2: compute delta for each cutoff
# ----------------------------------------
results = []

for cutoff in range(7, 31):

    # Early stage: each user's share of gap >= cutoff
    early_pct = (
        mh_early
        .groupby("user_id")["gap_days_adj"]
        .apply(lambda x: (x >= cutoff).mean())
        .reset_index()
        .rename(columns={"gap_days_adj": "early_pct"})
    )

    # Late stage: each user's share of gap >= cutoff
    late_pct = (
        mh_late
        .groupby("user_id")["gap_days_adj"]
        .apply(lambda x: (x >= cutoff).mean())
        .reset_index()
        .rename(columns={"gap_days_adj": "late_pct"})
    )

    # Merge and compute delta
    merged = (
        mh_base
        .merge(early_pct, on="user_id", how="inner")
        .merge(late_pct,  on="user_id", how="inner")
        .dropna()
    )

    merged["delta_pct"] = merged["late_pct"] - merged["early_pct"]

    # Compute correlation
    spearman_r, spearman_p = stats.spearmanr(
        merged["delta_pct"],
        merged["d_log_weekly"]
    )

    sig = "***" if spearman_p < 0.001 else (
          "**"  if spearman_p < 0.01  else (
          "*"   if spearman_p < 0.05  else "ns"))

    results.append({
        "cutoff"     : cutoff,
        "spearman_r" : round(spearman_r, 4),
        "sig"        : sig,
        "n"          : len(merged),
        "early_mean" : round(merged["early_pct"].mean(), 4),
        "late_mean"  : round(merged["late_pct"].mean(),  4),
        "delta_mean" : round(merged["delta_pct"].mean(), 4),
    })

results_df = pd.DataFrame(results)

# ----------------------------------------
# Step 3: output results
# ----------------------------------------
print("\n" + "="*70)
print("Delta Gap Cutoff vs. Weekly Growth Correlation")
print("="*70)
print(f"{'Cutoff':>8} {'Early':>8} {'Late':>8} "
      f"{'Delta':>8} {'Spearman':>10} {'Sig':>6}")
print("-"*55)

best_r = results_df["spearman_r"].min()

for _, row in results_df.iterrows():
    marker = " ← strongest" if row["spearman_r"] == best_r else ""
    print(f"ge{row['cutoff']:>2}d    "
          f"{row['early_mean']:>8.3f} "
          f"{row['late_mean']:>8.3f} "
          f"{row['delta_mean']:>+8.3f} "
          f"{row['spearman_r']:>10.4f} "
          f"{row['sig']:>6}{marker}")

# ----------------------------------------
# Step 4: find the strongest cutoff
# ----------------------------------------
best_idx     = results_df["spearman_r"].idxmin()
best_cutoff  = results_df.loc[best_idx, "cutoff"]
best_r       = results_df.loc[best_idx, "spearman_r"]

print(f"\n→ Cutoff with the strongest correlation: Day {best_cutoff}")
print(f"→ Spearman r = {best_r:.4f}")

# Compare key breakpoints
print(f"\nKey breakpoint comparison:")
for day in [7, 10, 15, 20, 22, 25, 30]:
    row = results_df[results_df["cutoff"] == day].iloc[0]
    print(f"  ge{day:>2}d: "
          f"Spearman = {row['spearman_r']:>8.4f} "
          f"{row['sig']}")

# ----------------------------------------
# Step 5: copyable table
# ----------------------------------------
print("\n" + "="*50)
print("Copyable table for Excel:")
print("="*50)
print("Cutoff\tEarly Mean\tLate Mean\tDelta Mean\tSpearman r\tSig")
for _, row in results_df.iterrows():
    print(f"ge{row['cutoff']}d\t"
          f"{row['early_mean']:.3f}\t"
          f"{row['late_mean']:.3f}\t"
          f"{row['delta_mean']:+.3f}\t"
          f"{row['spearman_r']:.4f}\t"
          f"{row['sig']}")

print("\n✅ New tables created:")
print("  - results_df  (correlation summary for each cutoff)")

Mid→High users: 14,217
Early orders: 142,597
Late orders:  163,978

======================================================================
Delta Gap Cutoff vs Weekly Growth 相关性
======================================================================
  Cutoff    Early     Late    Delta   Spearman    Sig
-------------------------------------------------------
ge 7d       0.721    0.567   -0.154    -0.2928    ***
ge 8d       0.627    0.449   -0.178    -0.3297    ***
ge 9d       0.568    0.382   -0.185    -0.3392    ***
ge10d       0.525    0.339   -0.185    -0.3453    *** ← 最强
ge11d       0.489    0.304   -0.185    -0.3446    ***
ge12d       0.458    0.277   -0.181    -0.3369    ***
ge13d       0.428    0.251   -0.177    -0.3336    ***
ge14d       0.394    0.224   -0.170    -0.3279    ***
ge15d       0.354    0.192   -0.162    -0.3296    ***
ge16d       0.326    0.172   -0.154    -0.3227    ***
ge17d       0.306    0.158   -0.148    -0.3167    ***
ge18d       0.290    0.147   -0.143    -0.3142    ***
ge19d       0.274    0.137   -0.137    -0.3029    ***
ge20d       0.259    0.127   -0.132    -0.3014    ***
ge21d       0.242    0.117   -0.125    -0.2982    ***
ge22d       0.222    0.106   -0.116    -0.2931    ***
ge23d       0.209    0.098   -0.111    -0.2883    ***
ge24d       0.199    0.093   -0.106    -0.2818    ***
ge25d       0.190    0.088   -0.103    -0.2737    ***
ge26d       0.182    0.084   -0.099    -0.2678    ***
ge27d       0.174    0.080   -0.094    -0.2569    ***
ge28d       0.165    0.075   -0.090    -0.2530    ***
ge29d       0.154    0.070   -0.084    -0.2512    ***
ge30d       0.147    0.067   -0.081    -0.2444    ***

→ 相关性最强的 cutoff：Day 10
→ Spearman r = -0.3453

关键节点对比：
  ge 7d: Spearman =  -0.2928 ***
  ge10d: Spearman =  -0.3453 ***
  ge15d: Spearman =  -0.3296 ***
  ge20d: Spearman =  -0.3014 ***
  ge22d: Spearman =  -0.2931 ***
  ge25d: Spearman =  -0.2737 ***
  ge30d: Spearman =  -0.2444 ***

==================================================
可复制到 Excel 的表格：
==================================================
Cutoff	Early Mean	Late Mean	Delta Mean	Spearman r	Sig
ge7d	0.721	0.567	-0.154	-0.2928	***
ge8d	0.627	0.449	-0.178	-0.3297	***
ge9d	0.568	0.382	-0.185	-0.3392	***
ge10d	0.525	0.339	-0.185	-0.3453	***
ge11d	0.489	0.304	-0.185	-0.3446	***
ge12d	0.458	0.277	-0.181	-0.3369	***
ge13d	0.428	0.251	-0.177	-0.3336	***
ge14d	0.394	0.224	-0.170	-0.3279	***
ge15d	0.354	0.192	-0.162	-0.3296	***
ge16d	0.326	0.172	-0.154	-0.3227	***
ge17d	0.306	0.158	-0.148	-0.3167	***
ge18d	0.290	0.147	-0.143	-0.3142	***
ge19d	0.274	0.137	-0.137	-0.3029	***
ge20d	0.259	0.127	-0.132	-0.3014	***
ge21d	0.242	0.117	-0.125	-0.2982	***
ge22d	0.222	0.106	-0.116	-0.2931	***
ge23d	0.209	0.098	-0.111	-0.2883	***
ge24d	0.199	0.093	-0.106	-0.2818	***
ge25d	0.190	0.088	-0.103	-0.2737	***
ge26d	0.182	0.084	-0.099	-0.2678	***
ge27d	0.174	0.080	-0.094	-0.2569	***
ge28d	0.165	0.075	-0.090	-0.2530	***
ge29d	0.154	0.070	-0.084	-0.2512	***
ge30d	0.147	0.067	-0.081	-0.2444	***

✅ New tables created:
  - results_df  (各 cutoff 的相关性汇总)

In [112]:
# Add the 10+ day share into the master table

# ============================================================
# Add early / late / delta ge10 share
# into analysis_mid_user_master
# ============================================================

# ----------------------------------------
# Step 1: compute each user's early-stage ge10 share
# ----------------------------------------
early_ge10 = (
    mh_early
    .groupby("user_id")["gap_days_adj"]
    .apply(lambda x: (x >= 10).mean())
    .reset_index()
    .rename(columns={"gap_days_adj": "pct_gap10_early"})
)

# ----------------------------------------
# Step 2: compute each user's late-stage ge10 share
# ----------------------------------------
late_ge10 = (
    mh_late
    .groupby("user_id")["gap_days_adj"]
    .apply(lambda x: (x >= 10).mean())
    .reset_index()
    .rename(columns={"gap_days_adj": "pct_gap10_late"})
)

# ----------------------------------------
# Step 3: merge into the master table
# ----------------------------------------
analysis_mid_user_master = (
    analysis_mid_user_master
    .merge(early_ge10, on="user_id", how="left")
    .merge(late_ge10,  on="user_id", how="left")
)

# Compute delta
analysis_mid_user_master["delta_pct_gap10"] = (
    analysis_mid_user_master["pct_gap10_late"] -
    analysis_mid_user_master["pct_gap10_early"]
)

# ----------------------------------------
# Step 4: validate
# ----------------------------------------
mh_check = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print("="*60)
print("pct_gap10_early distribution:")
print(mh_check["pct_gap10_early"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(4))

print("\npct_gap10_late distribution:")
print(mh_check["pct_gap10_late"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(4))

print("\ndelta_pct_gap10 distribution:")
print(mh_check["delta_pct_gap10"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(4))

print(f"\nImprovement share (delta < 0):")
print(f"{(mh_check['delta_pct_gap10'] < 0).mean():.1%}")

print(f"\nNew column confirmation:")
new_cols = ["pct_gap10_early", "pct_gap10_late", "delta_pct_gap10"]
print(analysis_mid_user_master[new_cols].head())

print(f"\nanalysis_mid_user_master shape: {analysis_mid_user_master.shape}")
print(f"New columns: {new_cols}")

============================================================
pct_gap10_early 分布：
count    14217.0000
mean         0.5249
std          0.2951
min          0.0000
10%          0.1250
25%          0.3077
50%          0.5000
75%          0.7500
90%          1.0000
max          1.0000
Name: pct_gap10_early, dtype: float64

pct_gap10_late 分布：
count    14217.0000
mean         0.3394
std          0.2490
min          0.0000
10%          0.0000
25%          0.1429
50%          0.3125
75%          0.5000
90%          0.6667
max          1.0000
Name: pct_gap10_late, dtype: float64

delta_pct_gap10 分布：
count    14217.0000
mean        -0.1855
std          0.2693
min         -1.0000
10%         -0.5143
25%         -0.3364
50%         -0.1667
75%         -0.0046
90%          0.1333
max          1.0000
Name: delta_pct_gap10, dtype: float64

改善比例（delta < 0）：
75.4%

新增列确认：
   pct_gap10_early  pct_gap10_late  delta_pct_gap10
0              NaN             NaN              NaN
1              NaN             NaN              NaN
2         0.333333        0.272727        -0.060606
3              NaN             NaN              NaN
4              NaN             NaN              NaN

analysis_mid_user_master shape: (73367, 66)
新增列：['pct_gap10_early', 'pct_gap10_late', 'delta_pct_gap10']

In [113]:
# Confirm that the 30-day share and 10-day share tell different stories

from scipy import stats

mh = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].dropna(subset=["delta_pct_gap10", "delta_pct_gap30"])

r, p = stats.pearsonr(
    mh["delta_pct_gap10"],
    mh["delta_pct_gap30"]
)
print(f"delta_ge10 vs. delta_ge30 correlation: r = {r:.4f}")

delta_ge10 vs delta_ge30 相关性: r = 0.3119

**ge10 vs. ge30 Correlation Validation**

**Result**: corr(ge10, ge30) = **0.31** (low correlation) → the two are independent signals, not a duplicate of the same signal.

**Explanation**: ge10 (share of intervals over 10 days) measures whether a user has established a weekly cadence — nearly all users have some, reflecting day-to-day purchase frequency; ge30 (share of intervals over 30 days) measures whether the user has entered an extreme low-frequency state — only some users reach this, reflecting churn risk. A user can have high ge10 but low ge30 (frequently exceeding 10 days but never reaching 30), showing the two capture different dimensions.

**Implications**:
- ge10 is an independent variable and cannot be substituted with ge30; the quantitative analysis needs a full update
- The Gap side has two independent levers: ge10 (establishing cadence) and ge30 (avoiding churn)
- The 2×2 analysis needs to be redone using ge10 in place of ge30 (basket × ge10 combination)

**Conclusion**: ge10 correlates more strongly with weekly (-0.345) than ge30 (-0.244), giving it priority — this is the basis for upgrading to the ge10 framework.

In [114]:
# ============================================================
# Step 1: validate the independent contribution of ge10 and ge30
# View both variables' correlation with weekly at the same time
# ============================================================

from scipy import stats
import pandas as pd
import numpy as np

# ----------------------------------------
# Step 1: prepare data
# ----------------------------------------
mh = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

# Confirm the needed columns are all present
needed_cols = [
    "user_id", "d_log_weekly",
    "delta_pct_gap10", "delta_pct_gap30",
    "delta_pct_gap10", "delta_n_unique_products"
]
print("Whether the needed columns exist:")
for col in needed_cols:
    exists = col in mh.columns
    print(f"  {col}: {'✅' if exists else '❌'}")

# ----------------------------------------
# Step 2: single-variable correlation comparison
# ----------------------------------------
print("\n" + "="*60)
print("Single-Variable Correlation Comparison")
print("="*60)

gap_metrics = {
    "delta_pct_gap10" : "ge10 share change (10+ days)",
    "delta_pct_gap30" : "ge30 share change (30+ days)",
    "d_log_gap"       : "overall gap change (log scale)",
}

print(f"\n{'Metric':<25} {'Spearman':>10} {'Sig':>6} {'Meaning'}")
print("-"*70)

for col, label in gap_metrics.items():
    if col not in mh.columns:
        print(f"  {col} ← not in table, skipped")
        continue

    valid = mh[[col, "d_log_weekly"]].dropna()
    r, p = stats.spearmanr(valid[col], valid["d_log_weekly"])
    sig = "***" if p < 0.001 else ("**" if p < 0.01 else
          ("*" if p < 0.05 else "ns"))
    print(f"  {col:<23} {r:>10.4f} {sig:>6}  {label}")

# ----------------------------------------
# Step 3: bucketed validation
# View the uplift curve for ge10 and ge30
# ----------------------------------------
print("\n" + "="*60)
print("Bucketed Validation: ge10 vs. ge30 Uplift Curve")
print("="*60)

for col, label in {
    "delta_pct_gap10": "ge10 (10+ day intervals decreasing)",
    "delta_pct_gap30": "ge30 (30+ day intervals decreasing)",
}.items():
    if col not in mh.columns:
        continue

    valid = mh[[col, "d_log_weekly"]].dropna().copy()
    valid["bucket"] = pd.qcut(
        valid[col].rank(method="first"),
        q=5,
        labels=["Q1", "Q2", "Q3", "Q4", "Q5"]
    )

    bucket_result = (
        valid.groupby("bucket", observed=True)
        .agg(
            users=(col, "count"),
            x_mean=(col, "mean"),
            weekly_mean=("d_log_weekly", "mean"),
        )
        .reset_index()
    )

    print(f"\n--- {label} ---")
    print(f"{'Bucket':<8} {'x_mean':>10} {'weekly_mean':>12}")
    for _, row in bucket_result.iterrows():
        print(f"{row['bucket']:<8} "
              f"{row['x_mean']:>10.4f} "
              f"{row['weekly_mean']:>12.4f}")

# ----------------------------------------
# Step 4: independent contribution of ge10 and ge30 respectively
# Using partial correlation
# ge10's independent contribution after controlling for ge30
# ge30's independent contribution after controlling for ge10
# ----------------------------------------
print("\n" + "="*60)
print("Partial Correlation Analysis: Independent Contributions")
print("="*60)

valid = mh[[
    "d_log_weekly",
    "delta_pct_gap10",
    "delta_pct_gap30"
]].dropna()

# Partial correlation: ge10 controlling for ge30
def partial_corr(x, y, z):
    """
    Compute the partial correlation between x and y
    controlling for the effect of z
    """
    from scipy import stats

    # x residual after removing z
    slope_xz, intercept_xz, _, _, _ = stats.linregress(z, x)
    x_resid = x - (slope_xz * z + intercept_xz)

    # y residual after removing z
    slope_yz, intercept_yz, _, _, _ = stats.linregress(z, y)
    y_resid = y - (slope_yz * z + intercept_yz)

    r, p = stats.pearsonr(x_resid, y_resid)
    return r, p

# ge10's independent contribution after controlling for ge30
r_ge10, p_ge10 = partial_corr(
    valid["delta_pct_gap10"].values,
    valid["d_log_weekly"].values,
    valid["delta_pct_gap30"].values
)

# ge30's independent contribution after controlling for ge10
r_ge30, p_ge30 = partial_corr(
    valid["delta_pct_gap30"].values,
    valid["d_log_weekly"].values,
    valid["delta_pct_gap10"].values
)

sig_ge10 = "***" if p_ge10 < 0.001 else "ns"
sig_ge30 = "***" if p_ge30 < 0.001 else "ns"

print(f"\n{'Variable':<25} {'Partial r':>10} {'Sig':>6} {'Meaning'}")
print("-"*65)
print(f"  ge10 (controlling for ge30)   {r_ge10:>10.4f} {sig_ge10:>6}  "
      f"ge10's independent contribution")
print(f"  ge30 (controlling for ge10)   {r_ge30:>10.4f} {sig_ge30:>6}  "
      f"ge30's independent contribution")

# ----------------------------------------
# Step 5: conclusion
# ----------------------------------------
print("\n" + "="*60)
print("Conclusion")
print("="*60)
print(f"""
Single-variable correlation:
  ge10 Spearman = -0.345 (stronger)
  ge30 Spearman = -0.244

Partial correlation (independent contribution):
  ge10 controlling for ge30 = {r_ge10:.4f} {sig_ge10}
  ge30 controlling for ge10 = {r_ge30:.4f} {sig_ge30}

Correlation between the two: r = 0.31 (independent)

Interpretation:
→ If both partial correlations are significant:
   it means ge10 and ge30 each contribute independently
   both should be retained in the analysis

→ If only ge10 is significant:
   it means ge10 already captures ge30's information
   ge30 can be replaced by ge10
""")

print("✅ Analysis complete")

需要的列是否存在：
  user_id: ✅
  d_log_weekly: ✅
  delta_pct_gap10: ✅
  delta_pct_gap30: ✅
  delta_pct_gap10: ✅
  delta_n_unique_products: ✅

============================================================
单变量相关性对比
============================================================

指标                          Spearman    Sig 含义
----------------------------------------------------------------------
  delta_pct_gap10            -0.3453    ***  ge10 share 变化（10天以上）
  delta_pct_gap30            -0.2411    ***  ge30 share 变化（30天以上）
  d_log_gap                  -0.5244    ***  整体 gap 变化（log scale）

============================================================
分桶验证：ge10 vs ge30 的 Uplift Curve
============================================================

--- ge10（10天以上间隔减少） ---
Bucket       x_mean  weekly_mean
Q1          -0.5739       0.9778
Q2          -0.3082       0.7936
Q3          -0.1725       0.7044
Q4          -0.0443       0.6148
Q5           0.1714       0.5657

--- ge30（30天以上间隔减少） ---
Bucket       x_mean  weekly_mean
Q1          -0.3742       0.9138
Q2          -0.1093       0.7606
Q3          -0.0082       0.6805
Q4           0.0000       0.6821
Q5           0.1442       0.6194

============================================================
偏相关分析：各自的独立贡献
============================================================

变量                             偏相关 r    Sig 含义
-----------------------------------------------------------------
  ge10（控制 ge30 后）      -0.2761    ***  ge10 的独立贡献
  ge30（控制 ge10 后）      -0.1251    ***  ge30 的独立贡献

============================================================
结论
============================================================

单变量相关性：
  ge10 Spearman = -0.345（更强）
  ge30 Spearman = -0.244

偏相关（独立贡献）：
  ge10 控制 ge30 后 = -0.2761 ***
  ge30 控制 ge10 后 = -0.1251 ***

两者相关性：r = 0.31（独立）

解读：
→ 如果两者偏相关都显著：
   说明 ge10 和 ge30 各有独立贡献
   都应该保留在分析里

→ 如果只有 ge10 显著：
   说明 ge10 已经捕捉了 ge30 的信息
   ge30 可以被 ge10 替代

✅ 分析完成

In [115]:
# ============================================================
# Step 2: redo the 2×2 analysis
# basket × ge10 (new) vs. basket × ge30 (original)
# ============================================================

from scipy import stats
import pandas as pd
import numpy as np

# ----------------------------------------
# Step 1: prepare data
# ----------------------------------------
mh = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"Mid→High users: {len(mh):,}")

# Confirm the needed columns
needed = [
    "user_id", "d_log_weekly",
    "delta_pct_gap10", "delta_pct_gap30",
    "delta_n_unique_products"
]
for col in needed:
    print(f"  {col}: {'✅' if col in mh.columns else '❌'}")

# ----------------------------------------
# Step 2: define the high/low split
# Split by median
# ----------------------------------------
# Basket：delta_n_unique_products
basket_median = mh["delta_n_unique_products"].median()

# ge10：delta_pct_gap10
ge10_median = mh["delta_pct_gap10"].median()

# ge30：delta_pct_gap30
ge30_median = mh["delta_pct_gap30"].median()

print(f"\nSplit point (median):")
print(f"  basket median : {basket_median:.4f}")
print(f"  ge10 median   : {ge10_median:.4f}")
print(f"  ge30 median   : {ge30_median:.4f}")

# ----------------------------------------
# Step 3: 2×2 analysis A: basket × ge10 (new)
# ----------------------------------------
mh["basket_high"] = (
    mh["delta_n_unique_products"] > basket_median
).astype(int)

mh["ge10_improved"] = (
    mh["delta_pct_gap10"] < ge10_median
).astype(int)

mh["ge30_improved"] = (
    mh["delta_pct_gap30"] < ge30_median
).astype(int)

# ----------------------------------------
# Step 4: output the 2×2 results
# ----------------------------------------
def run_2x2(df, x_col, y_col, x_label, y_label):
    """
    x_col: 0/1 variable (1=high/improved)
    y_col: 0/1 variable (1=high/improved)
    """
    results = []
    for x_val, x_name in [(1, f"{x_label}↑"), (0, f"{x_label}↓")]:
        for y_val, y_name in [(1, f"{y_label}↑"), (0, f"{y_label}↓")]:
            subset = df[
                (df[x_col] == x_val) &
                (df[y_col] == y_val)
            ]
            n = len(subset)
            share = n / len(df)
            d_log = subset["d_log_weekly"].mean()
            growth = np.exp(d_log)

            results.append({
                "group"      : f"{x_name} × {y_name}",
                "users"      : n,
                "share"      : share,
                "d_log_weekly": round(d_log, 4),
                "growth_x"   : round(growth, 2),
            })

    return pd.DataFrame(results)

# 2×2 A：basket × ge10
print("\n" + "="*70)
print("2×2 Analysis A: Basket × ge10 (new)")
print("="*70)
result_ge10 = run_2x2(
    mh,
    "basket_high", "ge10_improved",
    "Basket", "ge10"
)
print(f"\n{'Group':<30} {'Users':>7} {'Share':>7} "
      f"{'d_log':>8} {'Growth':>8}")
print("-"*65)
for _, row in result_ge10.iterrows():
    print(f"{row['group']:<30} "
          f"{row['users']:>7,} "
          f"{row['share']:>7.1%} "
          f"{row['d_log_weekly']:>8.4f} "
          f"{row['growth_x']:>7.2f}x")

# 2×2 B: basket × ge30 (original)
print("\n" + "="*70)
print("2×2 Analysis B: Basket × ge30 (original)")
print("="*70)
result_ge30 = run_2x2(
    mh,
    "basket_high", "ge30_improved",
    "Basket", "ge30"
)
print(f"\n{'Group':<30} {'Users':>7} {'Share':>7} "
      f"{'d_log':>8} {'Growth':>8}")
print("-"*65)
for _, row in result_ge30.iterrows():
    print(f"{row['group']:<30} "
          f"{row['users']:>7,} "
          f"{row['share']:>7.1%} "
          f"{row['d_log_weekly']:>8.4f} "
          f"{row['growth_x']:>7.2f}x")

# ----------------------------------------
# Step 5: incremental analysis comparison
# ----------------------------------------
print("\n" + "="*70)
print("Incremental Analysis Comparison: ge10 vs. ge30")
print("="*70)

def calc_incremental(result_df, x_label, y_label):
    both    = result_df[
        result_df["group"] == f"{x_label}↑ × {y_label}↑"
    ]["d_log_weekly"].values[0]
    x_only  = result_df[
        result_df["group"] == f"{x_label}↑ × {y_label}↓"
    ]["d_log_weekly"].values[0]
    y_only  = result_df[
        result_df["group"] == f"{x_label}↓ × {y_label}↑"
    ]["d_log_weekly"].values[0]
    neither = result_df[
        result_df["group"] == f"{x_label}↓ × {y_label}↓"
    ]["d_log_weekly"].values[0]

    inc_x = both - y_only    # basket increment (given gap↑)
    inc_y = both - x_only    # gap increment (given basket↑)

    return both, x_only, y_only, neither, inc_x, inc_y

both_10, basket_only_10, ge10_only, neither_10, inc_basket_10, inc_ge10 = \
    calc_incremental(result_ge10, "Basket", "ge10")

both_30, basket_only_30, ge30_only, neither_30, inc_basket_30, inc_ge30 = \
    calc_incremental(result_ge30, "Basket", "ge30")

print(f"\n{'Metric':<30} {'ge10 version':>12} {'ge30 version':>12}")
print("-"*55)
print(f"{'Both':<30} {both_10:>12.4f} {both_30:>12.4f}")
print(f"{'Basket only':<30} {basket_only_10:>12.4f} {basket_only_30:>12.4f}")
print(f"{'Gap only':<30} {ge10_only:>12.4f} {ge30_only:>12.4f}")
print(f"{'Neither':<30} {neither_10:>12.4f} {neither_30:>12.4f}")
print(f"{'Incremental Basket (given gap↑)':<30} {inc_basket_10:>12.4f} {inc_basket_30:>12.4f}")
print(f"{'Incremental Gap (given basket↑)':<30} {inc_ge10:>12.4f} {inc_ge30:>12.4f}")

# ----------------------------------------
# Step 6: 3×3 analysis (ge10 × ge30 × basket)
# View the combined effect of all three variables
# ----------------------------------------
print("\n" + "="*70)
print("3-Way Analysis: Basket × ge10 × ge30")
print("="*70)

results_3way = []
for b, b_name in [(1, "Basket↑"), (0, "Basket↓")]:
    for g10, g10_name in [(1, "ge10↑"), (0, "ge10↓")]:
        for g30, g30_name in [(1, "ge30↑"), (0, "ge30↓")]:
            subset = mh[
                (mh["basket_high"]    == b) &
                (mh["ge10_improved"]  == g10) &
                (mh["ge30_improved"]  == g30)
            ]
            n = len(subset)
            share = n / len(mh)
            d_log = subset["d_log_weekly"].mean()

            results_3way.append({
                "group"      : f"{b_name} × {g10_name} × {g30_name}",
                "users"      : n,
                "share"      : share,
                "d_log_weekly": round(d_log, 4),
                "growth_x"   : round(np.exp(d_log), 2),
            })

results_3way_df = pd.DataFrame(results_3way).sort_values(
    "d_log_weekly", ascending=False
)

print(f"\n{'Group':<40} {'Users':>7} {'Share':>7} "
      f"{'d_log':>8} {'Growth':>8}")
print("-"*75)
for _, row in results_3way_df.iterrows():
    print(f"{row['group']:<40} "
          f"{row['users']:>7,} "
          f"{row['share']:>7.1%} "
          f"{row['d_log_weekly']:>8.4f} "
          f"{row['growth_x']:>7.2f}x")

print("\n✅ New tables created:")
print("  - result_ge10      (2×2 basket × ge10)")
print("  - result_ge30      (2×2 basket × ge30)")
print("  - results_3way_df  (3way basket × ge10 × ge30)")

Mid→High users: 14,217
  user_id: ✅
  d_log_weekly: ✅
  delta_pct_gap10: ✅
  delta_pct_gap30: ✅
  delta_n_unique_products: ✅

切分点（中位数）：
  basket median : 2.0000
  ge10 median   : -0.1667
  ge30 median   : 0.0000

======================================================================
2×2 分析 A：Basket × ge10（新）
======================================================================

Group                            Users   Share    d_log   Growth
-----------------------------------------------------------------
Basket↑ × ge10↑                  2,801   19.7%   0.9955    2.71x
Basket↑ × ge10↓                  3,675   25.8%   0.7101    2.03x
Basket↓ × ge10↑                  4,239   29.8%   0.7580    2.13x
Basket↓ × ge10↓                  3,502   24.6%   0.5097    1.66x

======================================================================
2×2 分析 B：Basket × ge30（原来）
======================================================================

Group                            Users   Share    d_log   Growth
-----------------------------------------------------------------
Basket↑ × ge30↑                  3,018   21.2%   0.9185    2.51x
Basket↑ × ge30↓                  3,458   24.3%   0.7594    2.14x
Basket↓ × ge30↑                  3,518   24.7%   0.7336    2.08x
Basket↓ × ge30↓                  4,223   29.7%   0.5724    1.77x

======================================================================
增量分析对比：ge10 vs ge30
======================================================================

指标                                  ge10 版本      ge30 版本
-------------------------------------------------------
Both                                 0.9955       0.9185
Basket only                          0.7101       0.7594
Gap only                             0.7580       0.7336
Neither                              0.5097       0.5724
增量 Basket（given gap↑）                0.2375       0.1849
增量 Gap（given basket↑）                0.2854       0.1591

======================================================================
3way 分析：Basket × ge10 × ge30
======================================================================

Group                                      Users   Share    d_log   Growth
---------------------------------------------------------------------------
Basket↑ × ge10↑ × ge30↑                    1,692   11.9%   1.0562    2.88x
Basket↑ × ge10↑ × ge30↓                    1,109    7.8%   0.9030    2.47x
Basket↓ × ge10↑ × ge30↑                    2,365   16.6%   0.8210    2.27x
Basket↑ × ge10↓ × ge30↑                    1,326    9.3%   0.7429    2.10x
Basket↑ × ge10↓ × ge30↓                    2,349   16.5%   0.6916    2.00x
Basket↓ × ge10↑ × ge30↓                    1,874   13.2%   0.6784    1.97x
Basket↓ × ge10↓ × ge30↑                    1,153    8.1%   0.5542    1.74x
Basket↓ × ge10↓ × ge30↓                    2,349   16.5%   0.4879    1.63x

✅ New tables created:
  - result_ge10      (2×2 basket × ge10)
  - result_ge30      (2×2 basket × ge30)
  - results_3way_df  (3way basket × ge10 × ge30)

In [116]:
# ============================================================
# Gap-side Lever Scan (symmetric with the Basket side)
# Mid→High Stable Stepper users
# ============================================================

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from scipy import stats

# -------------------------
# 0) Parameters
# -------------------------
FILTER = {
    "path_9"          : "Mid Up to High",
    "stepper_subtype" : "stepper_stable_up",
}
MIN_N = 80

# -------------------------
# 1) Get data
# -------------------------
df_base = basket_master_user_wk.copy()

if FILTER.get("path_9"):
    df_base = df_base[df_base["path_9"] == FILTER["path_9"]].copy()
if FILTER.get("stepper_subtype") and "stepper_subtype" in df_base.columns:
    df_base = df_base[
        df_base["stepper_subtype"] == FILTER["stepper_subtype"]
    ].copy()

print(f"Selected users: {df_base['user_id'].nunique():,}")
print(f"Columns: {df_base.columns.tolist()}")

# -------------------------
# 2) Compute Gap-side metrics from order data
# Because basket_master_user_wk doesn't have gap's early/late
# -------------------------

# Get these users' orders
gap_users = df_base[["user_id"]].copy()

orders_gap = (
    orders_enriched2
    .merge(gap_users, on="user_id", how="inner")
    .sort_values(["user_id", "order_number"])
    .copy()
)

# Add pos and half
user_n = (
    orders_gap
    .groupby("user_id")["order_number"]
    .max()
    .reset_index()
    .rename(columns={"order_number": "n_orders"})
)
orders_gap = orders_gap.merge(user_n, on="user_id", how="left")
orders_gap["pos"]  = orders_gap["order_number"] / orders_gap["n_orders"]
orders_gap["half"] = np.where(orders_gap["pos"] <= 0.5, "early", "late")

print(f"\nOrders: {len(orders_gap):,}")
print(f"half distribution:")
print(orders_gap["half"].value_counts())

# -------------------------
# 3) Compute Gap-side early/late metrics
# -------------------------
def gap_half_metrics(g):
    gap = g["gap_days_adj"].astype(float)
    dow = g["order_dow"]
    n   = len(g)

    # gap metric
    gap_med   = float(gap.median())
    gap_std   = float(gap.std(ddof=0)) if n >= 2 else np.nan
    pct_gap10 = float((gap >= 10).mean())
    pct_gap30 = float((gap >= 30).mean())

    # Temporal structure metrics
    dow_cnt   = dow.value_counts(dropna=False)
    p         = (dow_cnt / dow_cnt.sum()).to_numpy(dtype=float)
    dom_share = float(p.max()) if len(p) else np.nan

    from scipy.stats import entropy as scipy_entropy
    ent = float(scipy_entropy(p)) if len(p) > 0 else np.nan

    return pd.Series({
        "gap_med"    : gap_med,
        "gap_std"    : gap_std,
        "pct_gap10"  : pct_gap10,
        "pct_gap30"  : pct_gap30,
        "dom_share"  : dom_share,
        "dow_entropy": ent,
    })

half_metrics = (
    orders_gap
    .groupby(["user_id", "half"])
    .apply(gap_half_metrics)
    .reset_index()
)

# pivot wide
gap_wide = half_metrics.pivot(
    index="user_id", columns="half"
)
gap_wide.columns = [f"{a}_{b}" for a, b in gap_wide.columns]
gap_wide = gap_wide.reset_index()

# Compute delta
for metric in ["gap_med", "gap_std", "pct_gap10",
               "pct_gap30", "dom_share", "dow_entropy"]:
    early_col = f"{metric}_early"
    late_col  = f"{metric}_late"
    if early_col in gap_wide.columns and late_col in gap_wide.columns:
        gap_wide[f"delta_{metric}"] = (
            gap_wide[late_col] - gap_wide[early_col]
        )

# d_log_gap
gap_wide["d_log_gap"] = (
    np.log(gap_wide["gap_med_late"]) -
    np.log(gap_wide["gap_med_early"])
)

print(f"\ngap_wide shape: {gap_wide.shape}")
print(f"columns: {gap_wide.columns.tolist()}")

# -------------------------
# 4) Merge in outcome
# -------------------------
outcome = df_base[["user_id", "d_log_weekly", "delta_weekly"]].copy()

dl_gap = gap_wide.merge(outcome, on="user_id", how="inner")
print(f"\ndl_gap shape: {dl_gap.shape}")

# -------------------------
# 5) Single-variable regression function
# -------------------------
def run_reg(data, x_col, y_col, min_n=MIN_N):
    d = data[[x_col, y_col]].replace(
        [np.inf, -np.inf], np.nan
    ).dropna()
    if len(d) < min_n:
        return None

    X = d[[x_col]].astype(float).values
    y = d[y_col].astype(float).values
    model = LinearRegression().fit(X, y)

    r_spearman, p_spearman = stats.spearmanr(
        d[x_col], d[y_col]
    )
    sig = ("***" if p_spearman < 0.001 else
           "**"  if p_spearman < 0.01  else
           "*"   if p_spearman < 0.05  else "ns")

    return {
        "lever"    : x_col,
        "n"        : int(len(d)),
        "coef"     : round(float(model.coef_[0]), 4),
        "r2"       : round(float(model.score(X, y)), 4),
        "spearman" : round(r_spearman, 4),
        "sig"      : sig,
        "x_mean"   : round(float(d[x_col].mean()), 4),
        "x_std"    : round(float(d[x_col].std()),  4),
    }

# -------------------------
# 6) Scan: d_log definition
# -------------------------
dlog_gap_vars = ["d_log_gap"]

dlog_results = []
for col in dlog_gap_vars:
    out = run_reg(dl_gap, col, "d_log_weekly")
    if out:
        dlog_results.append(out)

dlog_gap_scan = (
    pd.DataFrame(dlog_results)
    .sort_values("r2", ascending=False)
    .reset_index(drop=True)
)

# -------------------------
# 7) Scan: delta definition
# -------------------------
delta_gap_vars = [
    "delta_pct_gap10",   # ge10 ← newly added, most important
    "delta_pct_gap30",   # ge30
    "delta_gap_std",     # gap volatility
    "delta_gap_med",     # gap median
    "delta_dom_share",   # shopping-day concentration
    "delta_dow_entropy", # shopping-time randomness
]

delta_results = []
for col in delta_gap_vars:
    if col not in dl_gap.columns:
        print(f"⚠️ Column does not exist, skipped: {col}")
        continue
    out = run_reg(dl_gap, col, "delta_weekly")
    if out:
        delta_results.append(out)

delta_gap_scan = (
    pd.DataFrame(delta_results)
    .sort_values("r2", ascending=False)
    .reset_index(drop=True)
)

# -------------------------
# 8) Output results
# -------------------------
print("\n" + "="*70)
print("Gap-Side Lever Scan: d_log definition")
print("="*70)
print(f"\n{'Lever':<25} {'R²':>8} {'Spearman':>10} {'Sig':>6} {'Coef':>8}")
print("-"*60)
for _, row in dlog_gap_scan.iterrows():
    print(f"  {row['lever']:<23} {row['r2']:>8.4f} "
          f"{row['spearman']:>10.4f} {row['sig']:>6} "
          f"{row['coef']:>8.4f}")

print("\n" + "="*70)
print("Gap-Side Lever Scan: delta definition")
print("="*70)
print(f"\n{'Lever':<25} {'R²':>8} {'Spearman':>10} {'Sig':>6} {'Coef':>8}")
print("-"*60)
for _, row in delta_gap_scan.iterrows():
    print(f"  {row['lever']:<23} {row['r2']:>8.4f} "
          f"{row['spearman']:>10.4f} {row['sig']:>6} "
          f"{row['coef']:>8.4f}")

# -------------------------
# 9) Compare against the Basket side
# -------------------------
print("\n" + "="*70)
print("Basket vs. Gap Lever Comparison")
print("="*70)
print(f"""
Strongest Basket-side lever:
  d_log_basket_med    R² = 0.175  ← strongest
  delta_total_items   R² = 0.149

Strongest Gap-side lever:
  d_log_gap           R² = TBD
  delta_pct_gap10     R² = TBD  ← expected strongest
  delta_pct_gap30     R² = TBD
  delta_gap_std       R² = TBD
""")

print("✅ New tables created:")
print("  - dlog_gap_scan   (d_log definition)")
print("  - delta_gap_scan  (delta definition)")
print("  - dl_gap          (user-level gap metrics + outcome)")

Selected users: 3,066
Columns: ['user_id', 'consumable_share_early', 'consumable_share_late', 'core_share_early', 'core_share_late', 'dept_entropy_early', 'dept_entropy_late', 'dominant_dept_share_early', 'dominant_dept_share_late', 'durable_share_early', 'durable_share_late', 'items_per_unique_product_early', 'items_per_unique_product_late', 'n_unique_departments_early', 'n_unique_departments_late', 'n_unique_products_early', 'n_unique_products_late', 'reorder_ratio_early', 'reorder_ratio_late', 'total_items_early', 'total_items_late', 'variety_share_early', 'variety_share_late', 'delta_total_items', 'delta_n_unique_products', 'delta_n_unique_departments', 'delta_reorder_ratio', 'delta_items_per_unique_product', 'delta_consumable_share', 'delta_core_share', 'delta_variety_share', 'delta_durable_share', 'delta_dept_entropy', 'delta_dominant_dept_share', 'd_log_total_items', 'd_log_unique_products', 'd_log_reorder_ratio', 'd_log_dept_entropy', 'basket_med_early', 'basket_med_late', 'delta_basket_med', 'd_log_basket_med', 'path_9', 'stepper_subtype', 'label', 'weekly_med_early', 'weekly_med_late', 'delta_weekly', 'd_log_weekly']

Orders: 90,140
half 分布：
half
late     47367
early    42773
Name: count, dtype: int64

gap_wide shape: (3066, 20)
columns: ['user_id', 'gap_med_early', 'gap_med_late', 'gap_std_early', 'gap_std_late', 'pct_gap10_early', 'pct_gap10_late', 'pct_gap30_early', 'pct_gap30_late', 'dom_share_early', 'dom_share_late', 'dow_entropy_early', 'dow_entropy_late', 'delta_gap_med', 'delta_gap_std', 'delta_pct_gap10', 'delta_pct_gap30', 'delta_dom_share', 'delta_dow_entropy', 'd_log_gap']

dl_gap shape: (3066, 22)

======================================================================
Gap 侧 Lever Scan：d_log 口径
======================================================================

Lever                           R²   Spearman    Sig     Coef
------------------------------------------------------------
  d_log_gap                 0.1849    -0.4271    ***  -0.3862

======================================================================
Gap 侧 Lever Scan：delta 口径
======================================================================

Lever                           R²   Spearman    Sig     Coef
------------------------------------------------------------
  delta_gap_std             0.0787    -0.3043    ***  -0.4971
  delta_pct_gap10           0.0653    -0.3153    ***  -6.0840
  delta_gap_med             0.0404    -0.2893    ***  -0.1984
  delta_pct_gap30           0.0270    -0.2293    ***  -5.8621
  delta_dow_entropy         0.0002    -0.0281     ns  -0.2199
  delta_dom_share           0.0000     0.0280     ns   0.2129

======================================================================
Basket vs Gap Lever 对比
======================================================================

Basket 侧最强 lever：
  d_log_basket_med    R² = 0.175  ← 最强
  delta_total_items   R² = 0.149

Gap 侧最强 lever：
  d_log_gap           R² = 待填入
  delta_pct_gap10     R² = 待填入  ← 预期最强
  delta_pct_gap30     R² = 待填入
  delta_gap_std       R² = 待填入

✅ New tables created:
  - dlog_gap_scan   (d_log 口径)
  - delta_gap_scan  (delta 口径)
  - dl_gap          (用户级 gap 指标 + outcome)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/3789715899.py:100: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(gap_half_metrics)

**Supplementary analysis**: Extend the Gap-side Lever Scan to all Mid → High users, comparing results against the Stable Stepper subgroup.

In [117]:
# ============================================================
# Gap-side Lever Scan (symmetric with the Basket side)
# All Mid→High users
# ============================================================

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from scipy import stats

# -------------------------
# 0) Parameters
# -------------------------
FILTER = {
    "path_9" : "Mid Up to High",
    # No filter on stepper_subtype → keep all Mid→High users
}
MIN_N = 80

# -------------------------
# 1) Get data
# -------------------------
df_base = basket_master_user_wk.copy()

if FILTER.get("path_9"):
    df_base = df_base[df_base["path_9"] == FILTER["path_9"]].copy()
if FILTER.get("stepper_subtype") and "stepper_subtype" in df_base.columns:
    df_base = df_base[
        df_base["stepper_subtype"] == FILTER["stepper_subtype"]
    ].copy()

print(f"Selected users: {df_base['user_id'].nunique():,}")
print(f"Columns: {df_base.columns.tolist()}")

# -------------------------
# 2) Compute Gap-side metrics from order data
# -------------------------
gap_users = df_base[["user_id"]].copy()

orders_gap = (
    orders_enriched2
    .merge(gap_users, on="user_id", how="inner")
    .sort_values(["user_id", "order_number"])
    .copy()
)

user_n = (
    orders_gap
    .groupby("user_id")["order_number"]
    .max()
    .reset_index()
    .rename(columns={"order_number": "n_orders"})
)
orders_gap = orders_gap.merge(user_n, on="user_id", how="left")
orders_gap["pos"]  = orders_gap["order_number"] / orders_gap["n_orders"]
orders_gap["half"] = np.where(orders_gap["pos"] <= 0.5, "early", "late")

print(f"\nOrders: {len(orders_gap):,}")
print(f"half distribution:")
print(orders_gap["half"].value_counts())

# -------------------------
# 3) Compute Gap-side early/late metrics
# -------------------------
def gap_half_metrics(g):
    gap = g["gap_days_adj"].astype(float)
    dow = g["order_dow"]
    n   = len(g)

    gap_med   = float(gap.median())
    gap_std   = float(gap.std(ddof=0)) if n >= 2 else np.nan
    pct_gap10 = float((gap >= 10).mean())
    pct_gap30 = float((gap >= 30).mean())

    dow_cnt   = dow.value_counts(dropna=False)
    p         = (dow_cnt / dow_cnt.sum()).to_numpy(dtype=float)
    dom_share = float(p.max()) if len(p) else np.nan

    from scipy.stats import entropy as scipy_entropy
    ent = float(scipy_entropy(p)) if len(p) > 0 else np.nan

    return pd.Series({
        "gap_med"    : gap_med,
        "gap_std"    : gap_std,
        "pct_gap10"  : pct_gap10,
        "pct_gap30"  : pct_gap30,
        "dom_share"  : dom_share,
        "dow_entropy": ent,
    })

half_metrics = (
    orders_gap
    .groupby(["user_id", "half"])
    .apply(gap_half_metrics)
    .reset_index()
)

gap_wide = half_metrics.pivot(index="user_id", columns="half")
gap_wide.columns = [f"{a}_{b}" for a, b in gap_wide.columns]
gap_wide = gap_wide.reset_index()

for metric in ["gap_med", "gap_std", "pct_gap10",
               "pct_gap30", "dom_share", "dow_entropy"]:
    early_col = f"{metric}_early"
    late_col  = f"{metric}_late"
    if early_col in gap_wide.columns and late_col in gap_wide.columns:
        gap_wide[f"delta_{metric}"] = (
            gap_wide[late_col] - gap_wide[early_col]
        )

gap_wide["d_log_gap"] = (
    np.log(gap_wide["gap_med_late"]) -
    np.log(gap_wide["gap_med_early"])
)

print(f"\ngap_wide shape: {gap_wide.shape}")
print(f"columns: {gap_wide.columns.tolist()}")

# -------------------------
# 4) Merge in outcome
# -------------------------
outcome = df_base[["user_id", "d_log_weekly", "delta_weekly"]].copy()

dl_gap = gap_wide.merge(outcome, on="user_id", how="inner")
print(f"\ndl_gap shape: {dl_gap.shape}")

# -------------------------
# 5) Single-variable regression function
# -------------------------
def run_reg(data, x_col, y_col, min_n=MIN_N):
    d = data[[x_col, y_col]].replace(
        [np.inf, -np.inf], np.nan
    ).dropna()
    if len(d) < min_n:
        return None

    X = d[[x_col]].astype(float).values
    y = d[y_col].astype(float).values
    model = LinearRegression().fit(X, y)

    r_spearman, p_spearman = stats.spearmanr(d[x_col], d[y_col])
    sig = ("***" if p_spearman < 0.001 else
           "**"  if p_spearman < 0.01  else
           "*"   if p_spearman < 0.05  else "ns")

    return {
        "lever"    : x_col,
        "n"        : int(len(d)),
        "coef"     : round(float(model.coef_[0]), 4),
        "r2"       : round(float(model.score(X, y)), 4),
        "spearman" : round(r_spearman, 4),
        "sig"      : sig,
        "x_mean"   : round(float(d[x_col].mean()), 4),
        "x_std"    : round(float(d[x_col].std()),  4),
    }

# -------------------------
# 6) Scan: d_log definition
# -------------------------
dlog_results = []
for col in ["d_log_gap"]:
    out = run_reg(dl_gap, col, "d_log_weekly")
    if out:
        dlog_results.append(out)

dlog_gap_scan = (
    pd.DataFrame(dlog_results)
    .sort_values("r2", ascending=False)
    .reset_index(drop=True)
)

# -------------------------
# 7) Scan: delta definition
# -------------------------
delta_gap_vars = [
    "delta_pct_gap10",
    "delta_pct_gap30",
    "delta_gap_std",
    "delta_gap_med",
    "delta_dom_share",
    "delta_dow_entropy",
]

delta_results = []
for col in delta_gap_vars:
    if col not in dl_gap.columns:
        print(f"⚠️ Column does not exist, skipped: {col}")
        continue
    out = run_reg(dl_gap, col, "delta_weekly")
    if out:
        delta_results.append(out)

delta_gap_scan = (
    pd.DataFrame(delta_results)
    .sort_values("r2", ascending=False)
    .reset_index(drop=True)
)

# -------------------------
# 8) Output results
# -------------------------
print("\n" + "="*70)
print("Gap-Side Lever Scan: d_log definition (all Mid→High users)")
print("="*70)
print(f"\n{'Lever':<25} {'R²':>8} {'Spearman':>10} {'Sig':>6} {'Coef':>8}")
print("-"*60)
for _, row in dlog_gap_scan.iterrows():
    print(f"  {row['lever']:<23} {row['r2']:>8.4f} "
          f"{row['spearman']:>10.4f} {row['sig']:>6} "
          f"{row['coef']:>8.4f}")

print("\n" + "="*70)
print("Gap-Side Lever Scan: delta definition (all Mid→High users)")
print("="*70)
print(f"\n{'Lever':<25} {'R²':>8} {'Spearman':>10} {'Sig':>6} {'Coef':>8}")
print("-"*60)
for _, row in delta_gap_scan.iterrows():
    print(f"  {row['lever']:<23} {row['r2']:>8.4f} "
          f"{row['spearman']:>10.4f} {row['sig']:>6} "
          f"{row['coef']:>8.4f}")

# -------------------------
# 9) Compare against the Basket side
# -------------------------
print("\n" + "="*70)
print("Basket vs. Gap Lever Comparison (all Mid→High users)")
print("="*70)
print(f"""
Strongest Basket-side lever:
  d_log_basket_med    R² = 0.175  ← strongest
  delta_total_items   R² = 0.149

Strongest Gap-side lever:
  d_log_gap           R² = TBD
  delta_pct_gap10     R² = TBD  ← expected strongest
  delta_pct_gap30     R² = TBD
  delta_gap_std       R² = TBD
""")

print("✅ New tables created:")
print("  - dlog_gap_scan   (d_log definition)")
print("  - delta_gap_scan  (delta definition)")
print("  - dl_gap          (user-level gap metrics + outcome)")

Selected users: 14,217
Columns: ['user_id', 'consumable_share_early', 'consumable_share_late', 'core_share_early', 'core_share_late', 'dept_entropy_early', 'dept_entropy_late', 'dominant_dept_share_early', 'dominant_dept_share_late', 'durable_share_early', 'durable_share_late', 'items_per_unique_product_early', 'items_per_unique_product_late', 'n_unique_departments_early', 'n_unique_departments_late', 'n_unique_products_early', 'n_unique_products_late', 'reorder_ratio_early', 'reorder_ratio_late', 'total_items_early', 'total_items_late', 'variety_share_early', 'variety_share_late', 'delta_total_items', 'delta_n_unique_products', 'delta_n_unique_departments', 'delta_reorder_ratio', 'delta_items_per_unique_product', 'delta_consumable_share', 'delta_core_share', 'delta_variety_share', 'delta_durable_share', 'delta_dept_entropy', 'delta_dominant_dept_share', 'd_log_total_items', 'd_log_unique_products', 'd_log_reorder_ratio', 'd_log_dept_entropy', 'basket_med_early', 'basket_med_late', 'delta_basket_med', 'd_log_basket_med', 'path_9', 'stepper_subtype', 'label', 'weekly_med_early', 'weekly_med_late', 'delta_weekly', 'd_log_weekly']

Orders: 306,575
half 分布：
half
late     163978
early    142597
Name: count, dtype: int64

gap_wide shape: (14217, 20)
columns: ['user_id', 'gap_med_early', 'gap_med_late', 'gap_std_early', 'gap_std_late', 'pct_gap10_early', 'pct_gap10_late', 'pct_gap30_early', 'pct_gap30_late', 'dom_share_early', 'dom_share_late', 'dow_entropy_early', 'dow_entropy_late', 'delta_gap_med', 'delta_gap_std', 'delta_pct_gap10', 'delta_pct_gap30', 'delta_dom_share', 'delta_dow_entropy', 'd_log_gap']

dl_gap shape: (14217, 22)

======================================================================
Gap 侧 Lever Scan：d_log 口径（Mid→High 全体）
======================================================================

Lever                           R²   Spearman    Sig     Coef
------------------------------------------------------------
  d_log_gap                 0.1847    -0.4364    ***  -0.3580

======================================================================
Gap 侧 Lever Scan：delta 口径（Mid→High 全体）
======================================================================

Lever                           R²   Spearman    Sig     Coef
------------------------------------------------------------
  delta_pct_gap10           0.0607    -0.3213    ***  -5.3461
  delta_gap_med             0.0599    -0.3296    ***  -0.2255
  delta_gap_std             0.0280    -0.2289    ***  -0.2473
  delta_pct_gap30           0.0171    -0.1978    ***  -3.5141
  delta_dom_share           0.0015    -0.0131     ns  -1.0988
  delta_dow_entropy         0.0009     0.0105     ns   0.4704

======================================================================
Basket vs Gap Lever 对比（Mid→High 全体）
======================================================================

Basket 侧最强 lever：
  d_log_basket_med    R² = 0.175  ← 最强
  delta_total_items   R² = 0.149

Gap 侧最强 lever：
  d_log_gap           R² = 待填入
  delta_pct_gap10     R² = 待填入  ← 预期最强
  delta_pct_gap30     R² = 待填入
  delta_gap_std       R² = 待填入

✅ New tables created:
  - dlog_gap_scan   (d_log 口径)
  - delta_gap_scan  (delta 口径)
  - dl_gap          (用户级 gap 指标 + outcome)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/3791715338.py:94: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(gap_half_metrics)

**Next step**: Basket-side Lever Scan analysis (symmetric with the Gap side).

In [118]:
# ============================================================
# Basket-side Lever Scan (adds Spearman)
# Fully symmetric with the Gap side
# ============================================================

from sklearn.linear_model import LinearRegression
from scipy import stats
import numpy as np
import pandas as pd

# -------------------------
# 0) Parameters
# -------------------------
FILTER = {
    "path_9"          : "Mid Up to High",
    "stepper_subtype" : "stepper_stable_up",
}
MIN_N = 80

# -------------------------
# 1) Get data
# -------------------------
df = basket_master_user_wk.copy()

if FILTER.get("path_9"):
    df = df[df["path_9"] == FILTER["path_9"]].copy()
if FILTER.get("stepper_subtype") and "stepper_subtype" in df.columns:
    df = df[
        df["stepper_subtype"] == FILTER["stepper_subtype"]
    ].copy()

print(f"Selected users: {df['user_id'].nunique():,}")

# -------------------------
# 2) Identify scannable variables
# -------------------------
dlog_vars = [
    c for c in df.columns
    if c.startswith("d_log_")
    and c != "d_log_weekly"
]

delta_vars = [
    c for c in df.columns
    if c.startswith("delta_")
    and c != "delta_weekly"
]

print(f"\nd_log candidates: {dlog_vars}")
print(f"delta candidates: {delta_vars}")

# -------------------------
# 3) Single-variable regression + Spearman
# -------------------------
def run_reg(data, x_col, y_col, min_n=MIN_N):
    d = data[[x_col, y_col]].replace(
        [np.inf, -np.inf], np.nan
    ).dropna()
    if len(d) < min_n:
        return None

    X = d[[x_col]].astype(float).values
    y = d[y_col].astype(float).values
    model = LinearRegression().fit(X, y)

    r_sp, p_sp = stats.spearmanr(d[x_col], d[y_col])
    sig = ("***" if p_sp < 0.001 else
           "**"  if p_sp < 0.01  else
           "*"   if p_sp < 0.05  else "ns")

    return {
        "lever"    : x_col,
        "n"        : int(len(d)),
        "coef"     : round(float(model.coef_[0]), 4),
        "r2"       : round(float(model.score(X, y)), 4),
        "spearman" : round(r_sp, 4),
        "sig"      : sig,
        "x_mean"   : round(float(d[x_col].mean()), 4),
        "x_std"    : round(float(d[x_col].std()),  4),
    }

# -------------------------
# 4) Scan the d_log definition
# -------------------------
dlog_results = []
for col in dlog_vars:
    out = run_reg(df, col, "d_log_weekly")
    if out:
        dlog_results.append(out)

dlog_basket_scan = (
    pd.DataFrame(dlog_results)
    .sort_values("spearman", ascending=False)
    .reset_index(drop=True)
)

# -------------------------
# 5) Scan the delta definition
# -------------------------
delta_results = []
for col in delta_vars:
    out = run_reg(df, col, "delta_weekly")
    if out:
        delta_results.append(out)

delta_basket_scan = (
    pd.DataFrame(delta_results)
    .sort_values("spearman", ascending=False)
    .reset_index(drop=True)
)

# -------------------------
# 6) Output results
# -------------------------
print("\n" + "="*70)
print("Basket-Side Lever Scan: d_log definition")
print("="*70)
print(f"\n{'Lever':<30} {'R²':>8} {'Spearman':>10} {'Sig':>6} {'Coef':>8}")
print("-"*65)
for _, row in dlog_basket_scan.iterrows():
    print(f"  {row['lever']:<28} {row['r2']:>8.4f} "
          f"{row['spearman']:>10.4f} {row['sig']:>6} "
          f"{row['coef']:>8.4f}")

print("\n" + "="*70)
print("Basket-Side Lever Scan: delta definition")
print("="*70)
print(f"\n{'Lever':<30} {'R²':>8} {'Spearman':>10} {'Sig':>6} {'Coef':>8}")
print("-"*65)
for _, row in delta_basket_scan.iterrows():
    print(f"  {row['lever']:<28} {row['r2']:>8.4f} "
          f"{row['spearman']:>10.4f} {row['sig']:>6} "
          f"{row['coef']:>8.4f}")

# -------------------------
# 7) Basket vs. Gap full comparison
# -------------------------
print("\n" + "="*70)
print("Basket vs. Gap Full Comparison (Spearman)")
print("="*70)
print(f"\n{'Lever':<30} {'Definition':>8} {'R²':>8} {'Spearman':>10} {'Sig':>6}")
print("-"*65)

# Strongest Basket signal
for _, row in dlog_basket_scan.head(3).iterrows():
    print(f"  {row['lever']:<28} {'d_log':>8} "
          f"{row['r2']:>8.4f} {row['spearman']:>10.4f} {row['sig']:>6}")

print("  " + "-"*60)

# Strongest Gap signal
gap_compare = [
    ("d_log_gap",       "d_log", 0.1849, -0.4271, "***"),
    ("delta_pct_gap10", "delta", 0.0653, -0.3153, "***"),
    ("delta_gap_std",   "delta", 0.0787, -0.3043, "***"),
    ("delta_pct_gap30", "delta", 0.0270, -0.2293, "***"),
]
for lever, kou_jing, r2, sp, sig in gap_compare:
    print(f"  {lever:<28} {kou_jing:>8} "
          f"{r2:>8.4f} {sp:>10.4f} {sig:>6}")

print("\n✅ New tables created:")
print("  - dlog_basket_scan   (d_log definition)")
print("  - delta_basket_scan  (delta definition)")

Selected users: 3,066

d_log candidates: ['d_log_total_items', 'd_log_unique_products', 'd_log_reorder_ratio', 'd_log_dept_entropy', 'd_log_basket_med']
delta candidates: ['delta_total_items', 'delta_n_unique_products', 'delta_n_unique_departments', 'delta_reorder_ratio', 'delta_items_per_unique_product', 'delta_consumable_share', 'delta_core_share', 'delta_variety_share', 'delta_durable_share', 'delta_dept_entropy', 'delta_dominant_dept_share', 'delta_basket_med']

======================================================================
Basket 侧 Lever Scan：d_log 口径
======================================================================

Lever                                R²   Spearman    Sig     Coef
-----------------------------------------------------------------
  d_log_basket_med               0.1748     0.3695    ***   0.3943
  d_log_total_items              0.1748     0.3692    ***   0.3943
  d_log_unique_products          0.1748     0.3692    ***   0.3943
  d_log_dept_entropy             0.0115     0.2564    ***   0.0320
  d_log_reorder_ratio            0.0000    -0.0803    ***   0.0012

======================================================================
Basket 侧 Lever Scan：delta 口径
======================================================================

Lever                                R²   Spearman    Sig     Coef
-----------------------------------------------------------------
  delta_total_items              0.1489     0.3476    ***   0.4311
  delta_n_unique_products        0.1489     0.3476    ***   0.4311
  delta_basket_med               0.1489     0.3476    ***   0.4311
  delta_n_unique_departments     0.1005     0.2763    ***   1.0852
  delta_dept_entropy             0.0692     0.2312    ***   4.7974
  delta_durable_share            0.0027     0.0552     **   4.7893
  delta_variety_share            0.0000     0.0078     ns  -0.0390
  delta_core_share               0.0000    -0.0185     ns   0.0084
  delta_reorder_ratio            0.0188    -0.0989    ***  -3.7058
  delta_consumable_share         0.0116    -0.1002    ***  -5.0022
  delta_dominant_dept_share      0.0248    -0.1259    ***  -7.9583
  delta_items_per_unique_product   0.0000        nan     ns   0.0000

======================================================================
Basket vs Gap 完整对比（Spearman）
======================================================================

Lever                                口径       R²   Spearman    Sig
-----------------------------------------------------------------
  d_log_basket_med                d_log   0.1748     0.3695    ***
  d_log_total_items               d_log   0.1748     0.3692    ***
  d_log_unique_products           d_log   0.1748     0.3692    ***
  ------------------------------------------------------------
  d_log_gap                       d_log   0.1849    -0.4271    ***
  delta_pct_gap10                 delta   0.0653    -0.3153    ***
  delta_gap_std                   delta   0.0787    -0.3043    ***
  delta_pct_gap30                 delta   0.0270    -0.2293    ***

✅ New tables created:
  - dlog_basket_scan   (d_log 口径)
  - delta_basket_scan  (delta 口径)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/398775055.py:66: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  r_sp, p_sp = stats.spearmanr(d[x_col], d[y_col])

In [119]:
# # ============================================================
# Basket-side Lever Scan (adds Spearman)
# All Mid→High users
# ============================================================

from sklearn.linear_model import LinearRegression
from scipy import stats
import numpy as np
import pandas as pd

# -------------------------
# 0) Parameters
# -------------------------
FILTER = {
    "path_9" : "Mid Up to High",
    # No filter on stepper_subtype → keep all Mid→High users
}
MIN_N = 80

# -------------------------
# 1) Get data
# -------------------------
df = basket_master_user_wk.copy()

if FILTER.get("path_9"):
    df = df[df["path_9"] == FILTER["path_9"]].copy()
if FILTER.get("stepper_subtype") and "stepper_subtype" in df.columns:
    df = df[
        df["stepper_subtype"] == FILTER["stepper_subtype"]
    ].copy()

print(f"Selected users: {df['user_id'].nunique():,}")

# -------------------------
# 2) Identify scannable variables
# -------------------------
dlog_vars = [
    c for c in df.columns
    if c.startswith("d_log_")
    and c != "d_log_weekly"
]

delta_vars = [
    c for c in df.columns
    if c.startswith("delta_")
    and c != "delta_weekly"
]

print(f"\nd_log candidates: {dlog_vars}")
print(f"delta candidates: {delta_vars}")

# -------------------------
# 3) Single-variable regression + Spearman
# -------------------------
def run_reg(data, x_col, y_col, min_n=MIN_N):
    d = data[[x_col, y_col]].replace(
        [np.inf, -np.inf], np.nan
    ).dropna()
    if len(d) < min_n:
        return None

    X = d[[x_col]].astype(float).values
    y = d[y_col].astype(float).values
    model = LinearRegression().fit(X, y)

    r_sp, p_sp = stats.spearmanr(d[x_col], d[y_col])
    sig = ("***" if p_sp < 0.001 else
           "**"  if p_sp < 0.01  else
           "*"   if p_sp < 0.05  else "ns")

    return {
        "lever"    : x_col,
        "n"        : int(len(d)),
        "coef"     : round(float(model.coef_[0]), 4),
        "r2"       : round(float(model.score(X, y)), 4),
        "spearman" : round(r_sp, 4),
        "sig"      : sig,
        "x_mean"   : round(float(d[x_col].mean()), 4),
        "x_std"    : round(float(d[x_col].std()),  4),
    }

# -------------------------
# 4) Scan the d_log definition
# -------------------------
dlog_results = []
for col in dlog_vars:
    out = run_reg(df, col, "d_log_weekly")
    if out:
        dlog_results.append(out)

dlog_basket_scan = (
    pd.DataFrame(dlog_results)
    .sort_values("spearman", ascending=False)
    .reset_index(drop=True)
)

# -------------------------
# 5) Scan the delta definition
# -------------------------
delta_results = []
for col in delta_vars:
    out = run_reg(df, col, "delta_weekly")
    if out:
        delta_results.append(out)

delta_basket_scan = (
    pd.DataFrame(delta_results)
    .sort_values("spearman", ascending=False)
    .reset_index(drop=True)
)

# -------------------------
# 6) Output results
# -------------------------
print("\n" + "="*70)
print("Basket-Side Lever Scan: d_log definition (all Mid→High users)")
print("="*70)
print(f"\n{'Lever':<30} {'R²':>8} {'Spearman':>10} {'Sig':>6} {'Coef':>8}")
print("-"*65)
for _, row in dlog_basket_scan.iterrows():
    print(f"  {row['lever']:<28} {row['r2']:>8.4f} "
          f"{row['spearman']:>10.4f} {row['sig']:>6} "
          f"{row['coef']:>8.4f}")

print("\n" + "="*70)
print("Basket-Side Lever Scan: delta definition (all Mid→High users)")
print("="*70)
print(f"\n{'Lever':<30} {'R²':>8} {'Spearman':>10} {'Sig':>6} {'Coef':>8}")
print("-"*65)
for _, row in delta_basket_scan.iterrows():
    print(f"  {row['lever']:<28} {row['r2']:>8.4f} "
          f"{row['spearman']:>10.4f} {row['sig']:>6} "
          f"{row['coef']:>8.4f}")

# -------------------------
# 7) Basket vs. Gap full comparison
# -------------------------
print("\n" + "="*70)
print("Basket vs. Gap Full Comparison (all Mid→High users, Spearman)")
print("="*70)
print(f"\n{'Lever':<30} {'Definition':>8} {'R²':>8} {'Spearman':>10} {'Sig':>6}")
print("-"*65)

for _, row in dlog_basket_scan.head(3).iterrows():
    print(f"  {row['lever']:<28} {'d_log':>8} "
          f"{row['r2']:>8.4f} {row['spearman']:>10.4f} {row['sig']:>6}")

print("  " + "-"*60)

gap_compare = [
    ("d_log_gap",       "d_log", 0.1849, -0.4271, "***"),
    ("delta_pct_gap10", "delta", 0.0653, -0.3153, "***"),
    ("delta_gap_std",   "delta", 0.0787, -0.3043, "***"),
    ("delta_pct_gap30", "delta", 0.0270, -0.2293, "***"),
]
for lever, kou_jing, r2, sp, sig in gap_compare:
    print(f"  {lever:<28} {kou_jing:>8} "
          f"{r2:>8.4f} {sp:>10.4f} {sig:>6}")

print("\n✅ New tables created:")
print("  - dlog_basket_scan   (d_log definition)")
print("  - delta_basket_scan  (delta definition)")

Selected users: 14,217

d_log candidates: ['d_log_total_items', 'd_log_unique_products', 'd_log_reorder_ratio', 'd_log_dept_entropy', 'd_log_basket_med']
delta candidates: ['delta_total_items', 'delta_n_unique_products', 'delta_n_unique_departments', 'delta_reorder_ratio', 'delta_items_per_unique_product', 'delta_consumable_share', 'delta_core_share', 'delta_variety_share', 'delta_durable_share', 'delta_dept_entropy', 'delta_dominant_dept_share', 'delta_basket_med']

======================================================================
Basket 侧 Lever Scan：d_log 口径（Mid→High 全体）
======================================================================

Lever                                R²   Spearman    Sig     Coef
-----------------------------------------------------------------
  d_log_basket_med               0.0755     0.2604    ***   0.2933
  d_log_total_items              0.0755     0.2603    ***   0.2933
  d_log_unique_products          0.0755     0.2603    ***   0.2933
  d_log_dept_entropy             0.0077     0.1792    ***   0.0280
  d_log_reorder_ratio            0.0045     0.0188      *   0.0137

======================================================================
Basket 侧 Lever Scan：delta 口径（Mid→High 全体）
======================================================================

Lever                                R²   Spearman    Sig     Coef
-----------------------------------------------------------------
  delta_total_items              0.0396     0.2497    ***   0.2394
  delta_n_unique_products        0.0396     0.2497    ***   0.2394
  delta_basket_med               0.0396     0.2497    ***   0.2394
  delta_n_unique_departments     0.0242     0.2008    ***   0.5660
  delta_dept_entropy             0.0195     0.1706    ***   2.7218
  delta_durable_share            0.0004     0.0346    ***   1.6946
  delta_variety_share            0.0000     0.0204      *   0.0376
  delta_core_share               0.0001    -0.0179      *  -0.3232
  delta_reorder_ratio            0.0007    -0.0382    ***  -0.8054
  delta_consumable_share         0.0017    -0.0558    ***  -1.8407
  delta_dominant_dept_share      0.0069    -0.0843    ***  -4.2954
  delta_items_per_unique_product   0.0000        nan     ns   0.0000

======================================================================
Basket vs Gap 完整对比（Mid→High 全体，Spearman）
======================================================================

Lever                                口径       R²   Spearman    Sig
-----------------------------------------------------------------
  d_log_basket_med                d_log   0.0755     0.2604    ***
  d_log_total_items               d_log   0.0755     0.2603    ***
  d_log_unique_products           d_log   0.0755     0.2603    ***
  ------------------------------------------------------------
  d_log_gap                       d_log   0.1849    -0.4271    ***
  delta_pct_gap10                 delta   0.0653    -0.3153    ***
  delta_gap_std                   delta   0.0787    -0.3043    ***
  delta_pct_gap30                 delta   0.0270    -0.2293    ***

✅ New tables created:
  - dlog_basket_scan   (d_log 口径)
  - delta_basket_scan  (delta 口径)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/3099011694.py:66: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  r_sp, p_sp = stats.spearmanr(d[x_col], d[y_col])

# 💡 Section 9: Quantitative Simulation

> Intensify + Flow + Integrated scenarios（ge10 & unique item）

---

In [120]:
# gap - intensify - modeling (ge10 version)
# ================================

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy.stats import spearmanr

# ================================
# 1. Load data
# ================================
# Using the current master table (already has pct_gap10_early / delta_pct_gap10)
df = analysis_mid_user_master.copy()

# ================================
# 2. Sample filtering
# ================================
df_up = df[df["path_9"] == "Mid Up to High"].copy()
print("Sample size (Mid → High):", len(df_up))

# Confirm the needed columns are all present
needed = [
    "delta_weekly", "delta_pct_gap10", "pct_gap10_early",
    "weekly_med_early", "basket_med_early",
    "delta_n_unique_products"
]
for col in needed:
    print(f"  {col}: {'✅' if col in df_up.columns else '❌'}")

# ================================
# 3. Define variables
# ================================

# Y: weekly growth
df_up["y"] = df_up["delta_weekly"]

# X: ge10 improvement (sign flipped, so improvement = positive)
# delta_pct_gap10 = late - early
# A decrease in ge10 is good (cadence improves)
# Sign flipped → ge10 improvement = positive
df_up["x"] = -df_up["delta_pct_gap10"]

"""
📌 Explanation:
delta_pct_gap10 = -0.15 (ge10 decreased 15pp)
x = +0.15 → means "cadence improved by 15pp"
"""

# ================================
# 4. Control variables
# ================================
controls = [
    "weekly_med_early",        # user's initial scale
    "basket_med_early",        # basket control
    "pct_gap10_early",         # ⭐ avoid regression to the mean
    "delta_n_unique_products"  # ⭐ control for the basket-side effect
]

"""
📌 Control variable notes:
1. weekly_med_early: differing initial scale
2. basket_med_early: controls for basket to avoid confounding
3. pct_gap10_early: users with high ge10 are more likely to naturally decline
   → without controlling for this, ge10's effect would be overestimated
4. delta_n_unique_products：
   → controls for the basket-side effect, ruling out confounding
"""

model_df = df_up[["y", "x"] + controls].dropna()
print(f"\nModeling sample size (after dropping missing): {len(model_df):,}")

# ================================
# 5. Winsorize
# ================================
def winsorize(series, lower=0.01, upper=0.99):
    lower_bound = series.quantile(lower)
    upper_bound = series.quantile(upper)
    return series.clip(lower_bound, upper_bound)

model_df["y"] = winsorize(model_df["y"])

# ================================
# 6. OLS regression (with robust standard errors)
# ================================
formula = "y ~ x + " + " + ".join(controls)
model = smf.ols(formula=formula, data=model_df).fit(cov_type="HC3")

print("\n========== Regression Results (ge10 version) ==========")
print(model.summary())

# ================================
# 7. Core results
# ================================
beta_gap = model.params["x"]
ci_low, ci_high = model.conf_int().loc["x"]

print("\n========== Core Results ==========")
print(f"β_ge10 (ge10 improvement coefficient): {beta_gap:.4f}")
print(f"95% confidence interval: [{ci_low:.4f}, {ci_high:.4f}]")
print(f"\n📌 Business interpretation:")
print(f"Every 1pp improvement in ge10 → weekly increases by {beta_gap:.4f} on average")

# Compare against the original ge30 coefficient
print(f"\nComparison:")
print(f"  ge30 coefficient (original): 5.0605")
print(f"  ge10 coefficient (current): {beta_gap:.4f}")

# ================================
# 8. Bucketed validation (monotonicity check)
# ================================
model_df["x_bucket"] = pd.qcut(
    model_df["x"], q=5, duplicates="drop"
)

bucket = (
    model_df
    .groupby("x_bucket", observed=True)
    .agg(
        users=("y", "count"),
        x_mean=("x", "mean"),
        y_mean=("y", "mean"),
        y_median=("y", "median")
    )
    .reset_index()
)

print("\n========== Bucketed Results (monotonicity check) ==========")
print(bucket.to_string(index=False))

# ================================
# 9. Monotonicity test (Spearman)
# ================================
corr, pval = spearmanr(bucket["x_mean"], bucket["y_mean"])

print("\n========== Monotonicity Test ==========")
print(f"Spearman correlation coefficient: {corr:.4f}")
print(f"P-value: {pval:.4f}")

if corr > 0:
    print("✅ More ge10 improvement → more weekly growth (as expected)")
else:
    print("⚠️ No monotonic relationship shown, please check the data")

# ================================
# 10. Quadratic term (nonlinearity check)
# ================================
model_df["x2"] = model_df["x"] ** 2

formula_quad = "y ~ x + x2 + " + " + ".join(controls)
model_quad = smf.ols(
    formula=formula_quad, data=model_df
).fit(cov_type="HC3")

print("\n========== Quadratic Term Model (marginal-effect check) ==========")
print(model_quad.summary())

# ================================
# 11. ge10 vs. ge30 coefficient comparison
# ================================
print("\n" + "="*60)
print("ge10 vs. ge30 Full Comparison")
print("="*60)
print(f"""
                    ge30 (original)    ge10 (current)
β coefficient:       5.0605          {beta_gap:.4f}
95% CI lower bound:  4.3434          {ci_low:.4f}
95% CI upper bound:  5.7776          {ci_high:.4f}
Spearman：          -0.244          -0.345
R² (single variable): 0.027           0.065
""")

样本量（Mid → High）： 14217
  delta_weekly: ✅
  delta_pct_gap10: ✅
  pct_gap10_early: ✅
  weekly_med_early: ✅
  basket_med_early: ✅
  delta_n_unique_products: ✅

建模样本量（去缺失后）：14,217

========== 回归结果（ge10 版本） ==========
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.343
Model:                            OLS   Adj. R-squared:                  0.343
Method:                 Least Squares   F-statistic:                     679.4
Date:                Thu, 02 Jul 2026   Prob (F-statistic):               0.00
Time:                        16:29:02   Log-Likelihood:                -39741.
No. Observations:               14217   AIC:                         7.949e+04
Df Residuals:                   14211   BIC:                         7.954e+04
Df Model:                           5
Covariance Type:                  HC3
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                  11.2194      0.583     19.253      0.000      10.077      12.362
x                          11.0153      0.208     53.033      0.000      10.608      11.422
weekly_med_early           -0.9101      0.089    -10.251      0.000      -1.084      -0.736
basket_med_early            0.3983      0.020     19.436      0.000       0.358       0.438
pct_gap10_early           -11.3237      0.464    -24.421      0.000     -12.233     -10.415
delta_n_unique_products     0.4158      0.010     40.587      0.000       0.396       0.436
==============================================================================
Omnibus:                     6612.665   Durbin-Watson:                   1.984
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            50187.080
Skew:                           2.090   Prob(JB):                         0.00
Kurtosis:                      11.201   Cond. No.                         112.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

========== 核心结果 ==========
β_ge10（ge10 改善系数）: 11.0153
95% 置信区间: [10.6082, 11.4224]

📌 业务解释：
ge10 每改善 1pp → weekly 平均增加 11.0153

对比：
  ge30 系数（原来）：5.0605
  ge10 系数（现在）：11.0153

========== 分桶结果（单调性检查） ==========
      x_bucket  users    x_mean   y_mean  y_median
 (-1.001, 0.0]   3495 -0.139504 5.374075  4.433333
  (0.0, 0.107]   2197  0.057545 5.772489  4.900000
(0.107, 0.239]   2842  0.172688 6.723903  5.636364
  (0.239, 0.4]   2908  0.310516 7.315644  6.300000
    (0.4, 1.0]   2775  0.578241 9.229353  7.905882

========== 单调性检验 ==========
Spearman 相关系数: 1.0000
P-value: 0.0000
✅ ge10 改善越多 → weekly 增长越多（符合预期）

========== 二次项模型（边际效应检查） ==========
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.349
Model:                            OLS   Adj. R-squared:                  0.349
Method:                 Least Squares   F-statistic:                     588.3
Date:                Thu, 02 Jul 2026   Prob (F-statistic):               0.00
Time:                        16:29:02   Log-Likelihood:                -39676.
No. Observations:               14217   AIC:                         7.937e+04
Df Residuals:                   14210   BIC:                         7.942e+04
Df Model:                           6
Covariance Type:                  HC3
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                  11.0980      0.579     19.173      0.000       9.964      12.232
x                           9.7644      0.231     42.215      0.000       9.311      10.218
x2                          3.2390      0.351      9.234      0.000       2.551       3.926
weekly_med_early           -0.8988      0.088    -10.207      0.000      -1.071      -0.726
basket_med_early            0.3952      0.020     19.429      0.000       0.355       0.435
pct_gap10_early           -11.3865      0.459    -24.824      0.000     -12.286     -10.487
delta_n_unique_products     0.4167      0.010     40.755      0.000       0.397       0.437
==============================================================================
Omnibus:                     6524.962   Durbin-Watson:                   1.986
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            49207.166
Skew:                           2.058   Prob(JB):                         0.00
Kurtosis:                      11.132   Cond. No.                         133.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

============================================================
ge10 vs ge30 完整对比
============================================================

                    ge30（原来）    ge10（现在）
β 系数：             5.0605          11.0153
95% CI 下界：        4.3434          10.6082
95% CI 上界：        5.7776          11.4224
Spearman：          -0.244          -0.345
R²（单变量）：        0.027           0.065

In [121]:
# improve 3pp - ge10 version
# =========================================
import pandas as pd
import numpy as np

# =========================================
# 1. Load data
# =========================================
df = analysis_mid_user_master.copy()

# =========================================
# 2. Keep only Mid → High users
# =========================================
df_up = df[df["path_9"] == "Mid Up to High"].copy()
print("Mid → High sample size:", len(df_up))

# =========================================
# 3. Model coefficients (ge10 OLS results)
# =========================================
beta_gap      = 11.0153   # ge10 improvement coefficient (originally ge30 = 5.0605)
beta_weekly_early = -0.9101
beta_basket_early =  0.3983
beta_unique   =  0.4158
intercept     = 11.2194
beta_gap_early = -11.3237  # coefficient for pct_gap10_early

# =========================================
# 4. Define variables
# =========================================

# Raw ge10 (lower is better)
df_up["gap_early"] = df_up["pct_gap10_early"]

# Convert to an "improvement variable" (higher is better)
df_up["x_gap_old"] = -df_up["gap_early"]

# Other variables
df_up["x_unique"]    = df_up["delta_n_unique_products"]
df_up["weekly_early"] = df_up["weekly_med_early"]
df_up["basket_early"] = df_up["basket_med_early"]

# =========================================
# 5. Headroom (P20 version)
# =========================================
target_gap = df_up["gap_early"].quantile(0.2)
target_gap = max(target_gap, 0.02)

print(f"Target ge10（P20 + floor）: {target_gap:.4f}")
print(f"ge10 Early distribution:")
print(df_up["gap_early"].describe(
    percentiles=[.1, .2, .25, .5, .75, .9]
).round(4))

df_up["gap_headroom_pp"] = np.maximum(
    0,
    (df_up["gap_early"] - target_gap) * 100
)

print(f"\nUsers with headroom: {(df_up['gap_headroom_pp'] > 0).sum():,}")
print(f"Average headroom (pp): {df_up['gap_headroom_pp'].mean():.2f}")

# =========================================
# 6. Scenario: +3pp improvement
# =========================================
delta_gap_target = 3  # pp

df_up["delta_gap_applied_pp"] = np.minimum(
    delta_gap_target,
    df_up["gap_headroom_pp"]
)

# Convert to a proportion (0-1)
df_up["delta_gap_applied"] = df_up["delta_gap_applied_pp"] / 100

# =========================================
# 7. Baseline (old world)
# =========================================
df_up["delta_weekly_old_pred"] = (
    intercept
    + beta_gap        * df_up["x_gap_old"]
    + beta_gap_early  * df_up["gap_early"]
    + beta_unique     * df_up["x_unique"]
    + beta_weekly_early * df_up["weekly_early"]
    + beta_basket_early * df_up["basket_early"]
)

# =========================================
# 8. Scenario (new world)
# =========================================
# ge10 decreases → improvement variable increases
df_up["gap_new"]    = df_up["gap_early"] - df_up["delta_gap_applied"]
df_up["x_gap_new"]  = -df_up["gap_new"]

df_up["delta_weekly_new_pred"] = (
    intercept
    + beta_gap        * df_up["x_gap_new"]
    + beta_gap_early  * df_up["gap_early"]   # early unchanged
    + beta_unique     * df_up["x_unique"]
    + beta_weekly_early * df_up["weekly_early"]
    + beta_basket_early * df_up["basket_early"]
)

# =========================================
# 9. Uplift
# =========================================
df_up["uplift"] = (
    df_up["delta_weekly_new_pred"]
    - df_up["delta_weekly_old_pred"]
)

# =========================================
# 10. Summary
# =========================================
total_uplift         = df_up["uplift"].sum()
avg_uplift           = df_up["uplift"].mean()
total_weekly_baseline = df_up["weekly_med_late"].sum()
uplift_pct           = total_uplift / total_weekly_baseline
affected_users       = (df_up["delta_gap_applied_pp"] > 0).sum()
affected_pct         = affected_users / len(df_up)

# =========================================
# 11. Output
# =========================================
print("\n========== 🎯 ge10 Scenario (+3pp improvement) ==========")
print(f"Total uplift (weekly increment)   : {total_uplift:,.2f}")
print(f"Per-user uplift            : {avg_uplift:.4f}")
print(f"Overall uplift percentage  : {uplift_pct:.2%}")

print("\n========== 📊 Headroom ==========")
print(f"Users with room to improve  : {affected_users:,}")
print(f"Share                      : {affected_pct:.2%}")
print(f"Average Δge10 applied (pp) : {df_up['delta_gap_applied_pp'].mean():.2f}")

print("\n========== 🔍 Sanity Check ==========")
print(f"Theoretical per-pp uplift  : {beta_gap / 100:.4f}")
print(f"Theoretical +3pp uplift    : {(beta_gap / 100) * 3:.4f}")
print(f"Actual per-user uplift     : {avg_uplift:.4f}")

print("\n========== 📊 ge10 vs. ge30 Comparison ==========")
print(f"""
                    ge30 (original)    ge10 (current)
β coefficient:       5.0605          {beta_gap:.4f}
Theoretical per-pp uplift: 0.0506           {beta_gap/100:.4f}
Theoretical +3pp uplift:   0.1518           {(beta_gap/100)*3:.4f}
""")

print("👉 Uplift should be positive and close to the theoretical value (slightly lower = headroom-limited)")

Mid → High 样本量: 14217
Target ge10（P20 + floor）: 0.2500
ge10 Early 分布：
count    14217.0000
mean         0.5249
std          0.2951
min          0.0000
10%          0.1250
20%          0.2500
25%          0.3077
50%          0.5000
75%          0.7500
90%          1.0000
max          1.0000
Name: gap_early, dtype: float64

有 headroom 用户数：11,219
平均 headroom（pp）：30.22

========== 🎯 ge10 Scenario（+3pp 改善） ==========
总 uplift（weekly 增量）   : 3,681.24
人均 uplift               : 0.2589
整体提升比例               : 1.95%

========== 📊 Headroom ==========
有提升空间用户数            : 11,219
占比                       : 78.91%
平均 Δge10 applied（pp）   : 2.35

========== 🔍 Sanity Check ==========
理论 per pp uplift         : 0.1102
理论 +3pp uplift           : 0.3305
实际人均 uplift             : 0.2589

========== 📊 ge10 vs ge30 对比 ==========

                    ge30（原来）    ge10（现在）
β 系数：             5.0605          11.0153
理论 per pp uplift： 0.0506           0.1102
理论 +3pp uplift：   0.1518           0.3305

👉 uplift 应该是正数，并接近理论值（略低 = headroom 限制）

In [122]:
# ge10 Scenario Analysis - multi-scenario version (3/5/7/10pp)
# =========================================
import pandas as pd
import numpy as np

# =========================================
# 1. Load data
# =========================================
df = analysis_mid_user_master.copy()
df_up = df[df["path_9"] == "Mid Up to High"].copy()
print(f"Mid → High sample size: {len(df_up):,}")

# =========================================
# 2. Model coefficients (ge10 OLS results)
# =========================================
beta_gap        = 11.0153
beta_weekly_early = -0.9101
beta_basket_early =  0.3983
beta_unique     =  0.4158
intercept       = 11.2194
beta_gap_early  = -11.3237

# =========================================
# 3. Define variables
# =========================================
df_up["gap_early"]   = df_up["pct_gap10_early"]
df_up["x_gap_old"]   = -df_up["gap_early"]
df_up["x_unique"]    = df_up["delta_n_unique_products"]
df_up["weekly_early"] = df_up["weekly_med_early"]
df_up["basket_early"] = df_up["basket_med_early"]

# =========================================
# 4. Headroom（P20）
# =========================================
target_gap = df_up["gap_early"].quantile(0.2)
target_gap = max(target_gap, 0.02)

df_up["gap_headroom_pp"] = np.maximum(
    0,
    (df_up["gap_early"] - target_gap) * 100
)

# =========================================
# 5. Baseline prediction
# =========================================
df_up["delta_weekly_old_pred"] = (
    intercept
    + beta_gap          * df_up["x_gap_old"]
    + beta_gap_early    * df_up["gap_early"]
    + beta_unique       * df_up["x_unique"]
    + beta_weekly_early * df_up["weekly_early"]
    + beta_basket_early * df_up["basket_early"]
)

# =========================================
# 6. Multi-scenario calculation
# =========================================
scenarios = [3, 5, 7, 10]
results = []

for delta_pp in scenarios:

    col = f"delta_gap_{delta_pp}pp"

    # Apply improvement (capped at headroom)
    df_up[col] = np.minimum(
        delta_pp,
        df_up["gap_headroom_pp"]
    )

    # New-world prediction
    gap_new   = df_up["gap_early"] - df_up[col] / 100
    x_gap_new = -gap_new

    weekly_new_pred = (
        intercept
        + beta_gap          * x_gap_new
        + beta_gap_early    * df_up["gap_early"]
        + beta_unique       * df_up["x_unique"]
        + beta_weekly_early * df_up["weekly_early"]
        + beta_basket_early * df_up["basket_early"]
    )

    uplift = weekly_new_pred - df_up["delta_weekly_old_pred"]

    # Summary
    affected = (df_up[col] > 0).sum()
    avg_applied = df_up[col].mean()

    results.append({
        "scenario"          : f"+{delta_pp}pp",
        "total_uplift"      : round(uplift.sum(), 2),
        "avg_uplift"        : round(uplift.mean(), 4),
        "uplift_pct"        : round(
            uplift.sum() / df_up["weekly_med_late"].sum(), 4
        ),
        "affected_users"    : affected,
        "affected_pct"      : round(affected / len(df_up), 4),
        "avg_applied_pp"    : round(avg_applied, 2),
        "theory_uplift_pp"  : round(beta_gap / 100, 4),
        "theory_total_uplift": round(
            (beta_gap / 100) * delta_pp, 4
        ),
    })

results_df = pd.DataFrame(results)

# =========================================
# 7. Output results
# =========================================
print("\n" + "="*70)
print("ge10 Multi-Scenario Uplift Analysis")
print("="*70)

print(f"\n{'Scenario':<10} {'Total Uplift':>12} {'Per-user Uplift':>12} "
      f"{'Uplift%':>8} {'Affected Users':>12} {'Share':>8} "
      f"{'Actual avg pp':>12}")
print("-"*80)

for _, row in results_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['total_uplift']:>12,.2f} "
          f"{row['avg_uplift']:>12.4f} "
          f"{row['uplift_pct']:>8.2%} "
          f"{row['affected_users']:>12,} "
          f"{row['affected_pct']:>8.2%} "
          f"{row['avg_applied_pp']:>12.2f}")

# =========================================
# 8. Sanity Check
# =========================================
print("\n" + "="*70)
print("Sanity Check: Theoretical vs. Actual")
print("="*70)

print(f"\nTheoretical per-pp uplift: {beta_gap/100:.4f}")
print(f"\n{'Scenario':<10} {'Theoretical Total Uplift':>14} {'Actual Per-user Uplift':>16} {'Diff':>10}")
print("-"*55)

for _, row in results_df.iterrows():
    diff = row["avg_uplift"] - row["theory_total_uplift"]
    print(f"{row['scenario']:<10} "
          f"{row['theory_total_uplift']:>14.4f} "
          f"{row['avg_uplift']:>16.4f} "
          f"{diff:>+10.4f}")

# =========================================
# 9. Copyable Excel table
# =========================================
print("\n" + "="*70)
print("Copyable table for Excel:")
print("="*70)
print("Scenario\tTotal Uplift\tAvg Uplift\tUplift %\t"
      "Affected Users\tAffected %\tAvg Applied pp\t"
      "Theory Uplift per pp\tTheory Total Uplift")

for _, row in results_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['total_uplift']}\t"
          f"{row['avg_uplift']}\t"
          f"{row['uplift_pct']:.2%}\t"
          f"{row['affected_users']}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['avg_applied_pp']}\t"
          f"{row['theory_uplift_pp']}\t"
          f"{row['theory_total_uplift']}")

print("\n✅ New tables created:")
print("  - results_df  (multi-scenario summary)")

Mid → High 样本量: 14,217

======================================================================
ge10 多场景 Uplift 分析
======================================================================

场景              总Uplift     人均Uplift      提升%        受影响用户       占比     实际avg pp
--------------------------------------------------------------------------------
+3pp           3,681.24       0.2589    1.95%       11,219   78.91%         2.35
+5pp           6,077.35       0.4275    3.21%       11,219   78.91%         3.88
+7pp           8,421.38       0.5923    4.45%       11,219   78.91%         5.38
+10pp         11,786.63       0.8291    6.23%       11,219   78.91%         7.53

======================================================================
Sanity Check：理论 vs 实际
======================================================================

理论 per pp uplift：0.1102

场景              理论总uplift       实际人均uplift         差值
-------------------------------------------------------
+3pp               0.3305           0.2589    -0.0716
+5pp               0.5508           0.4275    -0.1233
+7pp               0.7711           0.5923    -0.1788
+10pp              1.1015           0.8291    -0.2724

======================================================================
可复制到 Excel 的表格：
======================================================================
Scenario	Total Uplift	Avg Uplift	Uplift %	Affected Users	Affected %	Avg Applied pp	Theory Uplift per pp	Theory Total Uplift
+3pp	3681.24	0.2589	1.95%	11219	78.91%	2.35	0.1102	0.3305
+5pp	6077.35	0.4275	3.21%	11219	78.91%	3.88	0.1102	0.5508
+7pp	8421.38	0.5923	4.45%	11219	78.91%	5.38	0.1102	0.7711
+10pp	11786.63	0.8291	6.23%	11219	78.91%	7.53	0.1102	1.1015

✅ New tables created:
  - results_df  (多场景汇总)

In [123]:
# =========================================
# ge10 Gap Headroom core metrics analysis
# =========================================

import pandas as pd
import numpy as np

# =========================================
# 1. Confirm data is ready
# =========================================
print(f"df_up sample size: {len(df_up):,}")
print(f"gap_headroom_pp exists: {'gap_headroom_pp' in df_up.columns}")
print(f"\nheadroom distribution:")
print(df_up["gap_headroom_pp"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(2))

# =========================================
# 2. Define scenario
# =========================================
delta_targets = [3, 5, 7, 10]
results = []

# =========================================
# 3. Loop through each scenario
# =========================================
for delta_target in delta_targets:

    temp = df_up.copy()

    # Actually applied Δge10 (pp)
    temp["delta_gap_applied_pp"] = np.minimum(
        delta_target,
        temp["gap_headroom_pp"]
    )

    # Metric 1: average Δge10 (pp)
    avg_gap = temp["delta_gap_applied_pp"].mean()

    # Metric 2: share of users where the full improvement was applied (sufficient headroom)
    full_apply_pct = (temp["gap_headroom_pp"] >= delta_target).mean()

    # Metric 3: share of users capped (insufficient headroom)
    clipped_pct = (temp["gap_headroom_pp"] < delta_target).mean()

    # Metric 4: share of users affected (any improvement at all)
    affected_pct = (temp["delta_gap_applied_pp"] > 0).mean()

    # Metric 5: users with no headroom (already doing well)
    no_headroom_pct = (temp["gap_headroom_pp"] == 0).mean()

    results.append({
        "scenario"          : f"+{delta_target}pp",
        "avg_applied_pp"    : round(avg_gap, 2),
        "full_apply_pct"    : round(full_apply_pct, 4),
        "clipped_pct"       : round(clipped_pct, 4),
        "affected_pct"      : round(affected_pct, 4),
        "no_headroom_pct"   : round(no_headroom_pct, 4),
    })

result_df = pd.DataFrame(results)

# =========================================
# 4. Output results
# =========================================
print("\n" + "="*70)
print("ge10 Gap Headroom Core Metrics")
print("="*70)

print(f"\n{'Scenario':<10} {'Actual avgpp':>10} {'Full Apply%':>10} "
      f"{'Clipped%':>10} {'Affected%':>10} {'No Headroom%':>10}")
print("-"*60)

for _, row in result_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['avg_applied_pp']:>10.2f} "
          f"{row['full_apply_pct']:>10.2%} "
          f"{row['clipped_pct']:>10.2%} "
          f"{row['affected_pct']:>10.2%} "
          f"{row['no_headroom_pct']:>10.2%}")

# =========================================
# 5. Friendly print
# =========================================
print("\n" + "="*70)
print("Detailed Interpretation")
print("="*70)

for r in results:
    print(f"""
--- Scenario: {r['scenario']} ge10 improvement ---
Average actual Δge10 : {r['avg_applied_pp']:.2f} pp
Full-apply share    : {r['full_apply_pct']:.2%} (sufficient headroom)
Clipped share        : {r['clipped_pct']:.2%} (insufficient headroom, partial improvement only)
Affected share       : {r['affected_pct']:.2%} (any improvement)
No-headroom share    : {r['no_headroom_pct']:.2%} (already at target, no intervention needed)
""")

# =========================================
# 6. Copyable Excel table
# =========================================
print("="*70)
print("Copyable table for Excel:")
print("="*70)
print("Scenario\tAvg Applied pp\tFull Apply %\t"
      "Clipped %\tAffected %\tNo Headroom %")

for _, row in result_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['avg_applied_pp']}\t"
          f"{row['full_apply_pct']:.2%}\t"
          f"{row['clipped_pct']:.2%}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['no_headroom_pct']:.2%}")

print("\n✅ New tables created:")
print("  - result_df  (ge10 headroom core metrics)")

df_up 样本量: 14,217
gap_headroom_pp 存在: True

headroom 分布：
count    14217.00
mean        30.22
std         25.69
min          0.00
10%          0.00
25%          5.77
50%         25.00
75%         50.00
90%         75.00
max         75.00
Name: gap_headroom_pp, dtype: float64

======================================================================
ge10 Gap Headroom 核心指标
======================================================================

场景            实际avgpp      完整施加%       被截断%       被影响%       无空间%
------------------------------------------------------------
+3pp             2.35     77.48%     22.52%     78.91%     21.09%
+5pp             3.88     75.39%     24.61%     78.91%     21.09%
+7pp             5.38     74.14%     25.86%     78.91%     21.09%
+10pp            7.53     69.25%     30.75%     78.91%     21.09%

======================================================================
详细解读
======================================================================

--- Scenario: +3pp ge10 improvement ---
平均实际 Δge10     : 2.35 pp
完整施加比例        : 77.48%（headroom 足够）
被截断比例          : 22.52%（headroom 不足，只能部分改善）
被影响比例          : 78.91%（有任何改善）
无 headroom 比例   : 21.09%（已经达到 target，无需干预）


--- Scenario: +5pp ge10 improvement ---
平均实际 Δge10     : 3.88 pp
完整施加比例        : 75.39%（headroom 足够）
被截断比例          : 24.61%（headroom 不足，只能部分改善）
被影响比例          : 78.91%（有任何改善）
无 headroom 比例   : 21.09%（已经达到 target，无需干预）


--- Scenario: +7pp ge10 improvement ---
平均实际 Δge10     : 5.38 pp
完整施加比例        : 74.14%（headroom 足够）
被截断比例          : 25.86%（headroom 不足，只能部分改善）
被影响比例          : 78.91%（有任何改善）
无 headroom 比例   : 21.09%（已经达到 target，无需干预）


--- Scenario: +10pp ge10 improvement ---
平均实际 Δge10     : 7.53 pp
完整施加比例        : 69.25%（headroom 足够）
被截断比例          : 30.75%（headroom 不足，只能部分改善）
被影响比例          : 78.91%（有任何改善）
无 headroom 比例   : 21.09%（已经达到 target，无需干预）

======================================================================
可复制到 Excel 的表格：
======================================================================
Scenario	Avg Applied pp	Full Apply %	Clipped %	Affected %	No Headroom %
+3pp	2.35	77.48%	22.52%	78.91%	21.09%
+5pp	3.88	75.39%	24.61%	78.91%	21.09%
+7pp	5.38	74.14%	25.86%	78.91%	21.09%
+10pp	7.53	69.25%	30.75%	78.91%	21.09%

✅ New tables created:
  - result_df  (ge10 headroom 核心指标)

**Objective**: Before Flow Shift analysis, first compute pct_gap10 for the entire Mid-pool user population.

In [124]:
# ============================================================
# Compute ge10 for the entire Mid-pool population
# Create a new table, analysis_mid_user_master_v2
# Do not modify any original table
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# Step 1: fully copy all columns from the original table
# Filter only by path_9, no column filtering
# ----------------------------------------
mid_base = analysis_mid_user_master[
    analysis_mid_user_master["path_9"].isin([
        "Mid Up to High",
        "Mid Stay",
        "Mid Down to Low"
    ])
].copy()  # ← no column names specified, keep all original columns

print(f"Mid pool sample size: {len(mid_base):,}")
print(f"Original table column count: {len(mid_base.columns)}")
print(f"\npath_9 distribution:")
print(mid_base["path_9"].value_counts())

# ----------------------------------------
# Step 2: compute ge10 for all Mid users from order data
# Includes Mid Stay and Mid Down (previously missing)
# ----------------------------------------
orders_mid = (
    orders_enriched2
    .merge(mid_base[["user_id"]], on="user_id", how="inner")
    .sort_values(["user_id", "order_number"])
    .copy()
)

print(f"\nMid pool order count: {len(orders_mid):,}")

# Add pos and half (first 50%=early, last 50%=late)
user_n = (
    orders_mid
    .groupby("user_id")["order_number"]
    .max()
    .reset_index()
    .rename(columns={"order_number": "n_orders"})
)
orders_mid = orders_mid.merge(user_n, on="user_id", how="left")
orders_mid["pos"]  = orders_mid["order_number"] / orders_mid["n_orders"]
orders_mid["half"] = np.where(
    orders_mid["pos"] <= 0.5, "early", "late"
)

print(f"\nhalf distribution:")
print(orders_mid["half"].value_counts())

# ge10 early: share of orders with gap >= 10 days in the early stage
ge10_early = (
    orders_mid[orders_mid["half"] == "early"]
    .groupby("user_id")["gap_days_adj"]
    .apply(lambda x: (x >= 10).mean())
    .reset_index()
    .rename(columns={"gap_days_adj": "pct_gap10_early_v2"})
)

# ge10 late: share of orders with gap >= 10 days in the late stage
ge10_late = (
    orders_mid[orders_mid["half"] == "late"]
    .groupby("user_id")["gap_days_adj"]
    .apply(lambda x: (x >= 10).mean())
    .reset_index()
    .rename(columns={"gap_days_adj": "pct_gap10_late_v2"})
)

# ----------------------------------------
# Step 3: add the ge10 columns on top of the full original table
# No original columns removed
# ----------------------------------------
analysis_mid_user_master_v2 = (
    mid_base
    .merge(ge10_early, on="user_id", how="left")
    .merge(ge10_late,  on="user_id", how="left")
)

# Compute delta (late - early)
analysis_mid_user_master_v2["delta_pct_gap10_v2"] = (
    analysis_mid_user_master_v2["pct_gap10_late_v2"] -
    analysis_mid_user_master_v2["pct_gap10_early_v2"]
)

# ----------------------------------------
# Step 4: validate
# ----------------------------------------
print(f"\nanalysis_mid_user_master_v2 shape: {analysis_mid_user_master_v2.shape}")
print(f"Total column count: {len(analysis_mid_user_master_v2.columns)}")
print(f"\nAll columns:")
print(analysis_mid_user_master_v2.columns.tolist())

print(f"\nUsers with ge10 data by group:")
print(
    analysis_mid_user_master_v2
    .groupby("path_9")["delta_pct_gap10_v2"]
    .apply(lambda x: x.notna().sum())
)

# Key column validation
print(f"\nKey column validation:")
key_cols = [
    "weekly_med_early", "weekly_med_late",
    "basket_med_early", "basket_med_late",
    "delta_n_unique_products",
    "pct_gap10_early_v2", "pct_gap10_late_v2",
    "delta_pct_gap10_v2"
]
for col in key_cols:
    exists = col in analysis_mid_user_master_v2.columns
    print(f"  {col}: {'✅' if exists else '❌'}")

print(f"\nge10 Early distribution (all Mid users):")
print(
    analysis_mid_user_master_v2["pct_gap10_early_v2"]
    .describe(percentiles=[.1, .25, .5, .75, .9])
    .round(3)
)

print(f"\ndelta_pct_gap10 distribution (all Mid users):")
print(
    analysis_mid_user_master_v2["delta_pct_gap10_v2"]
    .describe(percentiles=[.1, .25, .5, .75, .9])
    .round(3)
)

print("\n✅ New table created:")
print("  - analysis_mid_user_master_v2 (full original table + ge10 data)")
print("  Original table completely unmodified ✅")

Mid 母池样本量: 73,367
原表列数: 66

path_9 分布：
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

Mid 母池订单数: 1,210,493

half 分布：
half
late     660810
early    549683
Name: count, dtype: int64

analysis_mid_user_master_v2 shape: (73367, 69)
总列数: 69

所有列：
['user_id', 'consumable_share_early', 'consumable_share_late', 'core_share_early', 'core_share_late', 'dept_entropy_early', 'dept_entropy_late', 'dominant_dept_share_early', 'dominant_dept_share_late', 'durable_share_early', 'durable_share_late', 'items_per_unique_product_early', 'items_per_unique_product_late', 'n_unique_departments_early', 'n_unique_departments_late', 'n_unique_products_early', 'n_unique_products_late', 'reorder_ratio_early', 'reorder_ratio_late', 'total_items_early', 'total_items_late', 'variety_share_early', 'variety_share_late', 'delta_total_items', 'delta_n_unique_products', 'delta_n_unique_departments', 'delta_reorder_ratio', 'delta_items_per_unique_product', 'delta_consumable_share', 'delta_core_share', 'delta_variety_share', 'delta_durable_share', 'delta_dept_entropy', 'delta_dominant_dept_share', 'd_log_total_items', 'd_log_unique_products', 'd_log_reorder_ratio', 'd_log_dept_entropy', 'basket_med_early', 'basket_med_late', 'delta_basket_med', 'd_log_basket_med', 'path_9', 'stepper_subtype', 'label', 'weekly_med_early', 'weekly_med_late', 'delta_weekly', 'd_log_weekly', 'd_log_gap', 'd_log_basket', 'gap_med_early_x', 'gap_med_late_x', 'pct_gap30_early', 'pct_gap30_late', 'gap_std_early', 'gap_std_late', 'gap_med_early_y', 'gap_med_late_y', 'n_orders_half_early', 'n_orders_half_late', 'delta_pct_gap30', 'delta_gap_std', 'pct_gap10_early', 'pct_gap10_late', 'delta_pct_gap10', 'pct_gap10_early_v2', 'pct_gap10_late_v2', 'delta_pct_gap10_v2']

各组有 ge10 数据的用户：
path_9
Mid Down to Low    15370
Mid Stay           43780
Mid Up to High     14217
Name: delta_pct_gap10_v2, dtype: int64

关键列验证：
  weekly_med_early: ✅
  weekly_med_late: ✅
  basket_med_early: ✅
  basket_med_late: ✅
  delta_n_unique_products: ✅
  pct_gap10_early_v2: ✅
  pct_gap10_late_v2: ✅
  delta_pct_gap10_v2: ✅

ge10 Early 分布（全体 Mid 用户）：
count    73367.000
mean         0.580
std          0.313
min          0.000
10%          0.136
25%          0.333
50%          0.571
75%          0.833
90%          1.000
max          1.000
Name: pct_gap10_early_v2, dtype: float64

delta_pct_gap10 分布（全体 Mid 用户）：
count    73367.000
mean         0.011
std          0.303
min         -1.000
10%         -0.333
25%         -0.173
50%          0.000
75%          0.179
90%          0.400
max          1.000
Name: delta_pct_gap10_v2, dtype: float64

✅ New table created:
  - analysis_mid_user_master_v2（完整原表 + ge10 数据）
  原表完全未修改 ✅

In [125]:
# ============================================================
# ge10 Flow Shift modeling (v2 version)
# Using analysis_mid_user_master_v2
# ============================================================

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from scipy.stats import spearmanr

# ----------------------------------------
# Step 1: data already in analysis_mid_user_master_v2
# ----------------------------------------
print(f"Mid pool sample size: {len(analysis_mid_user_master_v2):,}")
print(analysis_mid_user_master_v2["path_9"].value_counts())

# ----------------------------------------
# Step 2: define variables
# ----------------------------------------
df_mid = analysis_mid_user_master_v2.copy()

# Y: whether upgraded
df_mid["y"] = np.where(
    df_mid["path_9"] == "Mid Up to High", 1, 0
)
print(f"\nUp share (actual): {df_mid['y'].mean():.4f}")

# X: ge10 improvement (sign flipped, improvement=positive)
df_mid["x"] = -df_mid["delta_pct_gap10_v2"]

# Control variables
controls = [
    "weekly_med_early",
    "basket_med_early",
    "pct_gap10_early_v2",
    "delta_n_unique_products"
]

# ----------------------------------------
# Step 3: build the modeling dataset
# ----------------------------------------
model_df = df_mid[["y", "x"] + controls].dropna()

print(f"\nModeling sample size: {len(model_df):,}")
print(f"Up share (post-modeling): {model_df['y'].mean():.4f}")
print(f"\npath_9 distribution (post-modeling):")
print(df_mid.loc[model_df.index, "path_9"].value_counts())

# ----------------------------------------
# Step 4：Winsorize
# ----------------------------------------
def winsorize(series, lower=0.01, upper=0.99):
    return series.clip(
        series.quantile(lower),
        series.quantile(upper)
    )

model_df = model_df.copy()
model_df["x"] = winsorize(model_df["x"])

print(f"\nX (ge10 improvement) distribution:")
print(model_df["x"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(4))

# ----------------------------------------
# Step 5: Logit model
# ----------------------------------------
formula = "y ~ x + " + " + ".join(controls)
model = smf.logit(formula=formula, data=model_df).fit()

print("\n========== Logit Regression Results (ge10 version) ==========")
print(model.summary())

# ----------------------------------------
# Step 6: core results
# ----------------------------------------
beta_gap = model.params["x"]
ci_low, ci_high = model.conf_int().loc["x"]

print("\n========== Core Results ==========")
print(f"β_ge10       : {beta_gap:.4f}")
print(f"95% CI       : [{ci_low:.4f}, {ci_high:.4f}]")
print(f"Odds Ratio   : {np.exp(beta_gap):.4f}")

if beta_gap > 0:
    print("✅ ge10 improvement → upgrade probability ↑ (reasonable)")
else:
    print("⚠️ ge10 direction is anomalous, please check the variable definition")

# ----------------------------------------
# Step 7: bucketed validation
# ----------------------------------------
model_df["p_pred"] = model.predict(model_df)
model_df["x_bucket"] = pd.qcut(
    model_df["x"], q=5, duplicates="drop"
)

bucket = (
    model_df
    .groupby("x_bucket", observed=True)
    .agg(
        users=("y", "count"),
        x_mean=("x", "mean"),
        up_rate=("y", "mean"),
        pred_prob=("p_pred", "mean")
    )
    .reset_index()
)

print("\n========== Bucketed Results (monotonicity check) ==========")
print(f"\n{'Bucket':<20} {'Users':>8} {'x_mean':>10} "
      f"{'Up Rate':>10} {'Pred Prob':>12}")
print("-"*65)
for _, row in bucket.iterrows():
    print(f"{str(row['x_bucket']):<20} {row['users']:>8,} "
          f"{row['x_mean']:>10.4f} {row['up_rate']:>10.4f} "
          f"{row['pred_prob']:>12.4f}")

# ----------------------------------------
# Step 8: monotonicity test
# ----------------------------------------
corr, pval = spearmanr(bucket["x_mean"], bucket["up_rate"])

print(f"\n========== Monotonicity Test ==========")
print(f"Spearman: {corr:.4f}  p={pval:.4f}")

if corr > 0:
    print("✅ ge10 improvement → upgrade probability rises monotonically")
else:
    print("⚠️ No monotonic relationship shown")

# ----------------------------------------
# Step 9: control-variable sanity check
# ----------------------------------------
print(f"\n========== Control-Variable Sanity Check ==========")

checks = {
    "pct_gap10_early_v2"     : ("< 0", "higher early ge10 → harder to upgrade"),
    "weekly_med_early"       : ("> 0", "higher initial activity → easier to upgrade"),
    "basket_med_early"       : ("> 0", "larger initial basket → easier to upgrade"),
    "delta_n_unique_products": ("> 0", "more SKU expansion → easier to upgrade"),
}

for var, (expected, desc) in checks.items():
    if var in model.params:
        coef = model.params[var]
        ok = (expected == "< 0" and coef < 0) or \
             (expected == "> 0" and coef > 0)
        flag = "✅" if ok else "⚠️"
        print(f"  {var:<30} {coef:>8.4f} {flag} {desc}")

print("\n✅ New tables created:")
print("  - model     (ge10 Logit model)")
print("  - model_df  (modeling data)")
print("  - bucket    (bucketed results)")

Mid 母池样本量: 73,367
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

Up 比例（真实）: 0.1938

建模样本量: 73,367
Up 比例（建模后）: 0.1938

path_9 分布（建模后）:
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

X（ge10 改善）分布：
count    73367.0000
mean        -0.0115
std          0.2936
min         -0.8333
10%         -0.4000
25%         -0.1786
50%          0.0000
75%          0.1726
90%          0.3333
max          0.6667
Name: x, dtype: float64
Optimization terminated successfully.
         Current function value: 0.258414
         Iterations 8

========== Logit 回归结果（ge10 版本）==========
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                73367
Model:                          Logit   Df Residuals:                    73361
Method:                           MLE   Df Model:                            5
Date:                Thu, 02 Jul 2026   Pseudo R-squ.:                  0.4744
Time:                        16:29:07   Log-Likelihood:                -18959.
converged:                       True   LL-Null:                       -36071.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                  -2.2196      0.054    -41.363      0.000      -2.325      -2.114
x                           8.9163      0.085    105.201      0.000       8.750       9.082
weekly_med_early            0.1100      0.007     14.949      0.000       0.096       0.124
basket_med_early            0.3728      0.005     79.794      0.000       0.364       0.382
pct_gap10_early_v2         -8.5060      0.094    -90.623      0.000      -8.690      -8.322
delta_n_unique_products     0.3907      0.004     90.475      0.000       0.382       0.399
===========================================================================================

========== 核心结果 ==========
β_ge10       : 8.9163
95% CI       : [8.7501, 9.0824]
Odds Ratio   : 7452.2028
✅ ge10 改善 → 升级概率 ↑（合理）

========== 分桶结果（单调性检查）==========

Bucket                  Users     x_mean    Up Rate    Pred Prob
-----------------------------------------------------------------
(-0.834, -0.25]        15,342    -0.4317     0.0482       0.0392
(-0.25, -0.0449]       14,010    -0.1317     0.1166       0.1138
(-0.0449, 0.0401]      14,668    -0.0021     0.1245       0.1524
(0.0401, 0.236]        14,678     0.1324     0.2894       0.2761
(0.236, 0.667]         14,669     0.3893     0.3933       0.3908

========== 单调性检验 ==========
Spearman: 1.0000  p=0.0000
✅ ge10 改善 → 升级概率单调上升

========== 控制变量 Sanity Check ==========
  pct_gap10_early_v2              -8.5060 ✅ 早期 ge10 越高 → 越难升级
  weekly_med_early                 0.1100 ✅ 初始活跃度越高 → 越容易升级
  basket_med_early                 0.3728 ✅ 初始 basket 越大 → 越容易升级
  delta_n_unique_products          0.3907 ✅ SKU 扩张越多 → 越容易升级

✅ New tables created:
  - model     (ge10 Logit 模型)
  - model_df  (建模数据)
  - bucket    (分桶结果)

In [126]:
# ge10 Flow Shift Scenario Analysis（+3/5/7/10pp）
# =========================================
import pandas as pd
import numpy as np

# =========================================
# 1. Load data (using the v2 table)
# =========================================
df_mid = analysis_mid_user_master_v2.copy()
print(f"Mid pool sample size: {len(df_mid):,}")
print(df_mid["path_9"].value_counts())

# =========================================
# 2. Define variables (fully consistent with the modeling)
# =========================================

# Raw ge10
df_mid["gap_early"] = df_mid["pct_gap10_early_v2"]

# Δge10（late - early）
df_mid["delta_gap"] = df_mid["delta_pct_gap10_v2"]

# Flip direction: ge10 improvement = positive
df_mid["x_gap"] = -df_mid["delta_gap"]

# Control variables
df_mid["weekly_early"] = df_mid["weekly_med_early"]
df_mid["basket_early"] = df_mid["basket_med_early"]
df_mid["x_unique"]     = df_mid["delta_n_unique_products"]

# =========================================
# 3. Model coefficients (ge10 Logit results)
# =========================================
beta_gap       =  8.9163
beta_weekly    =  0.1100
beta_basket    =  0.3728
beta_gap_early = -8.5060
beta_unique    =  0.3907
intercept      = -2.2196

# =========================================
# 4. sigmoid function
# =========================================
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# =========================================
# 5. Headroom（P20）
# =========================================
target_gap = df_mid["gap_early"].quantile(0.2)
target_gap = max(target_gap, 0.02)

print(f"\nTarget ge10（P20 + floor）: {target_gap:.4f}")

df_mid["gap_headroom_pp"] = np.maximum(
    0,
    (df_mid["gap_early"] - target_gap) * 100
)

print(f"Users with headroom: {(df_mid['gap_headroom_pp'] > 0).sum():,}")
print(f"Average headroom (pp): {df_mid['gap_headroom_pp'].mean():.2f}")

# =========================================
# 6. Baseline（P_old）
# =========================================
df_mid["logit_old"] = (
    intercept
    + beta_gap       * df_mid["x_gap"]
    + beta_weekly    * df_mid["weekly_early"]
    + beta_basket    * df_mid["basket_early"]
    + beta_gap_early * df_mid["gap_early"]
    + beta_unique    * df_mid["x_unique"]
)
df_mid["p_old"] = sigmoid(df_mid["logit_old"])

print(f"\nBaseline average upgrade probability: {df_mid['p_old'].mean():.4f}")
print(f"Actual Up share:        {(df_mid['path_9'] == 'Mid Up to High').mean():.4f}")

# =========================================
# 7. Multi-scenario calculation
# =========================================
delta_targets = [3, 5, 7, 10]
results = []

for delta_target in delta_targets:

    temp = df_mid.copy()

    # Actually applied Δge10 (pp)
    temp["delta_gap_applied_pp"] = np.minimum(
        delta_target,
        temp["gap_headroom_pp"]
    )
    temp["delta_gap_applied"] = temp["delta_gap_applied_pp"] / 100

    # Scenario（P_new）
    # ge10 decreases → x_gap increases
    temp["x_gap_new"] = temp["x_gap"] + temp["delta_gap_applied"]

    temp["logit_new"] = (
        intercept
        + beta_gap       * temp["x_gap_new"]
        + beta_weekly    * temp["weekly_early"]
        + beta_basket    * temp["basket_early"]
        + beta_gap_early * temp["gap_early"]
        + beta_unique    * temp["x_unique"]
    )
    temp["p_new"] = sigmoid(temp["logit_new"])

    # ΔP
    temp["delta_p"] = temp["p_new"] - temp["p_old"]

    # Summary
    baseline_up      = (temp["path_9"] == "Mid Up to High").sum()
    total_flow_uplift = temp["delta_p"].sum()
    avg_delta_p      = temp["delta_p"].mean()
    affected_users   = (temp["delta_gap_applied_pp"] > 0).sum()
    affected_pct     = affected_users / len(temp)
    avg_applied      = temp["delta_gap_applied_pp"].mean()
    full_apply_pct   = (temp["gap_headroom_pp"] >= delta_target).mean()
    clipped_pct      = (temp["gap_headroom_pp"] < delta_target).mean()
    uplift_vs_base   = total_flow_uplift / baseline_up

    results.append({
        "scenario"          : f"+{delta_target}pp",
        "new_up_users"      : round(total_flow_uplift, 2),
        "avg_delta_p"       : round(avg_delta_p, 4),
        "uplift_vs_base"    : round(uplift_vs_base, 4),
        "affected_users"    : affected_users,
        "affected_pct"      : round(affected_pct, 4),
        "avg_applied_pp"    : round(avg_applied, 2),
        "full_apply_pct"    : round(full_apply_pct, 4),
        "clipped_pct"       : round(clipped_pct, 4),
        "theory_delta_logit": round(beta_gap * delta_target / 100, 4),
    })

results_df = pd.DataFrame(results)

# =========================================
# 8. Output results
# =========================================
print("\n" + "="*70)
print("ge10 Flow Shift Multi-Scenario Analysis")
print("="*70)

print(f"\n{'Scenario':<10} {'New Up Users':>12} {'Per-user ΔP':>10} "
      f"{'% of Base Up':>12} {'Affected Users':>12} {'Share':>8} "
      f"{'Actual avgpp':>10}")
print("-"*80)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['new_up_users']:>12.2f} "
          f"{row['avg_delta_p']:>10.4f} "
          f"{row['uplift_vs_base']:>12.2%} "
          f"{row['affected_users']:>12,} "
          f"{row['affected_pct']:>8.2%} "
          f"{row['avg_applied_pp']:>10.2f}")

# =========================================
# 9. Headroom details
# =========================================
print("\n" + "="*70)
print("Headroom Details")
print("="*70)

print(f"\n{'Scenario':<10} {'Full Apply%':>12} {'Clipped%':>10} {'Actual avgpp':>12}")
print("-"*50)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['full_apply_pct']:>12.2%} "
          f"{row['clipped_pct']:>10.2%} "
          f"{row['avg_applied_pp']:>12.2f}")

# =========================================
# 10. Friendly print
# =========================================
print("\n" + "="*70)
print("Detailed Interpretation")
print("="*70)

baseline_up = (df_mid["path_9"] == "Mid Up to High").sum()

for r in results:
    print(f"""
--- Scenario: {r['scenario']} ge10 improvement ---
New Up users (expected)   : {r['new_up_users']:.2f}
Per-user upgrade probability increase : {r['avg_delta_p']:.4f}
Share of baseline Up users : {r['uplift_vs_base']:.2%}
Affected users             : {r['affected_users']:,} ({r['affected_pct']:.2%})
Average actual Δge10       : {r['avg_applied_pp']:.2f} pp
Full-apply share           : {r['full_apply_pct']:.2%}
Clipped share              : {r['clipped_pct']:.2%}
Theoretical Δlogit ({r['scenario']}): {r['theory_delta_logit']:.4f}
""")

# =========================================
# 11. Copyable Excel table
# =========================================
print("="*70)
print("Copyable table for Excel:")
print("="*70)
print("Scenario\tNew Up Users\tAvg ΔP\tUplift vs Base\t"
      "Affected Users\tAffected %\tAvg Applied pp\t"
      "Full Apply %\tClipped %")

for _, row in results_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['new_up_users']}\t"
          f"{row['avg_delta_p']}\t"
          f"{row['uplift_vs_base']:.2%}\t"
          f"{row['affected_users']}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['avg_applied_pp']}\t"
          f"{row['full_apply_pct']:.2%}\t"
          f"{row['clipped_pct']:.2%}")

print("\n✅ New tables created:")
print("  - results_df  (multi-scenario summary)")

Mid 母池样本量: 73,367
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

Target ge10（P20 + floor）: 0.2857
有 headroom 用户数: 58,667
平均 headroom（pp）: 32.65

Baseline 平均升级概率: 0.1957
实际 Up 比例:          0.1938

======================================================================
ge10 Flow Shift 多场景分析
======================================================================

场景               新增Up人数       人均ΔP    占Base Up%        受影响用户       占比    实际avgpp
--------------------------------------------------------------------------------
+3pp            1162.14     0.0158        8.17%       58,667   79.96%       2.38
+5pp            1959.35     0.0267       13.78%       58,667   79.96%       3.94
+7pp            2744.76     0.0374       19.31%       58,667   79.96%       5.42
+10pp           3949.88     0.0538       27.78%       58,667   79.96%       7.60

======================================================================
Headroom 详情
======================================================================

场景                完整施加%       被截断%      实际avgpp
--------------------------------------------------
+3pp             78.75%     21.25%         2.38
+5pp             73.94%     26.06%         3.94
+7pp             73.59%     26.41%         5.42
+10pp            71.41%     28.59%         7.60

======================================================================
详细解读
======================================================================

--- Scenario: +3pp ge10 improvement ---
新增 Up 用户（expected）  : 1162.14
人均升级概率提升           : 0.0158
占 baseline Up 用户比例    : 8.17%
受影响用户数               : 58,667（79.96%）
平均实际 Δge10             : 2.38 pp
完整施加比例               : 78.75%
被截断比例                 : 21.25%
理论 Δlogit（+3pp）: 0.2675


--- Scenario: +5pp ge10 improvement ---
新增 Up 用户（expected）  : 1959.35
人均升级概率提升           : 0.0267
占 baseline Up 用户比例    : 13.78%
受影响用户数               : 58,667（79.96%）
平均实际 Δge10             : 3.94 pp
完整施加比例               : 73.94%
被截断比例                 : 26.06%
理论 Δlogit（+5pp）: 0.4458


--- Scenario: +7pp ge10 improvement ---
新增 Up 用户（expected）  : 2744.76
人均升级概率提升           : 0.0374
占 baseline Up 用户比例    : 19.31%
受影响用户数               : 58,667（79.96%）
平均实际 Δge10             : 5.42 pp
完整施加比例               : 73.59%
被截断比例                 : 26.41%
理论 Δlogit（+7pp）: 0.6241


--- Scenario: +10pp ge10 improvement ---
新增 Up 用户（expected）  : 3949.88
人均升级概率提升           : 0.0538
占 baseline Up 用户比例    : 27.78%
受影响用户数               : 58,667（79.96%）
平均实际 Δge10             : 7.60 pp
完整施加比例               : 71.41%
被截断比例                 : 28.59%
理论 Δlogit（+10pp）: 0.8916

======================================================================
可复制到 Excel 的表格：
======================================================================
Scenario	New Up Users	Avg ΔP	Uplift vs Base	Affected Users	Affected %	Avg Applied pp	Full Apply %	Clipped %
+3pp	1162.14	0.0158	8.17%	58667	79.96%	2.38	78.75%	21.25%
+5pp	1959.35	0.0267	13.78%	58667	79.96%	3.94	73.94%	26.06%
+7pp	2744.76	0.0374	19.31%	58667	79.96%	5.42	73.59%	26.41%
+10pp	3949.88	0.0538	27.78%	58667	79.96%	7.6	71.41%	28.59%

✅ New tables created:
  - results_df  (多场景汇总)

In [127]:
# =========================================
# ge10 Flow Headroom analysis (v2 version)
# =========================================

import pandas as pd
import numpy as np

# =========================================
# 1. Data preparation
# =========================================
df_mid = analysis_mid_user_master_v2.copy()
df_mid["gap_early"] = df_mid["pct_gap10_early_v2"]

print(f"Mid pool sample size: {len(df_mid):,}")
print(df_mid["path_9"].value_counts())

# =========================================
# 2. Headroom (consistent with the main model)
# =========================================
target_gap = df_mid["gap_early"].quantile(0.2)
target_gap = max(target_gap, 0.02)

print(f"\nTarget ge10（P20 + floor）: {target_gap:.4f}")

df_mid["gap_headroom_pp"] = np.maximum(
    0,
    (df_mid["gap_early"] - target_gap) * 100
)

print(f"Users with headroom: {(df_mid['gap_headroom_pp'] > 0).sum():,}")
print(f"Average headroom (pp): {df_mid['gap_headroom_pp'].mean():.2f}")

# =========================================
# 3. Loop through scenarios
# =========================================
delta_targets = [3, 5, 7, 10]
results = []

for delta_target in delta_targets:

    temp = df_mid.copy()

    temp["delta_gap_applied_pp"] = np.minimum(
        delta_target,
        temp["gap_headroom_pp"]
    )

    avg_gap        = temp["delta_gap_applied_pp"].mean()
    full_apply_pct = (temp["gap_headroom_pp"] >= delta_target).mean()
    clipped_pct    = (temp["gap_headroom_pp"] < delta_target).mean()
    affected_pct   = (temp["delta_gap_applied_pp"] > 0).mean()
    no_headroom    = (temp["gap_headroom_pp"] == 0).mean()

    results.append({
        "scenario"          : f"+{delta_target}pp",
        "avg_applied_pp"    : round(avg_gap, 2),
        "full_apply_pct"    : round(full_apply_pct, 4),
        "clipped_pct"       : round(clipped_pct, 4),
        "affected_pct"      : round(affected_pct, 4),
        "no_headroom_pct"   : round(no_headroom, 4),
    })

result_df = pd.DataFrame(results)

# =========================================
# 4. Output results
# =========================================
print("\n" + "="*70)
print("ge10 Flow Headroom Core Metrics")
print("="*70)

print(f"\n{'Scenario':<10} {'Actual avgpp':>10} {'Full Apply%':>10} "
      f"{'Clipped%':>10} {'Affected%':>10} {'No Headroom%':>10}")
print("-"*60)

for _, row in result_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['avg_applied_pp']:>10.2f} "
          f"{row['full_apply_pct']:>10.2%} "
          f"{row['clipped_pct']:>10.2%} "
          f"{row['affected_pct']:>10.2%} "
          f"{row['no_headroom_pct']:>10.2%}")

# =========================================
# 5. Friendly print
# =========================================
print("\n" + "="*70)
print("Detailed Interpretation")
print("="*70)

for r in results:
    print(f"""
--- Scenario: {r['scenario']} ge10 improvement ---
Average actual Δge10 : {r['avg_applied_pp']:.2f} pp
Full-apply share    : {r['full_apply_pct']:.2%} (sufficient headroom)
Clipped share        : {r['clipped_pct']:.2%} (insufficient headroom)
Affected share       : {r['affected_pct']:.2%} (any improvement)
No-headroom share    : {r['no_headroom_pct']:.2%} (already at target)
""")

# =========================================
# 6. Copyable Excel table
# =========================================
print("="*70)
print("Copyable for Excel:")
print("="*70)
print("Scenario\tAvg Applied pp\tFull Apply %\t"
      "Clipped %\tAffected %\tNo Headroom %")

for _, row in result_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['avg_applied_pp']}\t"
          f"{row['full_apply_pct']:.2%}\t"
          f"{row['clipped_pct']:.2%}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['no_headroom_pct']:.2%}")

print("\n✅ New tables created:")
print("  - result_df  (ge10 flow headroom core metrics)")

Mid 母池样本量: 73,367
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

Target ge10（P20 + floor）: 0.2857
有 headroom 用户数: 58,667
平均 headroom（pp）: 32.65

======================================================================
ge10 Flow Headroom 核心指标
======================================================================

场景            实际avgpp      完整施加%       被截断%       被影响%       无空间%
------------------------------------------------------------
+3pp             2.38     78.75%     21.25%     79.96%     20.04%
+5pp             3.94     73.94%     26.06%     79.96%     20.04%
+7pp             5.42     73.59%     26.41%     79.96%     20.04%
+10pp            7.60     71.41%     28.59%     79.96%     20.04%

======================================================================
详细解读
======================================================================

--- Scenario: +3pp ge10 improvement ---
平均实际 Δge10     : 2.38 pp
完整施加比例        : 78.75%（headroom 足够）
被截断比例          : 21.25%（headroom 不足）
被影响比例          : 79.96%（有任何改善）
无 headroom 比例   : 20.04%（已达 target）


--- Scenario: +5pp ge10 improvement ---
平均实际 Δge10     : 3.94 pp
完整施加比例        : 73.94%（headroom 足够）
被截断比例          : 26.06%（headroom 不足）
被影响比例          : 79.96%（有任何改善）
无 headroom 比例   : 20.04%（已达 target）


--- Scenario: +7pp ge10 improvement ---
平均实际 Δge10     : 5.42 pp
完整施加比例        : 73.59%（headroom 足够）
被截断比例          : 26.41%（headroom 不足）
被影响比例          : 79.96%（有任何改善）
无 headroom 比例   : 20.04%（已达 target）


--- Scenario: +10pp ge10 improvement ---
平均实际 Δge10     : 7.60 pp
完整施加比例        : 71.41%（headroom 足够）
被截断比例          : 28.59%（headroom 不足）
被影响比例          : 79.96%（有任何改善）
无 headroom 比例   : 20.04%（已达 target）

======================================================================
可复制到 Excel：
======================================================================
Scenario	Avg Applied pp	Full Apply %	Clipped %	Affected %	No Headroom %
+3pp	2.38	78.75%	21.25%	79.96%	20.04%
+5pp	3.94	73.94%	26.06%	79.96%	20.04%
+7pp	5.42	73.59%	26.41%	79.96%	20.04%
+10pp	7.6	71.41%	28.59%	79.96%	20.04%

✅ New tables created:
  - result_df  (ge10 flow headroom 核心指标)

**Gap-Side Integrated Intensify + Flow + Headroom — Case A vs. Case B**

**Case A (conservative estimate)**

Flow Uplift calculation: `delta_p × (avg_high - weekly_old)`

Newly upgraded users' weekly = avg_high (average High-user level). Assumes Mid → High users reach the average High level immediately upon upgrading, only counting the level jump, without additionally accounting for the intensify effect from the intervention itself.

**Case B (aggressive estimate)**

Flow Uplift calculation: `delta_p × (avg_high - weekly_old + delta_weekly_i)`

Newly upgraded users' weekly = avg_high + Δweekly_i (additional growth from the intervention). On top of the level jump, this adds the intensify effect from the intervention itself.

**Numeric comparison (+3pp scenario)**

- Existing uplift: 1,140 (same for both Cases)
- Flow uplift: Case A 3,970 vs. Case B higher (due to the added intensify effect)
- Total uplift: Case A 5,110 vs. Case B higher
- % uplift: Case A 2.70% vs. Case B higher

**How to choose**: Case A is better suited for external reporting — it won't overstate the effect and is more easily accepted; Case B is better suited for internal planning — it accounts for the compounded effect of the intervention and is theoretically more complete, but carries overestimation risk.

In [128]:
# case a multi-scenario
# ============================================================
# ge10 Integrated Flow + Intensify（Case A）
# Fix: x_gap_old/new switched to use the improvement amount (delta), consistent with the modeling
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# 1. Load data
# ----------------------------------------
df_mid = analysis_mid_user_master_v2.copy()
df_up  = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"Mid pool: {len(df_mid):,}")
print(f"Mid→High: {len(df_up):,}")
print(df_mid["path_9"].value_counts())

# ----------------------------------------
# 2. Model parameters (ge10 version)
# ----------------------------------------

# Flow model (Logit)
flow_intercept      = -2.2196
flow_beta_gap       =  8.9163  # coefficient for ge10 improvement
flow_beta_weekly    =  0.1100
flow_beta_basket    =  0.3728
flow_beta_gap_early = -8.5060  # control-variable coefficient for early ge10 level
flow_beta_unique    =  0.3907

# Intensify model (OLS)
int_intercept      = 11.2194
int_beta_gap       = 11.0153   # coefficient for ge10 improvement
int_beta_weekly    = -0.9101
int_beta_basket    =  0.3983
int_beta_gap_early = -11.3237  # control-variable coefficient for early ge10 level
int_beta_unique    =  0.4158

# ----------------------------------------
# 3. Define variables
# ----------------------------------------

# Mid pool
df_mid["gap_early"]    = df_mid["pct_gap10_early_v2"]
# Meaning: the user's early-stage ge10 level (share of orders with gap>=10 days)
# Purpose: control variable, controls for the "regression to the mean" effect

df_mid["weekly_old"]   = df_mid["weekly_med_late"]
# Meaning: the user's current (late-stage) weekly level
# Purpose: to compute level jump = avg_high - weekly_old

df_mid["weekly_early"] = df_mid["weekly_med_early"]
# Meaning: the user's early-stage weekly level
# Purpose: control variable for the flow and intensify models

df_mid["basket"]       = df_mid["basket_med_early"]
# Meaning: the user's early-stage basket size
# Purpose: control variable

df_mid["unique"]       = df_mid["delta_n_unique_products"]
# Meaning: the user's change in unique SKUs (late - early)
# Purpose: control variable, to exclude the basket-side influence

df_mid["x_gap_old"]    = -df_mid["delta_pct_gap10_v2"]
# Meaning: the user's "pre-existing" ge10 improvement (sign flipped: improvement=positive)
# Purpose: fully consistent with x = -delta_pct_gap10_v2 used in modeling
# Note: delta_pct_gap10_v2 = late - early
#       so x_gap_old = -(late - early) = early - late
#       a larger value = more ge10 improvement

# Mid→High
df_up["gap_early"]    = df_up["pct_gap10_early"]
# Meaning: Mid→High users' early-stage ge10 level
# Purpose: control variable for the intensify model

df_up["weekly_early"] = df_up["weekly_med_early"]
df_up["basket"]       = df_up["basket_med_early"]
df_up["unique"]       = df_up["delta_n_unique_products"]

df_up["x_gap_old"]    = -df_up["delta_pct_gap10"]
# Meaning: Mid→High users' "pre-existing" ge10 improvement
# Purpose: consistent with the x definition used in modeling

# ----------------------------------------
# 4. Headroom（P20）
# Meaning: how much ge10 improvement headroom each user still has
# Calculation: user's early ge10 - P20 target value (0 if already at target)
# ----------------------------------------
target_gap = df_mid["gap_early"].quantile(0.2)
target_gap = max(target_gap, 0.02)

print(f"\nTarget ge10（P20 + floor）: {target_gap:.4f}")

df_mid["gap_headroom"] = np.maximum(
    0, (df_mid["gap_early"] - target_gap)
)
# Meaning: how much more ge10 the user can still improve
# = max(0, early ge10 - P20 target)
# Purpose: cap the intervention strength so users don't overshoot the target

df_up["gap_headroom"] = np.maximum(
    0, (df_up["gap_early"] - target_gap)
)

# ----------------------------------------
# 5. sigmoid function
# ----------------------------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# ----------------------------------------
# 6. avg_high and baseline
# ----------------------------------------
avg_high      = df_up["weekly_med_late"].mean()
# Meaning: Mid→High users' average late-stage weekly level
# Purpose: represents the "level achievable after upgrading"

baseline_high = df_up["weekly_med_late"].sum()
# Meaning: Mid→High users' total weekly (baseline)
# Purpose: to compute the uplift percentage

print(f"avg_high: {avg_high:.4f}")
print(f"baseline_high: {baseline_high:,.2f}")

# ----------------------------------------
# 7. Multi-scenario calculation (+3/5/7/10pp)
# ----------------------------------------
scenarios = [3, 5, 7, 10]
results = []

for scenario_pp in scenarios:

    scenario = scenario_pp / 100

    # delta_gap_applied: the ge10 improvement actually applied
    # = min(target improvement, user's remaining headroom)
    # Meaning: how many pp the intervention can improve for the user (capped by headroom)
    df_mid["delta_gap_applied"] = np.minimum(
        scenario, df_mid["gap_headroom"]
    )
    df_up["delta_gap_applied"] = np.minimum(
        scenario, df_up["gap_headroom"]
    )

    # x_gap_new: ge10 improvement after the intervention
    # = pre-existing improvement + additional intervention improvement
    # Meaning: the user's total improvement after the intervention (consistent with the x definition used in modeling)
    df_mid["x_gap_new"] = df_mid["x_gap_old"] + df_mid["delta_gap_applied"]
    df_up["x_gap_new"]  = df_up["x_gap_old"]  + df_up["delta_gap_applied"]

    # ---- Flow: compute ΔP ----
    # logit_old: the logit value before the intervention
    # Computed using the exact same formula as the modeling
    df_mid["logit_old"] = (
        flow_intercept
        + flow_beta_gap       * df_mid["x_gap_old"]    # contribution of ge10 improvement
        + flow_beta_weekly    * df_mid["weekly_early"]  # control for initial scale
        + flow_beta_basket    * df_mid["basket"]        # control for basket
        + flow_beta_gap_early * df_mid["gap_early"]     # control for early ge10 level
        + flow_beta_unique    * df_mid["unique"]        # control for SKU change
    )
    df_mid["p_old"] = sigmoid(df_mid["logit_old"])
    # Meaning: each user's upgrade probability before the intervention

    df_mid["logit_new"] = (
        flow_intercept
        + flow_beta_gap       * df_mid["x_gap_new"]    # ← only this term changed
        + flow_beta_weekly    * df_mid["weekly_early"]
        + flow_beta_basket    * df_mid["basket"]
        + flow_beta_gap_early * df_mid["gap_early"]    # gap_early unchanged!
        + flow_beta_unique    * df_mid["unique"]
    )
    df_mid["p_new"]   = sigmoid(df_mid["logit_new"])
    # Meaning: each user's upgrade probability after the intervention

    df_mid["delta_p"] = df_mid["p_new"] - df_mid["p_old"]
    # Meaning: the increase in upgrade probability from the intervention
    # Purpose: multiplied by level jump = each user's contribution to flow uplift

    # ---- Intensify：existing uplift ----
    df_up["delta_old"] = (
        int_intercept
        + int_beta_gap       * df_up["x_gap_old"]
        + int_beta_weekly    * df_up["weekly_early"]
        + int_beta_basket    * df_up["basket"]
        + int_beta_gap_early * df_up["gap_early"]
        + int_beta_unique    * df_up["unique"]
    )
    # Meaning: Mid→High users' predicted weekly growth before the intervention

    df_up["delta_new"] = (
        int_intercept
        + int_beta_gap       * df_up["x_gap_new"]     # ← only this term changed
        + int_beta_weekly    * df_up["weekly_early"]
        + int_beta_basket    * df_up["basket"]
        + int_beta_gap_early * df_up["gap_early"]
        + int_beta_unique    * df_up["unique"]
    )
    # Meaning: Mid→High users' predicted weekly growth after the intervention

    df_up["delta_weekly_i"] = np.maximum(
        0, df_up["delta_new"] - df_up["delta_old"]
    )
    # Meaning: the additional weekly growth from the intervention (intensify uplift)
    # max(0) prevents negative values

    existing_uplift = df_up["delta_weekly_i"].sum()
    # Meaning: total weekly increment for already-upgraded users (Mid→High)

    # ---- Case A：Flow uplift（level jump only）----
    df_mid["flow_uplift_i"] = np.maximum(
        0,
        df_mid["delta_p"] * (avg_high - df_mid["weekly_old"])
    )
    # Meaning:
    # delta_p = increase in upgrade probability
    # (avg_high - weekly_old) = level jump (from the current level to the average High level)
    # Product = this user's expected contribution to weekly increment
    # max(0) prevents negative values for users where weekly_old > avg_high

    flow_uplift  = df_mid["flow_uplift_i"].sum()
    # Meaning: total weekly increment contributed by newly upgraded users

    total_uplift = existing_uplift + flow_uplift
    # Meaning: total weekly increment = increment from already-upgraded users + increment from newly upgraded users

    results.append({
        "scenario"        : f"+{scenario_pp}pp",
        "existing_uplift" : round(existing_uplift, 2),
        "flow_uplift"     : round(flow_uplift, 2),
        "total_uplift"    : round(total_uplift, 2),
        "uplift_pct"      : round(total_uplift / baseline_high, 4),
        "new_up_users"    : round(df_mid["delta_p"].sum(), 2),
        "avg_delta_p"     : round(df_mid["delta_p"].mean(), 4),
        "avg_applied_pp"  : round(
            (df_mid["delta_gap_applied"] * 100).mean(), 2
        ),
        "affected_pct"    : round(
            (df_mid["delta_gap_applied"] > 0).mean(), 4
        ),
        "full_apply_pct"  : round(
            (df_mid["gap_headroom"] >= scenario).mean(), 4
        ),
    })

results_df = pd.DataFrame(results)

# ----------------------------------------
# 8. Output results
# ----------------------------------------
print("\n" + "="*70)
print("Case A: ge10 Integrated (Flow + Intensify) Multi-Scenario")
print("="*70)

print(f"\n{'Scenario':<10} {'Existing':>12} {'Flow':>12} "
      f"{'Total':>12} {'Uplift%':>8} {'New Up':>10}")
print("-"*68)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['existing_uplift']:>12,.2f} "
          f"{row['flow_uplift']:>12,.2f} "
          f"{row['total_uplift']:>12,.2f} "
          f"{row['uplift_pct']:>8.2%} "
          f"{row['new_up_users']:>10.2f}")

print("\n" + "="*70)
print("Headroom Details")
print("="*70)
print(f"\n{'Scenario':<10} {'Actual avgpp':>10} {'Full Apply%':>12} {'Affected%':>10}")
print("-"*45)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['avg_applied_pp']:>10.2f} "
          f"{row['full_apply_pct']:>12.2%} "
          f"{row['affected_pct']:>10.2%}")

print("\n" + "="*70)
print("Sanity Check")
print("="*70)
print(f"avg_high:       {avg_high:.4f}")
print(f"avg level jump: {(avg_high - df_mid['weekly_old']).mean():.4f}")
print(f"avg delta_p:    {df_mid['delta_p'].mean():.4f}")
print(f"avg p_old:      {df_mid['p_old'].mean():.4f}")

print("\n" + "="*70)
print("Copyable for Excel:")
print("="*70)
print("Scenario\tExisting Uplift\tFlow Uplift\tTotal Uplift\t"
      "Uplift %\tNew Up Users\tAvg Applied pp\tFull Apply %\tAffected %")
for _, row in results_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['existing_uplift']}\t"
          f"{row['flow_uplift']}\t"
          f"{row['total_uplift']}\t"
          f"{row['uplift_pct']:.2%}\t"
          f"{row['new_up_users']}\t"
          f"{row['avg_applied_pp']}\t"
          f"{row['full_apply_pct']:.2%}\t"
          f"{row['affected_pct']:.2%}")

print("\n✅ New tables created:")
print("  - results_df  (Case A multi-scenario summary)")

Mid 母池: 73,367
Mid→High: 14,217
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

Target ge10（P20 + floor）: 0.2857
avg_high: 13.3104
baseline_high: 189,233.54

======================================================================
Case A：ge10 Integrated（Flow + Intensify）多场景
======================================================================

场景             Existing         Flow        Total      提升%       新增Up
--------------------------------------------------------------------
+3pp           3,549.44     5,977.96     9,527.40    5.03%    1162.14
+5pp           5,853.75    10,251.59    16,105.34    8.51%    1959.35
+7pp           8,031.58    14,597.30    22,628.88   11.96%    2744.76
+10pp         11,210.47    21,533.21    32,743.68   17.30%    3949.88

======================================================================
Headroom 详情
======================================================================

场景            实际avgpp        完整施加%       被影响%
---------------------------------------------
+3pp             2.38       78.75%     79.96%
+5pp             3.94       73.94%     79.96%
+7pp             5.42       73.59%     79.96%
+10pp            7.60       71.41%     79.96%

======================================================================
Sanity Check
======================================================================
avg_high:       13.3104
avg level jump: 6.9980
avg delta_p:    0.0538
avg p_old:      0.1957

======================================================================
可复制到 Excel：
======================================================================
Scenario	Existing Uplift	Flow Uplift	Total Uplift	Uplift %	New Up Users	Avg Applied pp	Full Apply %	Affected %
+3pp	3549.44	5977.96	9527.4	5.03%	1162.14	2.38	78.75%	79.96%
+5pp	5853.75	10251.59	16105.34	8.51%	1959.35	3.94	73.94%	79.96%
+7pp	8031.58	14597.3	22628.88	11.96%	2744.76	5.42	73.59%	79.96%
+10pp	11210.47	21533.21	32743.68	17.30%	3949.88	7.6	71.41%	79.96%

✅ New tables created:
  - results_df  (Case A 多场景汇总)

In [129]:
# ============================================================
# ge10 Integrated Flow + Intensify（Case B）
# Case B：Flow uplift = ΔP × (level jump + marginal intensify)
# Fix: x_gap uses the improvement amount, multi-scenario, full pool
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# 1. Load data
# ----------------------------------------
df_mid = analysis_mid_user_master_v2.copy()
df_up  = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"Mid pool: {len(df_mid):,}")
print(f"Mid→High: {len(df_up):,}")
print(df_mid["path_9"].value_counts())

# ----------------------------------------
# 2. Model parameters (ge10 version)
# ----------------------------------------

# Flow model (Logit)
flow_intercept      = -2.2196
flow_beta_gap       =  8.9163
flow_beta_weekly    =  0.1100
flow_beta_basket    =  0.3728
flow_beta_gap_early = -8.5060
flow_beta_unique    =  0.3907

# Intensify model (OLS)
int_intercept      = 11.2194
int_beta_gap       = 11.0153
int_beta_weekly    = -0.9101
int_beta_basket    =  0.3983
int_beta_gap_early = -11.3237
int_beta_unique    =  0.4158

# ----------------------------------------
# 3. Define variables
# ----------------------------------------

# Mid pool
df_mid["gap_early"]    = df_mid["pct_gap10_early_v2"]
# Early-stage ge10 level, used as a control variable

df_mid["weekly_old"]   = df_mid["weekly_med_late"]
# The user's current weekly level, used to compute level jump

df_mid["weekly_early"] = df_mid["weekly_med_early"]
df_mid["basket"]       = df_mid["basket_med_early"]
df_mid["unique"]       = df_mid["delta_n_unique_products"]

df_mid["x_gap_old"]    = -df_mid["delta_pct_gap10_v2"]
# The user's pre-existing ge10 improvement (consistent with modeling)

# Mid→High
df_up["gap_early"]    = df_up["pct_gap10_early"]
df_up["weekly_early"] = df_up["weekly_med_early"]
df_up["basket"]       = df_up["basket_med_early"]
df_up["unique"]       = df_up["delta_n_unique_products"]

df_up["x_gap_old"]    = -df_up["delta_pct_gap10"]
# The user's pre-existing ge10 improvement

# ----------------------------------------
# 4. Headroom（P20）
# ----------------------------------------
target_gap = df_mid["gap_early"].quantile(0.2)
target_gap = max(target_gap, 0.02)

print(f"\nTarget ge10（P20 + floor）: {target_gap:.4f}")

df_mid["gap_headroom"] = np.maximum(
    0, (df_mid["gap_early"] - target_gap)
)
df_up["gap_headroom"] = np.maximum(
    0, (df_up["gap_early"] - target_gap)
)

# ----------------------------------------
# 5. sigmoid function
# ----------------------------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# ----------------------------------------
# 6. avg_high and baseline
# ----------------------------------------
avg_high      = df_up["weekly_med_late"].mean()
baseline_high = df_up["weekly_med_late"].sum()

print(f"avg_high: {avg_high:.4f}")
print(f"baseline_high: {baseline_high:,.2f}")

# ----------------------------------------
# 7. Multi-scenario calculation (+3/5/7/10pp)
# ----------------------------------------
scenarios = [3, 5, 7, 10]
results = []

for scenario_pp in scenarios:

    scenario = scenario_pp / 100

    # Actually applied (capped by headroom)
    df_mid["delta_gap_applied"] = np.minimum(
        scenario, df_mid["gap_headroom"]
    )
    df_up["delta_gap_applied"] = np.minimum(
        scenario, df_up["gap_headroom"]
    )

    # x_gap_new: pre-existing improvement + additional intervention amount
    df_mid["x_gap_new"] = df_mid["x_gap_old"] + df_mid["delta_gap_applied"]
    df_up["x_gap_new"]  = df_up["x_gap_old"]  + df_up["delta_gap_applied"]

    # ---- Flow: compute ΔP ----
    df_mid["logit_old"] = (
        flow_intercept
        + flow_beta_gap       * df_mid["x_gap_old"]
        + flow_beta_weekly    * df_mid["weekly_early"]
        + flow_beta_basket    * df_mid["basket"]
        + flow_beta_gap_early * df_mid["gap_early"]
        + flow_beta_unique    * df_mid["unique"]
    )
    df_mid["p_old"] = sigmoid(df_mid["logit_old"])

    df_mid["logit_new"] = (
        flow_intercept
        + flow_beta_gap       * df_mid["x_gap_new"]
        + flow_beta_weekly    * df_mid["weekly_early"]
        + flow_beta_basket    * df_mid["basket"]
        + flow_beta_gap_early * df_mid["gap_early"]
        + flow_beta_unique    * df_mid["unique"]
    )
    df_mid["p_new"]   = sigmoid(df_mid["logit_new"])
    df_mid["delta_p"] = df_mid["p_new"] - df_mid["p_old"]

    # ---- Existing intensify（df_up）----
    df_up["delta_old"] = (
        int_intercept
        + int_beta_gap       * df_up["x_gap_old"]
        + int_beta_weekly    * df_up["weekly_early"]
        + int_beta_basket    * df_up["basket"]
        + int_beta_gap_early * df_up["gap_early"]
        + int_beta_unique    * df_up["unique"]
    )
    df_up["delta_new"] = (
        int_intercept
        + int_beta_gap       * df_up["x_gap_new"]
        + int_beta_weekly    * df_up["weekly_early"]
        + int_beta_basket    * df_up["basket"]
        + int_beta_gap_early * df_up["gap_early"]
        + int_beta_unique    * df_up["unique"]
    )
    df_up["delta_weekly_i"] = np.maximum(
        0, df_up["delta_new"] - df_up["delta_old"]
    )
    existing_uplift = df_up["delta_weekly_i"].sum()

    # ---- Case B core: marginal intensify for the Mid pool ----
    # Compute how much extra weekly the intervention brings each Mid user, if they were to upgrade
    df_mid["delta_old_i"] = (
        int_intercept
        + int_beta_gap       * df_mid["x_gap_old"]
        + int_beta_weekly    * df_mid["weekly_early"]
        + int_beta_basket    * df_mid["basket"]
        + int_beta_gap_early * df_mid["gap_early"]
        + int_beta_unique    * df_mid["unique"]
    )
    df_mid["delta_new_i"] = (
        int_intercept
        + int_beta_gap       * df_mid["x_gap_new"]
        + int_beta_weekly    * df_mid["weekly_early"]
        + int_beta_basket    * df_mid["basket"]
        + int_beta_gap_early * df_mid["gap_early"]
        + int_beta_unique    * df_mid["unique"]
    )
    df_mid["delta_weekly_i"] = np.maximum(
        0, df_mid["delta_new_i"] - df_mid["delta_old_i"]
    )
    # Meaning: if this Mid user upgraded
    # how much extra weekly growth the intervention would give them

    # ---- Case B formula ----
    # flow uplift = ΔP × (level jump + marginal intensify)
    # level jump       = avg_high - weekly_old
    # marginal intensify = delta_weekly_i
    df_mid["flow_uplift_i"] = np.maximum(
        0,
        df_mid["delta_p"] * (
            (avg_high - df_mid["weekly_old"])
            + df_mid["delta_weekly_i"]
        )
    )
    flow_uplift  = df_mid["flow_uplift_i"].sum()
    total_uplift = existing_uplift + flow_uplift

    results.append({
        "scenario"        : f"+{scenario_pp}pp",
        "existing_uplift" : round(existing_uplift, 2),
        "flow_uplift"     : round(flow_uplift, 2),
        "total_uplift"    : round(total_uplift, 2),
        "uplift_pct"      : round(total_uplift / baseline_high, 4),
        "new_up_users"    : round(df_mid["delta_p"].sum(), 2),
        "avg_delta_p"     : round(df_mid["delta_p"].mean(), 4),
        "avg_applied_pp"  : round(
            (df_mid["delta_gap_applied"] * 100).mean(), 2
        ),
        "affected_pct"    : round(
            (df_mid["delta_gap_applied"] > 0).mean(), 4
        ),
        "full_apply_pct"  : round(
            (df_mid["gap_headroom"] >= scenario).mean(), 4
        ),
        "avg_delta_weekly_i": round(
            df_mid["delta_weekly_i"].mean(), 4
        ),
    })

results_df = pd.DataFrame(results)

# ----------------------------------------
# 8. Output results
# ----------------------------------------
print("\n" + "="*70)
print("Case B: ge10 Integrated (Flow + Intensify) Multi-Scenario")
print("="*70)

print(f"\n{'Scenario':<10} {'Existing':>12} {'Flow':>12} "
      f"{'Total':>12} {'Uplift%':>8} {'New Up':>10}")
print("-"*68)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['existing_uplift']:>12,.2f} "
          f"{row['flow_uplift']:>12,.2f} "
          f"{row['total_uplift']:>12,.2f} "
          f"{row['uplift_pct']:>8.2%} "
          f"{row['new_up_users']:>10.2f}")

print("\n" + "="*70)
print("Case A vs. Case B Comparison (Flow Uplift Difference)")
print("="*70)
print(f"\n{'Scenario':<10} {'avg Δweekly_i':>15} {'Note'}")
print("-"*50)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['avg_delta_weekly_i']:>15.4f}  "
          f"← marginal intensify per user")

print("\n" + "="*70)
print("Headroom Details")
print("="*70)
print(f"\n{'Scenario':<10} {'Actual avgpp':>10} {'Full Apply%':>12} {'Affected%':>10}")
print("-"*45)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<10} "
          f"{row['avg_applied_pp']:>10.2f} "
          f"{row['full_apply_pct']:>12.2%} "
          f"{row['affected_pct']:>10.2%}")

print("\n" + "="*70)
print("Sanity Check")
print("="*70)
print(f"avg_high:       {avg_high:.4f}")
print(f"avg level jump: {(avg_high - df_mid['weekly_old']).mean():.4f}")
print(f"avg delta_p:    {df_mid['delta_p'].mean():.4f}")
print(f"avg p_old:      {df_mid['p_old'].mean():.4f}")

print("\n" + "="*70)
print("Copyable for Excel:")
print("="*70)
print("Scenario\tExisting Uplift\tFlow Uplift\tTotal Uplift\t"
      "Uplift %\tNew Up Users\tAvg Applied pp\tFull Apply %\tAffected %\tAvg Δweekly_i")
for _, row in results_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['existing_uplift']}\t"
          f"{row['flow_uplift']}\t"
          f"{row['total_uplift']}\t"
          f"{row['uplift_pct']:.2%}\t"
          f"{row['new_up_users']}\t"
          f"{row['avg_applied_pp']}\t"
          f"{row['full_apply_pct']:.2%}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['avg_delta_weekly_i']}")

print("\n✅ New tables created:")
print("  - results_df  (Case B multi-scenario summary)")

Mid 母池: 73,367
Mid→High: 14,217
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

Target ge10（P20 + floor）: 0.2857
avg_high: 13.3104
baseline_high: 189,233.54

======================================================================
Case B：ge10 Integrated（Flow + Intensify）多场景
======================================================================

场景             Existing         Flow        Total      提升%       新增Up
--------------------------------------------------------------------
+3pp           3,549.44     6,326.24     9,875.68    5.22%    1162.14
+5pp           5,853.75    11,232.93    17,086.68    9.03%    1959.35
+7pp           8,031.58    16,518.15    24,549.73   12.97%    2744.76
+10pp         11,210.47    25,505.51    36,715.98   19.40%    3949.88

======================================================================
Case A vs Case B 对比（Flow Uplift 差异）
======================================================================

场景           avg Δweekly_i 说明
--------------------------------------------------
+3pp                0.2625  ← marginal intensify per user
+5pp                0.4343  ← marginal intensify per user
+7pp                0.5970  ← marginal intensify per user
+10pp               0.8369  ← marginal intensify per user

======================================================================
Headroom 详情
======================================================================

场景            实际avgpp        完整施加%       被影响%
---------------------------------------------
+3pp             2.38       78.75%     79.96%
+5pp             3.94       73.94%     79.96%
+7pp             5.42       73.59%     79.96%
+10pp            7.60       71.41%     79.96%

======================================================================
Sanity Check
======================================================================
avg_high:       13.3104
avg level jump: 6.9980
avg delta_p:    0.0538
avg p_old:      0.1957

======================================================================
可复制到 Excel：
======================================================================
Scenario	Existing Uplift	Flow Uplift	Total Uplift	Uplift %	New Up Users	Avg Applied pp	Full Apply %	Affected %	Avg Δweekly_i
+3pp	3549.44	6326.24	9875.68	5.22%	1162.14	2.38	78.75%	79.96%	0.2625
+5pp	5853.75	11232.93	17086.68	9.03%	1959.35	3.94	73.94%	79.96%	0.4343
+7pp	8031.58	16518.15	24549.73	12.97%	2744.76	5.42	73.59%	79.96%	0.597
+10pp	11210.47	25505.51	36715.98	19.40%	3949.88	7.6	71.41%	79.96%	0.8369

✅ New tables created:
  - results_df  (Case B 多场景汇总)

In [130]:
# Every step was carefully defined while reorganizing the code
# Rebuild the basket-side model
# basket / unique item - intensify - modeling (updated version)
# ================================
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from scipy.stats import spearmanr

# ================================
# 1. Load data
# ================================
df = analysis_mid_user_master.copy()

# ================================
# 2. Sample filtering (keep only Mid → High)
# ================================
df_up = df[df["path_9"] == "Mid Up to High"].copy()
print(f"Sample size (Mid → High): {len(df_up):,}")

# Confirm the needed columns are all present
needed = [
    "delta_weekly", "delta_n_unique_products",
    "weekly_med_early", "basket_med_early",
    "pct_gap10_early"
]
print("\nColumn check:")
for col in needed:
    print(f"  {col}: {'✅' if col in df_up.columns else '❌'}")

# ================================
# 3. Define variables
# ================================

# Y: weekly growth
df_up["y"] = df_up["delta_weekly"]

# X: unique growth
df_up["x"] = df_up["delta_n_unique_products"]

# Control variables
# ⭐ Replace pct_gap30_early with pct_gap10_early
controls = [
    "weekly_med_early",   # user's initial consumption level
    "basket_med_early",   # user's initial basket
    "pct_gap10_early"     # ⭐ ge10 frequency control (stronger than ge30)
]

"""
📌 Why replace pct_gap30_early with pct_gap10_early?

weekly = basket × frequency

Controlling for ge10 is more accurate than controlling for ge30:
→ ge10 Spearman = -0.345 (stronger signal)
→ ge30 Spearman = -0.244 (weaker signal)
→ controls for the stronger frequency signal
  makes basket's net effect cleaner
"""

model_df = df_up[["y", "x"] + controls].dropna()
print(f"\nModeling sample size: {len(model_df):,}")

# ================================
# 4. Winsorize
# ================================
def winsorize(series, lower=0.01, upper=0.99):
    return series.clip(
        series.quantile(lower),
        series.quantile(upper)
    )

model_df = model_df.copy()
model_df["y"] = winsorize(model_df["y"])

# ================================
# 5. OLS regression (HC3 robust standard errors)
# ================================
formula = "y ~ x + " + " + ".join(controls)
model = smf.ols(formula=formula, data=model_df).fit(cov_type="HC3")

print("\n========== Regression Results (Basket Side) ==========")
print(model.summary())

# ================================
# 6. Core results
# ================================
beta_unique = model.params["x"]
ci_low, ci_high = model.conf_int().loc["x"]

print("\n========== Core Results ==========")
print(f"β_unique (Δunique coefficient): {beta_unique:.4f}")
print(f"95% confidence interval: [{ci_low:.4f}, {ci_high:.4f}]")
print(f"\n📌 Business interpretation:")
print(f"Every 1 additional unique item → weekly increases by {beta_unique:.3f} on average")

# ================================
# 7. Bucketed validation (monotonicity check)
# ================================
model_df["x_bucket"] = pd.qcut(
    model_df["x"], q=5, duplicates="drop"
)

bucket = (
    model_df
    .groupby("x_bucket", observed=True)
    .agg(
        users=("y", "count"),
        x_mean=("x", "mean"),
        y_mean=("y", "mean"),
        y_median=("y", "median")
    )
    .reset_index()
)

print("\n========== Bucketed Results (monotonicity check) ==========")
print(f"\n{'Bucket':<20} {'Users':>8} {'x_mean':>10} "
      f"{'y_mean':>10} {'y_median':>10}")
print("-"*65)
for _, row in bucket.iterrows():
    print(f"{str(row['x_bucket']):<20} {row['users']:>8,} "
          f"{row['x_mean']:>10.4f} {row['y_mean']:>10.4f} "
          f"{row['y_median']:>10.4f}")

# ================================
# 8. Monotonicity test (Spearman)
# ================================
corr, pval = spearmanr(bucket["x_mean"], bucket["y_mean"])

print(f"\n========== Monotonicity Test ==========")
print(f"Spearman: {corr:.4f}  p={pval:.4f}")

if corr > 0:
    print("✅ Monotonic increasing relationship holds")
else:
    print("⚠️ No monotonic increase shown, please check the data")

# ================================
# 9. Quadratic term check (nonlinearity)
# ================================
model_df["x2"] = model_df["x"] ** 2

formula_quad = "y ~ x + x2 + " + " + ".join(controls)
model_quad = smf.ols(
    formula=formula_quad, data=model_df
).fit(cov_type="HC3")

print("\n========== Quadratic Term Model (nonlinearity check) ==========")
print(model_quad.summary())

# ================================
# 10. Compare ge10 vs. ge30 control variables
# ================================
print("\n========== Control-Variable Sanity Check ==========")

checks = {
    "pct_gap10_early"  : ("< 0", "higher early ge10 → harder weekly growth"),
    "weekly_med_early" : ("< 0", "larger initial scale → less room for growth"),
    "basket_med_early" : ("> 0", "larger initial basket → higher weekly"),
}

for var, (expected, desc) in checks.items():
    if var in model.params:
        coef = model.params[var]
        ok = (expected == "< 0" and coef < 0) or \
             (expected == "> 0" and coef > 0)
        flag = "✅" if ok else "⚠️"
        print(f"  {var:<25} {coef:>8.4f} {flag} {desc}")

print("\n✅ New tables created:")
print("  - model       (Basket-side OLS model)")
print("  - model_quad  (quadratic term model)")
print("  - model_df    (modeling data)")
print("  - bucket      (bucketed results)")

样本量（Mid → High）：14,217

列检查：
  delta_weekly: ✅
  delta_n_unique_products: ✅
  weekly_med_early: ✅
  basket_med_early: ✅
  pct_gap10_early: ✅

建模样本量：14,217

========== 回归结果（Basket 侧） ==========
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.168
Model:                            OLS   Adj. R-squared:                  0.167
Method:                 Least Squares   F-statistic:                     206.2
Date:                Thu, 02 Jul 2026   Prob (F-statistic):          3.26e-172
Time:                        16:29:07   Log-Likelihood:                -41422.
No. Observations:               14217   AIC:                         8.285e+04
Df Residuals:                   14212   BIC:                         8.289e+04
Df Model:                           4
Covariance Type:                  HC3
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           11.4604      0.552     20.745      0.000      10.378      12.543
x                    0.2304      0.011     21.468      0.000       0.209       0.251
weekly_med_early    -0.8796      0.084    -10.509      0.000      -1.044      -0.716
basket_med_early     0.1407      0.019      7.396      0.000       0.103       0.178
pct_gap10_early     -2.0565      0.395     -5.213      0.000      -2.830      -1.283
==============================================================================
Omnibus:                     6065.780   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            31010.748
Skew:                           2.035   Prob(JB):                         0.00
Kurtosis:                       8.982   Cond. No.                         81.1
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

========== 核心结果 ==========
β_unique（Δunique 系数）: 0.2304
95% 置信区间: [0.2094, 0.2514]

📌 业务解释：
unique 每增加 1 个 → weekly 平均增加 0.230

========== 分桶结果（单调性检查） ==========

Bucket                  Users     x_mean     y_mean   y_median
-----------------------------------------------------------------
(-26.501, -1.0]         3,052    -3.4874     6.0008     5.0383
(-1.0, 1.0]             3,036     0.3933     5.7794     4.9528
(1.0, 3.0]              3,089     2.2983     6.4323     5.5152
(3.0, 5.5]              2,321     4.3968     7.1916     6.3000
(5.5, 40.0]             2,719     9.5031     9.2082     7.9227

========== 单调性检验 ==========
Spearman: 0.9000  p=0.0374
✅ 单调上升关系成立

========== 二次项模型（非线性检查） ==========
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.174
Model:                            OLS   Adj. R-squared:                  0.174
Method:                 Least Squares   F-statistic:                     157.2
Date:                Thu, 02 Jul 2026   Prob (F-statistic):          4.29e-163
Time:                        16:29:07   Log-Likelihood:                -41364.
No. Observations:               14217   AIC:                         8.274e+04
Df Residuals:                   14211   BIC:                         8.278e+04
Df Model:                           5
Covariance Type:                  HC3
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           11.5457      0.541     21.331      0.000      10.485      12.607
x                    0.1598      0.014     11.815      0.000       0.133       0.186
x2                   0.0079      0.001      5.437      0.000       0.005       0.011
weekly_med_early    -0.8631      0.083    -10.449      0.000      -1.025      -0.701
basket_med_early     0.1109      0.020      5.649      0.000       0.072       0.149
pct_gap10_early     -1.9205      0.391     -4.910      0.000      -2.687      -1.154
==============================================================================
Omnibus:                     5943.367   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            30021.937
Skew:                           1.991   Prob(JB):                         0.00
Kurtosis:                       8.901   Cond. No.                         422.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

========== 控制变量 Sanity Check ==========
  pct_gap10_early            -2.0565 ✅ 早期 ge10 越高 → weekly 增长越难
  weekly_med_early           -0.8796 ✅ 初始规模越大 → 增长空间越小
  basket_med_early            0.1407 ✅ 初始 basket 越大 → weekly 越高

✅ New tables created:
  - model       (Basket 侧 OLS 模型)
  - model_quad  (二次项模型)
  - model_df    (建模数据)
  - bucket      (分桶结果)

In [131]:
# Additional check: relationship between unique items and pct_gap10

# Check the correlation between unique and ge10
from scipy import stats
r, p = stats.pearsonr(
    model_df["x"],
    model_df["pct_gap10_early"]
)
print(f"unique vs. ge10_early correlation: r={r:.4f}")

unique vs ge10_early 相关性: r=-0.0942

In [132]:
# Apply the model

# basket / unique item - intensify - apply the model (multi-scenario version)
# =========================================
import pandas as pd
import numpy as np

# =========================================
# 1. Load data
# =========================================
df = analysis_mid_user_master.copy()

# =========================================
# 2. Keep only Mid → High users
# =========================================
df_up = df[df["path_9"] == "Mid Up to High"].copy()
print(f"Mid → High sample size: {len(df_up):,}")

# Confirm columns
needed = [
    "delta_n_unique_products", "weekly_med_early",
    "basket_med_early", "pct_gap10_early",
    "weekly_med_late"
]
for col in needed:
    print(f"  {col}: {'✅' if col in df_up.columns else '❌'}")

# =========================================
# 3. Model coefficients (current ge10-version OLS results)
# =========================================
beta_unique       =  0.2304
beta_weekly_early = -0.8796
beta_basket_early =  0.1407
beta_gap_early    = -2.0565  # coefficient for pct_gap10_early
intercept         = 11.4604

# =========================================
# 4. Define variables
# =========================================
df_up["x"]            = df_up["delta_n_unique_products"]
df_up["weekly_early"] = df_up["weekly_med_early"]
df_up["basket_early"] = df_up["basket_med_early"]
df_up["gap_early"]    = df_up["pct_gap10_early"]

# =========================================
# 5. Headroom（P90）
# =========================================
p90_unique = df_up["x"].quantile(0.9)
print(f"\nP90 Δunique: {p90_unique:.2f}")
print(f"\nΔunique distribution:")
print(df_up["x"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(2))

df_up["headroom"] = np.maximum(0, p90_unique - df_up["x"])

print(f"\nUsers with headroom: {(df_up['headroom'] > 0).sum():,}")
print(f"Average headroom: {df_up['headroom'].mean():.2f}")

# =========================================
# 6. Baseline prediction
# =========================================
df_up["delta_weekly_old_pred"] = (
    intercept
    + beta_unique       * df_up["x"]
    + beta_weekly_early * df_up["weekly_early"]
    + beta_basket_early * df_up["basket_early"]
    + beta_gap_early    * df_up["gap_early"]
)

# =========================================
# 7. Multi-scenario calculation (+1/+2/+3 items)
# =========================================
delta_targets = [1, 2, 3]
results = []

for delta_target in delta_targets:

    temp = df_up.copy()

    # Actually applied (capped at headroom)
    temp["delta_x_applied"] = np.minimum(
        delta_target,
        temp["headroom"]
    )

    # New-world prediction
    temp["x_new"] = temp["x"] + temp["delta_x_applied"]

    temp["delta_weekly_new_pred"] = (
        intercept
        + beta_unique       * temp["x_new"]
        + beta_weekly_early * temp["weekly_early"]
        + beta_basket_early * temp["basket_early"]
        + beta_gap_early    * temp["gap_early"]
    )

    # Uplift
    temp["uplift"] = (
        temp["delta_weekly_new_pred"] -
        temp["delta_weekly_old_pred"]
    )

    # Summary
    total_uplift    = temp["uplift"].sum()
    avg_uplift      = temp["uplift"].mean()
    total_baseline  = temp["weekly_med_late"].sum()
    uplift_pct      = total_uplift / total_baseline
    affected_users  = (temp["delta_x_applied"] > 0).sum()
    affected_pct    = affected_users / len(temp)
    avg_applied     = temp["delta_x_applied"].mean()
    full_apply_pct  = (temp["headroom"] >= delta_target).mean()
    clipped_pct     = (temp["headroom"] < delta_target).mean()

    results.append({
        "scenario"       : f"+{delta_target} item",
        "total_uplift"   : round(total_uplift, 2),
        "avg_uplift"     : round(avg_uplift, 4),
        "uplift_pct"     : round(uplift_pct, 4),
        "affected_users" : affected_users,
        "affected_pct"   : round(affected_pct, 4),
        "avg_applied"    : round(avg_applied, 2),
        "full_apply_pct" : round(full_apply_pct, 4),
        "clipped_pct"    : round(clipped_pct, 4),
        "theory_uplift"  : round(beta_unique * delta_target, 4),
    })

results_df = pd.DataFrame(results)

# =========================================
# 8. Output results
# =========================================
print("\n" + "="*70)
print("Basket-Side Multi-Scenario Uplift Analysis (+1/+2/+3 item)")
print("="*70)

print(f"\n{'Scenario':<12} {'Total Uplift':>10} {'Per-user Uplift':>12} "
      f"{'Uplift%':>8} {'Affected Users':>12} {'Share':>8} "
      f"{'Actual avg':>8}")
print("-"*75)

for _, row in results_df.iterrows():
    print(f"{row['scenario']:<12} "
          f"{row['total_uplift']:>10,.2f} "
          f"{row['avg_uplift']:>12.4f} "
          f"{row['uplift_pct']:>8.2%} "
          f"{row['affected_users']:>12,} "
          f"{row['affected_pct']:>8.2%} "
          f"{row['avg_applied']:>8.2f}")

# =========================================
# 9. Sanity Check
# =========================================
print("\n" + "="*70)
print("Sanity Check: Theoretical vs. Actual")
print("="*70)

print(f"\nβ_unique = {beta_unique}")
print(f"\n{'Scenario':<12} {'Theoretical Uplift':>12} {'Actual Per-user Uplift':>16} {'Diff':>10}")
print("-"*55)

for _, row in results_df.iterrows():
    diff = row["avg_uplift"] - row["theory_uplift"]
    print(f"{row['scenario']:<12} "
          f"{row['theory_uplift']:>12.4f} "
          f"{row['avg_uplift']:>16.4f} "
          f"{diff:>+10.4f}")

# =========================================
# 10. Headroom details
# =========================================
print("\n" + "="*70)
print("Headroom Details")
print("="*70)

print(f"\n{'Scenario':<12} {'Full Apply%':>12} {'Clipped%':>10} {'Actual avg':>10}")
print("-"*48)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<12} "
          f"{row['full_apply_pct']:>12.2%} "
          f"{row['clipped_pct']:>10.2%} "
          f"{row['avg_applied']:>10.2f}")

# =========================================
# 11. Copyable Excel table
# =========================================
print("\n" + "="*70)
print("Copyable for Excel:")
print("="*70)
print("Scenario\tTotal Uplift\tAvg Uplift\tUplift %\t"
      "Affected Users\tAffected %\tAvg Applied\t"
      "Full Apply %\tClipped %\tTheory Uplift")

for _, row in results_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['total_uplift']}\t"
          f"{row['avg_uplift']}\t"
          f"{row['uplift_pct']:.2%}\t"
          f"{row['affected_users']}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['avg_applied']}\t"
          f"{row['full_apply_pct']:.2%}\t"
          f"{row['clipped_pct']:.2%}\t"
          f"{row['theory_uplift']}")

print("\n✅ New tables created:")
print("  - results_df  (multi-scenario summary)")

Mid → High 样本量: 14,217
  delta_n_unique_products: ✅
  weekly_med_early: ✅
  basket_med_early: ✅
  pct_gap10_early: ✅
  weekly_med_late: ✅

P90 Δunique: 8.00

Δunique 分布：
count    14217.00
mean         2.37
std          4.85
min        -26.50
10%         -3.00
25%          0.00
50%          2.00
75%          5.00
90%          8.00
max         40.00
Name: x, dtype: float64

有 headroom 用户数: 12,605
平均 headroom: 6.03

======================================================================
Basket 侧多场景 Uplift 分析（+1/+2/+3 item）
======================================================================

场景              总Uplift     人均Uplift      提升%        受影响用户       占比    实际avg
---------------------------------------------------------------------------
+1 item        2,886.57       0.2030    1.53%       12,605   88.66%     0.88
+2 item        5,654.02       0.3977    2.99%       12,605   88.66%     1.73
+3 item        8,271.59       0.5818    4.37%       12,605   88.66%     2.53

======================================================================
Sanity Check：理论 vs 实际
======================================================================

β_unique = 0.2304

场景               理论uplift       实际人均uplift         差值
-------------------------------------------------------
+1 item            0.2304           0.2030    -0.0274
+2 item            0.4608           0.3977    -0.0631
+3 item            0.6912           0.5818    -0.1094

======================================================================
Headroom 详情
======================================================================

场景                  完整施加%       被截断%      实际avg
------------------------------------------------
+1 item            87.59%     12.41%       0.88
+2 item            83.76%     16.24%       1.73
+3 item            78.95%     21.05%       2.53

======================================================================
可复制到 Excel：
======================================================================
Scenario	Total Uplift	Avg Uplift	Uplift %	Affected Users	Affected %	Avg Applied	Full Apply %	Clipped %	Theory Uplift
+1 item	2886.57	0.203	1.53%	12605	88.66%	0.88	87.59%	12.41%	0.2304
+2 item	5654.02	0.3977	2.99%	12605	88.66%	1.73	83.76%	16.24%	0.4608
+3 item	8271.59	0.5818	4.37%	12605	88.66%	2.53	78.95%	21.05%	0.6912

✅ New tables created:
  - results_df  (多场景汇总)

In [133]:
# =========================================
# Basket-side Headroom core metrics (+1/+2/+3 items)
# =========================================

import pandas as pd
import numpy as np

# =========================================
# 1. Confirm data is ready
# =========================================
print(f"df_up sample size: {len(df_up):,}")
print(f"headroom exists: {'headroom' in df_up.columns}")
print(f"\nheadroom distribution:")
print(df_up["headroom"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(2))

# =========================================
# 2. Define scenarios
# =========================================
delta_targets = [1, 2, 3]
results = []

# =========================================
# 3. Loop through each scenario
# =========================================
for delta_target in delta_targets:

    temp = df_up.copy()

    # Actually applied Δunique (capped at headroom)
    temp["delta_x_applied"] = np.minimum(
        delta_target,
        temp["headroom"]
    )

    # Metric 1: average actually-applied Δunique
    avg_dx = temp["delta_x_applied"].mean()

    # Metric 2: share fully applied
    full_apply_pct = (temp["headroom"] >= delta_target).mean()

    # Metric 3: share capped
    clipped_pct = (temp["headroom"] < delta_target).mean()

    # Metric 4: share affected
    affected_pct = (temp["delta_x_applied"] > 0).mean()

    # Metric 5: share with no headroom
    no_headroom_pct = (temp["headroom"] == 0).mean()

    results.append({
        "scenario"       : f"+{delta_target} item",
        "avg_applied"    : round(avg_dx, 3),
        "full_apply_pct" : round(full_apply_pct, 4),
        "clipped_pct"    : round(clipped_pct, 4),
        "affected_pct"   : round(affected_pct, 4),
        "no_headroom_pct": round(no_headroom_pct, 4),
    })

result_df = pd.DataFrame(results)

# =========================================
# 4. Output results
# =========================================
print("\n" + "="*70)
print("Basket-Side Headroom Core Metrics")
print("="*70)

print(f"\n{'Scenario':<12} {'Actual avg':>10} {'Full Apply%':>10} "
      f"{'Clipped%':>10} {'Affected%':>10} {'No Headroom%':>10}")
print("-"*62)

for _, row in result_df.iterrows():
    print(f"{row['scenario']:<12} "
          f"{row['avg_applied']:>10.3f} "
          f"{row['full_apply_pct']:>10.2%} "
          f"{row['clipped_pct']:>10.2%} "
          f"{row['affected_pct']:>10.2%} "
          f"{row['no_headroom_pct']:>10.2%}")

# =========================================
# 5. Friendly print
# =========================================
print("\n" + "="*70)
print("Detailed Interpretation")
print("="*70)

for r in results:
    print(f"""
--- Scenario: {r['scenario']} ---
Average actual increase Δunique : {r['avg_applied']:.3f}
Full-apply share      : {r['full_apply_pct']:.2%} (sufficient headroom)
Clipped share          : {r['clipped_pct']:.2%} (insufficient headroom)
Affected share         : {r['affected_pct']:.2%} (any improvement)
No-headroom share      : {r['no_headroom_pct']:.2%} (already at P90 target)
""")

# =========================================
# 6. Copyable Excel table
# =========================================
print("="*70)
print("Copyable for Excel:")
print("="*70)
print("Scenario\tAvg Applied\tFull Apply %\t"
      "Clipped %\tAffected %\tNo Headroom %")

for _, row in result_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['avg_applied']}\t"
          f"{row['full_apply_pct']:.2%}\t"
          f"{row['clipped_pct']:.2%}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['no_headroom_pct']:.2%}")

print("\n✅ New tables created:")
print("  - result_df  (Basket headroom core metrics)")

df_up 样本量: 14,217
headroom 存在: True

headroom 分布：
count    14217.00
mean         6.03
std          3.97
min          0.00
10%          0.00
25%          3.00
50%          6.00
75%          8.00
90%         11.00
max         34.50
Name: headroom, dtype: float64

======================================================================
Basket 侧 Headroom 核心指标
======================================================================

场景                实际avg      完整施加%       被截断%       被影响%       无空间%
--------------------------------------------------------------
+1 item           0.881     87.59%     12.41%     88.66%     11.34%
+2 item           1.726     83.76%     16.24%     88.66%     11.34%
+3 item           2.525     78.95%     21.05%     88.66%     11.34%

======================================================================
详细解读
======================================================================

--- Scenario: +1 item ---
平均实际增加 Δunique  : 0.881
完整施加比例          : 87.59%（headroom 足够）
被截断比例            : 12.41%（headroom 不足）
被影响比例            : 88.66%（有任何改善）
无 headroom 比例      : 11.34%（已达 P90 target）


--- Scenario: +2 item ---
平均实际增加 Δunique  : 1.726
完整施加比例          : 83.76%（headroom 足够）
被截断比例            : 16.24%（headroom 不足）
被影响比例            : 88.66%（有任何改善）
无 headroom 比例      : 11.34%（已达 P90 target）


--- Scenario: +3 item ---
平均实际增加 Δunique  : 2.525
完整施加比例          : 78.95%（headroom 足够）
被截断比例            : 21.05%（headroom 不足）
被影响比例            : 88.66%（有任何改善）
无 headroom 比例      : 11.34%（已达 P90 target）

======================================================================
可复制到 Excel：
======================================================================
Scenario	Avg Applied	Full Apply %	Clipped %	Affected %	No Headroom %
+1 item	0.881	87.59%	12.41%	88.66%	11.34%
+2 item	1.726	83.76%	16.24%	88.66%	11.34%
+3 item	2.525	78.95%	21.05%	88.66%	11.34%

✅ New tables created:
  - result_df  (Basket headroom 核心指标)

In [134]:
# basket / unique item - flow - modeling (fixed version)
# =========================================
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from scipy.stats import spearmanr

# =========================================
# 1. Load data
# Change: using the v2 table (contains ge10 for all Mid users, all three groups complete)
# =========================================
df_mid = analysis_mid_user_master_v2.copy()

print(f"Mid pool sample size: {len(df_mid):,}")
print(df_mid["path_9"].value_counts())

# =========================================
# 2. Define the dependent variable Y
# =========================================
df_mid["y"] = np.where(
    df_mid["path_9"] == "Mid Up to High", 1, 0
)
print(f"\nUp share (actual): {df_mid['y'].mean():.4f}")

# =========================================
# 3. Define the independent variable X
# X = delta_n_unique_products (improvement amount)
# =========================================
df_mid["x"] = df_mid["delta_n_unique_products"]

# =========================================
# 4. Control variables
# Change: pct_gap30_early → pct_gap10_early_v2
# =========================================
controls = [
    "weekly_med_early",    # user's initial scale
    "basket_med_early",    # user's initial basket
    "pct_gap10_early_v2"   # ← changed: ge10 frequency control (stronger signal)
]

# =========================================
# 5. Build the modeling dataset
# =========================================
model_df = df_mid[["y", "x"] + controls].dropna()

print(f"\nModeling sample size: {len(model_df):,}")
print(f"Up share (post-modeling): {model_df['y'].mean():.4f}")
print(f"\npath_9 distribution (post-modeling):")
print(df_mid.loc[model_df.index, "path_9"].value_counts())

# =========================================
# 6. Winsorize
# =========================================
def winsorize(series, lower=0.01, upper=0.99):
    return series.clip(
        series.quantile(lower),
        series.quantile(upper)
    )

model_df = model_df.copy()
model_df["x"] = winsorize(model_df["x"])

print(f"\nX (delta_unique) distribution:")
print(model_df["x"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(4))

# =========================================
# 7. Logit model
# =========================================
formula = "y ~ x + " + " + ".join(controls)
model_basket_flow = smf.logit(
    formula=formula, data=model_df
).fit()

print("\n========== Logit Regression Results (Basket Flow) ==========")
print(model_basket_flow.summary())

# =========================================
# 8. Core results
# =========================================
beta_unique = model_basket_flow.params["x"]
ci_low, ci_high = model_basket_flow.conf_int().loc["x"]

print("\n========== Core Results ==========")
print(f"β_unique: {beta_unique:.4f}")
print(f"95% CI  : [{ci_low:.4f}, {ci_high:.4f}]")
print(f"Odds Ratio: {np.exp(beta_unique):.4f}")

if beta_unique > 0:
    print("✅ Δunique ↑ → upgrade probability ↑ (reasonable)")
else:
    print("⚠️ Direction is anomalous, please check")

# =========================================
# 9. Model validation
# =========================================
model_df["p_pred"] = model_basket_flow.predict(model_df)

print(f"\n========== Model Validation ==========")
print(f"Average predicted probability: {model_df['p_pred'].mean():.4f}")
print(f"Actual Up share: {model_df['y'].mean():.4f}")

# =========================================
# 10. Bucketed validation (monotonicity check)
# =========================================
model_df["x_bucket"] = pd.qcut(
    model_df["x"], q=5, duplicates="drop"
)

bucket = (
    model_df
    .groupby("x_bucket", observed=True)
    .agg(
        users=("y", "count"),
        x_mean=("x", "mean"),
        up_rate=("y", "mean"),
        pred_prob=("p_pred", "mean")
    )
    .reset_index()
)

print(f"\n========== Bucketed Results (monotonicity check) ==========")
print(f"\n{'Bucket':<20} {'Users':>8} {'x_mean':>10} "
      f"{'Up Rate':>10} {'Pred Prob':>12}")
print("-"*65)
for _, row in bucket.iterrows():
    print(f"{str(row['x_bucket']):<20} {row['users']:>8,} "
          f"{row['x_mean']:>10.4f} {row['up_rate']:>10.4f} "
          f"{row['pred_prob']:>12.4f}")

# =========================================
# 11. Monotonicity test
# =========================================
corr, pval = spearmanr(bucket["x_mean"], bucket["up_rate"])

print(f"\n========== Monotonicity Test ==========")
print(f"Spearman: {corr:.4f}  p={pval:.4f}")

if corr > 0:
    print("✅ Δunique → upgrade probability rises monotonically")
else:
    print("⚠️ No monotonic relationship shown")

# =========================================
# 12. Control-variable sanity check
# =========================================
print(f"\n========== Control-Variable Sanity Check ==========")

checks = {
    "pct_gap10_early_v2": ("< 0", "higher early ge10 → harder to upgrade"),
    "weekly_med_early"  : ("> 0", "higher initial activity → easier to upgrade"),
    "basket_med_early"  : ("> 0", "larger initial basket → easier to upgrade"),
}

for var, (expected, desc) in checks.items():
    if var in model_basket_flow.params:
        coef = model_basket_flow.params[var]
        ok = (expected == "< 0" and coef < 0) or \
             (expected == "> 0" and coef > 0)
        flag = "✅" if ok else "⚠️"
        print(f"  {var:<25} {coef:>8.4f} {flag} {desc}")

print("\n✅ New tables created:")
print("  - model_basket_flow  (Basket Flow Logit model)")
print("  - model_df           (modeling data)")
print("  - bucket             (bucketed results)")

Mid 母池样本量: 73,367
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

Up 比例（真实）: 0.1938

建模样本量: 73,367
Up 比例（建模后）: 0.1938

path_9 分布（建模后）:
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

X（delta_unique）分布：
count    73367.0000
mean         0.0079
std          4.0886
min        -12.0000
10%         -5.0000
25%         -2.0000
50%          0.0000
75%          2.0000
90%          5.0000
max         12.0000
Name: x, dtype: float64
Optimization terminated successfully.
         Current function value: 0.409240
         Iterations 7

========== Logit 回归结果（Basket Flow） ==========
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                73367
Model:                          Logit   Df Residuals:                    73362
Method:                           MLE   Df Model:                            4
Date:                Thu, 02 Jul 2026   Pseudo R-squ.:                  0.1676
Time:                        16:29:07   Log-Likelihood:                -30025.
converged:                       True   LL-Null:                       -36071.
Covariance Type:            nonrobust   LLR p-value:                     0.000
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             -2.8449      0.044    -65.077      0.000      -2.931      -2.759
x                      0.2363      0.003     82.811      0.000       0.231       0.242
weekly_med_early       0.1051      0.006     17.565      0.000       0.093       0.117
basket_med_early       0.1846      0.003     60.221      0.000       0.179       0.191
pct_gap10_early_v2    -2.2678      0.051    -44.078      0.000      -2.369      -2.167
======================================================================================

========== 核心结果 ==========
β_unique: 0.2363
95% CI  : [0.2307, 0.2419]
Odds Ratio: 1.2665
✅ Δunique ↑ → 升级概率 ↑（合理）

========== 模型校验 ==========
平均预测概率: 0.1938
实际 Up 比例: 0.1938

========== 分桶结果（单调性检查） ==========

Bucket                  Users     x_mean    Up Rate    Pred Prob
-----------------------------------------------------------------
(-12.001, -3.0]        15,035    -5.5954     0.0956       0.0921
(-3.0, -1.0]           14,734    -1.5642     0.1095       0.1264
(-1.0, 1.0]            19,490     0.3104     0.1558       0.1648
(1.0, 3.0]             12,031     2.2262     0.2568       0.2310
(3.0, 12.0]            12,077     6.2036     0.4173       0.4122

========== 单调性检验 ==========
Spearman: 1.0000  p=0.0000
✅ Δunique → 升级概率单调上升

========== 控制变量 Sanity Check ==========
  pct_gap10_early_v2         -2.2678 ✅ 早期 ge10 越高 → 越难升级
  weekly_med_early            0.1051 ✅ 初始活跃度越高 → 越容易升级
  basket_med_early            0.1846 ✅ 初始 basket 越大 → 越容易升级

✅ New tables created:
  - model_basket_flow  (Basket Flow Logit 模型)
  - model_df           (建模数据)
  - bucket             (分桶结果)

In [135]:
# basket / unique item - flow - apply the model (fixed version)
# =========================================
import pandas as pd
import numpy as np

# =========================================
# 1. Load data
# Change: using the v2 table (entire Mid pool, all three groups complete)
# =========================================
df_mid = analysis_mid_user_master_v2.copy()

print(f"Mid pool sample size: {len(df_mid):,}")
print(df_mid["path_9"].value_counts())

# =========================================
# 2. Define variables (fully consistent with the modeling)
# =========================================

# X: Δunique (improvement amount)
df_mid["x"] = df_mid["delta_n_unique_products"]

# Control variables (consistent with modeling)
df_mid["weekly_early"] = df_mid["weekly_med_early"]
df_mid["basket_early"] = df_mid["basket_med_early"]
df_mid["gap_early"]    = df_mid["pct_gap10_early_v2"]  # ← changed: ge10

# weekly_old: used to compute level jump
df_mid["weekly_old"]   = df_mid["weekly_med_late"]

# =========================================
# 3. Model coefficients (changed: new parameters)
# =========================================
basket_flow_intercept      = -2.8449
basket_flow_beta_unique    =  0.2363
basket_flow_beta_weekly    =  0.1051
basket_flow_beta_basket    =  0.1846
basket_flow_beta_gap_early = -2.2678

# =========================================
# 4. sigmoid function
# =========================================
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# =========================================
# 5. Headroom (Mid-pool P90)
# Using the full Mid pool's P90 (since the model is applied to the entire Mid pool)
# =========================================
p90_unique = df_mid["x"].quantile(0.9)
print(f"\nP90 Δunique (Mid pool): {p90_unique:.2f}")

df_mid["headroom"] = np.maximum(0, p90_unique - df_mid["x"])

print(f"Users with headroom: {(df_mid['headroom'] > 0).sum():,}")
print(f"Average headroom: {df_mid['headroom'].mean():.2f}")

# =========================================
# 6. avg_high and baseline
# =========================================
df_up_ref = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

avg_high      = df_up_ref["weekly_med_late"].mean()
baseline_high = df_up_ref["weekly_med_late"].sum()

print(f"\navg_high: {avg_high:.4f}")
print(f"baseline_high: {baseline_high:,.2f}")

# =========================================
# 7. Multi-scenario calculation (+1/+2/+3 items)
# =========================================
delta_targets = [1, 2, 3]
results = []

for delta_target in delta_targets:

    temp = df_mid.copy()

    # Actually applied (capped by headroom)
    temp["delta_x_applied"] = np.minimum(
        delta_target, temp["headroom"]
    )

    # x_new = pre-existing improvement + intervention amount
    temp["x_new"] = temp["x"] + temp["delta_x_applied"]

    # ---- Compute P_old ----
    temp["logit_old"] = (
        basket_flow_intercept
        + basket_flow_beta_unique    * temp["x"]
        + basket_flow_beta_weekly    * temp["weekly_early"]
        + basket_flow_beta_basket    * temp["basket_early"]
        + basket_flow_beta_gap_early * temp["gap_early"]
    )
    temp["p_old"] = sigmoid(temp["logit_old"])

    # ---- Compute P_new ----
    temp["logit_new"] = (
        basket_flow_intercept
        + basket_flow_beta_unique    * temp["x_new"]   # ← only this term changed
        + basket_flow_beta_weekly    * temp["weekly_early"]
        + basket_flow_beta_basket    * temp["basket_early"]
        + basket_flow_beta_gap_early * temp["gap_early"]
    )
    temp["p_new"] = sigmoid(temp["logit_new"])

    # ---- ΔP ----
    temp["delta_p"] = temp["p_new"] - temp["p_old"]

    # ---- Case A：Flow uplift（level jump only）----
    temp["flow_uplift"] = np.maximum(
        0,
        temp["delta_p"] * (avg_high - temp["weekly_old"])
    )

    # Summary
    flow_uplift     = temp["flow_uplift"].sum()
    new_up_users    = temp["delta_p"].sum()
    avg_delta_p     = temp["delta_p"].mean()
    affected_users  = (temp["delta_x_applied"] > 0).sum()
    affected_pct    = affected_users / len(temp)
    avg_applied     = temp["delta_x_applied"].mean()
    full_apply_pct  = (temp["headroom"] >= delta_target).mean()
    clipped_pct     = (temp["headroom"] < delta_target).mean()
    uplift_pct      = flow_uplift / baseline_high
    actual_up       = (temp["path_9"] == "Mid Up to High").sum()

    results.append({
        "scenario"       : f"+{delta_target} item",
        "flow_uplift"    : round(flow_uplift, 2),
        "new_up_users"   : round(new_up_users, 2),
        "uplift_pct_base": round(new_up_users / actual_up, 4),
        "uplift_pct"     : round(uplift_pct, 4),
        "avg_delta_p"    : round(avg_delta_p, 4),
        "affected_users" : affected_users,
        "affected_pct"   : round(affected_pct, 4),
        "avg_applied"    : round(avg_applied, 2),
        "full_apply_pct" : round(full_apply_pct, 4),
        "clipped_pct"    : round(clipped_pct, 4),
    })

results_df = pd.DataFrame(results)

# =========================================
# 8. Output results
# =========================================
print("\n" + "="*70)
print("Basket Flow Multi-Scenario Analysis (+1/+2/+3 item)")
print("="*70)

print(f"\n{'Scenario':<12} {'Flow Uplift':>12} {'New Up':>10} "
      f"{'% of Base Up':>12} {'Uplift%':>8} {'avg ΔP':>10}")
print("-"*68)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<12} "
          f"{row['flow_uplift']:>12,.2f} "
          f"{row['new_up_users']:>10.2f} "
          f"{row['uplift_pct_base']:>12.2%} "
          f"{row['uplift_pct']:>8.2%} "
          f"{row['avg_delta_p']:>10.4f}")

print("\n" + "="*70)
print("Headroom Details")
print("="*70)
print(f"\n{'Scenario':<12} {'Actual avg':>10} {'Full Apply%':>12} "
      f"{'Clipped%':>10} {'Affected%':>10}")
print("-"*55)
for _, row in results_df.iterrows():
    print(f"{row['scenario']:<12} "
          f"{row['avg_applied']:>10.2f} "
          f"{row['full_apply_pct']:>12.2%} "
          f"{row['clipped_pct']:>10.2%} "
          f"{row['affected_pct']:>10.2%}")

print("\n" + "="*70)
print("Sanity Check")
print("="*70)
print(f"avg_high:    {avg_high:.4f}")
print(f"avg level jump: {(avg_high - df_mid['weekly_old']).mean():.4f}")
print(f"avg p_old:   {sigmoid(basket_flow_intercept + basket_flow_beta_unique * df_mid['x'].mean() + basket_flow_beta_weekly * df_mid['weekly_early'].mean() + basket_flow_beta_basket * df_mid['basket_early'].mean() + basket_flow_beta_gap_early * df_mid['gap_early'].mean()):.4f}")

print("\n" + "="*70)
print("Copyable for Excel:")
print("="*70)
print("Scenario\tFlow Uplift\tNew Up Users\tUplift vs Base%\t"
      "Uplift %\tAvg ΔP\tAvg Applied\tFull Apply %\tClipped %\tAffected %")
for _, row in results_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['flow_uplift']}\t"
          f"{row['new_up_users']}\t"
          f"{row['uplift_pct_base']:.2%}\t"
          f"{row['uplift_pct']:.2%}\t"
          f"{row['avg_delta_p']}\t"
          f"{row['avg_applied']}\t"
          f"{row['full_apply_pct']:.2%}\t"
          f"{row['clipped_pct']:.2%}\t"
          f"{row['affected_pct']:.2%}")

print("\n✅ New tables created:")
print("  - results_df  (Basket Flow multi-scenario summary)")

Mid 母池样本量: 73,367
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

P90 Δunique（Mid 母池）: 5.00
有 headroom 用户数: 65,651
平均 headroom: 5.29

avg_high: 13.3104
baseline_high: 189,233.54

======================================================================
Basket Flow 多场景分析（+1/+2/+3 item）
======================================================================

场景            Flow Uplift       新增Up    占Base Up%      提升%     avg ΔP
--------------------------------------------------------------------
+1 item         13,173.77    1941.06       13.65%    6.96%     0.0265
+2 item         27,366.77    3968.50       27.91%   14.46%     0.0541
+3 item         42,091.97    6000.90       42.21%   22.24%     0.0818

======================================================================
Headroom 详情
======================================================================

场景                实际avg        完整施加%       被截断%       被影响%
-------------------------------------------------------
+1 item            0.89       88.27%     11.73%     89.48%
+2 item            1.73       83.54%     16.46%     89.48%
+3 item            2.51       76.76%     23.24%     89.48%

======================================================================
Sanity Check
======================================================================
avg_high:    13.3104
avg level jump: 6.9980
avg p_old:   0.1493

======================================================================
可复制到 Excel：
======================================================================
Scenario	Flow Uplift	New Up Users	Uplift vs Base%	Uplift %	Avg ΔP	Avg Applied	Full Apply %	Clipped %	Affected %
+1 item	13173.77	1941.06	13.65%	6.96%	0.0265	0.89	88.27%	11.73%	89.48%
+2 item	27366.77	3968.5	27.91%	14.46%	0.0541	1.73	83.54%	16.46%	89.48%
+3 item	42091.97	6000.9	42.21%	22.24%	0.0818	2.51	76.76%	23.24%	89.48%

✅ New tables created:
  - results_df  (Basket Flow 多场景汇总)

In [136]:
print(temp.groupby("path_9")[["x", "p_old", "delta_p"]].mean().round(4))

                      x   p_old  delta_p
path_9
Mid Down to Low -2.2264  0.0834   0.0611
Mid Stay         0.0320  0.1866   0.0876
Mid Up to High   2.3700  0.3390   0.0863

In [137]:
# View each group's contribution to flow uplift
print(temp.groupby("path_9")["flow_uplift"].sum().round(2))

path_9
Mid Down to Low    10427.03
Mid Stay           29371.66
Mid Up to High      2293.28
Name: flow_uplift, dtype: float64

In [138]:
# =========================================
# Basket Flow Headroom analysis (fixed version)
# =========================================
import pandas as pd
import numpy as np

# =========================================
# 1. Load data (change: using the v2 table)
# =========================================
df_mid = analysis_mid_user_master_v2.copy()

print(f"Mid pool sample size: {len(df_mid):,}")
print(df_mid["path_9"].value_counts())

# =========================================
# 2. Define core variables
# =========================================
df_mid["x"] = df_mid["delta_n_unique_products"]

# =========================================
# 3. Headroom (Mid-pool P90)
# =========================================
p90_unique = df_mid["x"].quantile(0.9)
print(f"\nP90 Δunique (Mid pool): {p90_unique:.2f}")

df_mid["headroom"] = np.maximum(0, p90_unique - df_mid["x"])

print(f"Users with headroom: {(df_mid['headroom'] > 0).sum():,}")
print(f"Average headroom: {df_mid['headroom'].mean():.2f}")

# =========================================
# 4. Multi-scenario calculation
# =========================================
scenarios = [1, 2, 3]
results = []

for delta_target in scenarios:

    delta_x_applied = np.minimum(delta_target, df_mid["headroom"])

    avg_dx         = delta_x_applied.mean()
    full_apply_pct = (df_mid["headroom"] >= delta_target).mean()
    clipped_pct    = (df_mid["headroom"] < delta_target).mean()
    affected_pct   = (delta_x_applied > 0).mean()  # ← changed
    no_headroom    = (df_mid["headroom"] == 0).mean()

    results.append({
        "scenario"       : f"+{delta_target} item",
        "avg_applied"    : round(avg_dx, 3),
        "full_apply_pct" : round(full_apply_pct, 4),
        "clipped_pct"    : round(clipped_pct, 4),
        "affected_pct"   : round(affected_pct, 4),
        "no_headroom_pct": round(no_headroom, 4),
    })

result_df = pd.DataFrame(results)

# =========================================
# 5. Output results
# =========================================
print("\n" + "="*70)
print("Basket Flow Headroom Core Metrics")
print("="*70)

print(f"\n{'Scenario':<12} {'Actual avg':>10} {'Full Apply%':>10} "
      f"{'Clipped%':>10} {'Affected%':>10} {'No Headroom%':>10}")
print("-"*62)
for _, row in result_df.iterrows():
    print(f"{row['scenario']:<12} "
          f"{row['avg_applied']:>10.3f} "
          f"{row['full_apply_pct']:>10.2%} "
          f"{row['clipped_pct']:>10.2%} "
          f"{row['affected_pct']:>10.2%} "
          f"{row['no_headroom_pct']:>10.2%}")

# =========================================
# 6. Friendly print
# =========================================
print("\n" + "="*70)
print("Detailed Interpretation")
print("="*70)
for r in results:
    print(f"""
--- Scenario: {r['scenario']} ---
Average actual increase Δunique : {r['avg_applied']:.3f}
Full-apply share      : {r['full_apply_pct']:.2%} (sufficient headroom)
Clipped share          : {r['clipped_pct']:.2%} (insufficient headroom)
Affected share         : {r['affected_pct']:.2%} (any improvement)
No-headroom share      : {r['no_headroom_pct']:.2%} (already at P90 target)
""")

# =========================================
# 7. Copyable Excel table
# =========================================
print("="*70)
print("Copyable for Excel:")
print("="*70)
print("Scenario\tAvg Applied\tFull Apply %\t"
      "Clipped %\tAffected %\tNo Headroom %")
for _, row in result_df.iterrows():
    print(f"{row['scenario']}\t"
          f"{row['avg_applied']}\t"
          f"{row['full_apply_pct']:.2%}\t"
          f"{row['clipped_pct']:.2%}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['no_headroom_pct']:.2%}")

print("\n✅ New tables created:")
print("  - result_df  (Basket Flow headroom core metrics)")

Mid 母池样本量: 73,367
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

P90 Δunique（Mid 母池）: 5.00
有 headroom 用户数: 65,651
平均 headroom: 5.29

======================================================================
Basket Flow Headroom 核心指标
======================================================================

场景                实际avg      完整施加%       被截断%       被影响%       无空间%
--------------------------------------------------------------
+1 item           0.889     88.27%     11.73%     89.48%     10.52%
+2 item           1.733     83.54%     16.46%     89.48%     10.52%
+3 item           2.514     76.76%     23.24%     89.48%     10.52%

======================================================================
详细解读
======================================================================

--- Scenario: +1 item ---
平均实际增加 Δunique  : 0.889
完整施加比例          : 88.27%（headroom 足够）
被截断比例            : 11.73%（headroom 不足）
被影响比例            : 89.48%（有任何改善）
无 headroom 比例      : 10.52%（已达 P90 target）


--- Scenario: +2 item ---
平均实际增加 Δunique  : 1.733
完整施加比例          : 83.54%（headroom 足够）
被截断比例            : 16.46%（headroom 不足）
被影响比例            : 89.48%（有任何改善）
无 headroom 比例      : 10.52%（已达 P90 target）


--- Scenario: +3 item ---
平均实际增加 Δunique  : 2.514
完整施加比例          : 76.76%（headroom 足够）
被截断比例            : 23.24%（headroom 不足）
被影响比例            : 89.48%（有任何改善）
无 headroom 比例      : 10.52%（已达 P90 target）

======================================================================
可复制到 Excel：
======================================================================
Scenario	Avg Applied	Full Apply %	Clipped %	Affected %	No Headroom %
+1 item	0.889	88.27%	11.73%	89.48%	10.52%
+2 item	1.733	83.54%	16.46%	89.48%	10.52%
+3 item	2.514	76.76%	23.24%	89.48%	10.52%

✅ New tables created:
  - result_df  (Basket Flow headroom 核心指标)

In [139]:
# integrated flow and intensify - case a
# ============================================================
# Basket Integrated Flow + Intensify（Case A + Case B）
# Fix: new parameters, v2 table, ge10 control variable, multi-scenario
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# 1. Load data
# ----------------------------------------
df_mid = analysis_mid_user_master_v2.copy()
df_up  = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"Mid pool: {len(df_mid):,}")
print(f"Mid→High: {len(df_up):,}")
print(df_mid["path_9"].value_counts())

# ----------------------------------------
# 2. Model parameters (new version)
# ----------------------------------------

# Flow model (Logit)
flow_intercept      = -2.8449
flow_beta_unique    =  0.2363
flow_beta_weekly    =  0.1051
flow_beta_basket    =  0.1846
flow_beta_gap_early = -2.2678

# Intensify model (OLS)
int_intercept      = 11.4604
int_beta_unique    =  0.2304
int_beta_weekly    = -0.8796
int_beta_basket    =  0.1407
int_beta_gap_early = -2.0565

# ----------------------------------------
# 3. Define variables
# ----------------------------------------

# Mid pool
df_mid["x"]            = df_mid["delta_n_unique_products"]
df_mid["weekly_old"]   = df_mid["weekly_med_late"]
df_mid["weekly_early"] = df_mid["weekly_med_early"]
df_mid["basket"]       = df_mid["basket_med_early"]
df_mid["gap_early"]    = df_mid["pct_gap10_early_v2"]  # ← ge10

# Mid→High
df_up["x"]            = df_up["delta_n_unique_products"]
df_up["weekly_early"] = df_up["weekly_med_early"]
df_up["basket"]       = df_up["basket_med_early"]
df_up["gap_early"]    = df_up["pct_gap10_early"]       # ← ge10

# ----------------------------------------
# 4. Headroom (Mid-pool P90)
# ----------------------------------------
p90_unique = df_mid["x"].quantile(0.9)
print(f"\nP90 Δunique (Mid pool): {p90_unique:.2f}")

df_mid["headroom"] = np.maximum(0, p90_unique - df_mid["x"])
df_up["headroom"]  = np.maximum(0, p90_unique - df_up["x"])

print(f"Users with headroom (Mid pool): {(df_mid['headroom'] > 0).sum():,}")

# ----------------------------------------
# 5. sigmoid function
# ----------------------------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# ----------------------------------------
# 6. avg_high and baseline
# ----------------------------------------
avg_high      = df_up["weekly_med_late"].mean()
baseline_high = df_up["weekly_med_late"].sum()

print(f"avg_high: {avg_high:.4f}")
print(f"baseline_high: {baseline_high:,.2f}")

# ----------------------------------------
# 7. Multi-scenario calculation (+1/+2/+3 items)
# ----------------------------------------
delta_targets = [1, 2, 3]
results_a = []
results_b = []

for delta_target in delta_targets:

    # Actually applied (capped by headroom)
    df_mid["dx_applied"] = np.minimum(
        delta_target, df_mid["headroom"]
    )
    df_up["dx_applied"] = np.minimum(
        delta_target, df_up["headroom"]
    )

    # x_new = pre-existing improvement + intervention amount
    df_mid["x_new"] = df_mid["x"] + df_mid["dx_applied"]
    df_up["x_new"]  = df_up["x"]  + df_up["dx_applied"]

    # ---- Flow: compute ΔP ----
    df_mid["logit_old"] = (
        flow_intercept
        + flow_beta_unique    * df_mid["x"]
        + flow_beta_weekly    * df_mid["weekly_early"]
        + flow_beta_basket    * df_mid["basket"]
        + flow_beta_gap_early * df_mid["gap_early"]
    )
    df_mid["p_old"] = sigmoid(df_mid["logit_old"])

    df_mid["logit_new"] = (
        flow_intercept
        + flow_beta_unique    * df_mid["x_new"]   # ← only this term changed
        + flow_beta_weekly    * df_mid["weekly_early"]
        + flow_beta_basket    * df_mid["basket"]
        + flow_beta_gap_early * df_mid["gap_early"]
    )
    df_mid["p_new"]   = sigmoid(df_mid["logit_new"])
    df_mid["delta_p"] = df_mid["p_new"] - df_mid["p_old"]

    # ---- Intensify：existing uplift ----
    df_up["delta_old"] = (
        int_intercept
        + int_beta_unique    * df_up["x"]
        + int_beta_weekly    * df_up["weekly_early"]
        + int_beta_basket    * df_up["basket"]
        + int_beta_gap_early * df_up["gap_early"]
    )
    df_up["delta_new"] = (
        int_intercept
        + int_beta_unique    * df_up["x_new"]     # ← only this term changed
        + int_beta_weekly    * df_up["weekly_early"]
        + int_beta_basket    * df_up["basket"]
        + int_beta_gap_early * df_up["gap_early"]
    )
    df_up["delta_weekly_i"] = np.maximum(
        0, df_up["delta_new"] - df_up["delta_old"]
    )
    existing_uplift = df_up["delta_weekly_i"].sum()

    # ---- Case A：Flow uplift（level jump only）----
    df_mid["flow_uplift_a"] = np.maximum(
        0,
        df_mid["delta_p"] * (avg_high - df_mid["weekly_old"])
    )
    flow_uplift_a  = df_mid["flow_uplift_a"].sum()
    total_uplift_a = existing_uplift + flow_uplift_a

    # ---- Case B：Flow uplift（level jump + marginal intensify）----
    df_mid["delta_old_i"] = (
        int_intercept
        + int_beta_unique    * df_mid["x"]
        + int_beta_weekly    * df_mid["weekly_early"]
        + int_beta_basket    * df_mid["basket"]
        + int_beta_gap_early * df_mid["gap_early"]
    )
    df_mid["delta_new_i"] = (
        int_intercept
        + int_beta_unique    * df_mid["x_new"]
        + int_beta_weekly    * df_mid["weekly_early"]
        + int_beta_basket    * df_mid["basket"]
        + int_beta_gap_early * df_mid["gap_early"]
    )
    df_mid["delta_weekly_i"] = np.maximum(
        0, df_mid["delta_new_i"] - df_mid["delta_old_i"]
    )

    df_mid["flow_uplift_b"] = np.maximum(
        0,
        df_mid["delta_p"] * (
            (avg_high - df_mid["weekly_old"])
            + df_mid["delta_weekly_i"]
        )
    )
    flow_uplift_b  = df_mid["flow_uplift_b"].sum()
    total_uplift_b = existing_uplift + flow_uplift_b

    # Shared metrics
    new_up_users   = round(df_mid["delta_p"].sum(), 2)
    avg_delta_p    = round(df_mid["delta_p"].mean(), 4)
    avg_applied    = round(df_mid["dx_applied"].mean(), 2)
    affected_pct   = round((df_mid["dx_applied"] > 0).mean(), 4)
    full_apply_pct = round((df_mid["headroom"] >= delta_target).mean(), 4)

    results_a.append({
        "scenario"        : f"+{delta_target} item",
        "existing_uplift" : round(existing_uplift, 2),
        "flow_uplift"     : round(flow_uplift_a, 2),
        "total_uplift"    : round(total_uplift_a, 2),
        "uplift_pct"      : round(total_uplift_a / baseline_high, 4),
        "new_up_users"    : new_up_users,
        "avg_delta_p"     : avg_delta_p,
        "avg_applied"     : avg_applied,
        "affected_pct"    : affected_pct,
        "full_apply_pct"  : full_apply_pct,
    })

    results_b.append({
        "scenario"        : f"+{delta_target} item",
        "existing_uplift" : round(existing_uplift, 2),
        "flow_uplift"     : round(flow_uplift_b, 2),
        "total_uplift"    : round(total_uplift_b, 2),
        "uplift_pct"      : round(total_uplift_b / baseline_high, 4),
        "new_up_users"    : new_up_users,
        "avg_delta_p"     : avg_delta_p,
        "avg_delta_weekly_i": round(df_mid["delta_weekly_i"].mean(), 4),
        "avg_applied"     : avg_applied,
        "affected_pct"    : affected_pct,
        "full_apply_pct"  : full_apply_pct,
    })

results_a_df = pd.DataFrame(results_a)
results_b_df = pd.DataFrame(results_b)

# ----------------------------------------
# 8. Output results
# ----------------------------------------
print("\n" + "="*70)
print("Case A: Basket Integrated (Flow + Intensify) Multi-Scenario")
print("="*70)
print(f"\n{'Scenario':<12} {'Existing':>12} {'Flow':>12} "
      f"{'Total':>12} {'Uplift%':>8} {'New Up':>10}")
print("-"*68)
for _, row in results_a_df.iterrows():
    print(f"{row['scenario']:<12} "
          f"{row['existing_uplift']:>12,.2f} "
          f"{row['flow_uplift']:>12,.2f} "
          f"{row['total_uplift']:>12,.2f} "
          f"{row['uplift_pct']:>8.2%} "
          f"{row['new_up_users']:>10.2f}")

print("\n" + "="*70)
print("Case B: Basket Integrated (Flow + Intensify) Multi-Scenario")
print("="*70)
print(f"\n{'Scenario':<12} {'Existing':>12} {'Flow':>12} "
      f"{'Total':>12} {'Uplift%':>8} {'New Up':>10}")
print("-"*68)
for _, row in results_b_df.iterrows():
    print(f"{row['scenario']:<12} "
          f"{row['existing_uplift']:>12,.2f} "
          f"{row['flow_uplift']:>12,.2f} "
          f"{row['total_uplift']:>12,.2f} "
          f"{row['uplift_pct']:>8.2%} "
          f"{row['new_up_users']:>10.2f}")

print("\n" + "="*70)
print("Headroom Details")
print("="*70)
print(f"\n{'Scenario':<12} {'Actual avg':>10} {'Full Apply%':>12} {'Affected%':>10}")
print("-"*45)
for _, row in results_a_df.iterrows():
    print(f"{row['scenario']:<12} "
          f"{row['avg_applied']:>10.2f} "
          f"{row['full_apply_pct']:>12.2%} "
          f"{row['affected_pct']:>10.2%}")

print("\n" + "="*70)
print("Sanity Check")
print("="*70)
print(f"avg_high:       {avg_high:.4f}")
print(f"avg level jump: {(avg_high - df_mid['weekly_old']).mean():.4f}")
print(f"avg p_old:      {df_mid['p_old'].mean():.4f}")

print("\n" + "="*70)
print("Copyable for Excel (Case A):")
print("="*70)
print("Scenario\tExisting\tFlow\tTotal\tUplift %\tNew Up\tAvg Applied\tFull Apply %\tAffected %")
for _, row in results_a_df.iterrows():
    print(f"{row['scenario']}\t{row['existing_uplift']}\t"
          f"{row['flow_uplift']}\t{row['total_uplift']}\t"
          f"{row['uplift_pct']:.2%}\t{row['new_up_users']}\t"
          f"{row['avg_applied']}\t{row['full_apply_pct']:.2%}\t"
          f"{row['affected_pct']:.2%}")

print("\nCopyable for Excel (Case B):")
print("Scenario\tExisting\tFlow\tTotal\tUplift %\tNew Up\tAvg Δweekly_i\tAvg Applied\tFull Apply %\tAffected %")
for _, row in results_b_df.iterrows():
    print(f"{row['scenario']}\t{row['existing_uplift']}\t"
          f"{row['flow_uplift']}\t{row['total_uplift']}\t"
          f"{row['uplift_pct']:.2%}\t{row['new_up_users']}\t"
          f"{row['avg_delta_weekly_i']}\t{row['avg_applied']}\t"
          f"{row['full_apply_pct']:.2%}\t{row['affected_pct']:.2%}")

print("\n✅ New tables created:")
print("  - results_a_df  (Case A multi-scenario summary)")
print("  - results_b_df  (Case B multi-scenario summary)")

Mid 母池: 73,367
Mid→High: 14,217
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

P90 Δunique（Mid 母池）: 5.00
有 headroom 用户数（Mid 母池）: 65,651
avg_high: 13.3104
baseline_high: 189,233.54

======================================================================
Case A：Basket Integrated（Flow + Intensify）多场景
======================================================================

场景               Existing         Flow        Total      提升%       新增Up
--------------------------------------------------------------------
+1 item          2,418.05    13,173.77    15,591.82    8.24%    1941.06
+2 item          4,582.89    27,366.77    31,949.66   16.88%    3968.50
+3 item          6,426.20    42,091.97    48,518.17   25.64%    6000.90

======================================================================
Case B：Basket Integrated（Flow + Intensify）多场景
======================================================================

场景               Existing         Flow        Total      提升%       新增Up
--------------------------------------------------------------------
+1 item          2,418.05    13,587.88    16,005.92    8.46%    1941.06
+2 item          4,582.89    29,043.95    33,626.84   17.77%    3968.50
+3 item          6,426.20    45,841.51    52,267.71   27.62%    6000.90

======================================================================
Headroom 详情
======================================================================

场景                实际avg        完整施加%       被影响%
---------------------------------------------
+1 item            0.89       88.27%     89.48%
+2 item            1.73       83.54%     89.48%
+3 item            2.51       76.76%     89.48%

======================================================================
Sanity Check
======================================================================
avg_high:       13.3104
avg level jump: 6.9980
avg p_old:      0.1945

======================================================================
可复制到 Excel（Case A）：
======================================================================
Scenario	Existing	Flow	Total	Uplift %	New Up	Avg Applied	Full Apply %	Affected %
+1 item	2418.05	13173.77	15591.82	8.24%	1941.06	0.89	88.27%	89.48%
+2 item	4582.89	27366.77	31949.66	16.88%	3968.5	1.73	83.54%	89.48%
+3 item	6426.2	42091.97	48518.17	25.64%	6000.9	2.51	76.76%	89.48%

可复制到 Excel（Case B）：
Scenario	Existing	Flow	Total	Uplift %	New Up	Avg Δweekly_i	Avg Applied	Full Apply %	Affected %
+1 item	2418.05	13587.88	16005.92	8.46%	1941.06	0.2048	0.89	88.27%	89.48%
+2 item	4582.89	29043.95	33626.84	17.77%	3968.5	0.3994	1.73	83.54%	89.48%
+3 item	6426.2	45841.51	52267.71	27.62%	6000.9	0.5793	2.51	76.76%	89.48%

✅ New tables created:
  - results_a_df  (Case A 多场景汇总)
  - results_b_df  (Case B 多场景汇总)

In [140]:
# Begin jointly modeling unique item and pct_gap10 improvement
# intensify model
# ============================================================
# Joint Intensify model (Unique + ge10 Gap), fixed version
# ============================================================

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from scipy.stats import spearmanr

# ----------------------------------------
# 1. Load data
# ----------------------------------------
df_up = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"Sample size (Mid → High): {len(df_up):,}")

# Column check
needed = [
    "delta_weekly", "delta_n_unique_products",
    "delta_pct_gap10", "weekly_med_early",
    "basket_med_early", "pct_gap10_early"
]
print("\nColumn check:")
for col in needed:
    print(f"  {col}: {'✅' if col in df_up.columns else '❌'}")

# ----------------------------------------
# 2. Define variables
# ----------------------------------------

# Y: weekly growth
df_up["y"] = df_up["delta_weekly"]

# X1: unique improvement amount
df_up["x1"] = df_up["delta_n_unique_products"]

# X2: ge10 improvement amount (sign flipped, improvement=positive)
df_up["x2"] = -df_up["delta_pct_gap10"]   # ← changed: ge10

# X3: interaction term (synergy effect)
df_up["x3"] = df_up["x1"] * df_up["x2"]

# Control variables
controls = [
    "weekly_med_early",   # initial scale
    "basket_med_early",   # basket baseline
    "pct_gap10_early"     # ← changed: ge10 early controls for regression to the mean
]

# ----------------------------------------
# 3. Build the modeling dataset
# ----------------------------------------
model_df = df_up[["y", "x1", "x2", "x3"] + controls].dropna()

print(f"\nModeling sample size: {len(model_df):,}")
print(f"\nX1 (delta_unique) distribution:")
print(model_df["x1"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(3))
print(f"\nX2 (ge10 improvement) distribution:")
print(model_df["x2"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(3))

# ----------------------------------------
# 4. Winsorize (Y only)
# ----------------------------------------
def winsorize(series, lower=0.01, upper=0.99):
    return series.clip(
        series.quantile(lower),
        series.quantile(upper)
    )

model_df = model_df.copy()
model_df["y"] = winsorize(model_df["y"])

# ----------------------------------------
# 5. OLS regression (including interaction term)
# ----------------------------------------
formula = "y ~ x1 + x2 + x3 + " + " + ".join(controls)
model_joint = smf.ols(
    formula=formula, data=model_df
).fit(cov_type="HC3")

print("\n========== Joint Intensify Regression Results ==========")
print(model_joint.summary())

# ----------------------------------------
# 6. Core coefficients
# ----------------------------------------
beta_unique      = model_joint.params["x1"]
beta_gap         = model_joint.params["x2"]
beta_interaction = model_joint.params["x3"]

print("\n========== Core Coefficients ==========")
print(f"β_unique      : {beta_unique:.4f}")
print(f"β_gap         : {beta_gap:.4f}")
print(f"β_interaction : {beta_interaction:.4f}")

print("\n📌 Business interpretation:")
print(f"+1 unique → Δweekly ≈ {beta_unique:.4f}")
print(f"1pp ge10 improvement → Δweekly ≈ {beta_gap/100:.4f}")

if beta_interaction > 0:
    print(f"✅ Synergy effect: improving unique and ge10 together → super-linear effect")
elif beta_interaction < 0:
    print(f"⚠️ Substitution effect: the two engines offset each other")
else:
    print(f"The two engines operate independently")

# ----------------------------------------
# 7. Control-variable sanity check
# ----------------------------------------
print(f"\n========== Control-Variable Sanity Check ==========")

checks = {
    "pct_gap10_early" : ("< 0", "higher early ge10 → harder growth"),
    "weekly_med_early": ("< 0", "larger initial scale → less room for growth"),
    "basket_med_early": ("> 0", "larger initial basket → higher weekly"),
}
for var, (expected, desc) in checks.items():
    if var in model_joint.params:
        coef = model_joint.params[var]
        ok = (expected == "< 0" and coef < 0) or \
             (expected == "> 0" and coef > 0)
        flag = "✅" if ok else "⚠️"
        print(f"  {var:<25} {coef:>8.4f} {flag} {desc}")

# ----------------------------------------
# 8. Bucketed check (single-variable monotonicity)
# ----------------------------------------
model_df["x1_bucket"] = pd.qcut(
    model_df["x1"], q=3, duplicates="drop"
)
model_df["x2_bucket"] = pd.qcut(
    model_df["x2"], q=3, duplicates="drop"
)

# Unique monotonicity
bucket_unique = (
    model_df
    .groupby("x1_bucket", observed=True)
    .agg(
        users=("y", "count"),
        x_mean=("x1", "mean"),
        y_mean=("y", "mean")
    )
    .reset_index()
)
corr_u, _ = spearmanr(bucket_unique["x_mean"], bucket_unique["y_mean"])

print(f"\n========== Unique Monotonicity ==========")
print(f"\n{'Bucket':<20} {'Users':>8} {'x_mean':>10} {'y_mean':>10}")
print("-"*52)
for _, row in bucket_unique.iterrows():
    print(f"{str(row['x1_bucket']):<20} {row['users']:>8,} "
          f"{row['x_mean']:>10.4f} {row['y_mean']:>10.4f}")
print(f"Spearman: {corr_u:.4f}")
if corr_u > 0:
    print("✅ Unique rises monotonically")

# Gap monotonicity
bucket_gap = (
    model_df
    .groupby("x2_bucket", observed=True)
    .agg(
        users=("y", "count"),
        x_mean=("x2", "mean"),
        y_mean=("y", "mean")
    )
    .reset_index()
)
corr_g, _ = spearmanr(bucket_gap["x_mean"], bucket_gap["y_mean"])

print(f"\n========== Gap Monotonicity ==========")
print(f"\n{'Bucket':<20} {'Users':>8} {'x_mean':>10} {'y_mean':>10}")
print("-"*52)
for _, row in bucket_gap.iterrows():
    print(f"{str(row['x2_bucket']):<20} {row['users']:>8,} "
          f"{row['x_mean']:>10.4f} {row['y_mean']:>10.4f}")
print(f"Spearman: {corr_g:.4f}")
if corr_g > 0:
    print("✅ Gap rises monotonically")

# ----------------------------------------
# 9. Joint bucketing (2×2)
# ----------------------------------------
joint_bucket = (
    model_df
    .groupby(["x1_bucket", "x2_bucket"], observed=True)
    .agg(
        users=("y", "count"),
        y_mean=("y", "mean")
    )
    .reset_index()
)

print(f"\n========== Joint Bucketed Results (2D) ==========")
print(joint_bucket.to_string(index=False))

# ----------------------------------------
# 10. Nonlinearity check (optional)
# ----------------------------------------
model_df["x1_sq"] = model_df["x1"] ** 2
model_df["x2_sq"] = model_df["x2"] ** 2

formula_quad = (
    "y ~ x1 + x2 + x3 + x1_sq + x2_sq + "
    + " + ".join(controls)
)
model_quad = smf.ols(
    formula=formula_quad, data=model_df
).fit(cov_type="HC3")

print("\n========== Nonlinear Model (quadratic term check) ==========")
print(model_quad.summary())

print("\n✅ New tables created:")
print("  - model_joint  (Joint Intensify OLS model)")
print("  - model_quad   (nonlinear model)")
print("  - model_df     (modeling data)")
print("  - bucket_unique (Unique bucketing)")
print("  - bucket_gap   (Gap bucketing)")
print("  - joint_bucket (Joint 2D bucketing)")

样本量（Mid → High）: 14,217

列检查：
  delta_weekly: ✅
  delta_n_unique_products: ✅
  delta_pct_gap10: ✅
  weekly_med_early: ✅
  basket_med_early: ✅
  pct_gap10_early: ✅

建模样本量: 14,217

X1（delta_unique）分布：
count    14217.000
mean         2.370
std          4.855
min        -26.500
10%         -3.000
25%          0.000
50%          2.000
75%          5.000
90%          8.000
max         40.000
Name: x1, dtype: float64

X2（ge10 改善量）分布：
count    14217.000
mean         0.185
std          0.269
min         -1.000
10%         -0.133
25%          0.005
50%          0.167
75%          0.336
90%          0.514
max          1.000
Name: x2, dtype: float64

========== Joint Intensify 回归结果 ==========
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.343
Model:                            OLS   Adj. R-squared:                  0.343
Method:                 Least Squares   F-statistic:                     572.0
Date:                Thu, 02 Jul 2026   Prob (F-statistic):               0.00
Time:                        16:29:07   Log-Likelihood:                -39740.
No. Observations:               14217   AIC:                         7.949e+04
Df Residuals:                   14210   BIC:                         7.955e+04
Df Model:                           6
Covariance Type:                  HC3
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           11.2364      0.583     19.264      0.000      10.093      12.380
x1                   0.4101      0.011     36.626      0.000       0.388       0.432
x2                  10.9454      0.222     49.226      0.000      10.510      11.381
x3                   0.0322      0.029      1.114      0.265      -0.024       0.089
weekly_med_early    -0.9106      0.089    -10.254      0.000      -1.085      -0.737
basket_med_early     0.3992      0.021     19.464      0.000       0.359       0.439
pct_gap10_early    -11.3270      0.464    -24.420      0.000     -12.236     -10.418
==============================================================================
Omnibus:                     6624.173   Durbin-Watson:                   1.984
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            50423.178
Skew:                           2.093   Prob(JB):                         0.00
Kurtosis:                      11.221   Cond. No.                         113.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

========== 核心系数 ==========
β_unique      : 0.4101
β_gap         : 10.9454
β_interaction : 0.0322

📌 业务解释：
+1 unique → Δweekly ≈ 0.4101
ge10 改善 1pp → Δweekly ≈ 0.1095
✅ 协同效应：同时改善 unique 和 ge10 → 效果超线性

========== 控制变量 Sanity Check ==========
  pct_gap10_early           -11.3270 ✅ 早期 ge10 越高 → 增长越难
  weekly_med_early           -0.9106 ✅ 初始规模越大 → 增长空间越小
  basket_med_early            0.3992 ✅ 初始 basket 越大 → weekly 越高

========== Unique 单调性 ==========

Bucket                  Users     x_mean     y_mean
----------------------------------------------------
(-26.501, 0.5]          4,957    -2.1345     5.8805
(0.5, 3.5]              4,658     2.0961     6.3355
(3.5, 40.0]             4,602     7.4991     8.4309
Spearman: 1.0000
✅ Unique 单调上升

========== Gap 单调性 ==========

Bucket                  Users     x_mean     y_mean
----------------------------------------------------
(-1.001, 0.0667]        4,742    -0.0936     5.4319
(0.0667, 0.278]         4,757     0.1726     6.5857
(0.278, 1.0]            4,718     0.4789     8.5572
Spearman: 1.0000
✅ Gap 单调上升

========== Joint 分桶结果（2D）==========
     x1_bucket        x2_bucket  users    y_mean
(-26.501, 0.5] (-1.001, 0.0667]   1202  4.333584
(-26.501, 0.5]  (0.0667, 0.278]   1587  5.090761
(-26.501, 0.5]     (0.278, 1.0]   2168  7.316170
    (0.5, 3.5] (-1.001, 0.0667]   1627  4.712770
    (0.5, 3.5]  (0.0667, 0.278]   1708  6.188993
    (0.5, 3.5]     (0.278, 1.0]   1323  8.520131
   (3.5, 40.0] (-1.001, 0.0667]   1913  6.733688
   (3.5, 40.0]  (0.0667, 0.278]   1462  8.671976
   (3.5, 40.0]     (0.278, 1.0]   1227 10.789885

========== 非线性模型（二次项检查） ==========
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.354
Model:                            OLS   Adj. R-squared:                  0.354
Method:                 Least Squares   F-statistic:                     461.7
Date:                Thu, 02 Jul 2026   Prob (F-statistic):               0.00
Time:                        16:29:07   Log-Likelihood:                -39616.
No. Observations:               14217   AIC:                         7.925e+04
Df Residuals:                   14208   BIC:                         7.932e+04
Df Model:                           8
Covariance Type:                  HC3
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           11.2521      0.567     19.857      0.000      10.141      12.363
x1                   0.3219      0.015     21.654      0.000       0.293       0.351
x2                   8.8951      0.254     35.087      0.000       8.398       9.392
x3                   0.2135      0.033      6.422      0.000       0.148       0.279
x1_sq                0.0062      0.001      4.951      0.000       0.004       0.009
x2_sq                3.9798      0.357     11.137      0.000       3.279       4.680
weekly_med_early    -0.8862      0.087    -10.169      0.000      -1.057      -0.715
basket_med_early     0.3744      0.021     17.898      0.000       0.333       0.415
pct_gap10_early    -11.2148      0.459    -24.446      0.000     -12.114     -10.316
==============================================================================
Omnibus:                     6466.570   Durbin-Watson:                   1.988
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            48835.808
Skew:                           2.034   Prob(JB):                         0.00
Kurtosis:                      11.117   Cond. No.                         760.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

✅ New tables created:
  - model_joint  (Joint Intensify OLS 模型)
  - model_quad   (非线性模型)
  - model_df     (建模数据)
  - bucket_unique（Unique 分桶）
  - bucket_gap   （Gap 分桶）
  - joint_bucket （Joint 2D 分桶）

In [141]:
# ============================================================
# Joint Intensify apply the model (fixed version)
# Fix: ge10 variable, new parameters, multi-scenario grid
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# 1. Load data
# ----------------------------------------
df_up = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"Sample size (Mid → High): {len(df_up):,}")

# Column check
needed = [
    "delta_n_unique_products", "delta_pct_gap10",
    "pct_gap10_early", "weekly_med_late",
    "weekly_med_early", "basket_med_early"
]
print("\nColumn check:")
for col in needed:
    print(f"  {col}: {'✅' if col in df_up.columns else '❌'}")

# ----------------------------------------
# 2. Define variables (consistent with modeling)
# ----------------------------------------
df_up["x1"] = df_up["delta_n_unique_products"]  # unique improvement
df_up["x2"] = -df_up["delta_pct_gap10"]         # ge10 improvement ← changed

# ----------------------------------------
# 3. Model coefficients (linear model, new parameters)
# ----------------------------------------
beta_unique      =  0.4101   # ← changed
beta_gap         = 10.9454   # ← changed
beta_interaction =  0.0322   # ← changed (linear model, used directly)
intercept        = 11.2364   # ← changed (for sanity check)

# Control-variable coefficients (for sanity check)
beta_weekly      = -0.9106
beta_basket      =  0.3992
beta_gap_early   = -11.3270

print(f"\nModel parameters:")
print(f"  β_unique      = {beta_unique}")
print(f"  β_gap         = {beta_gap}")
print(f"  β_interaction = {beta_interaction}")

# ----------------------------------------
# 4. Baseline
# ----------------------------------------
baseline_total_weekly = df_up["weekly_med_late"].sum()
print(f"\nBaseline total weekly: {baseline_total_weekly:,.2f}")

# ----------------------------------------
# 5. Headroom calculation
# ----------------------------------------

# Unique headroom（P90）
p90_unique = df_up["x1"].quantile(0.9)
df_up["headroom_unique"] = np.maximum(0, p90_unique - df_up["x1"])

# Gap headroom (P20 + floor) ← change: using pct_gap10_early
gap_level   = df_up["pct_gap10_early"]           # ← changed
p20_gap     = gap_level.quantile(0.2)
gap_floor   = max(p20_gap, 0.02)
df_up["headroom_gap"] = np.maximum(0, gap_level - gap_floor)

print(f"\nP90 unique:          {p90_unique:.2f}")
print(f"P20 gap（ge10）:      {p20_gap:.4f}")
print(f"gap floor:            {gap_floor:.4f}")
print(f"Average unique headroom: {df_up['headroom_unique'].mean():.2f}")
print(f"Average gap headroom:    {df_up['headroom_gap'].mean():.4f}")

# ----------------------------------------
# 6. Scenario Grid
# ----------------------------------------
unique_scenarios = [1, 2, 3]
gap_scenarios    = [0.03, 0.05, 0.07, 0.10]

results = []

for u in unique_scenarios:
    for g in gap_scenarios:

        df_tmp = df_up.copy()

        # Actually applied (capped by headroom)
        df_tmp["du"] = np.minimum(u, df_tmp["headroom_unique"])
        df_tmp["dg"] = np.minimum(g, df_tmp["headroom_gap"])

        # Δweekly (linear model + interaction term)
        df_tmp["delta_weekly_pred"] = (
            beta_unique      * df_tmp["du"]
            + beta_gap       * df_tmp["dg"]
            + beta_interaction * df_tmp["du"] * df_tmp["dg"]
        )

        # Prevent negative values
        df_tmp["delta_weekly_pred"] = np.maximum(
            0, df_tmp["delta_weekly_pred"]
        )

        # Summary
        total_uplift   = df_tmp["delta_weekly_pred"].sum()
        avg_uplift     = df_tmp["delta_weekly_pred"].mean()
        uplift_pct     = total_uplift / baseline_total_weekly
        affected_users = (
            (df_tmp["du"] > 0) | (df_tmp["dg"] > 0)
        ).sum()
        affected_pct   = affected_users / len(df_tmp)
        avg_du         = df_tmp["du"].mean()
        avg_dg         = df_tmp["dg"].mean()

        # unique only (excluding the gap effect)
        uplift_unique_only = (beta_unique * df_tmp["du"]).sum()

        # gap only (excluding the unique effect)
        uplift_gap_only = (beta_gap * df_tmp["dg"]).sum()

        # interaction contribution
        uplift_interaction = (
            beta_interaction * df_tmp["du"] * df_tmp["dg"]
        ).sum()

        results.append({
            "unique_target"     : u,
            "gap_target_pp"     : int(g * 100),
            "total_uplift"      : round(total_uplift, 2),
            "avg_uplift"        : round(avg_uplift, 4),
            "uplift_pct"        : round(uplift_pct, 4),
            "uplift_unique_only": round(uplift_unique_only, 2),
            "uplift_gap_only"   : round(uplift_gap_only, 2),
            "uplift_interaction": round(uplift_interaction, 2),
            "affected_users"    : affected_users,
            "affected_pct"      : round(affected_pct, 4),
            "avg_du_applied"    : round(avg_du, 2),
            "avg_dg_applied_pp" : round(avg_dg * 100, 2),
        })

result_df = pd.DataFrame(results)

# ----------------------------------------
# 7. Output results
# ----------------------------------------
print("\n" + "="*70)
print("Joint Intensify Results (ge10 version)")
print("="*70)
print(result_df.to_string(index=False))

# ----------------------------------------
# 8. Pivot：Total Uplift Grid
# ----------------------------------------
pivot_total = result_df.pivot(
    index="gap_target_pp",
    columns="unique_target",
    values="total_uplift"
)
print("\n" + "="*70)
print("Total Uplift Grid")
print("="*70)
print(pivot_total)

# ----------------------------------------
# 9. Pivot：Uplift % Grid
# ----------------------------------------
pivot_pct = result_df.pivot(
    index="gap_target_pp",
    columns="unique_target",
    values="uplift_pct"
).applymap(lambda x: f"{x:.2%}")

print("\n" + "="*70)
print("Uplift % Grid")
print("="*70)
print(pivot_pct)

# ----------------------------------------
# 10. Pivot: contribution breakdown by engine (+3 unique, +10pp gap)
# ----------------------------------------
print("\n" + "="*70)
print("Engine Contribution Breakdown (+3 unique + +10pp gap)")
print("="*70)
row = result_df[
    (result_df["unique_target"] == 3) &
    (result_df["gap_target_pp"] == 10)
].iloc[0]

print(f"Unique contribution:  {row['uplift_unique_only']:>10,.2f} "
      f"({row['uplift_unique_only']/row['total_uplift']:.1%})")
print(f"Gap contribution:     {row['uplift_gap_only']:>10,.2f} "
      f"({row['uplift_gap_only']/row['total_uplift']:.1%})")
print(f"Interaction contribution: {row['uplift_interaction']:>10,.2f} "
      f"({row['uplift_interaction']/row['total_uplift']:.1%})")
print(f"Total：        {row['total_uplift']:>10,.2f}")

# ----------------------------------------
# 11. Sanity Check
# ----------------------------------------
print("\n" + "="*70)
print("Sanity Check")
print("="*70)
print(f"P90 unique headroom:  {p90_unique:.2f}")
print(f"P20 gap headroom:     {gap_floor:.4f}")
print(f"Average unique headroom: {df_up['headroom_unique'].mean():.2f}")
print(f"Average gap headroom:    {df_up['headroom_gap'].mean():.4f}")
print(f"Users with unique headroom:  "
      f"{(df_up['headroom_unique'] > 0).sum():,} "
      f"({(df_up['headroom_unique'] > 0).mean():.2%})")
print(f"Users with gap headroom:     "
      f"{(df_up['headroom_gap'] > 0).sum():,} "
      f"({(df_up['headroom_gap'] > 0).mean():.2%})")

# ----------------------------------------
# 12. Copyable Excel table
# ----------------------------------------
print("\n" + "="*70)
print("Copyable for Excel:")
print("="*70)
print("Unique Target\tGap Target pp\tTotal Uplift\tUplift %\t"
      "Unique Only\tGap Only\tInteraction\t"
      "Affected Users\tAffected %\tAvg du\tAvg dg pp")
for _, row in result_df.iterrows():
    print(f"{row['unique_target']}\t"
          f"{row['gap_target_pp']}\t"
          f"{row['total_uplift']}\t"
          f"{row['uplift_pct']:.2%}\t"
          f"{row['uplift_unique_only']}\t"
          f"{row['uplift_gap_only']}\t"
          f"{row['uplift_interaction']}\t"
          f"{row['affected_users']}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['avg_du_applied']}\t"
          f"{row['avg_dg_applied_pp']}")

print("\n✅ New tables created:")
print("  - result_df    (Joint Intensify all scenarios)")
print("  - pivot_total  (Total Uplift Grid)")
print("  - pivot_pct    (Uplift % Grid)")

样本量（Mid → High）: 14,217

列检查：
  delta_n_unique_products: ✅
  delta_pct_gap10: ✅
  pct_gap10_early: ✅
  weekly_med_late: ✅
  weekly_med_early: ✅
  basket_med_early: ✅

模型参数：
  β_unique      = 0.4101
  β_gap         = 10.9454
  β_interaction = 0.0322

Baseline total weekly: 189,233.54

P90 unique:          8.00
P20 gap（ge10）:      0.2500
gap floor:            0.2500
平均 unique headroom: 6.03
平均 gap headroom:    0.3022

======================================================================
Joint Intensify 结果（ge10 版本）
======================================================================
 unique_target  gap_target_pp  total_uplift  avg_uplift  uplift_pct  uplift_unique_only  uplift_gap_only  uplift_interaction  affected_users  affected_pct  avg_du_applied  avg_dg_applied_pp
             1              3       8805.26      0.6193      0.0465             5137.94          3657.88                9.44           13917        0.9789            0.88               2.35
             1              5      11192.30      0.7872      0.0591             5137.94          6038.78               15.58           13917        0.9789            0.88               3.88
             1              7      13527.46      0.9515      0.0715             5137.94          8367.94               21.58           13917        0.9789            0.88               5.38
             1             10      16879.97      1.1873      0.0892             5137.94         11711.84               30.19           13917        0.9789            0.88               7.53
             2              3      13740.22      0.9665      0.0726            10063.85          3657.88               18.48           13917        0.9789            1.73               2.35
             2              5      16133.14      1.1348      0.0853            10063.85          6038.78               30.50           13917        0.9789            1.73               3.88
             2              7      18474.06      1.2994      0.0976            10063.85          8367.94               42.27           13917        0.9789            1.73               5.38
             2             10      21834.81      1.5358      0.1154            10063.85         11711.84               59.12           13917        0.9789            1.73               7.53
             3              3      18407.92      1.2948      0.0973            14723.00          3657.88               27.03           13917        0.9789            2.53               2.35
             3              5      20806.40      1.4635      0.1100            14723.00          6038.78               44.62           13917        0.9789            2.53               3.88
             3              7      23152.76      1.6285      0.1224            14723.00          8367.94               61.82           13917        0.9789            2.53               5.38
             3             10      26521.32      1.8655      0.1402            14723.00         11711.84               86.48           13917        0.9789            2.53               7.53

======================================================================
Total Uplift Grid
======================================================================
unique_target         1         2         3
gap_target_pp
3               8805.26  13740.22  18407.92
5              11192.30  16133.14  20806.40
7              13527.46  18474.06  23152.76
10             16879.97  21834.81  26521.32

======================================================================
Uplift % Grid
======================================================================
unique_target      1       2       3
gap_target_pp
3              4.65%   7.26%   9.73%
5              5.91%   8.53%  11.00%
7              7.15%   9.76%  12.24%
10             8.92%  11.54%  14.02%

======================================================================
引擎贡献分解（+3 unique + +10pp gap）
======================================================================
Unique 贡献：   14,723.00 (55.5%)
Gap 贡献：      11,711.84 (44.2%)
交互项贡献：        86.48 (0.3%)
Total：         26,521.32

======================================================================
Sanity Check
======================================================================
P90 unique headroom:  8.00
P20 gap headroom:     0.2500
平均 unique headroom: 6.03
平均 gap headroom:    0.3022
有 unique 空间用户：  12,605 (88.66%)
有 gap 空间用户：     11,219 (78.91%)

======================================================================
可复制到 Excel：
======================================================================
Unique Target	Gap Target pp	Total Uplift	Uplift %	Unique Only	Gap Only	Interaction	Affected Users	Affected %	Avg du	Avg dg pp
1.0	3.0	8805.26	4.65%	5137.94	3657.88	9.44	13917.0	97.89%	0.88	2.35
1.0	5.0	11192.3	5.91%	5137.94	6038.78	15.58	13917.0	97.89%	0.88	3.88
1.0	7.0	13527.46	7.15%	5137.94	8367.94	21.58	13917.0	97.89%	0.88	5.38
1.0	10.0	16879.97	8.92%	5137.94	11711.84	30.19	13917.0	97.89%	0.88	7.53
2.0	3.0	13740.22	7.26%	10063.85	3657.88	18.48	13917.0	97.89%	1.73	2.35
2.0	5.0	16133.14	8.53%	10063.85	6038.78	30.5	13917.0	97.89%	1.73	3.88
2.0	7.0	18474.06	9.76%	10063.85	8367.94	42.27	13917.0	97.89%	1.73	5.38
2.0	10.0	21834.81	11.54%	10063.85	11711.84	59.12	13917.0	97.89%	1.73	7.53
3.0	3.0	18407.92	9.73%	14723.0	3657.88	27.03	13917.0	97.89%	2.53	2.35
3.0	5.0	20806.4	11.00%	14723.0	6038.78	44.62	13917.0	97.89%	2.53	3.88
3.0	7.0	23152.76	12.24%	14723.0	8367.94	61.82	13917.0	97.89%	2.53	5.38
3.0	10.0	26521.32	14.02%	14723.0	11711.84	86.48	13917.0	97.89%	2.53	7.53

✅ New tables created:
  - result_df    (Joint Intensify 全部场景)
  - pivot_total  (Total Uplift Grid)
  - pivot_pct    (Uplift % Grid)

/var/folders/c9/6ghzgq6144jf4_jfkb5kfk6c0000gn/T/ipykernel_5919/1923682381.py:174: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ).applymap(lambda x: f"{x:.2%}")

In [142]:
# ============================================================
# Joint Flow modeling (fixed version)
# Fix: v2 table, ge10 variable, all three groups' complete pool
# ============================================================

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from scipy.stats import spearmanr

# ----------------------------------------
# 1. Load data (change: using the v2 table)
# ----------------------------------------
df_mid = analysis_mid_user_master_v2.copy()

print(f"Mid pool sample size: {len(df_mid):,}")
print(df_mid["path_9"].value_counts())

# ----------------------------------------
# 2. Define the dependent variable Y
# ----------------------------------------
df_mid["y"] = np.where(
    df_mid["path_9"] == "Mid Up to High", 1, 0
)
print(f"\nActual Up share: {df_mid['y'].mean():.4f}")

# ----------------------------------------
# 3. Define independent variables
# ----------------------------------------

# X1: unique improvement amount
df_mid["x1"] = df_mid["delta_n_unique_products"]

# X2: ge10 improvement amount (sign flipped, improvement=positive) ← changed
df_mid["x2"] = -df_mid["delta_pct_gap10_v2"]

# X3: interaction term
df_mid["x3"] = df_mid["x1"] * df_mid["x2"]

# Control variables (changed: ge10)
controls = [
    "weekly_med_early",    # user's initial scale
    "basket_med_early",    # basket baseline
    "pct_gap10_early_v2"   # ← changed: ge10 early controls for regression to the mean
]

# ----------------------------------------
# 4. Build the modeling dataset
# ----------------------------------------
model_df = df_mid[["y", "x1", "x2", "x3"] + controls].dropna()

print(f"\nModeling sample size: {len(model_df):,}")
print(f"Up share (post-modeling): {model_df['y'].mean():.4f}")
print(f"\npath_9 distribution (post-modeling):")
print(df_mid.loc[model_df.index, "path_9"].value_counts())

print(f"\nX1 (delta_unique) distribution:")
print(model_df["x1"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(3))

print(f"\nX2 (ge10 improvement) distribution:")
print(model_df["x2"].describe(
    percentiles=[.1, .25, .5, .75, .9]
).round(3))

# ----------------------------------------
# 5. Winsorize (X1 and X2)
# ----------------------------------------
def winsorize(series, lower=0.01, upper=0.99):
    return series.clip(
        series.quantile(lower),
        series.quantile(upper)
    )

model_df = model_df.copy()
model_df["x1"] = winsorize(model_df["x1"])
model_df["x2"] = winsorize(model_df["x2"])

# Recompute the interaction term (based on winsorized values)
model_df["x3"] = model_df["x1"] * model_df["x2"]

# ----------------------------------------
# 6. Logit model
# ----------------------------------------
formula = "y ~ x1 + x2 + x3 + " + " + ".join(controls)
model_joint_flow = smf.logit(
    formula=formula, data=model_df
).fit()

print("\n========== Joint Flow Logit Regression Results ==========")
print(model_joint_flow.summary())

# ----------------------------------------
# 7. Core coefficients
# ----------------------------------------
beta_unique      = model_joint_flow.params["x1"]
beta_gap         = model_joint_flow.params["x2"]
beta_interaction = model_joint_flow.params["x3"]

ci = model_joint_flow.conf_int()

print("\n========== Core Coefficients ==========")
print(f"β_unique      : {beta_unique:.4f} "
      f"[{ci.loc['x1', 0]:.4f}, {ci.loc['x1', 1]:.4f}]")
print(f"β_gap         : {beta_gap:.4f} "
      f"[{ci.loc['x2', 0]:.4f}, {ci.loc['x2', 1]:.4f}]")
print(f"β_interaction : {beta_interaction:.4f} "
      f"[{ci.loc['x3', 0]:.4f}, {ci.loc['x3', 1]:.4f}]")

print("\n📌 Direction interpretation:")
if beta_unique > 0:
    print("✅ unique increases → Up probability ↑")
else:
    print("⚠️ unique direction is anomalous")

if beta_gap > 0:
    print("✅ ge10 improvement → Up probability ↑")
else:
    print("⚠️ ge10 direction is anomalous")

if beta_interaction > 0:
    print("🔥 interaction > 0 → the two engines reinforce each other")
elif beta_interaction < 0:
    print("⚠️ interaction < 0 → a substitution effect is present")
else:
    print("The two engines operate independently")

# ----------------------------------------
# 8. Model validation
# ----------------------------------------
model_df["p_pred"] = model_joint_flow.predict(model_df)

print(f"\n========== Model Validation ==========")
print(f"Average predicted probability: {model_df['p_pred'].mean():.4f}")
print(f"Actual Up share: {model_df['y'].mean():.4f}")

# ----------------------------------------
# 9. Control-variable sanity check
# ----------------------------------------
print(f"\n========== Control-Variable Sanity Check ==========")
checks = {
    "pct_gap10_early_v2": ("< 0", "higher early ge10 → harder to upgrade"),
    "weekly_med_early"  : ("> 0", "higher initial activity → easier to upgrade"),
    "basket_med_early"  : ("> 0", "larger initial basket → easier to upgrade"),
}
for var, (expected, desc) in checks.items():
    if var in model_joint_flow.params:
        coef = model_joint_flow.params[var]
        ok = (expected == "< 0" and coef < 0) or \
             (expected == "> 0" and coef > 0)
        flag = "✅" if ok else "⚠️"
        print(f"  {var:<25} {coef:>8.4f} {flag} {desc}")

# ----------------------------------------
# 10. Single-variable bucketed validation
# ----------------------------------------

# Unique monotonicity
model_df["x1_bucket"] = pd.qcut(
    model_df["x1"], q=5, duplicates="drop"
)
bucket_unique = (
    model_df
    .groupby("x1_bucket", observed=True)
    .agg(
        users=("y", "count"),
        x_mean=("x1", "mean"),
        up_rate=("y", "mean"),
        pred_prob=("p_pred", "mean")
    )
    .reset_index()
)
corr_u, pval_u = spearmanr(
    bucket_unique["x_mean"], bucket_unique["up_rate"]
)

print(f"\n========== Unique Monotonicity ==========")
print(f"\n{'Bucket':<20} {'Users':>8} {'x_mean':>10} "
      f"{'Up Rate':>10} {'Pred Prob':>12}")
print("-"*65)
for _, row in bucket_unique.iterrows():
    print(f"{str(row['x1_bucket']):<20} {row['users']:>8,} "
          f"{row['x_mean']:>10.4f} {row['up_rate']:>10.4f} "
          f"{row['pred_prob']:>12.4f}")
print(f"Spearman: {corr_u:.4f}  p={pval_u:.4f}")
if corr_u > 0:
    print("✅ Unique rises monotonically")

# Gap monotonicity
model_df["x2_bucket"] = pd.qcut(
    model_df["x2"], q=5, duplicates="drop"
)
bucket_gap = (
    model_df
    .groupby("x2_bucket", observed=True)
    .agg(
        users=("y", "count"),
        x_mean=("x2", "mean"),
        up_rate=("y", "mean"),
        pred_prob=("p_pred", "mean")
    )
    .reset_index()
)
corr_g, pval_g = spearmanr(
    bucket_gap["x_mean"], bucket_gap["up_rate"]
)

print(f"\n========== Gap Monotonicity ==========")
print(f"\n{'Bucket':<20} {'Users':>8} {'x_mean':>10} "
      f"{'Up Rate':>10} {'Pred Prob':>12}")
print("-"*65)
for _, row in bucket_gap.iterrows():
    print(f"{str(row['x2_bucket']):<20} {row['users']:>8,} "
          f"{row['x_mean']:>10.4f} {row['up_rate']:>10.4f} "
          f"{row['pred_prob']:>12.4f}")
print(f"Spearman: {corr_g:.4f}  p={pval_g:.4f}")
if corr_g > 0:
    print("✅ Gap rises monotonically")

# ----------------------------------------
# 11. Joint 2D bucketing
# ----------------------------------------
model_df["x1_bucket3"] = pd.qcut(
    model_df["x1"], q=3, duplicates="drop"
)
model_df["x2_bucket3"] = pd.qcut(
    model_df["x2"], q=3, duplicates="drop"
)

joint_bucket = (
    model_df
    .groupby(["x1_bucket3", "x2_bucket3"], observed=True)
    .agg(
        users=("y", "count"),
        up_rate=("y", "mean"),
        pred_prob=("p_pred", "mean")
    )
    .reset_index()
)

print(f"\n========== Joint 2D Bucketed Results ==========")
print(joint_bucket.to_string(index=False))

# ----------------------------------------
# 12. Interaction bucketing
# ----------------------------------------
model_df["x3_bucket"] = pd.qcut(
    model_df["x3"], q=5, duplicates="drop"
)
bucket_interaction = (
    model_df
    .groupby("x3_bucket", observed=True)
    .agg(
        users=("y", "count"),
        x_mean=("x3", "mean"),
        up_rate=("y", "mean")
    )
    .reset_index()
)
corr_i, pval_i = spearmanr(
    bucket_interaction["x_mean"],
    bucket_interaction["up_rate"]
)

print(f"\n========== Interaction Monotonicity ==========")
print(bucket_interaction.to_string(index=False))
print(f"Spearman: {corr_i:.4f}  p={pval_i:.4f}")

print("\n✅ New tables created:")
print("  - model_joint_flow  (Joint Flow Logit model)")
print("  - model_df          (modeling data)")
print("  - bucket_unique     (Unique bucketing)")
print("  - bucket_gap        (Gap bucketing)")
print("  - joint_bucket      (Joint 2D bucketing)")
print("  - bucket_interaction (Interaction bucketing)")

Mid 母池样本量: 73,367
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

实际 Up 比例: 0.1938

建模样本量: 73,367
Up 比例（建模后）: 0.1938

path_9 分布（建模后）:
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

X1（delta_unique）分布：
count    73367.000
mean         0.012
std          4.349
min        -31.000
10%         -5.000
25%         -2.000
50%          0.000
75%          2.000
90%          5.000
max         40.000
Name: x1, dtype: float64

X2（ge10 改善量）分布：
count    73367.000
mean        -0.011
std          0.303
min         -1.000
10%         -0.400
25%         -0.179
50%          0.000
75%          0.173
90%          0.333
max          1.000
Name: x2, dtype: float64
Optimization terminated successfully.
         Current function value: 0.257844
         Iterations 8

========== Joint Flow Logit 回归结果 ==========
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                73367
Model:                          Logit   Df Residuals:                    73360
Method:                           MLE   Df Model:                            6
Date:                Thu, 02 Jul 2026   Pseudo R-squ.:                  0.4756
Time:                        16:29:07   Log-Likelihood:                -18917.
converged:                       True   LL-Null:                       -36071.
Covariance Type:            nonrobust   LLR p-value:                     0.000
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             -2.2570      0.054    -41.725      0.000      -2.363      -2.151
x1                     0.4211      0.005     89.234      0.000       0.412       0.430
x2                     9.0105      0.087    103.928      0.000       8.841       9.180
x3                    -0.0730      0.011     -6.361      0.000      -0.096      -0.051
weekly_med_early       0.1137      0.007     15.347      0.000       0.099       0.128
basket_med_early       0.3673      0.005     78.949      0.000       0.358       0.376
pct_gap10_early_v2    -8.4695      0.094    -90.352      0.000      -8.653      -8.286
======================================================================================

========== 核心系数 ==========
β_unique      : 0.4211 [0.4119, 0.4304]
β_gap         : 9.0105 [8.8405, 9.1804]
β_interaction : -0.0730 [-0.0955, -0.0505]

📌 方向解释：
✅ unique 增加 → Up 概率 ↑
✅ ge10 改善 → Up 概率 ↑
⚠️ interaction < 0 → 存在替代效应

========== 模型校验 ==========
平均预测概率: 0.1938
实际 Up 比例: 0.1938

========== 控制变量 Sanity Check ==========
  pct_gap10_early_v2         -8.4695 ✅ 早期 ge10 越高 → 越难升级
  weekly_med_early            0.1137 ✅ 初始活跃度越高 → 越容易升级
  basket_med_early            0.3673 ✅ 初始 basket 越大 → 越容易升级

========== Unique 单调性 ==========

Bucket                  Users     x_mean    Up Rate    Pred Prob
-----------------------------------------------------------------
(-12.001, -3.0]        15,035    -5.5954     0.0956       0.0888
(-3.0, -1.0]           14,734    -1.5642     0.1095       0.1204
(-1.0, 1.0]            19,490     0.3104     0.1558       0.1683
(1.0, 3.0]             12,031     2.2262     0.2568       0.2417
(3.0, 12.0]            12,077     6.2036     0.4173       0.4073
Spearman: 1.0000  p=0.0000
✅ Unique 单调上升

========== Gap 单调性 ==========

Bucket                  Users     x_mean    Up Rate    Pred Prob
-----------------------------------------------------------------
(-0.834, -0.25]        15,342    -0.4317     0.0482       0.0409
(-0.25, -0.0449]       14,010    -0.1317     0.1166       0.1143
(-0.0449, 0.0401]      14,668    -0.0021     0.1245       0.1509
(0.0401, 0.236]        14,678     0.1324     0.2894       0.2743
(0.236, 0.667]         14,669     0.3893     0.3933       0.3919
Spearman: 1.0000  p=0.0000
✅ Gap 单调上升

========== Joint 2D 分桶结果 ==========
     x1_bucket3        x2_bucket3  users  up_rate  pred_prob
(-12.001, -1.0] (-0.834, -0.0972]   8651 0.025199   0.018222
(-12.001, -1.0] (-0.0972, 0.0972]  10210 0.050343   0.062170
(-12.001, -1.0]   (0.0972, 0.667]  10908 0.212688   0.212413
    (-1.0, 1.0] (-0.834, -0.0972]   7385 0.038727   0.040925
    (-1.0, 1.0] (-0.0972, 0.0972]   6485 0.129530   0.172716
    (-1.0, 1.0]   (0.0972, 0.667]   5620 0.339858   0.330652
    (1.0, 12.0] (-0.834, -0.0972]   8431 0.142806   0.128380
    (1.0, 12.0] (-0.0972, 0.0972]   7756 0.306730   0.302655
    (1.0, 12.0]   (0.0972, 0.667]   7921 0.573917   0.555142

========== Interaction 单调性 ==========
        x3_bucket  users    x_mean  up_rate
(-10.001, -0.505]  14674 -1.742501 0.187883
(-0.505, -0.0321]  14673 -0.231875 0.154774
   (-0.0321, 0.0]  16850 -0.001121 0.105579
     (0.0, 0.346]  12496  0.159486 0.200624
     (0.346, 8.0]  14674  1.209942 0.334128
Spearman: 0.6000  p=0.2848

✅ New tables created:
  - model_joint_flow  (Joint Flow Logit 模型)
  - model_df          (建模数据)
  - bucket_unique     (Unique 分桶)
  - bucket_gap        (Gap 分桶)
  - joint_bucket      (Joint 2D 分桶)
  - bucket_interaction（Interaction 分桶）

In [143]:
# Apply the model

# ============================================================
# Joint Flow apply the model (fixed version)
# Fix: v2 table, ge10 variable, new parameters
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# 1. Load data (change: using the v2 table)
# ----------------------------------------
df_mid = analysis_mid_user_master_v2.copy()

print(f"Mid pool sample size: {len(df_mid):,}")
print(df_mid["path_9"].value_counts())

# ----------------------------------------
# 2. Define variables (consistent with modeling)
# ----------------------------------------

# X1: unique improvement amount
df_mid["x1"] = df_mid["delta_n_unique_products"]

# X2: ge10 improvement amount (sign flipped) ← changed
df_mid["x2"] = -df_mid["delta_pct_gap10_v2"]

# X3: interaction term
df_mid["x3"] = df_mid["x1"] * df_mid["x2"]

# Control variables
df_mid["weekly_early"] = df_mid["weekly_med_early"]
df_mid["basket_early"] = df_mid["basket_med_early"]
df_mid["gap_early"]    = df_mid["pct_gap10_early_v2"]  # ← changed

# Baseline Up user count
df_mid["y"] = np.where(
    df_mid["path_9"] == "Mid Up to High", 1, 0
)
baseline_up = df_mid["y"].sum()
print(f"\nBaseline Up user count: {baseline_up:,}")
print(f"Baseline Up share: {df_mid['y'].mean():.4f}")

# ----------------------------------------
# 3. Model coefficients (changed: new parameters)
# ----------------------------------------
beta_0           = -2.2570
beta_unique      =  0.4211
beta_gap         =  9.0105
beta_interaction = -0.0730
beta_weekly      =  0.1137
beta_basket      =  0.3673
beta_gap_early   = -8.4695

print(f"\nModel parameters:")
print(f"  β_unique      = {beta_unique}")
print(f"  β_gap         = {beta_gap}")
print(f"  β_interaction = {beta_interaction}")

# ----------------------------------------
# 4. sigmoid function
# ----------------------------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# ----------------------------------------
# 5. Headroom calculation
# ----------------------------------------

# Unique headroom (Mid-pool P90)
p90_unique = df_mid["x1"].quantile(0.9)
df_mid["headroom_unique"] = np.maximum(0, p90_unique - df_mid["x1"])

# Gap headroom (P20 + floor) ← changed: using pct_gap10_early_v2
gap_level = df_mid["pct_gap10_early_v2"]
p20_gap   = gap_level.quantile(0.2)
gap_floor = max(p20_gap, 0.02)
df_mid["headroom_gap"] = np.maximum(0, gap_level - gap_floor)

print(f"\nP90 unique:           {p90_unique:.2f}")
print(f"P20 gap（ge10）:       {p20_gap:.4f}")
print(f"gap floor:             {gap_floor:.4f}")
print(f"Average unique headroom:  {df_mid['headroom_unique'].mean():.2f}")
print(f"Average gap headroom:     {df_mid['headroom_gap'].mean():.4f}")
print(f"Users with unique headroom:   "
      f"{(df_mid['headroom_unique'] > 0).sum():,} "
      f"({(df_mid['headroom_unique'] > 0).mean():.2%})")
print(f"Users with gap headroom:      "
      f"{(df_mid['headroom_gap'] > 0).sum():,} "
      f"({(df_mid['headroom_gap'] > 0).mean():.2%})")

# ----------------------------------------
# 6. Baseline probability (P_old)
# ----------------------------------------
df_mid["logit_old"] = (
    beta_0
    + beta_unique      * df_mid["x1"]
    + beta_gap         * df_mid["x2"]
    + beta_interaction * df_mid["x3"]
    + beta_weekly      * df_mid["weekly_early"]
    + beta_basket      * df_mid["basket_early"]
    + beta_gap_early   * df_mid["gap_early"]
)
df_mid["p_old"] = sigmoid(df_mid["logit_old"])

print(f"\nAverage p_old:  {df_mid['p_old'].mean():.4f}")
print(f"Actual Up share:{df_mid['y'].mean():.4f}")

# ----------------------------------------
# 7. Scenario Grid（+1/2/3 unique × +3/5/7/10pp gap）
# ----------------------------------------
unique_scenarios = [1, 2, 3]
gap_scenarios    = [0.03, 0.05, 0.07, 0.10]

results = []

for u in unique_scenarios:
    for g in gap_scenarios:

        df_tmp = df_mid.copy()

        # Actually applied (capped by headroom)
        df_tmp["du"] = np.minimum(u, df_tmp["headroom_unique"])
        df_tmp["dg"] = np.minimum(g, df_tmp["headroom_gap"])

        # New variable
        df_tmp["x1_new"] = df_tmp["x1"] + df_tmp["du"]
        df_tmp["x2_new"] = df_tmp["x2"] + df_tmp["dg"]
        df_tmp["x3_new"] = df_tmp["x1_new"] * df_tmp["x2_new"]

        # P_new
        df_tmp["logit_new"] = (
            beta_0
            + beta_unique      * df_tmp["x1_new"]
            + beta_gap         * df_tmp["x2_new"]
            + beta_interaction * df_tmp["x3_new"]
            + beta_weekly      * df_tmp["weekly_early"]
            + beta_basket      * df_tmp["basket_early"]
            + beta_gap_early   * df_tmp["gap_early"]
        )
        df_tmp["p_new"] = sigmoid(df_tmp["logit_new"])

        # ΔP
        df_tmp["delta_p"] = df_tmp["p_new"] - df_tmp["p_old"]

        # Summary
        delta_up       = df_tmp["delta_p"].sum()
        avg_delta_p    = df_tmp["delta_p"].mean()
        uplift_pct     = delta_up / baseline_up
        affected_users = (
            (df_tmp["du"] > 0) | (df_tmp["dg"] > 0)
        ).sum()
        affected_pct   = affected_users / len(df_tmp)
        avg_du         = df_tmp["du"].mean()
        avg_dg         = df_tmp["dg"].mean()

        results.append({
            "unique_target"    : u,
            "gap_target_pp"    : int(g * 100),
            "delta_up_users"   : round(delta_up, 2),
            "avg_delta_p"      : round(avg_delta_p, 4),
            "uplift_pct"       : round(uplift_pct, 4),
            "affected_users"   : affected_users,
            "affected_pct"     : round(affected_pct, 4),
            "avg_du_applied"   : round(avg_du, 2),
            "avg_dg_applied_pp": round(avg_dg * 100, 2),
        })

result_df = pd.DataFrame(results)

# ----------------------------------------
# 8. Output results
# ----------------------------------------
print("\n" + "="*70)
print("Joint Flow Results (ge10 version)")
print("="*70)
print(result_df.to_string(index=False))

# ----------------------------------------
# 9. Pivot: newly-added Up-user grid
# ----------------------------------------
pivot_users = result_df.pivot(
    index="gap_target_pp",
    columns="unique_target",
    values="delta_up_users"
)
print("\n" + "="*70)
print("New Up Users Grid")
print("="*70)
print(pivot_users)

# ----------------------------------------
# 10. Pivot：Uplift % Grid
# ----------------------------------------
pivot_pct = result_df.pivot(
    index="gap_target_pp",
    columns="unique_target",
    values="uplift_pct"
).map(lambda x: f"{x:.2%}")

print("\n" + "="*70)
print("Uplift % Grid (share of Baseline Up)")
print("="*70)
print(pivot_pct)

# ----------------------------------------
# 11. Sanity Check
# ----------------------------------------
print("\n" + "="*70)
print("Sanity Check")
print("="*70)
print(f"Baseline Up user count: {baseline_up:,}")
print(f"Average p_old:          {df_mid['p_old'].mean():.4f}")
print(f"P90 unique headroom：  {p90_unique:.2f}")
print(f"Gap floor（ge10）：    {gap_floor:.4f}")
print(f"Average unique headroom: {df_mid['headroom_unique'].mean():.2f}")
print(f"Average gap headroom:    {df_mid['headroom_gap'].mean():.4f}")

# ----------------------------------------
# 12. Copyable Excel table
# ----------------------------------------
print("\n" + "="*70)
print("Copyable for Excel:")
print("="*70)
print("Unique Target\tGap Target pp\tDelta Up Users\tUplift %\t"
      "Avg ΔP\tAffected Users\tAffected %\tAvg du\tAvg dg pp")
for _, row in result_df.iterrows():
    print(f"{row['unique_target']}\t"
          f"{row['gap_target_pp']}\t"
          f"{row['delta_up_users']}\t"
          f"{row['uplift_pct']:.2%}\t"
          f"{row['avg_delta_p']}\t"
          f"{row['affected_users']}\t"
          f"{row['affected_pct']:.2%}\t"
          f"{row['avg_du_applied']}\t"
          f"{row['avg_dg_applied_pp']}")

print("\n✅ New tables created:")
print("  - result_df    (Joint Flow all scenarios)")
print("  - pivot_users  (new Up users grid)")
print("  - pivot_pct    (Uplift % Grid)")

Mid 母池样本量: 73,367
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

Baseline Up 人数: 14,217
Baseline Up 比例: 0.1938

模型参数：
  β_unique      = 0.4211
  β_gap         = 9.0105
  β_interaction = -0.073

P90 unique:           5.00
P20 gap（ge10）:       0.2857
gap floor:             0.2857
平均 unique headroom:  5.29
平均 gap headroom:     0.3265
有 unique 空间用户：   65,651 (89.48%)
有 gap 空间用户：      58,667 (79.96%)

平均 p_old:     0.1963
实际 Up 比例:   0.1938

======================================================================
Joint Flow 结果（ge10 版本）
======================================================================
 unique_target  gap_target_pp  delta_up_users  avg_delta_p  uplift_pct  affected_users  affected_pct  avg_du_applied  avg_dg_applied_pp
             1              3         3395.20       0.0463      0.2388           72048         0.982            0.89               2.38
             1              5         4259.15       0.0581      0.2996           72048         0.982            0.89               3.94
             1              7         5107.41       0.0696      0.3592           72048         0.982            0.89               5.42
             1             10         6403.92       0.0873      0.4504           72048         0.982            0.89               7.60
             2              3         5705.26       0.0778      0.4013           72048         0.982            1.73               2.38
             2              5         6635.80       0.0904      0.4668           72048         0.982            1.73               3.94
             2              7         7545.87       0.1029      0.5308           72048         0.982            1.73               5.42
             2             10         8930.54       0.1217      0.6282           72048         0.982            1.73               7.60
             3              3         7987.86       0.1089      0.5619           72048         0.982            2.51               2.38
             3              5         8978.54       0.1224      0.6315           72048         0.982            2.51               3.94
             3              7         9943.94       0.1355      0.6994           72048         0.982            2.51               5.42
             3             10        11406.63       0.1555      0.8023           72048         0.982            2.51               7.60

======================================================================
新增 Up 用户 Grid
======================================================================
unique_target        1        2         3
gap_target_pp
3              3395.20  5705.26   7987.86
5              4259.15  6635.80   8978.54
7              5107.41  7545.87   9943.94
10             6403.92  8930.54  11406.63

======================================================================
Uplift % Grid（占 Baseline Up）
======================================================================
unique_target       1       2       3
gap_target_pp
3              23.88%  40.13%  56.19%
5              29.96%  46.68%  63.15%
7              35.92%  53.08%  69.94%
10             45.04%  62.82%  80.23%

======================================================================
Sanity Check
======================================================================
Baseline Up 人数：     14,217
平均 p_old：           0.1963
P90 unique headroom：  5.00
Gap floor（ge10）：    0.2857
平均 unique headroom： 5.29
平均 gap headroom：    0.3265

======================================================================
可复制到 Excel：
======================================================================
Unique Target	Gap Target pp	Delta Up Users	Uplift %	Avg ΔP	Affected Users	Affected %	Avg du	Avg dg pp
1.0	3.0	3395.2	23.88%	0.0463	72048.0	98.20%	0.89	2.38
1.0	5.0	4259.15	29.96%	0.0581	72048.0	98.20%	0.89	3.94
1.0	7.0	5107.41	35.92%	0.0696	72048.0	98.20%	0.89	5.42
1.0	10.0	6403.92	45.04%	0.0873	72048.0	98.20%	0.89	7.6
2.0	3.0	5705.26	40.13%	0.0778	72048.0	98.20%	1.73	2.38
2.0	5.0	6635.8	46.68%	0.0904	72048.0	98.20%	1.73	3.94
2.0	7.0	7545.87	53.08%	0.1029	72048.0	98.20%	1.73	5.42
2.0	10.0	8930.54	62.82%	0.1217	72048.0	98.20%	1.73	7.6
3.0	3.0	7987.86	56.19%	0.1089	72048.0	98.20%	2.51	2.38
3.0	5.0	8978.54	63.15%	0.1224	72048.0	98.20%	2.51	3.94
3.0	7.0	9943.94	69.94%	0.1355	72048.0	98.20%	2.51	5.42
3.0	10.0	11406.63	80.23%	0.1555	72048.0	98.20%	2.51	7.6

✅ New tables created:
  - result_df    (Joint Flow 全部场景)
  - pivot_users  (新增 Up 用户 Grid)
  - pivot_pct    (Uplift % Grid)

In [144]:
# combined flow and intensify - model application case a - newly-flowed users take on the original late Mid-to-High state

# ============================================================
# Joint Case A: Flow + Intensify combined model (fixed version)
# Fix: v2 table, ge10 variable, new parameters, intensify changed to delta_new - delta_old
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# 1. Load data
# ----------------------------------------
df_mid = analysis_mid_user_master_v2.copy()
df_up  = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"Mid pool: {len(df_mid):,}")
print(f"Mid→High: {len(df_up):,}")
print(df_mid["path_9"].value_counts())

# ----------------------------------------
# 2. Define variables
# ----------------------------------------

# Mid pool
df_mid["x1"]           = df_mid["delta_n_unique_products"]
df_mid["x2"]           = -df_mid["delta_pct_gap10_v2"]      # ← changed
df_mid["weekly_old"]   = df_mid["weekly_med_late"]
df_mid["weekly_early"] = df_mid["weekly_med_early"]
df_mid["basket"]       = df_mid["basket_med_early"]
df_mid["gap_early"]    = df_mid["pct_gap10_early_v2"]        # ← changed

# Mid→High
df_up["x1"]           = df_up["delta_n_unique_products"]
df_up["x2"]           = -df_up["delta_pct_gap10"]           # ← changed
df_up["weekly_early"] = df_up["weekly_med_early"]
df_up["basket"]       = df_up["basket_med_early"]
df_up["gap_early"]    = df_up["pct_gap10_early"]             # ← changed

# ----------------------------------------
# 3. Flow model parameters (new parameters)
# ----------------------------------------
flow_intercept        = -2.2570
flow_beta_unique      =  0.4211
flow_beta_gap         =  9.0105
flow_beta_interaction = -0.0730
flow_beta_weekly      =  0.1137
flow_beta_basket      =  0.3673
flow_beta_gap_early   = -8.4695

# ----------------------------------------
# 4. Intensify model parameters (new parameters)
# ----------------------------------------
int_intercept        = 11.2364
int_beta_unique      =  0.4101
int_beta_gap         = 10.9454
int_beta_interaction =  0.0322
int_beta_weekly      = -0.9106
int_beta_basket      =  0.3992
int_beta_gap_early   = -11.3270

# ----------------------------------------
# 5. sigmoid function
# ----------------------------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# ----------------------------------------
# 6. Headroom
# ----------------------------------------

# Unique headroom (Mid-pool P90)
p90_unique = df_mid["x1"].quantile(0.9)
df_mid["headroom_unique"] = np.maximum(0, p90_unique - df_mid["x1"])
df_up["headroom_unique"]  = np.maximum(0, p90_unique - df_up["x1"])

# Gap headroom（P20 + floor）← ge10
gap_level = df_mid["gap_early"]
p20_gap   = gap_level.quantile(0.2)
gap_floor = max(p20_gap, 0.02)

df_mid["headroom_gap"] = np.maximum(0, df_mid["gap_early"] - gap_floor)
df_up["headroom_gap"]  = np.maximum(0, df_up["gap_early"]  - gap_floor)

print(f"\nP90 unique:           {p90_unique:.2f}")
print(f"P20 gap（ge10）:       {p20_gap:.4f}")
print(f"gap floor:             {gap_floor:.4f}")
print(f"Average unique headroom:  {df_mid['headroom_unique'].mean():.2f}")
print(f"Average gap headroom:     {df_mid['headroom_gap'].mean():.4f}")

# ----------------------------------------
# 7. avg_high and baseline
# ----------------------------------------
avg_high      = df_up["weekly_med_late"].mean()
baseline_high = df_up["weekly_med_late"].sum()

print(f"\navg_high:       {avg_high:.4f}")
print(f"baseline_high:  {baseline_high:,.2f}")

# ----------------------------------------
# 8. Scenario Grid
# ----------------------------------------
unique_scenarios = [1, 2, 3]
gap_scenarios    = [0.03, 0.05, 0.07, 0.10]

results = []

for u in unique_scenarios:
    for g in gap_scenarios:

        df_mid_tmp = df_mid.copy()
        df_up_tmp  = df_up.copy()

        # Actually applied (capped by headroom)
        df_mid_tmp["du"] = np.minimum(u, df_mid_tmp["headroom_unique"])
        df_mid_tmp["dg"] = np.minimum(g, df_mid_tmp["headroom_gap"])
        df_up_tmp["du"]  = np.minimum(u, df_up_tmp["headroom_unique"])
        df_up_tmp["dg"]  = np.minimum(g, df_up_tmp["headroom_gap"])

        # New variable
        df_mid_tmp["x1_new"] = df_mid_tmp["x1"] + df_mid_tmp["du"]
        df_mid_tmp["x2_new"] = df_mid_tmp["x2"] + df_mid_tmp["dg"]
        df_up_tmp["x1_new"]  = df_up_tmp["x1"]  + df_up_tmp["du"]
        df_up_tmp["x2_new"]  = df_up_tmp["x2"]  + df_up_tmp["dg"]

        # ---- Flow: compute ΔP ----
        df_mid_tmp["logit_old"] = (
            flow_intercept
            + flow_beta_unique      * df_mid_tmp["x1"]
            + flow_beta_gap         * df_mid_tmp["x2"]
            + flow_beta_interaction * df_mid_tmp["x1"] * df_mid_tmp["x2"]
            + flow_beta_weekly      * df_mid_tmp["weekly_early"]
            + flow_beta_basket      * df_mid_tmp["basket"]
            + flow_beta_gap_early   * df_mid_tmp["gap_early"]
        )
        df_mid_tmp["p_old"] = sigmoid(df_mid_tmp["logit_old"])

        df_mid_tmp["logit_new"] = (
            flow_intercept
            + flow_beta_unique      * df_mid_tmp["x1_new"]
            + flow_beta_gap         * df_mid_tmp["x2_new"]
            + flow_beta_interaction * df_mid_tmp["x1_new"] * df_mid_tmp["x2_new"]
            + flow_beta_weekly      * df_mid_tmp["weekly_early"]
            + flow_beta_basket      * df_mid_tmp["basket"]
            + flow_beta_gap_early   * df_mid_tmp["gap_early"]
        )
        df_mid_tmp["p_new"]   = sigmoid(df_mid_tmp["logit_new"])
        df_mid_tmp["delta_p"] = df_mid_tmp["p_new"] - df_mid_tmp["p_old"]

        # ---- Case A：Flow uplift（level jump only）----
        df_mid_tmp["flow_uplift"] = np.maximum(
            0,
            df_mid_tmp["delta_p"] * (avg_high - df_mid_tmp["weekly_old"])
        )
        flow_uplift = df_mid_tmp["flow_uplift"].sum()

        # ---- Intensify：existing uplift（delta_new - delta_old）----
        df_up_tmp["delta_old"] = (
            int_intercept
            + int_beta_unique      * df_up_tmp["x1"]
            + int_beta_gap         * df_up_tmp["x2"]
            + int_beta_interaction * df_up_tmp["x1"] * df_up_tmp["x2"]
            + int_beta_weekly      * df_up_tmp["weekly_early"]
            + int_beta_basket      * df_up_tmp["basket"]
            + int_beta_gap_early   * df_up_tmp["gap_early"]
        )
        df_up_tmp["delta_new"] = (
            int_intercept
            + int_beta_unique      * df_up_tmp["x1_new"]
            + int_beta_gap         * df_up_tmp["x2_new"]
            + int_beta_interaction * df_up_tmp["x1_new"] * df_up_tmp["x2_new"]
            + int_beta_weekly      * df_up_tmp["weekly_early"]
            + int_beta_basket      * df_up_tmp["basket"]
            + int_beta_gap_early   * df_up_tmp["gap_early"]
        )
        df_up_tmp["delta_weekly_i"] = np.maximum(
            0, df_up_tmp["delta_new"] - df_up_tmp["delta_old"]
        )
        existing_uplift = df_up_tmp["delta_weekly_i"].sum()

        # ---- Total ----
        total_uplift = existing_uplift + flow_uplift

        results.append({
            "unique_target"   : u,
            "gap_target_pp"   : int(g * 100),
            "existing_uplift" : round(existing_uplift, 2),
            "flow_uplift"     : round(flow_uplift, 2),
            "total_uplift"    : round(total_uplift, 2),
            "uplift_pct"      : round(total_uplift / baseline_high, 4),
            "delta_up_users"  : round(df_mid_tmp["delta_p"].sum(), 2),
            "avg_delta_p"     : round(df_mid_tmp["delta_p"].mean(), 4),
            "avg_p_old"       : round(df_mid_tmp["p_old"].mean(), 4),
        })

result_df = pd.DataFrame(results)

# ----------------------------------------
# 9. Output results
# ----------------------------------------
print("\n" + "="*70)
print("Case A: Joint Flow + Intensify Multi-Scenario")
print("="*70)
print(f"\n{'unique':>8} {'gap_pp':>8} {'Existing':>12} {'Flow':>12} "
      f"{'Total':>12} {'Uplift%':>8} {'New Up':>10}")
print("-"*75)
for _, row in result_df.iterrows():
    print(f"{row['unique_target']:>8} "
          f"{row['gap_target_pp']:>8} "
          f"{row['existing_uplift']:>12,.2f} "
          f"{row['flow_uplift']:>12,.2f} "
          f"{row['total_uplift']:>12,.2f} "
          f"{row['uplift_pct']:>8.2%} "
          f"{row['delta_up_users']:>10.2f}")

# ----------------------------------------
# 10. Pivot：Total Uplift Grid
# ----------------------------------------
pivot_total = result_df.pivot(
    index="gap_target_pp",
    columns="unique_target",
    values="total_uplift"
)
print("\n" + "="*70)
print("Total Uplift Grid")
print("="*70)
print(pivot_total)

# ----------------------------------------
# 11. Pivot：Uplift % Grid
# ----------------------------------------
pivot_pct = result_df.pivot(
    index="gap_target_pp",
    columns="unique_target",
    values="uplift_pct"
).map(lambda x: f"{x:.2%}")

print("\n" + "="*70)
print("Uplift % Grid")
print("="*70)
print(pivot_pct)

# ----------------------------------------
# 12. Sanity Check
# ----------------------------------------
print("\n" + "="*70)
print("Sanity Check")
print("="*70)
print(f"avg_high:      {avg_high:.4f}")
print(f"avg level jump: {(avg_high - df_mid['weekly_old']).mean():.4f}")
print(f"avg p_old:     {result_df['avg_p_old'].mean():.4f}")

# ----------------------------------------
# 13. Copyable Excel table
# ----------------------------------------
print("\n" + "="*70)
print("Copyable for Excel:")
print("="*70)
print("Unique\tGap pp\tExisting\tFlow\tTotal\tUplift %\tNew Up Users")
for _, row in result_df.iterrows():
    print(f"{row['unique_target']}\t"
          f"{row['gap_target_pp']}\t"
          f"{row['existing_uplift']}\t"
          f"{row['flow_uplift']}\t"
          f"{row['total_uplift']}\t"
          f"{row['uplift_pct']:.2%}\t"
          f"{row['delta_up_users']}")

print("\n✅ New tables created:")
print("  - result_df    (Joint Case A all scenarios)")
print("  - pivot_total  (Total Uplift Grid)")
print("  - pivot_pct    (Uplift % Grid)")

Mid 母池: 73,367
Mid→High: 14,217
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

P90 unique:           5.00
P20 gap（ge10）:       0.2857
gap floor:             0.2857
平均 unique headroom:  5.29
平均 gap headroom:     0.3265

avg_high:       13.3104
baseline_high:  189,233.54

======================================================================
Case A：Joint Flow + Intensify 多场景
======================================================================

  unique   gap_pp     Existing         Flow        Total      提升%       新增Up
---------------------------------------------------------------------------
     1.0      3.0     7,931.70    18,443.32    26,375.01   13.94%    3395.20
     1.0      5.0    10,240.81    23,359.71    33,600.52   17.76%    4259.15
     1.0      7.0    12,423.00    28,331.75    40,754.75   21.54%    5107.41
     1.0     10.0    15,608.18    36,215.06    51,823.24   27.39%    6403.92
     2.0      3.0    11,857.07    32,314.33    44,171.40   23.34%    5705.26
     2.0      5.0    14,170.62    37,898.22    52,068.84   27.52%    6635.80
     2.0      7.0    16,357.02    43,512.78    59,869.79   31.64%    7545.87
     2.0     10.0    19,548.30    52,351.15    71,899.45   38.00%    8930.54
     3.0      3.0    15,202.10    47,027.54    62,229.64   32.89%    7987.86
     3.0      5.0    17,519.49    53,254.80    70,774.29   37.40%    8978.54
     3.0      7.0    19,709.52    59,482.65    79,192.17   41.85%    9943.94
     3.0     10.0    22,906.10    69,222.37    92,128.47   48.69%   11406.63

======================================================================
Total Uplift Grid
======================================================================
unique_target         1         2         3
gap_target_pp
3              26375.01  44171.40  62229.64
5              33600.52  52068.84  70774.29
7              40754.75  59869.79  79192.17
10             51823.24  71899.45  92128.47

======================================================================
Uplift % Grid
======================================================================
unique_target       1       2       3
gap_target_pp
3              13.94%  23.34%  32.89%
5              17.76%  27.52%  37.40%
7              21.54%  31.64%  41.85%
10             27.39%  38.00%  48.69%

======================================================================
Sanity Check
======================================================================
avg_high:      13.3104
avg level jump: 6.9980
avg p_old:     0.1963

======================================================================
可复制到 Excel：
======================================================================
Unique	Gap pp	Existing	Flow	Total	Uplift %	New Up Users
1.0	3.0	7931.7	18443.32	26375.01	13.94%	3395.2
1.0	5.0	10240.81	23359.71	33600.52	17.76%	4259.15
1.0	7.0	12423.0	28331.75	40754.75	21.54%	5107.41
1.0	10.0	15608.18	36215.06	51823.24	27.39%	6403.92
2.0	3.0	11857.07	32314.33	44171.4	23.34%	5705.26
2.0	5.0	14170.62	37898.22	52068.84	27.52%	6635.8
2.0	7.0	16357.02	43512.78	59869.79	31.64%	7545.87
2.0	10.0	19548.3	52351.15	71899.45	38.00%	8930.54
3.0	3.0	15202.1	47027.54	62229.64	32.89%	7987.86
3.0	5.0	17519.49	53254.8	70774.29	37.40%	8978.54
3.0	7.0	19709.52	59482.65	79192.17	41.85%	9943.94
3.0	10.0	22906.1	69222.37	92128.47	48.69%	11406.63

✅ New tables created:
  - result_df    (Joint Case A 全部场景)
  - pivot_total  (Total Uplift Grid)
  - pivot_pct    (Uplift % Grid)

In [145]:
# case b

# ============================================================
# Joint Case B: Flow + Intensify combined model (fixed version)
# Case B：flow uplift = ΔP × (level jump + marginal intensify)
# ============================================================

import pandas as pd
import numpy as np

# ----------------------------------------
# 1. Load data
# ----------------------------------------
df_mid = analysis_mid_user_master_v2.copy()
df_up  = analysis_mid_user_master[
    analysis_mid_user_master["path_9"] == "Mid Up to High"
].copy()

print(f"Mid pool: {len(df_mid):,}")
print(f"Mid→High: {len(df_up):,}")
print(df_mid["path_9"].value_counts())

# ----------------------------------------
# 2. Define variables
# ----------------------------------------

# Mid pool
df_mid["x1"]           = df_mid["delta_n_unique_products"]
df_mid["x2"]           = -df_mid["delta_pct_gap10_v2"]      # ← ge10
df_mid["weekly_old"]   = df_mid["weekly_med_late"]
df_mid["weekly_early"] = df_mid["weekly_med_early"]
df_mid["basket"]       = df_mid["basket_med_early"]
df_mid["gap_early"]    = df_mid["pct_gap10_early_v2"]        # ← ge10

# Mid→High
df_up["x1"]           = df_up["delta_n_unique_products"]
df_up["x2"]           = -df_up["delta_pct_gap10"]           # ← ge10
df_up["weekly_early"] = df_up["weekly_med_early"]
df_up["basket"]       = df_up["basket_med_early"]
df_up["gap_early"]    = df_up["pct_gap10_early"]             # ← ge10

# ----------------------------------------
# 3. Flow model parameters (new parameters)
# ----------------------------------------
flow_intercept        = -2.2570
flow_beta_unique      =  0.4211
flow_beta_gap         =  9.0105
flow_beta_interaction = -0.0730
flow_beta_weekly      =  0.1137
flow_beta_basket      =  0.3673
flow_beta_gap_early   = -8.4695

# ----------------------------------------
# 4. Intensify model parameters (new parameters)
# ----------------------------------------
int_intercept        = 11.2364
int_beta_unique      =  0.4101
int_beta_gap         = 10.9454
int_beta_interaction =  0.0322
int_beta_weekly      = -0.9106
int_beta_basket      =  0.3992
int_beta_gap_early   = -11.3270

# ----------------------------------------
# 5. sigmoid function
# ----------------------------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# ----------------------------------------
# 6. Headroom
# ----------------------------------------

# Unique headroom (Mid-pool P90)
p90_unique = df_mid["x1"].quantile(0.9)
df_mid["headroom_unique"] = np.maximum(0, p90_unique - df_mid["x1"])
df_up["headroom_unique"]  = np.maximum(0, p90_unique - df_up["x1"])

# Gap headroom（P20 + floor）← ge10
gap_level = df_mid["gap_early"]
p20_gap   = gap_level.quantile(0.2)
gap_floor = max(p20_gap, 0.02)

df_mid["headroom_gap"] = np.maximum(0, df_mid["gap_early"] - gap_floor)
df_up["headroom_gap"]  = np.maximum(0, df_up["gap_early"]  - gap_floor)

print(f"\nP90 unique:           {p90_unique:.2f}")
print(f"P20 gap（ge10）:       {p20_gap:.4f}")
print(f"gap floor:             {gap_floor:.4f}")
print(f"Average unique headroom:  {df_mid['headroom_unique'].mean():.2f}")
print(f"Average gap headroom:     {df_mid['headroom_gap'].mean():.4f}")

# ----------------------------------------
# 7. avg_high and baseline
# ----------------------------------------
avg_high      = df_up["weekly_med_late"].mean()
baseline_high = df_up["weekly_med_late"].sum()

print(f"\navg_high:       {avg_high:.4f}")
print(f"baseline_high:  {baseline_high:,.2f}")

# ----------------------------------------
# 8. Scenario Grid
# ----------------------------------------
unique_scenarios = [1, 2, 3]
gap_scenarios    = [0.03, 0.05, 0.07, 0.10]

results = []

for u in unique_scenarios:
    for g in gap_scenarios:

        df_mid_tmp = df_mid.copy()
        df_up_tmp  = df_up.copy()

        # Actually applied (capped by headroom)
        df_mid_tmp["du"] = np.minimum(u, df_mid_tmp["headroom_unique"])
        df_mid_tmp["dg"] = np.minimum(g, df_mid_tmp["headroom_gap"])
        df_up_tmp["du"]  = np.minimum(u, df_up_tmp["headroom_unique"])
        df_up_tmp["dg"]  = np.minimum(g, df_up_tmp["headroom_gap"])

        # New variable
        df_mid_tmp["x1_new"] = df_mid_tmp["x1"] + df_mid_tmp["du"]
        df_mid_tmp["x2_new"] = df_mid_tmp["x2"] + df_mid_tmp["dg"]
        df_up_tmp["x1_new"]  = df_up_tmp["x1"]  + df_up_tmp["du"]
        df_up_tmp["x2_new"]  = df_up_tmp["x2"]  + df_up_tmp["dg"]

        # ---- Flow: compute ΔP ----
        df_mid_tmp["logit_old"] = (
            flow_intercept
            + flow_beta_unique      * df_mid_tmp["x1"]
            + flow_beta_gap         * df_mid_tmp["x2"]
            + flow_beta_interaction * df_mid_tmp["x1"] * df_mid_tmp["x2"]
            + flow_beta_weekly      * df_mid_tmp["weekly_early"]
            + flow_beta_basket      * df_mid_tmp["basket"]
            + flow_beta_gap_early   * df_mid_tmp["gap_early"]
        )
        df_mid_tmp["p_old"] = sigmoid(df_mid_tmp["logit_old"])

        df_mid_tmp["logit_new"] = (
            flow_intercept
            + flow_beta_unique      * df_mid_tmp["x1_new"]
            + flow_beta_gap         * df_mid_tmp["x2_new"]
            + flow_beta_interaction * df_mid_tmp["x1_new"] * df_mid_tmp["x2_new"]
            + flow_beta_weekly      * df_mid_tmp["weekly_early"]
            + flow_beta_basket      * df_mid_tmp["basket"]
            + flow_beta_gap_early   * df_mid_tmp["gap_early"]
        )
        df_mid_tmp["p_new"]   = sigmoid(df_mid_tmp["logit_new"])
        df_mid_tmp["delta_p"] = df_mid_tmp["p_new"] - df_mid_tmp["p_old"]

        # ---- Existing intensify（df_up，delta_new - delta_old）----
        df_up_tmp["delta_old"] = (
            int_intercept
            + int_beta_unique      * df_up_tmp["x1"]
            + int_beta_gap         * df_up_tmp["x2"]
            + int_beta_interaction * df_up_tmp["x1"] * df_up_tmp["x2"]
            + int_beta_weekly      * df_up_tmp["weekly_early"]
            + int_beta_basket      * df_up_tmp["basket"]
            + int_beta_gap_early   * df_up_tmp["gap_early"]
        )
        df_up_tmp["delta_new"] = (
            int_intercept
            + int_beta_unique      * df_up_tmp["x1_new"]
            + int_beta_gap         * df_up_tmp["x2_new"]
            + int_beta_interaction * df_up_tmp["x1_new"] * df_up_tmp["x2_new"]
            + int_beta_weekly      * df_up_tmp["weekly_early"]
            + int_beta_basket      * df_up_tmp["basket"]
            + int_beta_gap_early   * df_up_tmp["gap_early"]
        )
        df_up_tmp["delta_weekly_i"] = np.maximum(
            0, df_up_tmp["delta_new"] - df_up_tmp["delta_old"]
        )
        existing_uplift = df_up_tmp["delta_weekly_i"].sum()

        # ---- Case B core: marginal intensify for the Mid pool ----
        # delta_new - delta_old (same approach as existing)
        df_mid_tmp["delta_old_i"] = (
            int_intercept
            + int_beta_unique      * df_mid_tmp["x1"]
            + int_beta_gap         * df_mid_tmp["x2"]
            + int_beta_interaction * df_mid_tmp["x1"] * df_mid_tmp["x2"]
            + int_beta_weekly      * df_mid_tmp["weekly_early"]
            + int_beta_basket      * df_mid_tmp["basket"]
            + int_beta_gap_early   * df_mid_tmp["gap_early"]
        )
        df_mid_tmp["delta_new_i"] = (
            int_intercept
            + int_beta_unique      * df_mid_tmp["x1_new"]
            + int_beta_gap         * df_mid_tmp["x2_new"]
            + int_beta_interaction * df_mid_tmp["x1_new"] * df_mid_tmp["x2_new"]
            + int_beta_weekly      * df_mid_tmp["weekly_early"]
            + int_beta_basket      * df_mid_tmp["basket"]
            + int_beta_gap_early   * df_mid_tmp["gap_early"]
        )
        df_mid_tmp["delta_weekly_i"] = np.maximum(
            0, df_mid_tmp["delta_new_i"] - df_mid_tmp["delta_old_i"]
        )

        # ---- Case B formula ----
        # flow uplift = ΔP × (level jump + marginal intensify)
        df_mid_tmp["flow_uplift"] = np.maximum(
            0,
            df_mid_tmp["delta_p"] * (
                (avg_high - df_mid_tmp["weekly_old"])
                + df_mid_tmp["delta_weekly_i"]
            )
        )
        flow_uplift  = df_mid_tmp["flow_uplift"].sum()
        total_uplift = existing_uplift + flow_uplift

        results.append({
            "unique_target"     : u,
            "gap_target_pp"     : int(g * 100),
            "existing_uplift"   : round(existing_uplift, 2),
            "flow_uplift"       : round(flow_uplift, 2),
            "total_uplift"      : round(total_uplift, 2),
            "uplift_pct"        : round(total_uplift / baseline_high, 4),
            "delta_up_users"    : round(df_mid_tmp["delta_p"].sum(), 2),
            "avg_delta_p"       : round(df_mid_tmp["delta_p"].mean(), 4),
            "avg_delta_weekly_i": round(df_mid_tmp["delta_weekly_i"].mean(), 4),
            "avg_p_old"         : round(df_mid_tmp["p_old"].mean(), 4),
        })

result_df = pd.DataFrame(results)

# ----------------------------------------
# 9. Output results
# ----------------------------------------
print("\n" + "="*70)
print("Case B: Joint Flow + Intensify Multi-Scenario")
print("="*70)
print(f"\n{'unique':>8} {'gap_pp':>8} {'Existing':>12} {'Flow':>12} "
      f"{'Total':>12} {'Uplift%':>8} {'New Up':>10}")
print("-"*75)
for _, row in result_df.iterrows():
    print(f"{row['unique_target']:>8} "
          f"{row['gap_target_pp']:>8} "
          f"{row['existing_uplift']:>12,.2f} "
          f"{row['flow_uplift']:>12,.2f} "
          f"{row['total_uplift']:>12,.2f} "
          f"{row['uplift_pct']:>8.2%} "
          f"{row['delta_up_users']:>10.2f}")

# ----------------------------------------
# 10. Pivot：Total Uplift Grid
# ----------------------------------------
pivot_total = result_df.pivot(
    index="gap_target_pp",
    columns="unique_target",
    values="total_uplift"
)
print("\n" + "="*70)
print("Total Uplift Grid")
print("="*70)
print(pivot_total)

# ----------------------------------------
# 11. Pivot：Uplift % Grid
# ----------------------------------------
pivot_pct = result_df.pivot(
    index="gap_target_pp",
    columns="unique_target",
    values="uplift_pct"
).map(lambda x: f"{x:.2%}")

print("\n" + "="*70)
print("Uplift % Grid")
print("="*70)
print(pivot_pct)

# ----------------------------------------
# 12. Case A vs. Case B comparison
# ----------------------------------------
print("\n" + "="*70)
print("avg Δweekly_i（marginal intensify per user）")
print("="*70)
pivot_i = result_df.pivot(
    index="gap_target_pp",
    columns="unique_target",
    values="avg_delta_weekly_i"
)
print(pivot_i)

# ----------------------------------------
# 13. Sanity Check
# ----------------------------------------
print("\n" + "="*70)
print("Sanity Check")
print("="*70)
print(f"avg_high:       {avg_high:.4f}")
print(f"avg level jump: {(avg_high - df_mid['weekly_old']).mean():.4f}")
print(f"avg p_old:      {result_df['avg_p_old'].mean():.4f}")

# ----------------------------------------
# 14. Copyable Excel table
# ----------------------------------------
print("\n" + "="*70)
print("Copyable for Excel:")
print("="*70)
print("Unique\tGap pp\tExisting\tFlow\tTotal\tUplift %\t"
      "New Up Users\tAvg Δweekly_i")
for _, row in result_df.iterrows():
    print(f"{row['unique_target']}\t"
          f"{row['gap_target_pp']}\t"
          f"{row['existing_uplift']}\t"
          f"{row['flow_uplift']}\t"
          f"{row['total_uplift']}\t"
          f"{row['uplift_pct']:.2%}\t"
          f"{row['delta_up_users']}\t"
          f"{row['avg_delta_weekly_i']}")

print("\n✅ New tables created:")
print("  - result_df    (Joint Case B all scenarios)")
print("  - pivot_total  (Total Uplift Grid)")
print("  - pivot_pct    (Uplift % Grid)")
print("  - pivot_i      (Avg Δweekly_i Grid)")

Mid 母池: 73,367
Mid→High: 14,217
path_9
Mid Stay           43780
Mid Down to Low    15370
Mid Up to High     14217
Name: count, dtype: int64

P90 unique:           5.00
P20 gap（ge10）:       0.2857
gap floor:             0.2857
平均 unique headroom:  5.29
平均 gap headroom:     0.3265

avg_high:       13.3104
baseline_high:  189,233.54

======================================================================
Case B：Joint Flow + Intensify 多场景
======================================================================

  unique   gap_pp     Existing         Flow        Total      提升%       新增Up
---------------------------------------------------------------------------
     1.0      3.0     7,931.70    20,499.81    28,431.51   15.02%    3395.20
     1.0      5.0    10,240.81    26,703.08    36,943.89   19.52%    4259.15
     1.0      7.0    12,423.00    33,276.34    45,699.34   24.15%    5107.41
     1.0     10.0    15,608.18    44,248.81    59,856.99   31.63%    6403.92
     2.0      3.0    11,857.07    37,867.92    49,724.98   26.28%    5705.26
     2.0      5.0    14,170.62    45,451.21    59,621.84   31.51%    6635.80
     2.0      7.0    16,357.02    53,382.07    69,739.09   36.85%    7545.87
     2.0     10.0    19,548.30    66,428.27    85,976.56   45.43%    8930.54
     3.0      3.0    15,202.10    57,728.10    72,930.20   38.54%    7987.86
     3.0      5.0    17,519.49    66,689.03    84,208.52   44.50%    8978.54
     3.0      7.0    19,709.52    75,963.49    95,673.01   50.56%    9943.94
     3.0     10.0    22,906.10    91,040.88   113,946.98   60.22%   11406.63

======================================================================
Total Uplift Grid
======================================================================
unique_target         1         2          3
gap_target_pp
3              28431.51  49724.98   72930.20
5              36943.89  59621.84   84208.52
7              45699.34  69739.09   95673.01
10             59856.99  85976.56  113946.98

======================================================================
Uplift % Grid
======================================================================
unique_target       1       2       3
gap_target_pp
3              15.02%  26.28%  38.54%
5              19.52%  31.51%  44.50%
7              24.15%  36.85%  50.56%
10             31.63%  45.43%  60.22%

======================================================================
avg Δweekly_i（marginal intensify per user）
======================================================================
unique_target       1       2       3
gap_target_pp
3              0.6255  0.9723  1.2929
5              0.7966  1.1437  1.4648
7              0.9585  1.3061  1.6275
10             1.1972  1.5454  1.8673

======================================================================
Sanity Check
======================================================================
avg_high:       13.3104
avg level jump: 6.9980
avg p_old:      0.1963

======================================================================
可复制到 Excel：
======================================================================
Unique	Gap pp	Existing	Flow	Total	Uplift %	New Up Users	Avg Δweekly_i
1.0	3.0	7931.7	20499.81	28431.51	15.02%	3395.2	0.6255
1.0	5.0	10240.81	26703.08	36943.89	19.52%	4259.15	0.7966
1.0	7.0	12423.0	33276.34	45699.34	24.15%	5107.41	0.9585
1.0	10.0	15608.18	44248.81	59856.99	31.63%	6403.92	1.1972
2.0	3.0	11857.07	37867.92	49724.98	26.28%	5705.26	0.9723
2.0	5.0	14170.62	45451.21	59621.84	31.51%	6635.8	1.1437
2.0	7.0	16357.02	53382.07	69739.09	36.85%	7545.87	1.3061
2.0	10.0	19548.3	66428.27	85976.56	45.43%	8930.54	1.5454
3.0	3.0	15202.1	57728.1	72930.2	38.54%	7987.86	1.2929
3.0	5.0	17519.49	66689.03	84208.52	44.50%	8978.54	1.4648
3.0	7.0	19709.52	75963.49	95673.01	50.56%	9943.94	1.6275
3.0	10.0	22906.1	91040.88	113946.98	60.22%	11406.63	1.8673

✅ New tables created:
  - result_df    (Joint Case B 全部场景)
  - pivot_total  (Total Uplift Grid)
  - pivot_pct    (Uplift % Grid)
  - pivot_i      (Avg Δweekly_i Grid)

In [146]:
print(f"Mid→High weekly sum: {df_up['weekly_med_late'].sum():,.2f}")
print(f"Full Mid-pool weekly sum: {df_mid['weekly_med_late'].sum():,.2f}")
print(f"\nUsing the full Mid pool as the denominator:")
print(f"{113947 / df_mid['weekly_med_late'].sum():.2%}")

Mid→High weekly sum: 189,233.54
全体 Mid 母池 weekly sum: 463,122.12

用全体 Mid 母池为分母：
24.60%

In [147]:
# Maximum scenario (+3 unique + +10pp)
# View each group's delta_p and flow_uplift
print(df_mid_tmp.groupby("path_9")[
    ["delta_p", "weekly_old", "flow_uplift",
     "delta_weekly_i"]
].agg(["mean", "sum"]).round(2))

                delta_p          weekly_old            flow_uplift            \
                   mean      sum       mean        sum        mean       sum
path_9
Mid Down to Low    0.03   490.17       2.13   32673.64        0.41   6324.38
Mid Stay           0.18  8033.76       5.51  241214.94        1.68  73756.10
Mid Up to High     0.20  2882.71      13.31  189233.54        0.77  10960.39

                delta_weekly_i
                          mean       sum
path_9
Mid Down to Low           2.02  31082.75
Mid Stay                  1.90  83009.36
Mid Up to High            1.61  22906.10